### ISSUE TITLE
Spawner Pickaxe isn't work in 1.14.4

### ISSUE THREAD

**Issue by coco0325** [TheBusyBiscuit/Slimefun4#1000]
## Description (Required)
Can't get broken spawner from breaking spawners by using Spawner Pickaxe. (Only happen in 1.14.4)

## Steps to reproduce the Issue (Required)
Use Spawner Pickaxe to break spawners

## Expected behavior (Required)
It drops broken spawner

## Server Log / Error Report
None
## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: 135
 - CS-CoreLib Version: 64

**Comment by dniym** [comment]
Can not reproduce this bug using 1.14.4 + SF version 147 can probably close this
