### ISSUE TITLE
Duplication via Block Placer

### ISSUE THREAD

**Issue by EkaZo** [TheBusyBiscuit/Slimefun4#1002]
## Description (Required)
When funneling block entities into a hopper that feeds into a Block Placer that is operated by a fast redstone clock, the player can right click the block placer and spam shift left click on the top left cell when new items go through the block placer. What this does is that the block placer places the entity as a block and the player also gets the entity version causing a duplication.

## Server Log
None

## Evidence / Proof (Required)
https://plays.tv/video/5d4b770526174fa717/dupe-glitch 

## Environment (Required)
Minecraft: 1.14.4
Paper v1_14_R1
CS-CoreLib vv1.6.1
SlimeFun vDEV - 124 (git 6389a570)

**Comment by aenaveen** [comment]
This is now repeated with a observer, with latest version of slimefun. People put items in shulker box and duplicate the shulker easily. Either we have to blacklist items or disable block placer itself.
