### ISSUE TITLE
Zelda Hearts and SLimedustry

### ISSUE THREAD

**Issue by ZenOhSupreme** [TheBusyBiscuit/Slimefun4#101]
## Description
When I run the console It tells me there is an error with Zelda hearts is it up to date and that there is an error with slimedustry is it up to date. I also still have an issue with blocks that become invincible that cannot be deleted. even if I go into mcedit and delete all the entity info it prevents that block space from being used. I cannot replicate that issue but I can give you the server log for the Slimedustry and Zelda hearts issue 

## Server Log
http://pastebin.com/j53jLnj1

## Environment
 I am on 1.11.2 for mine craft running the most up to date JAR files for the slimefun extras you have. Before you consider this closed please tell me what the problem is. Everytime I bring up an issue you guys close it and say forget about it. Players like slime fun

**Comment by NathanAdhitya** [comment]
First, Regarding what you said about us closing your issues without any reasons.
The first issue, I already answered. Don't go crazy with WorldEdit. The ones that made the server crash was WE. Slimefun has nothing to do with this. If you need support for that, You don't ask it here. (Probably you can, but it may be a bad idea :P). For the thing regarding this, Slimedustry and ZeldaHearts doesn't look like supports 1.11.2? Ill bug TheBusyBiscuit for that. *insert evil face here*

**Comment by ZenOhSupreme** [comment]
but slot of times it leaves like shrunken floating orange wool. I did do the world edit on unbreakable glass and now have an unbuildable area.

**Comment by NathanAdhitya** [comment]
Well then, place the block back, and then break it manually. that's for sure a solution.
