### ISSUE TITLE
Can't craft ancient rune of fire

### ISSUE THREAD

**Issue by StarWishsama** [TheBusyBiscuit/Slimefun4#1013]
## Description (Required)
Can't craft ancient rune of fire

## Steps to reproduce the Issue (Required)
https://i.loli.net/2019/08/17/6usf5nLJW8pOkqy.png

## Expected behavior (Required)
get 4 ancient rune of fire

## Server Log / Error Report

No error log

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: Slimefun4 - DEV 135 (git f54fd)
 - CS-CoreLib Version: CS-CoreLib - DEV 61 (git 4d33f)
--

**Comment by SoSeDiK** [comment]
Don't you need one more fire charge?
I mean it seems like one pedestal is missing the item.

**Comment by StarWishsama** [comment]
> Don't you need one more fire charge?
> I mean it seems like one pedestal is missing the item.

I tried
![Image](https://i.loli.net/2019/08/18/rwYkVx4zW38hyAI.png)

**Comment by J3fftw1** [comment]
you have to turn arround the recipe 90 degrees
if it doesnt work same progress
after same progress player on my server had same issue

**Comment by StarWishsama** [comment]
> you have to turn arround the recipe 90 degrees
> if it doesnt work same progress
> after same progress player on my server had same issue

it works, thx
![](https://i.loli.net/2019/08/18/ZAFlKnXo47BJeuE.png)
