### ISSUE TITLE
Towny Mayors unable to access Slimefun Machines within their own Towns

### ISSUE THREAD

**Issue by GutzV314** [TheBusyBiscuit/Slimefun4#102]
## Description
Towny Mayors are unable to access their Slimefun machines within their own town borders.

It is unconfirmed if the same problem exists with Programmable Androids and Cargo Blocks.

Slimefun Machines do work for Mayors in Wilderness and other Towns.

Have tested all /plot settings for the Mayor in their Town, confirmed not working.

Unknown if the problem is within Towny or Slimefun

## Server Log
No Log Available

## Evidence / Proof
![2017-01-15_17 40 20](https://cloud.githubusercontent.com/assets/25141564/21968583/ee4d44a8-db4a-11e6-88cc-d94e062c25fb.png)
Machine in this screenshot Coal Generator crafted by GutzV314 non-op player
## Environment
Latest Update

## Our Current Forum on Issue
http://aeonlegion.us/forum/view_topic/?tid=43

**Comment by AlexLander123** [comment]
Issue is already fixed in TheBusyBiscuit/CS-CoreLib#17
