### ISSUE TITLE
Slimefun now only operates in primary world

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1020]
## Description (Required)
Around build #136, Slimefun has ceased to function in every world except for the main one.  The plugin is still "installed" in these worlds because I can still use the /sf give command for items... these items just don't function in the world.  (Cargo nodes cannot be accessed... there is no "Connected: _" information when right clicking connection nodes).

## Steps to reproduce the Issue (Required)
Updating to slimefun build 137+ should reproduce the issue.

## Expected behavior (Required)
Should still function as normally.

## Server Log / Error Report
This error is repeated for every world except the main one so is the likeliest cause:
https://pastebin.com/agk3n0rz
Probably not possible to tell, but I'm right clicking the mess out of this Trash Can in The End:
https://youtu.be/9fx-LmZwX6k

## Environment (Required)
[08:40:58 INFO]: Paper v1_14_R1 (173)
[08:40:58 INFO]:
[08:40:58 INFO]: CS-CoreLib vDEV - 66 (git 9174f09d)
[08:40:58 INFO]: Slimefun vDEV - 142 (git 0d7fc6af)
[08:40:58 INFO]:
[08:40:58 INFO]: Installed Addons (7)
[08:40:58 INFO]:  Barrels vDEV - 2 (git 847bc83b)
[08:40:58 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[08:40:58 INFO]:  ChestTerminal v1.0
[08:40:58 INFO]:  HotbarPets vDEV - 10 (git 7d790905)
[08:40:58 INFO]:  ExoticGarden vDEV - 17 (git 122f5555)
[08:40:58 INFO]:  SoulJars vDEV - 3 (git ebabf39f)
[08:40:58 INFO]:  ElectricSpawners vDEV - 2 (git 49ffa319)

**Comment by TheBusyBiscuit** [comment]
Do /sf debug_fish and use it to display the block's data.
Then post the output.

**Comment by mrcoffee1026** [comment]
Can't get any output on any block in any world other than in the main world. ( new trash can block in the end has no effect, acts like the fish isn't even a thing.  When I go to world and right click a trash can block with debug fish I get:
```
 PLAYER_HEAD @ X: 493 Y: 64 Z: 569
 ID: TRASH_CAN_BLOCK
 Skull: ?
   Rotation: WEST
 Inventory: ?
 Ticking: ?
   Async: ?
   Timings: 0ms
   Total Timings: 0ms
   Chunk Timings: 0ms
 Chargable: ?
 {"id":"TRASH_CAN_BLOCK"}

```

**Comment by TheBusyBiscuit** [comment]
Alright, good.
Now, this is very important:

1. What are your World's names?
2. Do you use Multiworlds / Multiverse, etc...? It'd be best if you could give us a list of all your plugins.
3. Could you also give us a full server log of the Server starting up and shutting down?

**Comment by TheBusyBiscuit** [comment]
Disregard my previous comment, found something in the error you posted.
Please post the contents of your "data-storage/Slimefun/universal-inventories" folder.
This is likely connected to https://github.com/TheBusyBiscuit/ColoredEnderChests/issues/4

**Comment by mrcoffee1026** [comment]
1.  world*, world_nether*, world_the_end*, pixelmap, pixelmaptwo, creative, creativetwo, gallifrey, roleplay, siluria, skaro, staff_creative, tardis_timevortex*, tardis_zero_room  (*denotes the worlds slimefun is actually active in)
2. Multiverse .....

Oh ok um there are 4 files in there:
COLORED_ENDER_CHEST_BIG_0_0_0.sfi
COLORED_ENDER_CHEST_BIG_0_0_1.sfi
COLORED_ENDER_CHEST_BIG_10_10_10.sfi
COLORED_ENDER_CHEST_SMALL_7_12_0.sfi

Contents of each file is one line:
preset: <the filename above without the .sfi>
And that is all.  After I opened that ticket, I removed that addon since they clear all content after every restart.  Again, I think this an issue independent of that one.. this did not restore slimefun functionality in other worlds, so I do not believe the two are related that closely.

**Comment by TheBusyBiscuit** [comment]
Well, the error at least comes from the fact that the addon has been removed.

And no with "looking good on the fish so far", I meant that it looks good.
Because no message means that it is a problem with moving it to RAM, not data corruption.

**Comment by TheBusyBiscuit** [comment]
Please post a full server log with startup and shutdown then.

**Comment by mrcoffee1026** [comment]
No these errors were present before I removed the addon as well.  May take me an hour or so to get you that kind of log, I'll post it shortly.

**Comment by TheBusyBiscuit** [comment]
If the error was there with ColoredEnderChests installed, then there must have been more files than you posted...

Because the error is the result of that directory containing a file that cannot be recognized.

**Comment by mrcoffee1026** [comment]
Yeah ok well I missed something it is due to the colored enderchests thing so this is just that and nothing else.  I swear I found both issues at around the same time but hadn't removed the addon yet but to fix the error in this ticket, all I have to do is remove those files from the universal-inventories folder.  They'd probably be needed if there was anything of value like actual inventory in them but since there isn't... that's my short-term fix.  And yeah I was super shocked when I didn't see the errors on my local copy since I hadn't removed the addon from there.
