### ISSUE TITLE
Talisman of the Whirlwind destroys Trident with Loyalty

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1022]
## Description (Required)
Only works in PVP player on player situation.  If your target has a wirlwind talisman the trident will be deflected... wherever... but it can't be picked up again.

## Steps to reproduce the Issue (Required)
Have one player have a whirlwind talisman (or both, but the target must have this).  Throw trident at player (regardless of enchant this is the result, but a loyalty enchanted trident should return to you).  Your target will receive the "Your talisman deflected the projectile!" notice... and your trident will be forever stuck in whatever block it got deflected into and unretrievable.
https://imgur.com/a/QaonEBg

## Expected behavior (Required)
Trident should return to the thrower regardless of the talsman the target has. 

## Server Log / Error Report
No errors for this, just observed behavior.

## Environment (Required)
[10:49:14 INFO]: Paper v1_14_R1 (173)
[10:49:14 INFO]:
[10:49:14 INFO]: CS-CoreLib vDEV - 66 (git 9174f09d)
[10:49:14 INFO]: Slimefun vDEV - 142 (git 0d7fc6af)
[10:49:14 INFO]:
[10:49:14 INFO]: Installed Addons (7)
[10:49:14 INFO]:  Barrels vDEV - 2 (git 847bc83b)
[10:49:14 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[10:49:14 INFO]:  ChestTerminal v1.0
[10:49:14 INFO]:  HotbarPets vDEV - 10 (git 7d790905)
[10:49:14 INFO]:  ExoticGarden vDEV - 17 (git 122f5555)
[10:49:14 INFO]:  SoulJars vDEV - 3 (git ebabf39f)
[10:49:14 INFO]:  ElectricSpawners vDEV - 2 (git 49ffa319)

**Comment by TheBusyBiscuit** [comment]
Bukkit / Spigot API does not include "loyal" Tridents yet..., so there is not really an easy approach for it at the moment.
So this Issue may sit around for a while.

**Comment by ExoVamp** [comment]
{ • [ Perhaps ] • }

•^ Autonomize Tridents with [[org.bukkit.enchantments.Enchantment.LOYALTY]] to be [~/makeshift~] immaterially returned to {the caster}.

?_.> Plugin ==>

=_:: Upon a listener detecting collision of thrown Trident with the aforementioned ":Whirlwind:" ≈

))) Copy all metadata from Trident.
))) Destroy Trident
))) Give {King Neptune} an identical Trident

/|/\// Add water _whoosh_ sound ⌠ and _glistening_ particles -⌡- to indicate that even though the [Sea] would have no [Power] without the [Wind], the {King} must have his [Scepter], lest the [)MerPeople(] abandon all hope, and contrive maneuvering to solid ground, where {)LandPeople(} fight gravity and each other.

Or perhaps... the ⌡design⌠ scrutinizes a stranger predicament: What is Nature, if a Temporal Being can act against the source of Its own power -- or rather :|:: Is the Source of Being not Nature?

```
             ╒═╕
              ■
             ╘╦╛
         ╔╤═╦═╬═╦═╤╗
        ╔╣├─╨─╨─╨─┤╠╕
♪   ♪ ♫ ╞╬╡ExoVamp╞╬╡☼ ☼   ☼       ☼             ☼                           ♥
        ╚╣├┬┬┬╥┬┬┬┤╠╛
         ╚╧╧╧╧╬╧╧╧╧╝
             ╒╩╕
              ○
             ╘═╛
```

**Comment by TheBusyBiscuit** [comment]
@mrcoffee1026 Somewhat lazy fix but Tridents are simply no longer affected by the talisman now :P

**Comment by mrcoffee1026** [comment]
Well that's still a fix, thanks!
