### ISSUE TITLE
How to use Charging Bench in Slimefun4?

### ISSUE THREAD

**Issue by Tiande** [TheBusyBiscuit/Slimefun4#103]
## Description
In the Wiki, there has no content about Charging Bench.
I tried to use a battery+Rocket backpack, but nothing happen.

## Server Log
I'm not a Server Admin...

## Environment
Minecraft 1.10.2, Slimefun 4

Thanks！

**Comment by xH3LLRAIZ3Rx** [comment]
did you apply power to the charging bench?

**Comment by Tiande** [comment]
![img](http://i.imgur.com/SnIKmvd.png)
@xH3LLRAIZ3Rx 
I use a lava generator, but the Charging Bench just work like a Crafting Table. 
I put the Jetpack in it and nothing happens.

**Comment by AlexLander123** [comment]
@Tiande  Can you show us the charging bench GUI and the exact version of your slimefun.

**Comment by Tiande** [comment]
@AlexLander123 
The charging Bench's GUI is just like a 3x3  Crafting Table ( and can make things like Crafting Table do ), 
and SlimeFun's Version is 4.0.15.

**Comment by TheBusyBiscuit** [comment]
Thats not a Charging Bench, its a Crafting Table then...
