### ISSUE TITLE
When I break a block it does not drop.

### ISSUE THREAD

**Issue by Laurethan** [TheBusyBiscuit/Slimefun4#1034]
Hello, I have a problem with the plugin, when I break a block with my hand or another object (block tools ...) it does not drop on the ground yet I can drop items on the floor. I know this is not another plugin that poses this problem because when I delete the plugin block drop on the floor. I also noticed that when I take some Slime Fun Guide tools and break a block with the drop block.

Youtube vidéo : https://youtu.be/0dtFo4Cboao

I think there is a problem of configuration or version.

Thanks in advance this plugin is great!
(Translated with Google Translate)

Other information :

 - Minecraft Version:
 - Slimefun Version:
 - CS-CoreLib Version:

Any error in the serveur log.

-CraftBukkit v1_14_R1
 - Minecraft Version: 1.14.2
 - Slimefun Version: vDEV - 150 (git 9476e838)
 - CS-CoreLib Version: vv1.6.1

**Comment by TheBusyBiscuit** [comment]
@dniym

**Comment by Laurethan** [comment]
I tried in the version Slimefun4 - DEV 130 (git c46d1) and there is no block drop problem.

**Comment by TheBusyBiscuit** [comment]
Fixed in build 151
