### ISSUE TITLE
Large Number of Errors

### ISSUE THREAD

**Issue by SuperNar3k** [TheBusyBiscuit/Slimefun4#1035]
I've had a lot of errors in the console. Like A LOT. I have no idea in hell what they mean, but they said "[Slimefun] Exception caught while ticking a Block:java.lang.NullPointerException" and "[Slimefun] Please consider sending this File to the developer(s) of Slimefun, sending this Error won't get you any help though." So uh here I am sending these files to the developer(s) of Slimefun. I have no idea what caused them or what they even do, but I hope it's of some use to you peoples. Now, there are about 20-30 error logs, and I don't want to copy/paste all of them into Pastebin, so I just downloaded them into a zip and uploaded it to a public dropbox. Sorry if its an inconvenience.

https://www.dropbox.com/s/4zzyxex8zwua6i1/mftp_zip_2019_08_25_03_58_17.zip?dl=0

The server is running Spigot 1.14.4, has CS-CoreLib vDEV - 64 (git 9091bb0b), Slimefun vDEV - 143 (git cb702c07), and ExoticGarden vDEV - 17 (git 122f5555) installed, and a couple other plugins (Vault, EssentialsX, PlayerVaults, JobsReborn, Towny, LWC, WorldEdit, WorldGuard, SimpleRename). 

None of these really have a problem with slimefun, and i dont understand the error logs at all. Thank you devs for your amazing plugins and addons!

**Comment by TheBusyBiscuit** [comment]
Update your builds, you are running a bunch of versions late.
Try with Slimefun build 153 and see if the Issue still persists, if so then you may post the Issue again with fresh error-reports.

But please follow the template next time.
