### ISSUE TITLE
All colored enderchest contents empty on server restart

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1036]
## Description (Required)
All items are cleared from all of the color ender chests on the server after every restart of the server.

## Steps to reproduce the Issue (Required)
Place items in any color enderchest.  Revisit that color enderchest after the server restart to see the items be magically gone.

## Expected behavior (Required)
Contents should stay in tact between restarts. 

## Server Log / Error Report
Nothing by way of errors coming up on this.

## Environment (Required)
Paper v1_14_R1 (175)

CS-CoreLib vDEV - 68 (git d7071a19)
Slimefun vDEV - 151 (git 0fad51e2)

Installed Addons (8)
Barrels vDEV - 2 (git 847bc83b)
ExtraGear vDEV - 3 (git de222ab7)
ChestTerminal v1.0
HotbarPets vDEV - 10 (git 7d790905)
ExoticGarden vDEV - 17 (git 122f5555)
SoulJars vDEV - 3 (git ebabf39f)
ElectricSpawners vDEV - 2 (git 49ffa319)
ColoredEnderChests vDEV - 6 (git 6e80c4b)

**Comment by TheBusyBiscuit** [comment]
Can you confirm this as fixed?

**Comment by mrcoffee1026** [comment]
Works now!  Perfect thanks!
