### ISSUE TITLE
Lack of knowledge Error continues to display every 1o seconds or so

### ISSUE THREAD

**Issue by jeddell** [TheBusyBiscuit/Slimefun4#104]
Hi

I just installed Slimefun on my server and some, not all, are complaining that the "You dont have the knowledge" message keeps on displaying in their chat. not all people a re seeing this from what I can see. and I can replicate this.

Some help on troubleshooting this would be great.

Cheers

Jeddell

**Comment by FrostExZo** [comment]
omg..

**Comment by TheBusyBiscuit** [comment]
Sick of you people spamming the issues with this post...

I will change the message to tell you what item it exactly is...
