### ISSUE TITLE
Android Miner bug

### ISSUE THREAD

**Issue by YuriNMDS** [TheBusyBiscuit/Slimefun4#1045]
The android miner don't break blocks in this new version.
I can't have any video, but you can confirm this. The script (break) just don't work.
Don't have any errors in console.

Version: Slimefun vDEV - 153

 - Minecraft Version: 1.14.4
 - Slimefun Version: DEV - 153
 - CS-CoreLib Version: DEV -68

**Comment by TheBusyBiscuit** [comment]
Please follow the format and you will have to post a video of it.
