### ISSUE TITLE
Automated Crafting Chambers Don't Keep the Recipe for Uranium

### ISSUE THREAD

**Issue by Goonhaven** [TheBusyBiscuit/Slimefun4#1047]
## Description
When an Automated Crafting Chamber is fed Tiny Piles of Uranium or Small Chunks of Uranium automatically by Cargo Nodes using Round Robin mode (and not), one or more of the slots representing the crafting recipe disappear so the whole process grounds to a halt. I haven't tested for other items, but it seems to only happen when automatically fed by Cargo Nodes. Manually creating motors / electromagnets is fine.

## Steps to reproduce the Issue
![Chamber Set-Up](https://i.imgur.com/ynIUu0Y.png)
![Full with Uranium](https://i.imgur.com/HfF10F2.png)
![Lost one slot of Uranium](https://i.imgur.com/0WyTw6E.png)
Another example:
![Another example](https://i.imgur.com/kZKYaJj.png)
This time it loses even more slots:
![With the result being more drastic](https://i.imgur.com/DncdXUh.png)

This is how the channels are set up:
![Output node ch 9](https://i.imgur.com/yl9igD8.png)
![Input node ch 10](https://i.imgur.com/D1FJcEx.png)

## Expected behavior
The process of creating Small Chunks of Uranium (and Uranium) should continue without losing the recipe structure.

## Environment

 - Minecraft Version: 1.14.4
 - Slimefun Version: vDEV 242, vDEV-248
 - CS-CoreLib Version: vDEV-69

EDIT: Errors gone, but the above issue remains in the new version.
EDIT2: Errors returned in a different format (others like this one include many other machines): https://pastebin.com/96xfHE8m
EDIT3: Happens in vDEV 248 as well. It ran for a few hours, during which it was fine, before 7 spots were missing, and 2 were filled with Tiny Piles of Uranium. I tested it with extreme lag (down to 8 TPS) and it was fine. So I think what happens is chunks get unloaded and some part of the cargo network messes up. Needs testing with everything in one chunk.

**Comment by Goonhaven** [comment]
I've got a few error reports that seem to happen every half an hour at least. They're for basically every machine in my base and a couple other people's. There is some lag on the server at the moment.

Latest error: https://pastebin.com/Ef5i51iX

Error reports (electric ore grinder, charging bench, ingot factory, gps transmitter, heated pressure chamber, electric gold pan):
https://pastebin.com/SezGYKny
https://pastebin.com/qJdJmBXg
https://pastebin.com/huNzj4s5
https://pastebin.com/3xGaAJi4
https://pastebin.com/7gmKbtrZ
https://pastebin.com/sBCef0pQ

**Comment by TheBusyBiscuit** [comment]
@Goonhaven Note that you are running more than 50 versions behind, so you should probably update to the latest build first.

**Comment by Goonhaven** [comment]
Confirmed still an issue in Slime vDEV 206, and CS-CoreLib vDEV 68. The errors have stopped though.

P.S. Thanks so much for such frequent updates!

**Comment by LinoxGH** [comment]
Unable to reproduce this issue for Slimefun vDEV 246 and CS-CoreLib vDEV 69.

**Comment by Goonhaven** [comment]
Still happens for me in vDEV 242 with CS-CoreLib vDEV 69, will check again after server restarts for the next update today.

**Comment by ajan-12** [comment]
Yeah 242 is a bit old am I right?
