### ISSUE TITLE
Addon items can't be crafted

### ISSUE THREAD

**Issue by TypicalAndy** [TheBusyBiscuit/Slimefun4#1048]
I'm not able to craft any addon items, Im using the right Multiblock.

![grafik](https://user-images.githubusercontent.com/32031536/63780185-0007f480-c8e8-11e9-9288-a5bc361955a5.png)

This image shows the crafting recipe for the Hamburger from Exotic Garden, when I try to craft it it gives me the "Sorry, I could not recognize this Pattern. Please place the Items in the correct Pattern into the Dispenser." Message, yet im doing everything right.

I expected to get the Hamburger Item.

Nothing was in the Server Console.

![grafik](https://user-images.githubusercontent.com/32031536/63780524-891f2b80-c8e8-11e9-8e2e-bc874967c9ec.png)

 - Minecraft Version: 1.14.4
 - Slimefun Version: v1_14_R1
 - CS-CoreLib Version: vv1.6.1

**Comment by TheBusyBiscuit** [comment]
You are using the wrong Machine...

ExoticGarden Food is crafted in a Kitchen.

**Comment by TypicalAndy** [comment]
Ah, alright. The Guide missleaded it then. 
![grafik](https://user-images.githubusercontent.com/32031536/63781650-58d88c80-c8ea-11e9-8a7b-76ccdeaa465b.png)

Im also making sure that I'll report that to the Specific Addon Issue tracker.

**Comment by TheBusyBiscuit** [comment]
Note that you are using a version of ExoticGarden from 2 years ago...
That's why there is no Kitchen and it's not working.
You should probably update...
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExoticGarden/master/

**Comment by TypicalAndy** [comment]
God damn it! I should really take the time to find the stuff. alright, thanks.
