### ISSUE TITLE
If I want to use Charging Bench, I need to hold a Jetpack and Press Shift-key first...

### ISSUE THREAD

**Issue by Tiande** [TheBusyBiscuit/Slimefun4#105]
Just now, after my last issue was closed ([How to use Charging Bench in Slimefun4?](https://github.com/TheBusyBiscuit/Slimefun4/issues/103)) , 
I found how to use the Charging Bench.

**I must hold a Jetpack and Press Shift-key, then the right click can open Charging Bench's GUI correctly.**
Otherwise it just work like a Crafting Table.

I don't know where is the problem, but I think I should report to you.

Forgive my noisy.

## Environment

Minecraft 1.10.2, Slimefun 4.0.15

**Comment by TheBusyBiscuit** [comment]
"Slimefun 4.0.15" You are using a VERY OLD Version...
