### ISSUE TITLE
Corrupted File

### ISSUE THREAD

**Issue by brnxx** [TheBusyBiscuit/Slimefun4#1065]
[12:00:52 WARN]: [Slimefun] Corrupted file detected!
>.... [12:00:52 WARN]: [Slimefun] Slimefun will simply skip this File, but you
>.... [12:00:52 WARN]: [Slimefun] should probably look into it!

what can I do to solve this or find the file corrupt?

Version: Previous version: git-Paper-175 (MC: 1.14.4)

CS-Core: 
CS-CoreLib version DEV - 68 (git d7071a19)
Slimefun: 
[12:29:11 INFO]: Slimefun version DEV - 192 (git 5fa929e6)

**Comment by TheBusyBiscuit** [comment]
You don't have to do anything, you can ignore this message or delete the file.

You can find it under /data-storage/Slimefun/blocks/<world name>/null.sfb
