### ISSUE TITLE
Pressure Chamber (simple machine) not working

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1066]
## Description (Required)
Pressure Chamber does not function, currently.  Nothing happens on right click, no items are used, no error messages given.  Thought this might have affected ALL multiblock issue deal with in build 199 but this problem persists.  (Also while you're at it any chance the recipe for this machine could be updated to use smooth_stone_slab instead of stone_slab for the construction -- purely for the aesthetics of it?)

## Steps to reproduce the Issue (Required)
Try recipe for Synthetic Diamond or Carbonado, for example.

## Expected behavior (Required)
For the items to be produced as normal and items to be used in their production.

## Server Log / Error Report
No error are happening with this, The pressure chamber seems to have been broken through a large number of builds, I've tried all the way back to build 187 and this machine still does not have any functionality.

## Environment (Required)
Paper v1_14_R1 (175)

CS-CoreLib vDEV - 68 (git d7071a19)
Slimefun vDEV - 199 (git 5ec7a27b)

Installed Addons (8)
 Barrels vDEV - 3 (git fa8139b6)
 ExtraGear vDEV - 3 (git de222ab7)
 ChestTerminal vDEV - 12 (git 7e4e61a3)
 HotbarPets vDEV - 16 (git 19414e50)
 ExoticGarden vDEV - 18 (git 0ad817dd)
 SoulJars vDEV - 3 (git ebabf39f)
 ElectricSpawners vDEV - 4 (git 2565651b)
 ColoredEnderChests vDEV - 6 (git 6e80c4ba)

**Comment by TheBusyBiscuit** [comment]
It works just fine for me. (Even the recipes you mentioned)
But I can change the slabs.
