### ISSUE TITLE
table saw infinite wood glitch (again?)

### ISSUE THREAD

**Issue by Sobsz** [TheBusyBiscuit/Slimefun4#1072]
## Description (Required)
using anything that isn't a log block on the table saw (up to and including an empty hand) produces 8 oak wood blocks (`minecraft:oak_wood`)

## Steps to reproduce the Issue (Required)
https://files.catbox.moe/5gp971.mp4

## Expected behavior (Required)
a message along the lines of "sorry, i could not recognize the item you right clicked me with"

## Server Log / Error Report
if using a non-block item: https://gist.github.com/Sobsz/90a2cf728f7511fdd8ed55d67c1adceb
no reported errors otherwise

## Environment (Required)
 - Minecraft Version: 1.14.4 (git-Paper-175)
 - Slimefun Version: vDEV - 209
 - CS-CoreLib Version: v1.6.1

**Comment by TheBusyBiscuit** [comment]
You are using an outdated Version of CS-CoreLib.
