### ISSUE TITLE
Permissions bug or just need the new permission node.

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1079]
## Description (Required)
I am the only user who can access androids or machine interfaces on the server  AT ALL and can either due to my status of OP or permission to *.  In any case this is now how things should be, players should certainly have access to their own machines... or access to machines within claims they have containertrust (GriefPrevetion) in.  Need either an update or a permissions node I can assign to people which is NOT slimefun.inventory.bypass - as I believe that's the only thing that's in place I can use right now to try to combat this issue.

## Steps to reproduce the Issue (Required)
Try to access any electrical machine (whether you placed it or not) with a user that does not have OP status.

## Expected behavior (Required)
Machines should be accessible by the people who placed those machines and since there's no way of providing access to other players within slimefun, slimefun should really not lock down these machines to any other users but let existing plugins on the server handle that sort of thing.

## Environment (Required)
[21:51:20 INFO]: Paper v1_14_R1 (182)
[21:51:20 INFO]:
[21:51:20 INFO]: CS-CoreLib vDEV - 67 (git 1bd1883b)
[21:51:20 INFO]: Slimefun vDEV - 228 (git a4987796)
[21:51:20 INFO]:
[21:51:20 INFO]: Installed Addons (8)
[21:51:20 INFO]:  Barrels vDEV - 7 (git 0d14dd9f)
[21:51:20 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[21:51:20 INFO]:  ChestTerminal vDEV - 13 (git 59336f44)
[21:51:20 INFO]:  HotbarPets vDEV - 16 (git 19414e50)
[21:51:20 INFO]:  ExoticGarden vDEV - 18 (git 0ad817dd)
[21:51:20 INFO]:  SoulJars vDEV - 3 (git ebabf39f)
[21:51:20 INFO]:  ElectricSpawners vDEV - 4 (git 2565651b)
[21:51:20 INFO]:  ColoredEnderChests vDEV - 6 (git 6e80c4ba)

**Comment by mrcoffee1026** [comment]
Oh correction, owner of machines can now open their machines... there is no method of sharing these devices with other people, however.  If there isn't to be a method to unlock or add people to a device ... then I don't want them locked down.

**Comment by TheBusyBiscuit** [comment]
What protection plugins are you using? (All)
You can also post the startup part of your Server log.

**Comment by mrcoffee1026** [comment]
GriefPrevention and ModernLWC although I don't think there's a way to utilize LWC for this... I *might* be able to add things like the terracotta blocks to its config as items it can lock... but it would then be able to lock all terracotta blocks, not just those that were Gold Pans, for instance.  Besides I don't want to add MORE layers of protection, I want to be able to share the machines among users as we were able to do previously, but no longer can.  I also use WorldGuard, but not in any way that would allow or prevent slimefun machine use.  Startup log:
https://pastebin.com/FB5givzh

**Comment by mrcoffee1026** [comment]
probably nothing to do with this issue but moments after startup this error from slimefun appeared:

**Comment by mrcoffee1026** [comment]
https://pastebin.com/N79u6rtN

**Comment by TheBusyBiscuit** [comment]
It is actually WorldGuard, that is causing this to happen.
Can you do /rg info or something like that to get the WorldGuard data for one of these blocks?

**Comment by mrcoffee1026** [comment]
this is happening well outside of worldbuard regions so I do not agree.  Also a worldguard update didn't cause machines to become inaccessible to everyone except for me on a prior build and then only accessible to the person who placed it on a build following that.   /rg info for most machines just return the __global__ region information which has nothing in regards to the various glass and terracotta blocks used for slimefun electric machines.

**Comment by TheBusyBiscuit** [comment]
I repeat:
Can you do /rg info or something like that to get the WorldGuard data for one of these blocks?

**Comment by mrcoffee1026** [comment]
Alright well then you've changed the way sf handles worldguard i suppose.  The machines in my lab used to be shareable now are not.  When I went to some random location to place one it let my alt into it so the region settings are here: https://imgur.com/a/Je6NiFf  what do i need to add to them to allow them to be interacted with?

**Comment by mrcoffee1026** [comment]
nevermind... figured out "use" allows it now.  thanks.
