### ISSUE TITLE
furnaces instant uses fuel

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/Slimefun4#1085]
## Description (Required)

When placing lava or coal blocks in a enhanced furnace x, enhanced furnace xi, ,reinforced furnace and carbonado edged furnace it instant uses 1 block of coal or a lava bucket as show in the video
## Steps to reproduce the Issue (Required)

https://streamable.com/sskkf
https://streamable.com/wkm95
## Expected behavior (Required)

that it should less fuel

## Environment (Required)

 - Minecraft Version:1.14.4
 - Slimefun Version:234
 - CS-CoreLib Version:69

**Comment by xH3LLRAIZ3Rx** [comment]
Can confirm this happens.

**Comment by LinoxGH** [comment]
Working on this.
