### ISSUE TITLE
Cargo Net Spam in Console

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#1087]
## Description (Required)
Some Cargo Nets (but not all of them) are causing spam in console with errors

## Steps to reproduce the Issue (Required)
1: Just place Cargo Net
2: Console Spam

## Expected behavior (Required)
It should not be doing this.

## Server Log / Error Report
https://pastebin.com/YTC6nCzd

## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: vDEV - 234
 - CS-CoreLib Version: vDEV - 68

**Comment by TheBusyBiscuit** [comment]
Your Environment mismatches the versions seen in the error.
It'd also be helpful if you could provide which cargo nets do that, like screenshots or videos.
