### ISSUE TITLE
Cargo Net Spam in Console

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#1088]
## Description (Required)
Spam in console when placing cargo nets

## Steps to reproduce the Issue (Required)
1: Place Cargo Net
2: Place Chest Terminal (Optional)
3: Spam

It still spams without Chest Terminal placed.

https://i.imgur.com/dWE5rK9.png

## Expected behavior (Required)
It should not be doing this.

## Server Log / Error Report
https://pastebin.com/ALYYRPZx

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: vDEV - 234
 - CS-CoreLib Version: vDEV - 68

**Comment by dniym** [comment]
04.09 17:31:46 [Server] Server thread/INFO CS-CoreLib vDEV - 69 (git 2a0d6fcf)
04.09 17:31:46 [Server] Server thread/INFO Slimefun vDEV - 235 (git d5cbb822)
04.09 17:31:46 [Server] Server thread/INFO Installed Addons (1)
04.09 17:31:46 [Server] Server thread/INFO ChestTerminal v1.0

I am unable to reproduce this bug using the above plugin versions.   

http://prntscr.com/p1wxog

Please try updating to the latest versions of slimefun and cs-core and verify the issue still exists.

**Comment by xH3LLRAIZ3Rx** [comment]
I tried, still does it, it seems to only happen in a specific area possibly

**Comment by TheBusyBiscuit** [comment]
Well, according to the error you posted:
Someone has somehow managed to place a Cargo Node on TOP of a block.
This is a State that should normally be unreachable, therefore causing the error.
