### ISSUE TITLE
All of Slimefun's machinery stopped working for no reason, suddenly.

### ISSUE THREAD

**Issue by ThatsCube** [TheBusyBiscuit/Slimefun4#1091]
**Description**

_(Sorry my bad english, i'm italian)_

In short, all of a sudden I realized that machinaries no longer worked, none of them, but the strange thing is that there are no errors and all other slimefun stuff are working normally! 

**for example, backpacks work perfectly.**

With /pl everything appears in green.

**PLUGIN LIST:**
Plugins (33): EZColors, dynmap, LuckPerms, WorldEdit, LoginSecurity, PlaceholderAPI, MySkin, WorldGuard, WolfyUtilities, KixsChatAnnouncer, SurvivalPlus, EasyWhitelist, MOTD, CS-CoreLib, Vault, Statz, SimpleScore, Essentials, CustomCrafting, KillerMoney, ActionHealth, Shopkeepers, Slimefun, BetterSleeping, HotbarPets, SlimefunLuckyBlocks, EssentialsChat, ExoticGarden, Barrels, SoulJars, EssentialsSpawn, ExtraGear, PrivateStorage

I don't have videos and a screenshot can't help, but every time I use the machines it's like they're disabled, I tried to restart, but nothing.

**Server Log / Error Report**
_No log error!_ this is so strange!!

I have NEVER done /reload or /spigot reload but I always restart from the multicraft panel.

 - Minecraft Version: 1.14.4
 - Server: Spigot 
 - Slimefun Version: DEV 236
 - CS-CoreLib Version: DEV 69

**How can I fix it quickly? reinstalling slimefun?**

**Comment by ThatsCube** [comment]
How can I fix it quickly? reinstalling slimefun?

**Comment by TheBusyBiscuit** [comment]
This was already fixed in #1090
