### ISSUE TITLE
Slimefun Multiblock Machines Broken

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#1093]
## Description (Required)
The multiblock machines are broken

## Steps to reproduce the Issue (Required)
1: make multiblock
2: right click
3: NPE in console

## Expected behavior (Required)
It should work as intended

## Server Log / Error Report
https://pastebin.com/0hZfpjsJ
theres nothing under the caused by, I tried to find it but it never showed

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: vDEV - 240 (git 26750e5c)
 - CS-CoreLib Version: vDEV - 69 (git 2a0d6fcf)

**Comment by TheBusyBiscuit** [comment]
Post the full error next time....
I had to start up a Minecraft Server at 2 Am because of you...

**Comment by xH3LLRAIZ3Rx** [comment]
That was the full error...

There was nothing at all after the Caused by:

**Comment by TheBusyBiscuit** [comment]
It wasn't.
And there was. There always is.

Seriously, don't even bother posting incomplete error messages, they are just useless.

**Comment by xH3LLRAIZ3Rx** [comment]
Shit sorry, I guess most of the errors didn't show but one actually did show properly at the very top, I apologize.

**Comment by TheBusyBiscuit** [comment]
Oh yeah, they get trimmed by some Servers after a while.
So just scroll up till you find a full stacktrace in the future.
