### ISSUE TITLE
Wrong item message on Automated Panning Machine

### ISSUE THREAD

**Issue by Kokersito** [TheBusyBiscuit/Slimefun4#1095]
## Description (Required)
Wrong item message appears even when right-clicking with gravel.

## Steps to reproduce the Issue (Required)
Right-click the Panning Machine with gravel in hand.

## Expected behavior (Required)
That no error appears.

## Server Log / Error Report
Nothing.

## Environment (Required)
Paper v1_14_R1

CS-CoreLib vDEV - 69 (git 2a0d6fcf)
Slimefun vDEV - 242 (git 92938083)

Installed Addons (3)
 ExtraGear vDEV - 3 (git de222ab7)
 PrivateStorage vDEV - 5 (git aee2d472)
 ColoredEnderChests vDEV - 6 (git 6e80c4ba)

 - Minecraft Version: 1.14.4
 - Slimefun Version: DEV 242
 - CS-CoreLib Version: DEV 69

**Comment by Kokersito** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/blob/92938083579d88f27b36e0fef6e94881e738304e/src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/multiblocks/AutomatedPanningMachine.java#L67

maybe this has something to do with it?

**Comment by TheBusyBiscuit** [comment]
It would have been helpful if you posted that message...
