### ISSUE TITLE
Rainbow Glass/Pane/Wool/Clay

### ISSUE THREAD

**Issue by Fluffy-7** [TheBusyBiscuit/Slimefun4#1098]
## Description (Required)
Rainbow Glass - Rainbow Glass Pane - Rainbow Wool - Rainbow Clay.
Those items don't change the color and dissappear after a few seconds. 3 to 5 seconds.

## Steps to reproduce the Issue (Required)
The player who put the blocks is in survival mode. But you can reply this in Creative too.
https://imgur.com/sdv1u1k

## Expected behavior (Required)
When you put the blocks, they should change color (type of block).
## Server Log / Error Report
Rainbow Wool » https://pastebin.com/raw/fZdV4u0t
Rainbow Glass » https://pastebin.com/raw/4kEfxt8Z
Rainbow Glass Pane » https://pastebin.com/raw/pxGMLSGz
Rainbow Clay » https://pastebin.com/raw/xusvM0qp

## Environment (Required)
https://imgur.com/a/zF87cdh

**Comment by Goonhaven** [comment]
This happens in vDEV 242 CS-CoreLib v69 as well, but they don't disappear.

**Comment by Fluffy-7** [comment]
This happend anywere in the world.. with protection or not.
