### ISSUE TITLE
Boot of the Stomper can "kill" the totem of undying

### ISSUE THREAD

**Issue by Fluffy-7** [TheBusyBiscuit/Slimefun4#1104]
## Description (Required)
If the area don't have the flag "tnt deny" the boots hurts the player or can kill him. If the player have the Totem, the boots take off that item and the player is save.
## Steps to reproduce the Issue (Required)
[Test video](https://imgur.com/6Flk88F)
- 2 Players
- 1 with the boots / other with the totem
- The player with the boots must fall from a moderate height
-- The player with the totem take damage. If the damage is to much, the player dies and the totem is used. If the damage is moderate, the player only loses a few hearts. --

## Expected behavior (Required)
The boots can't hurt or kill players in protected areas.
As the "Test video" show, the players are in a protected area (spawn) withe this [flags](https://imgur.com/3U9ctCs)
If I put the flag "tnt deny", players are save. This should not happen, since it is a protected area and the boots shouldn't hurt

## Server Log / Error Report
Clean, no errors. Just an inssue.

## Environment (Required)
[Versions info](https://imgur.com/ifbV7r5)

**Comment by LinoxGH** [comment]
Boots don't create a tnt but rather act like they attack you so IDK if this is a valid bug.

**Comment by Fluffy-7** [comment]
Yes.. but like in the video.. the boots can damage you in a protected zone. I use the Totem, so the boots dont kill me.. just kill the totem

**Comment by LinoxGH** [comment]
Then this is a bad named issue.

"Boots of Stomper deal damage in no-pvp areas."
Describes this issue better.

**Comment by Fluffy-7** [comment]
I think I managed to explain things better.
