### ISSUE TITLE
oregrinder opening wrong interface

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/Slimefun4#1106]
## Description (Required)
when you right click a ore grinder with a slimefun book you open the furnace interface

## Steps to reproduce the Issue (Required)
https://streamable.com/f2cf4

## Expected behavior (Required)
to open the sf book or the ore grinder interface

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: 248
 - CS-CoreLib Version: 69

**Comment by TheBusyBiscuit** [comment]
Please give your Issues a proper title... "oregrinder" does not give any info on what the Issue will be about.

**Comment by J3fftw1** [comment]
> 
> 
> Please give your Issues a proper title... "oregrinder" does not give any info on what the Issue will be about.

i updated the title

**Comment by TheBusyBiscuit** [comment]
Well is it all Machines or only Ore Grinders?
Is it all Ore Grinders or just this one?
Does it open the normal interface when you don't use a book?
Did you check that it actually IS an Ore Grinder using the debug fish?
