### ISSUE TITLE
Teleport Not Working

### ISSUE THREAD

**Issue by Thezerix** [TheBusyBiscuit/Slimefun4#1111]
## Description (Required)
When trying to teleport, upon first opening teleport it shows waypoints as it shoud, but it does not teleport. Afterwards it doesnt even show menu.

## Steps to reproduce the Issue (Required)

Build Teleport (only tested with shared) and try to teleport

## Expected behavior (Required)

Teleport you.

## Server Log / Error Report

None

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: DEV 249
 - CS-CoreLib Version: DEV 69

**Comment by TheBusyBiscuit** [comment]
You need to give much much more explanation than that...
A video would be best.
Just saying "try it yourself" is not helpful.
