### ISSUE TITLE
slimefun elevator book replacing item

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/Slimefun4#1114]
## Description (Required)
when you step on the slimefun elevator it replaces the item ur holding for the book

## Steps to reproduce the Issue (Required)
https://streamable.com/qf79c

## Expected behavior (Required)
to add it to the inventory not replace the item

## Environment (Required)

 - Minecraft Version: 1.14.
 - Slimefun Version: 248
 - CS-CoreLib Version: 69

**Comment by TheBusyBiscuit** [comment]
You are using quite outdated versions.
Update CS-CoreLib and Slimefun before posting an Issue.
