### ISSUE TITLE
[Suggestion] Add event for Cargo Network

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#112]
## Description
Apologies if this is already available, but I couldn't find info on it. My suggestion is to add an event for the Cargo Network so plugins can listen to when items are inserted or removed from inventories. This would make it possible to increase compatibility with the Slimefun Cargo systems and "custom" blocks from other plugins that operate when items are inserted into them. The event should probably include the same information as the InventoryMoveItemEvent. Alternatively, calling the InventoryMoveItemEvent, if possible, would probably be a better approach.

**Comment by AlexLander123** [comment]
Was just about to request for this event. xD +1

**Comment by TheBusyBiscuit** [comment]
BlockMenu#registerEvent() for adding a Listener to a specific SlimefunItem

but I have no idea what you are talking about.
Please make it clear what kind of event you mean...
per-block listeners are a thing.

**Comment by BlackBeltPanda** [comment]
As an example, I have a container that needs to do something when an item is inserted into it. Currently, it listens to the InventoryMoveItemEvent, which allows it to operate when a hopper inserts an item into it. It'd be great if there was an event it could listen to so it can operate when an Output Node inserts an item into it.

**Comment by TheBusyBiscuit** [comment]
Make it a SlimefunItem, add a BlockMenu, add a Listener...

BlockMenu#registerEvent()

**Comment by TheBusyBiscuit** [comment]
If you want to work with Vanilla Inventories such as Chests, then you can use the ChestManipulator class I just added:

ChestManipulator.registerListener()
