### ISSUE TITLE
EXPLOSIVE_SHOVEL not decrease, Capacitance Data create a null.sfb

### ISSUE THREAD

**Issue by EterLzb** [TheBusyBiscuit/Slimefun4#1121]
# One:
## Description (Required)
`damageItem(e.getPlayer(), item);` is not work,
when I use the EXPLOSIVE_SHOVEL, durability will not decrease.
I guess the 'isDamageable()' is not work.
## Steps to reproduce the Issue (Required)
use the EXPLOSIVE_SHOVEL
## Expected behavior (Required)
Durability decreases
## Server Log / Error Report
None
## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: Slimefun4 - DEV 252 (git 25ee0)
 - CS-CoreLib Version: CS-CoreLib - DEV 76 (git aaef2)
# Two:
## Description (Required)
Text Error Storing Capacitance Data.
It will create a null.sfb in /data-storage/Slimefun/stored-blocks
## Steps to reproduce the Issue (Required)
Place a capacitor next to the power core, remove the capacitor, place the capacitor again,and then restart the server.
## Expected behavior (Required)
Capacitance data should be recorded correctly.
## Server Log / Error Report
[21:12:40 WARN]: [Slimefun] Corrupted file detected!
[21:12:40 WARN]: [Slimefun] Slimefun will simply skip this File, but you
[21:12:40 WARN]: [Slimefun] should maybe look into it!
[21:12:40 WARN]: [Slimefun] data-storage/Slimefun/stored-blocks/world/null.sfb
## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: Slimefun4 - DEV 252 (git 25ee0)
 - CS-CoreLib Version: CS-CoreLib - DEV 76 (git aaef2)

**Comment by TheBusyBiscuit** [comment]
1. Don't post two issues in once.
2. Write a proper description "It doesn't work" is not helpful at all.
3. Try to post at least something of value, again saying "it doesn't work" is not helpful.
4. You can ignore the warning, it is a warning, not an error...
