### ISSUE TITLE
Explosive Shovel durability not decrease

### ISSUE THREAD

**Issue by EterLzb** [TheBusyBiscuit/Slimefun4#1122]
## Description (Required)
when I use the Explosive Shovel, durability will not decrease.
I guess the
```
@Override
	public boolean isDamageable() {
		return damageOnUse;
	} 
```
is not work.
## Steps to reproduce the Issue (Required)
use the Explosive Shovel to break some blocks.
## Expected behavior (Required)
Durability will decreases.
## Server Log / Error Report
None
## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: Slimefun4 - DEV 252 (git 25ee0)
 - CS-CoreLib Version: CS-CoreLib - DEV 76 (git aaef2)

**Comment by TheBusyBiscuit** [comment]
Did you even enable "damage-on-use"...?

**Comment by EterLzb** [comment]
> Did you even enable "damage-on-use"...?

ahhh, I haven't seen this option before.
I'm sorry to waste your time.
