### ISSUE TITLE
Smeltery Multiblock causes dispenser to not show gui

### ISSUE THREAD

**Issue by ice4ed** [TheBusyBiscuit/Slimefun4#1129]
## Description (Required)

Smeltery Multiblock, when placed correctly, does not allow opening of dispenser gui and the nether fence does not produce any messages like unknown recipe like it normally would. If I break the multiblock dispenser functions normal.

## Steps to reproduce the Issue (Required)

1. Create Smeltery Multiblock
2. Right-Click Smeltery
3. No Response

## Expected behavior (Required)

A message of unknown recipe or when items are in (if placed before making into a multiblock) a item output into the dispenser

## Server Log / Error Report

https://pastebin.com/w7wahCaj

## Environment (Required)

 - Minecraft Version: Minecraft 1.14.4 
 - Minecraft Server Jar: CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4)
 - Slimefun Version: Slimefun4 - #266
 - CS-CoreLib Version: CS-CoreLib - #76

I ran this with many server plugins and without any server plugins both produced the same error log where right clicking a dispenser caused the "Could not pass event PlayerInteractEvent to Slimefun vDEV - 266" error to happen.

**Comment by TheBusyBiscuit** [comment]
If an Error occured, then post it...

**Comment by ice4ed** [comment]
I'm sorry I formatted the link wrong and made it hide in the comments section, it should be fixed now. My apologies.

**Comment by mrcoffee1026** [comment]
Can't smelt anything in build 267 now.  I get the gui but nothing smelts when I click the fence, don't even get a "I could not recognize the recipe" message if I leave it empty and click the fence.

**Comment by WalshyDev** [comment]
You don't need to message on multiple issues. Especially a closed one, isn't going to do much.
