### ISSUE TITLE
Can't place Cargo Input/Output nodes on top or below containers

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#113]
## Description
When trying to place an input node on the top of a container, such as a chest, I receive the error, "Must be placed onto a Chest or Machine". When trying to place the node on the bottom of a container, no error is printed but the node doesn't place.

## Evidence / Proof
Placing on top: https://i.gyazo.com/e6160deaf0248abef9c298f2f9dd0240.mp4
Placing on bottom: https://i.gyazo.com/a51d5439451960defff67f51ad9c948f.mp4

## Environment
MC version: 1.11.2 (git-Paper-1032)
CS-CoreLib version: 1.5.12
Slimefun version: 4.1.1

**Comment by TheBusyBiscuit** [comment]
Message may not be the best but its supposed to be that way...
