### ISSUE TITLE
lumberaxe doesnt break stripped wood and wood

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/Slimefun4#1135]
## Description (Required)
when you break stripped wood or normal wood with a lumberaxe, it doesnt break the tree it registers it as not a wood type like it breaks as normal wood.

## Steps to reproduce the Issue (Required)
place down or find a custom tree that uses it
break the wood / stripped wood with the lumberaxe

## Expected behavior (Required)
expected behavior is to see it break all the connected wood, stripped wood, logs and stripped logs

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: 269
 - CS-CoreLib Version: 76

**Comment by TheBusyBiscuit** [comment]
This Bug is a false positive.
It does not occur, the Lumber Axe already supports all versions of logs, wood and their stripped variants.
