### ISSUE TITLE
Saw Table making wood without any wood logs

### ISSUE THREAD

**Issue by SuperSlimey5** [TheBusyBiscuit/Slimefun4#1151]
If i right click the Saw Table without anything it gives me wood logs.

![2019-10-04_18 22 31](https://user-images.githubusercontent.com/47258749/66192222-57f9fe00-e6d3-11e9-83ff-74faa9a4dcb1.png)
![2019-10-04_18 22 27](https://user-images.githubusercontent.com/47258749/66192223-57f9fe00-e6d3-11e9-92cf-528c698e377b.png)

![Capture](https://user-images.githubusercontent.com/47258749/66192159-37ca3f00-e6d3-11e9-8a90-cea8e2ed2341.JPG)

**Comment by WalshyDev** [comment]
Update SF and CS-CoreLib.
