### ISSUE TITLE
The water will wash away the machine

### ISSUE THREAD

**Issue by Longcg** [TheBusyBiscuit/Slimefun4#1156]
## Description (Required)
The water will wash away the head disguised as a machine. After the machine is washed away, it will become "CSCoreLib's head". This place can no longer place the square. After the water washes away the machine, the console will not report the error immediately, but the console will An error is generated at other times.

## Steps to reproduce the Issue (Required)
https://youtu.be/Ie0ipzwCql4

## Expected behavior (Required)
I hope that the machine will not be washed away by water, and the console will not make mistakes.（I have been troubled by this problem for many days, and I can't solve it.My English may not be very good, thank you very much.）

## Server Log / Error Report
https://pastebin.com/GCzeYw0g

## Environment (Required)

 - Minecraft Version: 1.14.4   Paper v1_14_R1(paper#209)
 - Slimefun Version:  vRC-2(git 4bb9abd2)
 - CS-CoreLib Version: v1.6

**Comment by J3fftw1** [comment]
im on dev build and my CS-CoreLib version is more up to date but it doesnt get washed away at sf version vDEV 278 and Cs-CoreLib 76
i would advice updating CS-CoreLib
