### ISSUE TITLE
Explosive pickaxe not functional.

### ISSUE THREAD

**Issue by teamaonn** [TheBusyBiscuit/Slimefun4#116]
!!! BEFORE POSTING !!!

1. Do not adress Issues that don't regard Slimefun, even Issues about Slimefun Addons are not allowed to be posted here. - Main Plugin, check.
2. Make sure to check other Issues before posting yours, we do not want any duplicates! - Didn't see any.
3. Your Issue will be CLOSED WITHOUT WARNING if you do not match the above mentioned criteria.

## Description
When using the explosive pickaxe, either enchanted or unenchanted, to mine any block, an explosion should occur but does not. Normal particles seem to happen as they should but only one block is mined.

## Server Log
Wasn't generated, but i was happy to copy the errors I was seeing, plus added data from some other slimefun error logs to help out. Only plugins out of date listed there are slimefun which I updated after seeing the issue for the first time.

http://pastebin.com/ZUzvw5R0

## Evidence / Proof
https://youtu.be/PdMHjXgk9h4

## Environment
Slimefun is 4.1, also happened after upgrade to 4.1.1, Cscorelib is 1.5.12. Minecraft server runs on Spigot Version 1.11.

**Comment by TheBusyBiscuit** [comment]
Try updating WorldGuard.

**Comment by teamaonn** [comment]
Okay, I'll look into that Immediatly. Thank you. i will let you know the result.

**Comment by teamaonn** [comment]
Updated worldguard to 6.2, same issue appears

**Comment by teamaonn** [comment]
I have a quick question. Should I remove world guard, would things function normally again?

**Comment by TheBusyBiscuit** [comment]
I don't know.
But the error you attached is a WorldGuard protection check failing...

**Comment by teamaonn** [comment]
it looks like the same error with this one. Let me generate it for you.

**Comment by teamaonn** [comment]
http://pastebin.com/i6HVyuaD - Updated error

**Comment by teamaonn** [comment]
Yes, removing worldguard solved this issue. I will reinstate it when they fix the error on their end.
