### ISSUE TITLE
Smeltery glitch

### ISSUE THREAD

**Issue by amxrmxhdx** [TheBusyBiscuit/Slimefun4#1163]
## Description (Required)
Gold dust + Goldingot 24K + Gold ingot = goldingot(unlimited)

## Steps to reproduce the Issue (Required)
[https://workupload.com/file/cpBNu5pD](Link)

## Expected behavior (Required)
It should not give out unlimited gold ingots, that's a glitch.

## Environment (Required)
Paper v1_14_R1
CS-CoreLib vDEV - 75 (git ed542c05)
Slimefun vDEV - 284 (git b36f9cd3)

**Comment by TheBusyBiscuit** [comment]
Update.
