### ISSUE TITLE
Block placer put empty shulker boxes

### ISSUE THREAD

**Issue by clementgallois** [TheBusyBiscuit/Slimefun4#1164]
## Description (Required)
Using a block placer with a shulker box containing items place an empty shulker box instead

## Steps to reproduce the Issue (Required)
- fill a shulker box with any items
- put it in a block placer
- put the shulker box in the block placer
- activate the block placer
- the shulker box is empty

## Expected behavior (Required)
the placed shulker box should be the same (filled) as the one put in the block placer

## Server Log / Error Report
No console errors to report

## Environment (Required)

 - Minecraft Version: git-paper-192
 - Slimefun Version: vDEV 276
 - CS-CoreLib Version:

**Comment by J3fftw1** [comment]
Any item that stores nbt data breaks when its being placed with blockplacer
