### ISSUE TITLE
Electric Ore Grinder Does not Open Interface

### ISSUE THREAD

**Issue by Augies** [TheBusyBiscuit/Slimefun4#1166]
## Description (Required)
When interacting with Electric Ore Grinders in the Latest Dev. Build, the interface fails to appear, instead showing a default furnace interface.
<img src = "https://i.imgur.com/LjefK7h.png"></img>

## Steps to reproduce the Issue (Required)
1. Place an Electric Ore Grinder (Tier 1 or 2)
2. Right click to attempt to open the interface

## Expected behavior (Required)

Open an interface such as this but for the electric ore grinder
<img src = "https://i.imgur.com/tKnhCEu.png"></img>

## Server Log / Error Report

No Relevant information appeared in logs

## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: vDEV - 290 (git 58889c46)
 - CS-CoreLib Version: v1.6.1

**Comment by TheBusyBiscuit** [comment]
Have you tried placing a new one down...?

**Comment by Augies** [comment]
> Have you tried placing a new one down...?

Yup. Also tried restarting the server and individually reloading the plugin

**Comment by J3fftw1** [comment]
try updating CS-CoreLib

**Comment by mrcoffee1026** [comment]
I think it may just be mismapped in the .sfb files.  (can happen when moving slimefun blocks around sometimes) You can check with your /sf debug_fish (need creative mode to use it).  If you right click it'll probably tell you the block is a gold pan of some level.  you can shift+left click this block to clear its block data... then break it and place a new one to resolve the issue - if that's what it is.  When I place a new one, the interface opens normally and my old ones also open normally, so I don't think it's the plugin itself.

**Comment by Augies** [comment]
Latest Dev Build of CS-CoreLib fixed the issue. Just broken for v1.6.1 I suppose. It was not an issue with the .sfb files but rather an outdated cs-corelib
