### ISSUE TITLE
Slimefun installs, creates config files, and then stops working.

### ISSUE THREAD

**Issue by Void-25** [TheBusyBiscuit/Slimefun4#1168]
## Description (Required)
I installed slimefun, started the server, it said i had to restart it, so i did, after that it said that it updated and i needed to restart again, so i did, it made some config files and acted like everything was fun but when i went in game and did /sf guide it didn't do anything, so i checked /plugins and it doesn't even show up there...
It's like it's not even installed.
(After checking the logs the only mention i find of slimefun is that it failed to load, but the first two times i started the server it did load, and it told me to restart...)

## Steps to reproduce the Issue (Required)
All i did was install it and cs-corelib.

## Expected behavior (Required)
I expected it to install, and then work like it should.

## Server Log / Error Report
https://pastebin.com/1vgpcqQp
## Environment (Required)

 - Minecraft Version: 1.9.4
 - Slimefun Version: 4.0.9
 - CS-CoreLib Version: 1.6.1

**Comment by WalshyDev** [comment]
A bunch of your files seem fucked, your SF, CS-CoreLib and SilkSpawners all are empty jar files. You can download the latest SF for 1.9 here - https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#52

You'll need to find which CS-CoreLib to go with it. As for Silkspawners... I guess you'll need to re-download and put that in (Make sure it's again correct to your MC version) then disable auto-updates so they don't go to one unsupported for your MC ver.

either way, this isn't a bug, just you have fucked files.

**Comment by Void-25** [comment]
> A bunch of your files seem fucked, your SF, CS-CoreLib and SilkSpawners all are empty jar files. You can download the latest SF for 1.9 here - https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#52
> 
> You'll need to find which CS-CoreLib to go with it. As for Silkspawners... I guess you'll need to re-download and put that in (Make sure it's again correct to your MC version) then disable auto-updates so they don't go to one unsupported for your MC ver.
> 
> either way, this isn't a bug, just you have fucked files.

Thank you, i'l download it again and see if it works, i guess silkspawners is also fucked then... it's like everything on my server just wants to break xD
