### ISSUE TITLE
not being able to go back to the homepage

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/Slimefun4#1170]
## Description (Required)

When you use the sf search function via the book. and click a item to see the recipe do that for another item and another then trying to go back to the main page of the sf book your not able to (for anyone who trys it reloging fixes it)
also doesnt work all the time
## Steps to reproduce the Issue (Required)

https://streamable.com/1w72g
open the sf guide
click search
type in a name or what i did a "A"
click a recipe, click in that recipe a item, click in that item another item
go back and ur stuck

## Expected behavior (Required)

being able to go back to the main page

## Environment (Required)

 - Minecraft Version:1.14.4
 - Slimefun Version:76
 - CS-CoreLib Version:293

**Comment by TheBusyBiscuit** [comment]
You can literally do shift-click...
It literally says it there on the tooltip.
