### ISSUE TITLE
Players unable to place/interact

### ISSUE THREAD

**Issue by Sniddunc** [TheBusyBiscuit/Slimefun4#1180]
## Description (Required)
Players are unable to build/interact in one of the latest dev builds. My guess is that it's a cancelled PlayerInteractEvent, but I am currently unable to check the code myself. I have tested on various spigot/paper versions on a few machines and the issue always persists. Downgrading to the latest stable build fixed it.

## Steps to reproduce the Issue (Required)
Install [dev build 303](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#303)

## Expected behavior (Required)
PlayerInteractEvent wouldn't be cancelled.

## Server Log / Error Report
**There are no error messages whatsoever.**

## Environment (Required)
Paper v1_14_R1
 - Minecraft Version: 1.14.4
 - Slimefun Version: DEV 303 (git 090f45d9)
 - CS-CoreLib Version: 1.6.1

**Comment by Sniddunc** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/1179#issuecomment-541498615

**Comment by cattoyt** [comment]
I have the same problem running 
Paper v1_14_R1

Minecraft Version: 1.14.4
Slimefun Version: DEV 303 (git 090f45d)
CS-CoreLib Version: 1.6.1

After downgrading the problem persisted and I disabled SlimeFun it started letting me placeblocks again
