### ISSUE TITLE
Alot of items missing from Energy & Electricity

### ISSUE THREAD

**Issue by itslukemango** [TheBusyBiscuit/Slimefun4#1185]
## Description (Required)

Theres a ton of items missing from Energy & Electricity
## Steps to reproduce the Issue (Required)

I have no idea what happened, we had them, reboot and they were all gone from /sf guide
## Expected behavior (Required)

Items not to be gone, they're enabled in our SF configs
## Server Log / Error Report

There's no errors from Slimefun in the console, it randomly happened over a reboot.
## Environment (Required)

 - Minecraft Version: Paper git 214 [1.14.4]
 - Slimefun Version: vDEV - 309
 - CS-CoreLib Version: vDEV - 77
![image](https://user-images.githubusercontent.com/29614155/66855050-6b7e5200-ef7a-11e9-930e-2828726f385d.png)

- If you need any configs etc, please let me know; this is really odd to me.

**Comment by J3fftw1** [comment]
update slimexpension

**Comment by itslukemango** [comment]
Tried that, didn't fix it :/

**Comment by J3fftw1** [comment]
what items are missing?

**Comment by itslukemango** [comment]
Like half of the items in Energy and Electricity, I can't name them all because theres so many gone

**Comment by WalshyDev** [comment]
Are they SF items or from an addon?

**Comment by itslukemango** [comment]
Generic SF items
