### ISSUE TITLE
Cargo Nodes should listen for canAccessChest()

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#119]
## Description
Using the Cargo system, you're able to remove items from chests protected with Lockette. It'd be awesome if it could prevent players from abusing this.

## Evidence / Proof
GIF: https://i.gyazo.com/53c7de0a0de53d5575358ab0b64ae75b.gif

## Environment
MC version: 1.11.2 (git-Paper-1032)
CS-CoreLib version: 1.5.12
Slimefun version: 4.1.1

**Comment by DaddyElf** [comment]
Explosive pickaxe also ignores Lockette protections.

**Comment by Poslovitch** [comment]
@TheBusyBiscuit You should close this issue -> done in https://github.com/TheBusyBiscuit/Slimefun4/commit/07dbfbd318916c7f70c8773e586011768e9598a5
