### ISSUE TITLE
Tons of items dissapear in Versions #309 and above

### ISSUE THREAD

**Issue by itslukemango** [TheBusyBiscuit/Slimefun4#1193]
## Description (Required)

Tons of items dissapear in Versions #309 and above, no longer in guide etc
## Steps to reproduce the Issue (Required)

Update to 309?
## Expected behavior (Required)

Not to dissapear
## Server Log / Error Report

No errors
## Environment (Required)

 - Minecraft Version: 1.14.4
 - Slimefun Version: 309
 - CS-CoreLib Version: 77

**Comment by itslukemango** [comment]
My previous ticket was closed but the issue was never resolved

**Comment by J3fftw1** [comment]
I tried to recreate and i had no missing items.

Maybe join the discord and ask for help there
