### ISSUE TITLE
Explosive item broken

### ISSUE THREAD

**Issue by firebl0od** [TheBusyBiscuit/Slimefun4#1195]
## Description (Required)
Whenever you use an explosive pickaxe or an explosive shovel, it doesn't mine the area it should. it mine normaly

## Steps to reproduce the Issue (Required)
get an explosive pickaxe or an explosive shovel on latest slimefun dev version

## Expected behavior (Required)
the behavoir of explosive stuff

## Server Log / Error Report
no server error

## Environment (Required)

![](https://i.gyazo.com/bc764738b91ee9db1f15e26c67bf0669.png)

**Comment by J3fftw1** [comment]
same issue for 
* diet cookie
* monster jerky
* Sword of beheading
* Hercules pickaxe
* talisman of hunter
* pickaxe of containment
* pickaxe of vein mining
* Smelters pickaxe
* soulbound rune

**Comment by J3fftw1** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/pull/1197 
fixed in this pr
