### ISSUE TITLE
Error in console after updating to Slimefun DEV - 316 (git 260c3a51)

### ISSUE THREAD

**Issue by sglorch** [TheBusyBiscuit/Slimefun4#1200]
## Description (Required)
When starting the server, an error appears when Slimefun is trying to load Items.

## Steps to reproduce the Issue (Required)
Update to latest build found on https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

## Server Log / Error Report
https://pastebin.com/qLXD5Kzn

## Environment (Required)

 - Minecraft Version: git-paper-218 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
 - Slimefun Version: vDev - 316 (git 260c3a51)
 - CS-CoreLib Version: vv1.6.1

**Comment by J3fftw1** [comment]
Also update cscorelib
