### ISSUE TITLE
TPS spike when destroying many blocks

### ISSUE THREAD

**Issue by killianperez** [TheBusyBiscuit/Slimefun4#1204]
## Description (Required)
When the player destroys a lot of blocks in a short time, TPS falling down when destroying many blocks.
NOTE: The all things is lagging except the player who breaks the blocks

## Steps to reproduce the Issue (Required)
1. Enchant a diamond pickaxe with Efficiency X, Fortune X, Unbreaking X and Mending
2. Go and mine without stopping.

Video: https://youtu.be/NXMv1FVY5Vc
Timings: https://timings.aikar.co/?id=e0788b1be4404c308c7c7103d31cce29

## Expected behavior (Required)
TPS Freeze or crash.

## Server Log / Error Report
Error report No1: https://pastebin.com/embed_js/eD0kuh9b/noheader
Error report No2: https://pastebin.com/embed_js/SWS51jcB/no_header
Error report No3: https://pastebin.com/embed_js/VMCud1qG/no_header

## Environment (Required)

 - Minecraft Version: 1.14.4 (Paper v1_14_R1)
 - Slimefun Version: vDEV - 321 (git ad3ca513)
 - CS-CoreLib Version: vDEV - 78 (git 199e1b1e)
 - Installed Addons (14):
		Barrels vDEV - 7 (git 0d14dd9f)
		SlimeXpansion vDEV - 4 (git 5bf10c29)
		ExtraGear vDEV - 3 (git de222ab7)
		SkUniversal v2.6
		ChestTerminal vDEV - 17 (git 933a7d36)
		HotbarPets vDEV - 20 (git cd87bc60)
		SlimefunLuckyBlocks vDEV - 15 (git 53d7e43d)
		ExoticGarden vDEV - 22 (git a855f5b7)
		SoulJars vDEV - 4 (git 4a600aa2)
		SlimefunOreChunks vDEV - 2 (git 24d90a3e)
		ElectricSpawners vDEV - 5 (git c3f8cc9d)
		ExtraHeads v1.1
		PrivateStorage vDEV - 6 (git b012877e)
		ColoredEnderChests vDEV - 7 (git 6885cb88)

**Comment by J3fftw1** [comment]
I checked ur timings report but it shows that ultimate stacker is lagging ur server
Slimefun only uses 0.5% of the resources

**Comment by killianperez** [comment]
I  put UltimateStacker plugin because I think that lag caused by drops.
It's very clear that UltimateStacker is falsifying my timings.

So I removed everything except: Barrels, ChestTerminal, ColoredEnderChests, CS-CoreLib, ElectricSpawners, ExoticGarden, ExtraGear, ExtraHeads, HotbarPets, PacketListenerApi*, PrivateStorage, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimeMobs*, SlimeXpansion, SoulJars

And the problem still continue... https://timings.aikar.co/?id=772b969ca5ce418897bc6d1ad74d41de
98% tps loss and 6 tps while I mined

**Comment by J3fftw1** [comment]
is the pickaxe from slimefun or is it from something else

**Comment by killianperez** [comment]
We tested w/ Explosive pickaxe and cobalt pickaxe... The result is: no lag

So, I rem Extraheads → Same Results
Afterthat, I rem skUniversal (always w/o Extraheads) → Same results

**Comment by J3fftw1** [comment]
Join the discord
