### ISSUE TITLE
Reactor access port not working

### ISSUE THREAD

**Issue by LoutreBleue** [TheBusyBiscuit/Slimefun4#1207]
## Description (Required)

When a reactor access port is connected to a nuclear reactor, the items in the reactor access port that are supposed to go into the reactor disappear

## Steps to reproduce the Issue (Required)

Build a reactor normally and connect it to a reactor access port and then put items in the reactor access port

## Expected behavior (Required)

That the items in the reactor access port go well in the reactor

## Server Log / Error Report

No error

## Environment (Required)

![Sf versions](https://user-images.githubusercontent.com/57031748/67617251-9a4dc100-f7e1-11e9-8372-71c8b23dbf4e.png)

**Comment by EnderBro123** [comment]
Update to Build 124.
