### ISSUE TITLE
[Request] 1.13 backwards compatibility

### ISSUE THREAD

**Issue by Leomelonseeds** [TheBusyBiscuit/Slimefun4#1209]
Ever since the 1.14 builds came out, a lot of good updates and builds have gone by without 1.13 backwards compatibility. Are there any plans for this?

Thanks in advance.

**Comment by WalshyDev** [comment]
Why not just update your server? Adding 1.13 support will have performance penalties and generally be a pain considering we're using things specifically in 1.14. So, no.
Update your server.
