### ISSUE TITLE
Ancien Altar when underground pops the result trough the roof.

### ISSUE THREAD

**Issue by LoutreBleue** [TheBusyBiscuit/Slimefun4#1219]
## Description (Required)

Ancien Altar when underground pops the result trough the roof.
## Steps to reproduce the Issue (Required)

Get an ancien altar undeground with a low roof and use it.
## Expected behavior (Required)

Item should pop at ground level and not above the altar.
## Server Log / Error Report
No error

## Environment (Required)

![image](https://user-images.githubusercontent.com/57031748/67876755-b1214a00-fb38-11e9-8223-14b38f48f33f.png)

**Comment by TheBusyBiscuit** [comment]
Please provide a video. I have no clue what you mean.

**Comment by firebl0od** [comment]
![javaw_2019-10-30_17-52-03-06](https://user-images.githubusercontent.com/24475748/67880479-f8123e00-fb3e-11e9-83c4-d8470f4dcb96.gif)
