### ISSUE TITLE
Toggle "Free Researches in Creative Mode" via config

### ISSUE THREAD

**Issue by flapjack1968** [TheBusyBiscuit/Slimefun4#122]
We are running Slimefun on a 1.10 Spigot server and the plugin is working well.  We allow players to earn creative (based on game time) and they are able to research items without expending XP.  Is there a workaround for this?  I've searched and cannot finding anything.  

Thoughts would be to:  Charge money instead of XP levels or to Disable plugin features when player in game mode.  I could find nothing in the config to allow either.

Any thoughts would be appreciated.  Great plugin, fantastic work.

**Comment by NathanAdhitya** [comment]
Technicially, you could just let them use /sf cheat for that.
If you need to have researches given, you could also do /sf give (If i was correct)

**Comment by ipodtouch0218** [comment]
I think he wants to add a gamemode check option in the config, so people can't unlock everything from creative mode.

**Comment by NathanAdhitya** [comment]
Ah, right. So basically, if game mode equals to x, don't allow players to research, maybe?
That's possible for sure.

**Comment by TheBusyBiscuit** [comment]
#128
