### ISSUE TITLE
Directly waterlogged SF4 machines lose their texture.

### ISSUE THREAD

**Issue by Brittank88** [TheBusyBiscuit/Slimefun4#1221]
## Description (Required)
If water is placed into the same blockspace as a SF4 machine, water will temporarily appear in place of the machine (and the bucket will empty) before the bucket is reverted to its full state and the machine returns to replace the water source...but without its custom texture.

Important to note is that the machine _is still the machine_. It will respond to interaction (the GUI can still be opened if there is one) and function normally (for example a 'water-bugged' edition of a cargo input node will still pull items into the cargo network). The machine can be broken to give a correct version of its item form, and when placed down again will once more have its proper texture.

## Steps to reproduce the Issue (Required)
1. Place a SF4 machine of any kind down:

![image](https://user-images.githubusercontent.com/24266948/67922076-c01e0000-fbfd-11e9-808d-aa88ee14245c.png)

2. Waterlog the machine by placing a water source down in the same blockspace:

![image](https://user-images.githubusercontent.com/24266948/67922099-d62bc080-fbfd-11e9-84ef-6e9fb4725f98.png)

3. Watch as the machine comes back from oblivion, infinitely more creepy than it was originally:

![image](https://user-images.githubusercontent.com/24266948/67922136-f0659e80-fbfd-11e9-9a02-18c5aa719721.png)

## Expected behavior (Required)
Either of two things:
1. The water placement is cancelled and the machine is re-placed _with its custom texture_.
2. The machine is dropped as an item and the water source is left alone.

Option 1 is in many ways preferable in my opinion. However, this is of course up to the devs. 😃 

## Server Log / Error Report
No error is printed to the server console / log / an error report.

## Environment (Required)
![image](https://user-images.githubusercontent.com/24266948/67922211-3a4e8480-fbfe-11e9-9d6c-a982b80f47db.png)

![image](https://user-images.githubusercontent.com/24266948/67922204-3458a380-fbfe-11e9-9e8d-d7619fa0f313.png)

**Comment by TheBusyBiscuit** [comment]
That is a client-side thing.

**Comment by Brittank88** [comment]
Alright, thanks for letting me know!
