### ISSUE TITLE
Ancient Altar Bug Report

### ISSUE THREAD

**Issue by bramar2** [TheBusyBiscuit/Slimefun4#1243]
## Description (Required)
The issue is when i want to craft the Blank Rune with the Ancient Altar. I put the recipe and think it was going to work but it doesn't. When i right click the obsidian in the enchantment table, It does nothing. I can't interact with the enchantment table or even pick up the item from the Pedestal without breaking them. 

## Steps to reproduce the Issue (Required)
I just have a screenshot of it. Hopefully, its useful.
![2019-11-15_17 02 18](https://user-images.githubusercontent.com/57794236/68934708-c26d8600-07c9-11ea-9af8-325fe45bff7a.png)

## Expected behavior (Required)
I expected it to work like normal. I expected to get the item.

## Server Log / Error Report
https://pastebin.com/djf4gtxR

## Environment (Required)

 - Minecraft Version: 1.12.2
 - Slimefun Version: Slimefun v4.1.15
 - CS-CoreLib Version: CS-Corelib v1.6.1

**Comment by J3fftw1** [comment]
That version isnt supported anymore only supported minecraft version is 1.14
