### ISSUE TITLE
Question: all researches available from start

### ISSUE THREAD

**Issue by robinmuilwijk** [TheBusyBiscuit/Slimefun4#125]
I am running MC 1.11.2, with CS-CoreLib v1.5.12 and Slimefun_v4.1.2.

For some reason, if we run a new world, all researches are enabled by default. You do not have to use XP to actually unlock something, and then be able build it. 

We were able to have this working once, but can't get it to work anymore. Any hints?

**Comment by John000708** [comment]
You will need to remove the researches from the players manually. go to data-storage/Slimefun/Players and delete all the files, that will reset the researches.

**Comment by robinmuilwijk** [comment]
Thanks for the reply. I looked in that folders, but there are no files.

**Comment by NathanAdhitya** [comment]
If you want to give all researches: /sf research
If you want to delete all researches, do what john said to do.

**Comment by robinmuilwijk** [comment]
We looked into the data-storage folder, but there was nothing there. And running those commands do not seem to have the effect we want. I'll dig a bit further.

If anyone has any ideas, they are welcome. Thanks.

**Comment by John000708** [comment]
That's very weird. The data-storage folder must have something in it, otherwise, the players wouldn't have any researches at all. Are you looking in the correct folder? It is located in the server's root directory. (Where the server.properties is located etc.)

**Comment by robinmuilwijk** [comment]
Yes, the weird part is that it is a payed server (minespan), and it did work the first time. After setting up a new world, we can not get it to work anymore.

I can see the data-storage folder in the root, with lots of sub folders, including the 'Players' folder. I set up a local server to quickly test etc, same problem here. As soon as I use a complete clean setup (server etc), we get all researches, and that Player folder remains empty.

**Comment by FrostExZo** [comment]
just delete all researches from you and reboot server

**Comment by akashaggarwal7** [comment]
I know what the issue is. Happened to me too. Apparently you installed the dependency Lib(i forgot its name) and SlimeFun together. Delete both the plugin data. First install the Lib plugin, then install slimefun.
