### ISSUE TITLE
Ancient Altar Glitch

### ISSUE THREAD

**Issue by yamieyam** [TheBusyBiscuit/Slimefun4#1250]
Description (Required)
When trying to create something with the Ancient Altar, all works well. All items go on the pedestals as expected. When I use the Catalyst, it takes the item and the procedure begins. After all items on the pedestals are taken, the rune pops out and disappears, and cannot be picked up.

## Evidence / Proof (Required)
https://media.discordapp.net/attachments/511859320112152589/645538745789054987/2019-11-17_15.32.20.png?width=916&height=473

## Environment (Required)
Minecraft Version: 1.14.4
CS-CoreLib Version: CS-CoreLib v1.6.1.jar
Slimefun Version: Slimefun4

**Comment by J3fftw1** [comment]
What is latest? Also it wi be closed if you dont change it

**Comment by yamieyam** [comment]
CS-CoreLib Version: CS-CoreLib v1.6.1.jar
Slimefun Version: Slimefun4
