### ISSUE TITLE
Radiant Backpack automatically given ID

### ISSUE THREAD

**Issue by itslukemango** [TheBusyBiscuit/Slimefun4#1253]
## Description (Required)

Radiant Backpack automatically given ID, can't craft Soulbound with it

## Steps to reproduce the Issue (Required)

https://streamable.com/uwvaz

## Expected behavior (Required)

It to have <ID> instead of an actual ID

## Server Log / Error Report

Not needed (i think?)

## Environment (Required)

 - Minecraft Version: 1.14.4 (Paper)
 - Slimefun Version: 339
 - CS-CoreLib Version: 78

**Comment by TheBusyBiscuit** [comment]
It's supposed to have an id...

**Comment by itslukemango** [comment]
All other backpacks make you have to right-click it to give it an ID, this just gets one by default

**Comment by J3fftw1** [comment]
getting a id is right all newly crafted backpacks gets a id but the bug is that when you want to craft a soulbound backpack it doesnt ignore the idea to create 1 @itslukemango
