### ISSUE TITLE
Coolers won't open

### ISSUE THREAD

**Issue by FatherWh0** [TheBusyBiscuit/Slimefun4#127]
We are unable to get coolers to open or function in any way. The fact is I first noticed this last summer. Sry for just now reporting but I only recently added Exotic Gardens which has increased the use of drinks on my server. 

Mc 1.11.2 paper #1045
Slimefun v. 4.1.2
cs-corelib 1.5.12

**Comment by John000708** [comment]
I just tested them and they're working just fine, also nobody else seems to have reported this. It could be a paperspigot only issue, maybe?

**Comment by FatherWh0** [comment]
To be clear you simply hold it in your hand and right-click correct? If so I can test it with regular spigot.

**Comment by John000708** [comment]
Correct

**Comment by FatherWh0** [comment]
I sorted it out. Turns out coolers are hooked into backpacks. I needed backpacks enabled in the config and items and can only disable them in whitelist.yml. They are working now. Thanks for your help.
