### ISSUE TITLE
Duplication using androids.

### ISSUE THREAD

**Issue by Joapple** [TheBusyBiscuit/Slimefun4#147]
## Description
Miner androids: We found a duplication, where you place any slimefun blocks. ex: gold 24c block, auto-enchanter, auto-disenchenter, any placed blocks. Use a minerbot to mine the slimefun blocks, the blocks disapear. Open the android interface and get the vanilla block, so if used 24c gold block, there will be a Gold Block in it. Place a sand to drop on where the 24c block used to be, mine the sand, get it back AND the slimefun block. End of process: Used a 24c block got: 24c goldblock, gold block and sand isn't consumed in the process.

## Server Log
No errors in logs, auto-saving  every 5m with 180k + changes

## Evidence / Proof
None, can take them if need be.

## Environment
paperclip 1.11.2 (We try to be the latest possible) sf: 4.1.1 Cs-CoreLib: 1.5.12

**Comment by Joapple** [comment]
Thanks for not looking into that, i guess you don't care anyway

**Comment by TheBusyBiscuit** [comment]
I abandoned this Project a very long time ago, so yep, I really dont care about issues.
And seeing you as an example for this plugins community is proof enough that the community doesnt want to keep this plugin alive either.

**Comment by Joapple** [comment]
I totally understand that you abandonned this project a long time and don't care about issues, i'm a new to JAVA and been trying to learn and fix issues, but when i see my issue closed AND locked without any comments make me so angry while I'M FRENCH and still try to do my best to explain myself, but when you don't give chances to people, it just make people leave and not helping. If you don't care about this project anymore, why still closing issues and such while someone could just reply, Hey i know your issue let me help you, but no they can't YOU locked it >.< I don't even know how to do a pull request on github, i've been waiting for a friend to help me, i fixed many stuff from this plugin INTO mine, because github, but as seeing you closing my issues like that, it doesn't tell me that YOU want to keep this plugin alive even though you abandonned it. If you really don't care, just don't do anything and stop closing issues, maybe someone else would be helping me.

Joapple, a FRENCH new dev, that would love to keep this project alive, but yeah, thanks for reading me and I hope you understand me why i feel that way.

**Comment by TheBusyBiscuit** [comment]
You made an issue about lag.
Issues like this go right into the trash can. Not going to argue why.

**Comment by freethemice** [comment]
The cargo nodes are to be ignored there's a major problem with them. That eats up CPU not lag. You delete mine to and other people that said cargo node are a huge problem. I have told removed them from my sever because of this

**Comment by freethemice** [comment]
Are not*
