### ISSUE TITLE
Jetpack/Enchant Duplication glitch + SF Barrels broken

### ISSUE THREAD

**Issue by dart737** [TheBusyBiscuit/Slimefun4#148]
## Description
**Jetpack and Enchant Duplication**
I was able to replicate the jetpack duplication rather easy, but I've had multiple reports of this same thing working in the same way with the Disenchanter. I haven't checked but it may also work with other plugins. Its done by letting a charging station charge your jetpack to completion, you take it out, and leave the chunk, if the server restarts/crashes shortly after, the jetpack will then be in your inventory as well as back in the machine itself. The enchantment duplication works the same way, I just haven't been able to replicate it but I have gotten several reports from users that it happens around a restart/crash and that you've taken it out of the machine and it shows back up.
**Slimefun Barrels**
I'm not sure if this is the appropriate place to put this, but I figured I may as well mention it since the author of it is the same author as for slimefun. But the Barrels plugin is very broken at the moment, if you attempt to put a small amount of things into a barrel, it has a chance to simply ignore any additional stacks that you've put into it besides the newest amount. Essentially, you can keep putting stacks into it and it will only say you've put 64 in it and not allow you to retrieve them. I was able to get it to work on occassions, but it seemed like the majority of the time it was messed up.
## Server Log
I have no logs for the slimefun Barrels glitch, as it provides no errors.
Here is my full server log for me simply testing the glitch and getting it to work successfully: http://pastebin.com/5fms1x4M
I found a segment of it mentioning slimefun, so here's the segment of it: http://pastebin.com/0EWT0T0h

## Evidence / Proof
I have no evidence of it, but its rather easily replicated, I was able to do it on a second try after doing exactly what I mentioned to do.

## Environment
Minecraft: 1.11.2
Slimefun: 4.1.2
CS-Corelib: 1.5.12

**Comment by DaddyElf** [comment]
I have found duplicate items in many of the electric machines after a reboot. I always assumed the game was rebooted before the data was saved about it being removed.

**Comment by dart737** [comment]
Thats what I imagine the error is telling, I linked the error that occurs with the duplication in a pastebin link in the server logs section.

**Comment by freethemice** [comment]
all you have to do to fix this as add the folowing at kine 27 to rc\me\mrCookieSlime\Slimefun\api\inventory\BlockMenu.java****
	@Override
	public void open(Player... players){
		super.open(players);
		this.changes++;
         }
This way every time someone looks or changes the inv on any mach. it flags it for save.

**Comment by dart737** [comment]
Donno how to do that, but hopefully the SF authors will see that and fix it.

**Comment by xXumarkuXx** [comment]
I also have the slimefun barrel issue, they havent worked for me since Slimefun 4.1.1 i had to downgrade back to that version until this gets fixed.

**Comment by dart737** [comment]
Yeah...There needs to be a fix for this glitch rather badly. Barrels are completely unusable. and I've had the same item duplicate 5 times now. It simply duplicates any of the last item you put in it every single restart. Into both the enchanter and disenchanter.

**Comment by dart737** [comment]
@freethemice Do you think you could actually do that for us and send us a download? I've attempted to do it but I just ended up breaking the plugin entirely and this post has been up for nearly a month without any sort of response from the staff and they haven't posted any sort of update in over a month, so I'm under the impression that they're sorta dead. 
Its a very very horrendous bug that doesn't seem to be having anything done about it and I simply don't know what programs I should be using to properly edit the line you're mentioning. If you don't feel like putting a download for it, could you at least suggest a program so that I can attempt to fix it myself? I tried simply using notepad, and replicating the spacing but it didn't turn out so well.
