### ISSUE TITLE
Slimefun Guide is not opening 

### ISSUE THREAD

**Issue by DrEnder** [TheBusyBiscuit/Slimefun4#149]
## Description
When you enter '/sf guide' it works. It gives the book and all its default lores. However, when you click on the book (right-click) it doesn't open nor message in chat. But, in console, Yes there is. The error will be shown below. 

## Server Log / Evidence
http://pastebin.com/B92vGPGv

## Environment
SERVER JAR: 1.9
CS-CORELIB: 1.5.4
SLIMEFUN: 4.0.9
MY MINECRAFT CLIENT: 1.9.2 (Should be not important)

**Comment by John000708** [comment]
Too old Slimefun and CS-CoreLib versions...z
