### ISSUE TITLE
Hunter Talisman duplicating items

### ISSUE THREAD

**Issue by Sheepotastic** [TheBusyBiscuit/Slimefun4#1490]
## Description (Required)
Drop an item towards a mob that can pick items up, they pick it up. Have the hunter talisman in your inv/ender talisman in your enderchest. Kill the mob, get a duplicate of the item you just handed them.

## Expected behavior (Required)
To not allow duplication of literally any item. Hunter talisman should only duplicate vanilla drop tables.

## Server Log / Error Report
No error 

## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: vDev - 438
 - CS-CoreLib Version:vDev - 83

**Comment by Clexus** [comment]
Yes, this bug is very serious. I hope to fix it as soon as possible

**Comment by WalshyDev** [comment]
I fixed this quite a while ago since we found the issue on a server. I never made the PR (can't remember why), the commit is [here](https://github.com/WalshyDev/Slimefun4/commit/ca67b3841faf13b3126d39ee00bf6f966bca310c) . Someone is free to take and PR it, I can't at the min.

**Comment by J3fftw1** [comment]
> I fixed this quite a while ago since we found the issue on a server. I never made the PR (can't remember why), the commit is [here](https://github.com/WalshyDev/Slimefun4/commit/ca67b3841faf13b3126d39ee00bf6f966bca310c) . Someone is free to take and PR it, I can't at the min.

You didnt PR it because we solved the issue in another way

**Comment by WalshyDev** [comment]
> > I fixed this quite a while ago since we found the issue on a server. I never made the PR (can't remember why), the commit is [here](https://github.com/WalshyDev/Slimefun4/commit/ca67b3841faf13b3126d39ee00bf6f966bca310c) . Someone is free to take and PR it, I can't at the min.
> 
> You didnt PR it because we solved the issue in another way

Oh, LUL
