### ISSUE TITLE
Hotkeying items into backpacks/slimefun guide forever

### ISSUE THREAD

**Issue by RokuDoan** [TheBusyBiscuit/Slimefun4#155]
## Description
Any item in current hot bar can be transferred by using hotkey 0~9 into any empty space of backpacks/guide/cheat. If backpack is placed inside a backpack, it's no longer be able to obtained back even with hotkey.

## Server Log
No error-report found in slimefun
Server's log work normal as below:
[http://pastebin.com/qx1wefAb](url)

## Evidence / Proof
![2017-02-21_12 18 57](https://cloud.githubusercontent.com/assets/25916165/23148407/42ae0480-f831-11e6-9a6a-29d0197f2207.png)
![2017-02-21_12 19 38](https://cloud.githubusercontent.com/assets/25916165/23148418/5db78ac6-f831-11e6-844b-3296423d557a.png)

## Environment
Minecraft v1.11.2, CS-CoreLib v1.5.12, Slimefun v4.1.2

**Comment by Tiande** [comment]
When put the backpack into itself, it will disappear forever. 😳
Only the Enderpack is perfect.

**Comment by Joapple** [comment]
We had the same issue, but instead of editing the slimefun code i did it in my own plugin, i can look into doing a pull request and implements it in slimefun.

**Comment by DaddyElf** [comment]
I did this by accident (hit the wrong hotkey) and now the backpack with all my diamonds etc is stuck inside my junk backpack.

**Comment by VoidAngel** [comment]
Fixed in #664 & #267
