### ISSUE TITLE
Slimfun. Multimetr on click dont show color

### ISSUE THREAD

**Issue by HaZeLnUtPL** [TheBusyBiscuit/Slimefun4#157]
Hello,
I have one problem with multimetr text message. On chat dont write in color only white with "&". How i can fix this.

P.S Sorry for bad english :)

http://iv.pl/images/29804907197975765460.png <-- image with problem

Minecraft version 1.11.2 all update to new plugin

**Comment by DaddyElf** [comment]
Yea when I first started using slimefun that drove me mad, that extra 3 infront of the reading threw me off alot.

**Comment by Joapple** [comment]
Dunno how to pullrequest only that change, i've done too many change to the plugin, but leaving this here. https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L3707 need to replace all & with §

**Comment by HaZeLnUtPL** [comment]
Joapple then tell me why all items have normal color, only this text don't work.

**Comment by Joapple** [comment]
In JAVA you need to translate alternate color code, minecraft doesn't know that & symbol is a color code while the other one is. In the section I posted, they did neither, so it shows &3 instead of the color 😉
