### ISSUE TITLE
Suggestion: Cobblestone Generator

### ISSUE THREAD

**Issue by eslachance** [TheBusyBiscuit/Slimefun4#158]
While this isn't an issue, I'm suggesting this as an addition because I feel like it's one of the only things missing in slimefun. Not only this, it's one thing missing *in bukkit* as a whole! An *automated* cobblestone generator would basically enable "infinite" ores, and if well balanced in terms of speed, would not make this OP. Obviously while an automated Pan/Washer/Smeltery would be its main use in the pack, smelting cobble into stone, then bricks, would also be something it could do.

There are 2 ways I see this happening: One would be a straight-up cobblestone generator *block* (no power required) made with, say, the following recipe in an ECT:

```
OPO
WCL
OAO
```
(Where O = Obsidian, W = water bucket, L = lava, A = pickAxe, C = cobble.. in a )

The other method would be a world mechanics change. I've seen one *very* old plugin (4 years old) that lets you break cobble with a piston, if there is cobble straight in front of it and an obsidian behind it. This would be more "vanilla-feel" but requires block updates, so more lag. 

And... yeah sure I might be told "do it yourself as a slimefun plugin!" but I don't know Java at all, so the time it would take me to figure out APIs and setup an environment, whereas one of you could probably do it in... oh, a couple hours probably...

Please please please pretty please with a cherry on top?

**Comment by eslachance** [comment]
**ALTERNATIVE**: A *Block Breaker* that could collect cobble, Obsidian, or any other block in front of it, and hold it in an inventory slot.

**Comment by TheBusyBiscuit** [comment]
Androids.
