### ISSUE TITLE
Chain Armor Bug

### ISSUE THREAD

**Issue by EloiseRaeCullen** [TheBusyBiscuit/Slimefun4#159]
I play on the Rockville Server which uses SlimeFun and recently encountered an issue with the chain armor. I know there's special chain armor in the SlimeFun guide, but there's also vanilla chain that can be crafted and falls off mobs. When I put this armor on, I was spammed with the "You don't have enough knowledge to use this item" message which confused me. I think the code is confusing SlimeFun chain and Vanilla MC chain.

**Comment by Joapple** [comment]
In vanilla behaviour there is no recipe to craft Chain armor, you can only get it by killings mobs that has them in their inventories, slimefun add a way to craft them, and since they have no lore or no custom names, normal vanilla chair armor will spam you with no knowledge until you unlock them
