### ISSUE TITLE
Explosive shovel not breaking Podzol and Concrete Powder

### ISSUE THREAD

**Issue by OwerPlay** [TheBusyBiscuit/Slimefun4#1619]
## Description (Required)

Explosive shovel not breaking blocks like podzol, concrete, concrete powder, terracota and clay.
## Steps to reproduce the Issue (Required)

1. Place down one of the blocks mentioned above
2. Break it
## Expected behavior (Required)

Blocks would break
## Server Log / Error Report

No error
## Environment (Required)

https://prnt.sc/rc9exg

**Comment by TheBusyBiscuit** [comment]
Concrete and Terracotta are broken with a Pickaxe not a shovel...

**Comment by J3fftw1** [comment]
Nope ther are broken by pickaxe

**Comment by WalshyDev** [comment]
https://minecraft.gamepedia.com/Concrete
Tool: Pickaxe

https://minecraft.gamepedia.com/Terracotta
Tool: Pickaxe

**Comment by OwerPlay** [comment]
Ohh sorry, than only Podzol seems to be problem
