### ISSUE TITLE
Cargo Managers leaving "Holograms" behind after broken

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#162]
## Description
When broken, sometimes the Cargo Manager leaves behind it's floating text. This doesn't happen all the time and doesn't seem to throw any errors in the console.

## Evidence / Proof
Screenshot: https://i.gyazo.com/5b462255325bf3500b2a066e914c67a0.png

## Environment
MC Version: Paper 1.11.2-1059
CS-CoreLib Version: 1.5.12
Slimefun Version: 4.1.2

**Comment by BlackBeltPanda** [comment]
Placing a new Cargo Manager where the old one was and breaking it usually gets rid of the floating text.

**Comment by MSaK9** [comment]
I've been removing them with /minecraft:kill @e[type=armor_stand,r=5] while standing next to them. Based off of what I've seen, I believe it only occurs when the chunk that the Cargo Manager was placed in is unloaded, and then it is broken.

**Comment by akashaggarwal7** [comment]
@MSaK9 I might as well try this out, I've been facing the same issue.

**Comment by BlackBeltPanda** [comment]
Seems to be getting worse lately. I can't remove them by killing the invisible entity as it just respawns the hologram. Only way to get rid of them is to manually remove them from the database.

Screenshot: https://i.gyazo.com/ebc3827f855bf7b53bb85f68c6e4485f.png

**Comment by BlackBeltPanda** [comment]
K, found a way to get rid of the stubborn ones without editing the database manually:

Using WorldEdit, select the area the nodes were in, where the holograms are floating, and set it to air. Then remove/kill the invisible entities and they should disappear.

**Comment by BlackBeltPanda** [comment]
I was able to capture a GIF of it happening: https://i.gyazo.com/fd60e4dd4ad8f224e3f4fc3d8d91f72b.gif

**Comment by ScuroK** [comment]
i can confirm this issue!
