### ISSUE TITLE
Urgant dupe bug that needs fixing

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#163]
## Description
Using backpacks you can dupe them, this is what a player explained to me:

you can get 2 of the same backpack id and then doing a little process You can also do it with just one backpack as there is about a 3ms delay between right clicking and a slimefun item activating just right click, throw the backpack, someone else picks it up

## Evidence / Proof
Can't give any photo's or videos, but just follow the steps above and it should happen

## Environment

CraftBukkit version git-Spigot-d4f98a3-cb61ac0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Slimefun v4.1.3
CS-CoreLib version 1.5.13

Addons:
ExoticGarden v1.6.1
TinkerTools v1.03
SlimeXpansion v1.1.8
EmeraldEnchants v2.0
SlimefunLuckyBlocks v1.1
ElectricSpawners v1.0
MagicLoot v3.0
ExtraHeads v1.0
SoulJars v1.0

**Comment by TheBusyBiscuit** [comment]
Slimefun does not cause this Issue. Either a Spigot/Minecraft Issue or a Plugin Interference.
