### ISSUE TITLE
Pickaxe of Vein Mining not working on redstone (1.11.2)

### ISSUE THREAD

**Issue by Syntex77** [TheBusyBiscuit/Slimefun4#167]
When I mine redstone ore with a pickaxe of vein mining it sometimes only mines a little bit of redstone, but not all of it, sometimes it doesn't veinmine the redstone at all.

![2017-02-26_17 37 35](https://cloud.githubusercontent.com/assets/26050001/23345952/69d5a956-fc4a-11e6-87f5-c879797074f1.png)

**Comment by MrCubed** [comment]
This could be because of how Redstone Ore "glows" when it's interacted with, which is a different block state of redstone ore.

**Comment by yhdesai** [comment]
It didn't work for me on 1.10.2 too. It just mined 1 block.

**Comment by TheBusyBiscuit** [comment]
Fixed in the latest Version of CS-CoreLib.
