### ISSUE TITLE
Generic Issue for Tests

### ISSUE THREAD

**Issue by John000708** [TheBusyBiscuit/Slimefun4#171]
Plz fix!!! no work!!! help help! mainecreft ver. 1.2 alpha gtx 980ti

**Comment by TheBusyBiscuit** [comment]
i fixt dis issu, tanks 4 report dat.

**Comment by TheBusyBiscuit** [comment]
Doing more tests with dat github addon 
![bitmoji](https://render.bitstrips.com/v2/cpanel/10216978-196095049_1-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by TheBusyBiscuit** [comment]
Gonna try improving The Craft Of GitHub to make a button that locks, closes and comments a saved reply all at the same time.
I hope (especially the comment) will bring some clarification.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.34235432432432

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.34235432432432

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Holy recursion...

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Hello world, its me I was wondering if after all those years you'd like to meet.

**Comment by TheBusyBiscuit** [comment]
Test<br>This is a new line

**Comment by TheBusyBiscuit** [comment]
Test<br>This is a new line

**Comment by TheBusyBiscuit** [comment]
Test<br>This is a new line

**Comment by TheBusyBiscuit** [comment]
https://github.com/TheBusyBiscuit/Slimefun4

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting:<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md

**Comment by TheBusyBiscuit** [comment]
So Emojis gotta be tested as well :P
For reasons that are unrelated to this repo but hey, we have a test issue in here.

👍 
💯 
🖌 
👶 
😃

**Comment by TheBusyBiscuit** [comment]
🎉
