### ISSUE TITLE
Severe Disenchanter Balance Issue

### ISSUE THREAD

**Issue by negativevoltage** [TheBusyBiscuit/Slimefun4#174]
Slimefun Version: 4.1.1

Description of issue:
The way most end-game items (or even lesser items, like the walking sticks) handle power by applying enchantments. This would normally be ok, except for the fact of a machine called the disenchanter. The normally-balanced enchants can be stripped off of their original items, and applied to something else, to get much more value than originally intended. While the disenchanter is very expensive, if you use solar-panel power (and who doesn't) and have a sugar cane and cow farm (which are very easy to make), there is no further recurring cost for using the disenchanter. You can then use mid-endgame items (or even just a walking stick) to get extremely powerful enchant books, which can then be applied to other items for broken gear. Yes, this is all end-game, but end-game shouldn't mean creative mode, it should mean powerful but balanced gear, and the disenchanter breaks this. I don't think the disenchanter should be removed, but maybe not allow it to disenchant slimefun items?

**Comment by TheBusyBiscuit** [comment]
Items.yml
