### ISSUE TITLE
Items Disappearing from Input and Advanced Output Nodes' Whitelists

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#179]
## Description
Items inside the Cargo Network's Input and Advanced Output Nodes' whitelists randomly disappear. They don't seem to go into any inventory; just vanish from the Node. I think this happens after the chunk they're in is unloaded.

## Server Log
http://pastebin.com/raw/9KWwt9j0

## Evidence / Proof
None at the moment.

## Environment
MC Version: Paper 1.11.2-1062
CS-CoreLib Version: 1.5.12
Slimefun Version: 4.1.2

**Comment by NathanAdhitya** [comment]
Hmm, weird.... doesn't seen to happen to me? I've had those whitelists working for ages... (Just not when someone steals it.)

**Comment by BlackBeltPanda** [comment]
I'm working on gathering more information about how the system is setup. Seems to affect the same Nodes each time but their system is complicated and consists of some 50 or so Advanced Output Nodes.
