### ISSUE TITLE
Slimefun not working with 1.8 when it says it supports it

### ISSUE THREAD

**Issue by Adventure2098** [TheBusyBiscuit/Slimefun4#181]
## Description
I am running a server with slimefun and recently saw that slimefun 1.10 including support for 1.8.1 so I decided to update slimefun to this and it says it does not support it on the server logs, where it just disabled slimefun after the server starts.

## Server Log
http://pastebin.com/QfUJZHs1

## Environment
I am using spigot 1.8.8, slimefun 4.1, and cs-corelib version 1.5.11

**Comment by NathanAdhitya** [comment]
Sir, read what it said in the logs.
If you still want to use slimefun, use another version with auto update disabled.
