### ISSUE TITLE
Enhanced furnaces eat very high speed the block of coal

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#1829]
## Description (Required)

Enhanced furnaces eat very high speed the block of coal

## Steps to reproduce the Issue (Required)

1. Place the Enhanced furnace
2. Put the block of coal.
3. Put the diamond ore.
4. Enhanced furnace eats the Block of coal in few minutes.
https://www.youtube.com/watch?v=pcX3d8VO9jI

## Expected behavior (Required)

Enhanced furnaces no eat very high speed the block of coal

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 493 (git 4cc6a028)
 - CS-CoreLib Version: vDEV - 85 (git 4a7fce52)

**Comment by Rhenic** [comment]
I have a similar issue with enhanced furnaces. After smelting about 4 items, it will cease smelting and just sit there burning coal.

**Comment by TheBusyBiscuit** [comment]
Unable to reproduce this. Send a full plugins list please, maybe something is interefering.

**Comment by andris155** [comment]
git-Paper-257 (MC: 1.15.2)
Plugins (2): CS-CoreLib, Slimefun
Java 11.0.6
