### ISSUE TITLE
Talisman of the Magician Giving enchantments to wrong items

### ISSUE THREAD

**Issue by Derpylove** [TheBusyBiscuit/Slimefun4#1833]
## Description (Required)

The talisman of the Magician is giving enchantments to the wrong items examples of enchantments ive gotten on the pickaxes are protection, multishot, fire aspect, projectile protection, curse of binding and luck of the sea. I have also tested Diamond Helmet and got Depth Strider, multishot and bane of arthopods. 
## Steps to reproduce the Issue (Required)

https://youtu.be/a1KFj_xuIaE
Have the talisman of the magician and use it on an enchantment table. Doesnt matter what level enchantment u put on it.
I have restarted the server 2 times and it hasn't fixed it.
## Expected behavior (Required)

I expected it to give me for example give unbreaking if i got efficency 4 only. Not Projectile Protection

## Server Log / Error Report

There are no errors.
## Environment (Required)

![image](https://user-images.githubusercontent.com/45398741/80389480-6b58fa80-88ab-11ea-8feb-28d679ca330b.png)
![image](https://user-images.githubusercontent.com/45398741/80389538-79a71680-88ab-11ea-99ad-c782c93ce65e.png)

**Comment by TheBusyBiscuit** [comment]
Interesting, this issue has actually existed for 5 years and noone noticed apparently.
