### ISSUE TITLE
basic circuit board only drops once per restart

### ISSUE THREAD

**Issue by VulkanoTG** [TheBusyBiscuit/Slimefun4#1834]
## Description (Required)
when starting the server and killing an iron golem the basic cricuit board drops from the iron golem, however when killing the next few times it does not drop the basic circuit board

## Steps to reproduce the Issue (Required)
https://youtu.be/A71W9FPtKUQ

## Expected behavior (Required)

drop the item whenever it kills the iron golem

## Server Log / Error Report

the console has no errors

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: 
in the video it shows a version that was passed to me on discord by an admin but I tested it on build 495-494-493-492 and the same things happened
 - CS-CoreLib Version: 
tested on builds 79-85

**Comment by VulkanoTG** [comment]
doing some tests I found out that the problem with the circuit board is PaperMC which for some reason that I don't know, does not let the item drop.

follow the video testing the 2 versions and proving the reason for the bug.

https://youtu.be/uKMw72DJO34

**Comment by TheBusyBiscuit** [comment]
Paper probably broke that sometime ago if it only happens with Paper...
Try and see if it is fixed and comment below if it still happens.

BTW thank you a lot for making such a detailed report with videos and such.
We don't get such detailed reports very often and it really makes our lives easier.
