### ISSUE TITLE
SlimeFun slimeblock piston glitch

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#186]
## Description
SlimeFun slimeblock piston glitch

## Evidence / Proof
https://www.youtube.com/watch?v=sc5T12mj8YQ

## Environment
MC Version: Paper 1.11.2-1056
CS-CoreLib Version: 1.5.13
Slimefun Version: 4.1.2

**Comment by comonier** [comment]
same problem on my server

**Comment by comonier** [comment]
found a solution with this plugin =P

https://www.spigotmc.org/resources/disable-piston-farming.37793/

**Comment by andris155** [comment]
Thanks

**Comment by Poslovitch** [comment]
@TheBusyBiscuit close this issue, fixed in 4.1.11 (https://github.com/TheBusyBiscuit/Slimefun4/pull/425/commits/eb17f19258dbd44ef7b9a721a918871d7ee632f0)
