### ISSUE TITLE
Slime fun Item names [Suggestion]

### ISSUE THREAD

**Issue by jeddell** [TheBusyBiscuit/Slimefun4#188]
I dont know where to post this as it is more of a suggestion than a request.

I cannot find the item names of the slime fun items. By that I mean when using the command:
/sf give <player> <SF Itemname> Half of the item name I cant resolve.

And before anyone states the obvious, not all of the items displayed in game are the names of the items for example, feel free to try **/sf give <player> Elemental_Staff_Wind**
There are mnay others that I have found that I cant find item names for.

My Suggestion is a list here in the wiki, A list of item names that work. Id be happy to help if youd provide the list 

Kind regards

Jeddell

**Comment by John000708** [comment]
Just compiled a list with all Slimefun items, you can find it here: https://github.com/TheBusyBiscuit/Slimefun4/wiki/Items-List
