### ISSUE TITLE
Auto breeder does not stop when animals can't breed again

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#1883]
## Description (Required)

Auto breeder does not stop when animals can't breed again and eat Organic all organic food.

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=vIyzI6lzqSw

## Expected behavior (Required)

Auto breeder stop when animals can't breed again.

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 497 (git 4131a900)
 - CS-CoreLib Version: vDEV - 85 (git 4a7fce52)

**Comment by TheBusyBiscuit** [comment]
So far noone was able to reproduce this bug either.
What Server Software are you running? Any other plugins besides Slimefun and CS-CoreLib?

**Comment by andris155** [comment]
git-Paper-260
[18:58:17 INFO]: Plugins (2): CS-CoreLib, Slimefun
Java 11.0.6
