### ISSUE TITLE
Infused hopper glitch

### ISSUE THREAD

**Issue by shotgun9756** [TheBusyBiscuit/Slimefun4#190]
## Description
With the infused hopper whenever you place it, it will spawn a armor stand on top of it and when you break the infused hopper the armor stand stays there

## Server Log
I am a player so I don't have access 

## Evidence / Proof
https://youtu.be/6kewBt2LZFk

## Environment
MC Version: Paper 1.11.2-1056
 CS-CoreLib Version: 1.5.13
 Slimefun Version: 4.1.2

**Comment by shotgun9756** [comment]
please don't close this one I just want you guys to be aware about the issue/bug

**Comment by John000708** [comment]
I can't reproduce the issue, does the server have a base protection plugin or anything similar?
