### ISSUE TITLE
Players in Creative have access to machines

### ISSUE THREAD

**Issue by whoshenry** [TheBusyBiscuit/Slimefun4#192]
Pretty simple, I think it would be great if there's an option to disable interacting with the machines completely whilst a player is in Creative mode with a bypass permission, I'm surprised it hasn't been implemented already.

Without this, players can glitch items into their survival inventory.

I've tried writing scripts to fix this but no luck.

Would be grateful if this was implemented.

Running spigot 1.11.2 git-Spigot-65a0347-1a71021 and Slimefun 4.1.2.

**Comment by flapjack1968** [comment]
running into similar issues on our server as well (1.10.2, 4.1.6). Thanks for letting me tag along.
