### ISSUE TITLE
Extra materials enter the Electric Smeltery

### ISSUE THREAD

**Issue by NCBPFluffyBear** [TheBusyBiscuit/Slimefun4#1951]
## Description (Required)
When automating alloys with the electric smeltery, there is a chance for an extra of one of the materials to make it into the smeltery, creating two stacks of it. I have been avoiding this problem by clogging the other spots in my smeltery with a non smeltable item, but a fix would still be nice.

## Steps to reproduce the Issue (Required)
1. Hook up an Electric Smeltery to cargo and electricity
2. Set the advanced output node on the smeltery to whitelist Iron Dust, Iron Ingots, and Copper Dust (Nickel Recipe)
3. Add an input node on the smeltery that carts off the nickel elsewhere, this won't be needed anymore.
4. Wait a while, and look inside the smeltery. On some occasions, an extra stack of dust will appear inside.

*Reproducing this problem might not be very easy, this isn't very common.

## Expected behavior (Required)
Extra stacks of materials should not appear in the smeltery

## Server Log / Error Report
No error.

## Environment (Required)
Minecraft Version: 1.15.2
Slimefun Version: vDEV-523 (git f65ac)
CS-CoreLib Version: vDEV-85 (git 4a7fce52)

**Comment by fpsqdb** [comment]
@TheBusyBiscuit  This bug has not been fixed, and other problems have occurred.
![20200616004730](https://user-images.githubusercontent.com/6482819/84684631-82db6800-af6b-11ea-85e8-497f327c4010.png)

Reproduce:
![GIF 2020-06-16 00-43-57](https://user-images.githubusercontent.com/6482819/84684688-9ab2ec00-af6b-11ea-8aab-0cbecbb31f00.gif)

just leave the third cell blank, If there is tin dust in the third cell, no extra items will be added, just like the gif below
![GIF 2020-06-16 00-44-44](https://user-images.githubusercontent.com/6482819/84685044-23ca2300-af6c-11ea-89ae-6c2ea5ffa5de.gif)

**Another strange problem is that please note that the first cell contains less than 64 copper dusts. In fact, there is enough copper dusts to use**

**Comment by NCBPFluffyBear** [comment]
A proposed (potential?) fix for this is to change the Electric Smelterys to operate like Automatic Crafting Chambers, where the player puts in the recipe and it just completes each stack.
