### ISSUE TITLE
Grappling hook duplication glitch when firing at portals

### ISSUE THREAD

**Issue by Derpylove** [TheBusyBiscuit/Slimefun4#1959]
## Description (Required)

If you switch the multi tool function to grappling hook  and use it towards the nether portal then the nether portal will break it and lead will appear. Also tested it with with a normal grappling hook and the result is the same. As far as i know this issue has existed for 2 years since thats when i first discovered it. Recently remembered it agian and thought that maybe i should report it
It works with the grappling hook and the multitool, but if you do it with the grappling hook then you lose the grappling hook and gain a lead.
Tested them on the end portal and they work on it too. So you can make them into lead in any portal
## Steps to reproduce the Issue (Required)

https://youtu.be/8xKlOBPDDMU
Throw a grappling hook into the nether portal (might have to do so the grappling hook stays in the portal and doesnt go through it. So basicly do the same thing i did in the video)

## Expected behavior (Required)

Not exactly sure what i expect to happen. Maybe something like it stops before it hits the portal

## Server Log / Error Report

No errors found/seen

## Environment (Required)

![image](https://user-images.githubusercontent.com/45398741/84182630-fae8f000-aa8a-11ea-9590-ca6451d9784f.png)

**Comment by TheBusyBiscuit** [comment]
Does this happen with both, the grappling hook and the multitool?
And does it only work with Nether Portals?

**Comment by Derpylove** [comment]
It works with the grappling hook and the multitool, but if you do it with the grappling hook then you lose the grappling hook and gain a lead. 
Tested them on the end portal and they work on it too. So you can make them into lead in any portal

**Comment by NCBPFluffyBear** [comment]
Also reproducible on item frames
