### ISSUE TITLE
"You do not have enough knowledge to understand this" while breaking blocks with any item in hand

### ISSUE THREAD

**Issue by KevXtroy** [TheBusyBiscuit/Slimefun4#1971]
## Description (Required)
Whenever I try to break a block with any item (including vanilla items), Slimefun tells me "You do not have enough knowledge to understand this". The block breaks fine, but the message gets annoying.

## Steps to reproduce the Issue (Required)
Break a block with any item in hand.

## Expected behavior (Required)
The message shouldn't appear in chat

## Environment (Required)
 - Minecraft Version: 1.15.2-R0.1-snapshot
 - Slimefun Version: dev - 529 
 - CS-CoreLib Version: dev - 84

**Comment by Akuzi74** [comment]
![unknown](https://user-images.githubusercontent.com/66760787/84337430-6cab6180-ab91-11ea-8aac-902af23f090b.png)
Ive also got a server having this problem

**Comment by benjiouo** [comment]
what is the solution??? Please, is very annoying

**Comment by WalshyDev** [comment]
Update.
