### ISSUE TITLE
Error in console just report it :D

### ISSUE THREAD

**Issue by Scarlet2031** [TheBusyBiscuit/Slimefun4#1988]
## Description (Required)
a error console 

## Server Log / Error Report
https://pastebin.com/tN59tkS6

## Environment (Required)

 - Minecraft Version: 1.15.2 paper
 - Slimefun Version: 535
 - CS-CoreLib Version: 85

**Comment by WalshyDev** [comment]
These bug reports have gotten very detailed lately...
