### ISSUE TITLE
Placing mob spawners with block placer bug

### ISSUE THREAD

**Issue by JustPixeled** [TheBusyBiscuit/Slimefun4#1993]
## Description (Required)
Placing any spawner using a block placer will turn the spawner into a reinforced pig spawner.
This happens with both broken spawners and reinforced spawners.

## Steps to reproduce the Issue (Required)
Step 1 obtain a broken or reinforced spawner, step 2 place the spawner into a block placer, step 3 activate the block placer using redstone, step 4 mine the now placed spawner and it will be a reinforced pig spawner.
Video link: https://youtu.be/XLcrCo0vKnc

## Expected behavior (Required)
Broken spawners shouldn't be able to be placed and reinforced spawner should place the specified spawner type, not just default to a pig spawner

## Server Log / Error Report
I didn't see any errors but here's the server log just in-case I missed any.
Link: https://pastebin.com/7myZ8G4x
There also were no error reports created in plugins/slimefun/error-reports

## Environment (Required)
The server is running CraftBukkit version git-Spigot-a99063f-c9d7c16 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) 

- Minecraft Version: 1.15.2 (CraftBukkit v1_15_R1)
 - Slimefun Version: vDEV - 538 (git 2bead0cd)
 - CS-CoreLib Version: vDEV - 85 (git 4a7fce52)

**Comment by TheBusyBiscuit** [comment]
Thanks for reporting this in such detail! 
I am sadly not able to say that too often but this info and especially the video really made it easier to track down the issue.
So thanks a lot.

**Comment by JustPixeled** [comment]
I wasn't sure how I should of write it down until I read your bug report guidelines, the things on what you need in the bug report was really helpful
