### ISSUE TITLE
Unable to remove items from output boxes of electric machines

### ISSUE THREAD

**Issue by DaddyElf** [TheBusyBiscuit/Slimefun4#202]
version: Slimefun 4.1.3

Unable to remove output items from electric machines by hand (manual machines work as intended). Items in the input boxes are unaffected and work as intended.

Same behavior in and out of towny regions.

This issue started yesterday. (the server does daily updates to stay current)

Basically clicking on anything in an output slot of an electric machine has the click cancelled.

[Short Clip](https://youtu.be/IurVn-tlwp8)

**Comment by 112madgamer** [comment]
Thisis also a issue on a server I play on called Treasure island.

**Comment by VoidAngel** [comment]
This happens in the official version released 11 hours ago. RIP
For the people who reacted to this post as "confused" Just download the latest version and try to use the  item inventory of an android.

**Comment by John000708** [comment]
For now use the version before the last update. The issue has been found and will be fixed.

**Comment by TheBusyBiscuit** [comment]
Should be fixed in 4.1.5
