### ISSUE TITLE
Multi tool

### ISSUE THREAD

**Issue by 100petr** [TheBusyBiscuit/Slimefun4#2062]
## Description (Required)
The multi tool does not discharge, but charges

## Steps to reproduce the Issue (Required)
Get Multi Tool (I use VII) (has 0 / 100 J)
Use it
Now has 0.3 / 100 J
Use again now has 0.6 / 100 J
https://imgur.com/a/W32r43K

## Expected behavior (Required)
Energy will decrease, not increase

## Server Log / Error Report
No errors

## Environment (Required)
![Screenshot_1](https://user-images.githubusercontent.com/29830635/85939972-e1182b80-b919-11ea-8a15-f55c160fcec5.png)

**Comment by willthree123** [comment]
![image](https://user-images.githubusercontent.com/50272419/85943434-a8507480-b962-11ea-9fd3-c5939616ed76.png)
Me too!
