### ISSUE TITLE
Mining Talisman Not Playing Well With mcMMO

### ISSUE THREAD

**Issue by Bumbullbee** [TheBusyBiscuit/Slimefun4#2077]
## Description:
When mining Iron, Gold, etc. the player will receive a message that their ore has been doubled, however, they only receive one. On top of this, even when the player should be receiving double drops from mcMMO mining skill they are only receiving one. Often times you can see multiple items drop from the mined block as well.

## Reproducing the Issue: 
Simply mine iron and/or gold with a high mcMMO mining level and a talisman in your inventory to reproduce.

## Expected Behavior:
I expected either the talisman or the mining level to double the drops, or in the rare case things played well together, maybe even quadruple the drop.

## Environment:
Minecraft Version: 1.15.2
Paper: Latest
Slimefun4: DEV - 566
CS-CoreLib: vDEV - 79

Addons:

ExtraGear vDEV - 10
ExoticGarden vDEV - 54

**Comment by Bumbullbee** [comment]
Addons: 

ExtraGear vDEV - 10

ExoticGarden vDEV - 54


Sorry, forgot to include the addons in the original post.

**Comment by TheBusyBiscuit** [comment]
This issue is now fixed in build 630 and later.
However, on the rare occasion that these two features align, it will sadly not quadruple but triple instead.
