### ISSUE TITLE
Block Placer can place blocks to protected area

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#2138]
## Description (REQUIRED)

Block Placer can place blocks to the PlotSquared protected plot wall.
Block Placer can place blocks to the WorldGuard protection.
Block Placer can place blocks to the Griefprevention protection.
Block Placer can place blocks to outside the BentoBox island.

## Steps to reproduce the Issue (REQUIRED)

1. Give and place an Block Placer near the PlotSquared road or near protected region.
2. Put a block to Block Placer.
3. Activate the Block Placer.

![2020-07-26_22 59 29](https://user-images.githubusercontent.com/8324198/88489794-f8891980-cf96-11ea-8ace-4dedc01a1461.png)

![2020-07-26_23 08 54](https://user-images.githubusercontent.com/8324198/88489795-fd4dcd80-cf96-11ea-931e-69df5547a466.png)

![2020-07-26_23 14 02](https://user-images.githubusercontent.com/8324198/88489801-00e15480-cf97-11ea-875f-773ed3dd4a6c.png)

![2020-07-26_23 48 16](https://user-images.githubusercontent.com/8324198/88490269-bfeb3f00-cf9a-11ea-8e6e-54bdc3708f11.png)

## Expected behavior (REQUIRED)

Block Placer can't place to blocks to the PlotSquared plot wall.
Block Placer can't place blocks to the WorldGuard protection.
Block Placer can't place blocks to the Griefprevention protection.
Block Placer can't place blocks to outside the BentoBox island.

## Environment (REQUIRED)

 - Server Software: Paper
 - Minecraft Version: 1.16.1
 - Slimefun Version: vDEV - 600 (git 63569fac)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)

**Comment by TheBusyBiscuit** [comment]
This is fixed in build "DEV 635" and later.
But just a heads up that this fix will only affect **newly placed** Block Placers.

Any existing Block Placer will still face this issue until they have been replaced.
Since they can only place blocks one block far into other territories this temporary issue should not be much of a problem though.

**Comment by andris155** [comment]
Thanks
