### ISSUE TITLE
bug report with tape measure

### ISSUE THREAD

**Issue by amarcais53** [TheBusyBiscuit/Slimefun4#2143]
## Description (REQUIRED)
when i use tape measure that make an error on consol and do "nul" in game

## Steps to reproduce the Issue (REQUIRED)
just click with tape measure on the ground like right click

## Expected behavior (REQUIRED)

logically it's supposed to measure

## Server Log
https://pastebin.com/K514GzKP

## Error Reports
nothing in error report

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version: 1.15.2 PAPER last build
 - Slimefun Version: DEV 600
 - CS-CoreLib Version: dev 79

**Comment by dniym** [comment]
I could not reproduce this error on 

28.07 17:05:39 [Server] Server thread/INFO Spigot v1_16_R1
28.07 17:05:39 [Server] Server thread/INFO CS-CoreLib vDEV - 85 (git 4a7fce52)
28.07 17:05:39 [Server] Server thread/INFO Slimefun vDEV - 600 (git 63569fac)

looks like your cs core lib is a bit out of date, perhaps that's the issue?
