### ISSUE TITLE
The Explosion Bow and Icy Bow player protection not work perfectly protected areas

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#2180]
## Description (REQUIRED)

The Explosion Bow and Icy Bow player protection not work perfectly protected areas

Icy Bow cause: The player cannot move for a few seconds.
Explosion Bow cause: Player throw up, and fall damage.

## Steps to reproduce the Issue (REQUIRED)

Shoot the player on the protected area with Icy Bow or Explosion Bow.

https://www.youtube.com/watch?v=xmwetdt5EKE
https://www.youtube.com/watch?v=ZdNxm46sb4E

## Expected behavior (REQUIRED)

Icy Bow cause: Do not cause anything in the protected areas.
Explosion Bow cause: Do not cause anything in the protected areas.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.1
 - Slimefun Version: vDEV - 612 (git f32280a4)
 - CS-CoreLib Version: CS-CoreLib vDEV - 90 (git 9dd4a1cf)

**Comment by TheBusyBiscuit** [comment]
What protection plugin and version are you using...?
You should always include this information when reporting bugs like this.

**Comment by andris155** [comment]
GriefPrevention version 16.14.0

**Comment by andris155** [comment]
Thanks
