### ISSUE TITLE
SF Explosive Pickaxe versus Orebfuscator Plugin Anti Xray

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#219]
BEFORE
![comonier](http://image.prntscr.com/image/0fa75026eb384500be8161986ce4a995.png)
AFTER
![comonier](http://image.prntscr.com/image/69322c2311a149f99d93bc3e09d46792.png)
Any way to solve this Issue ?

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
