### ISSUE TITLE
ExoticGarden Plants and Bushes versus GriefPrevention

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#220]
Without any permission from GriefPrevention
accesstrust permit player to use, click, open door.
containertrust permit player to open chest, use workbeanch, enchantment table, potion support etc.
trust permit player to edit

any non-trusted player can click on bushes and plants to steal fruit/ores from slimefun inside GriefPrevention claims without trust to do that.

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
