### ISSUE TITLE
Cargo Nodes remain in database after removing with WorldEdit

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#222]
## Description
When removing an area with WorldEdit, such as deleting islands on a Skyblock server, the Cargo Nodes remain in the database preventing players from placing blocks where they once were and leaving floating holograms where Cargo Managers were.

## Evidence / Proof
Screenshot of Skyblock island after being reset: https://i.gyazo.com/7e059c86885bbe3f832f12068d21fc18.png

## Environment
MC Version: Paper 1.11.2-1072
CS-CoreLib Version: 1.5.12
Slimefun Version: 4.1.2

**Comment by TheBusyBiscuit** [comment]
That should not happen.
What Version of WorldEdit are you using...?

**Comment by BlackBeltPanda** [comment]
WorldEdit 6.1.7-SNAPSHOT:3674-9f24f84

It's also happening in some cases without WorldEdit and seems to be getting worse. The Managers/nodes remain in the database even though the block is gone. The only way to remove them is by removing them manually from the database, as it just respawns the hologram if I only delete the invisible entity.

Screenshot: https://i.gyazo.com/ebc3827f855bf7b53bb85f68c6e4485f.png

**Comment by BlackBeltPanda** [comment]
Maybe an extra check when the data's loaded? So if the block is air, remove the data from the database. Not sure if that'd work.

**Comment by TheBusyBiscuit** [comment]
It would. But only after a Restart.

**Comment by BlackBeltPanda** [comment]
It does if I set the area to air manually with "//set 0". If it's done automatically with uSkyBlock, it doesn't remove the block.
Also, the blocks are sometimes left in the database after being broken by players, as well. I have to remove several floating Cargo Manager holograms each day from players who broke them but the holograms were left behind.

**Comment by TheBusyBiscuit** [comment]
Well you should contact the uSkyBock developer to call BlockStorage.clearBlockInfo(Block) when clearing Islands.

**Comment by BlackBeltPanda** [comment]
K, thank you. I don't think the uSkyBlock dev will add that but I'll add it into my plugin which utilizes the uSkyBlock API. I'll try to test that out today. =)
