### ISSUE TITLE
Jet Boots Recipe Bug

### ISSUE THREAD

**Issue by kljigs500** [TheBusyBiscuit/Slimefun4#223]
## Description
Jet Boots III and IV recipe: 1 ingot of each misplaced? 

Also I'm adding the normal recipe of Jet boots II for reference.

## Server Log
Player of the server so no access.

## Evidence / Proof

![2017-03-30_16 02 40](https://cloud.githubusercontent.com/assets/26787840/24494082/97f0f17e-1563-11e7-8474-ac2ecda856ca.png)
![2017-03-30_16 02 45](https://cloud.githubusercontent.com/assets/26787840/24494081/97e37a94-1563-11e7-91c6-b9ed61e1178d.png)
![2017-03-30_16 10 48](https://cloud.githubusercontent.com/assets/26787840/24494079/97d7d108-1563-11e7-9328-0d742da4515f.png)

I think pictures are good enough unless I need to be more specific?

## Environment
Minecraft: 1.11.2
Slimefun: 4.1.5
CS-CoreLib: not sure. trying to contact owner.

**Comment by mmcclimans12** [comment]
Not sure, does it work normally?

**Comment by mmcclimans12** [comment]
with the ingots in the right place
