### ISSUE TITLE
Boots of the Stomper error sometimes

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#2249]
## Description (REQUIRED)

Boots of the Stomper error sometimes

## Steps to reproduce the Issue (REQUIRED)

1. Use the Boots of the Stomper for stomp and sometimes cause error.

## Expected behavior (REQUIRED)

Boots of the Stomper no cause error.

## Error Reports

https://pastebin.com/3LECU8VD

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.2
 - Slimefun Version: vDEV - 639 (git ec95797c)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)

**Comment by LinoxGH** [comment]
I recommend fixing this by checking if entity n and the player are in the same block. If they are either apply a constant vector or none at all.

**Comment by TheBusyBiscuit** [comment]
> I recommend fixing this by checking if entity n and the player are in the same block. If they are either apply a constant vector or none at all.

I am very much against this.
Bugs should just be fixed rather than removing the entire mechanic of an item...

**Comment by LinoxGH** [comment]
> > I recommend fixing this by checking if entity n and the player are in the same block. If they are either apply a constant vector or none at all.
> 
> I am very much against this.
> Bugs should just be fixed rather than removing the entire mechanic of an item...

I didn't say remove it I said just check for 1 specific case that's causing this and apply a constant/or none knockback to that specific entity.

**Comment by TheBusyBiscuit** [comment]
Ah, pardon, I misread that as "making it only work if they are in the same block".

**Comment by TheBusyBiscuit** [comment]
@LinoxGH Yep, you were right, sorry about that.
This should definitely fix it.

**Comment by andris155** [comment]
thanks
