### ISSUE TITLE
Android Issue/Bug?

### ISSUE THREAD

**Issue by kljigs500** [TheBusyBiscuit/Slimefun4#225]
## Description
This is quite an interesting and complicated issue. It applies to all androids. After programming and putting the script, and loading the fuel with 64 coal blocks, it works for a certain amount of time (did not try any other source of fuel). About an hour or two later, they suddenly break or stop moving and turn to Cs-CoreLib Heads once mined out. I am not certain what exactly is the cause is since takes about a few hours before the said issue happens. My possible theories are, it could be a chunk loader issue, a server restart issue, or a plugin conflict. I'm just curious because the androids are really fun to use and it would be a hassle to make another one unless a good cargo net system was made.

## Server Log
Player - No access

## Evidence / Proof
![2017-03-31_08 30 23](https://cloud.githubusercontent.com/assets/26787840/24531646/055d18ee-15ed-11e7-8252-de86fd317db3.png)
![2017-03-31_08 30 28](https://cloud.githubusercontent.com/assets/26787840/24531648/056fdf7e-15ed-11e7-8d62-974e53c3adea.png)
![2017-03-31_08 30 48](https://cloud.githubusercontent.com/assets/26787840/24531649/057d1900-15ed-11e7-89d4-69ada6460945.png)
![2017-03-31_08 31 01](https://cloud.githubusercontent.com/assets/26787840/24531647/05607fb6-15ed-11e7-863c-1bb816a47731.png)

The pictures above are miner androids but it applies to all. I've heard of complaints from a couple of other users that their fisherman and farmer androids also broke into Cs-CoreLib heads.

## Environment
Minecraft: 1.11.2
Slimefun: 4.1.5
CS-CoreLib: 1.5.14
Server: (I'll try to contact the owner in case the server version may be also part of the issue)

P.S.
I've tried contacting any admin or owner of the server about the said issue above, but to no avail as of today. Thank you for your understanding and will look forward to your response.

Warm regards,
kljigs500

**Comment by TheBusyBiscuit** [comment]
Corruption is nothing that can be investigated.
