### ISSUE TITLE
use Ancient Pedestal bug to copy items

### ISSUE THREAD

**Issue by Rothes** [TheBusyBiscuit/Slimefun4#2251]
## Description (REQUIRED)

This is a Ancient Pedestal bug. You can copy everything you like using it.

## Steps to reproduce the Issue (REQUIRED)

1.Place a Ancient Pedestal
2.Use an auto-clicker, right click quickly to Ancient Pedestal
3.Let a player break the Ancient Pedestal
VIDEO: https://drive.google.com/file/d/1dR0ahb2NZllxMs4VdYeIrITps1TAcaEl/view?usp=sharing

## Expected behavior (REQUIRED)

The player should get a Ancient Pedestal , and one item on it.

## Server Log

nothing was logged

## Error Reports

nothing was reported

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): git-Spigot-379750e-eaf0bac (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
 - Minecraft Version: v1_16_R2
 - Slimefun Version: vDEV - 639 (git ec95797c)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)

**Comment by NCBPFluffyBear** [comment]
That happens when you are using Item Stacking, disabling item stacking will prevent this from happening.

**Comment by Rothes** [comment]
I think this bug should be fixed from slimefun. We can solve it by blocking breaking the Ancient Pedestal within a seconds of interacting with it

**Comment by Rothes** [comment]
To add on:
1.I tried to disable holographic item plugin, the bug still occurs.
2.The bug also occurs on the paperspigot server.(Test on git-Paper-144 / git-Paper-141)
3.I learned about this bug from one of my players. He seems to have used the bug on other servers.

**Comment by NCBPFluffyBear** [comment]
I worked with @Rothes to try to determine the cause of the problem, and it was not due to item stacking like I originally thought (Item stacking still causes dupes and bugs though, he didn't have item stacking). I used a command block + delay using repeaters to sudo myself to do /break while rapidly spamming the pedestal.

**Comment by WalshyDev** [comment]
> I used a command block + delay using repeaters to sudo myself to do /break while rapidly spamming the pedestal.
That isn't something a normal user can do

You have a plugin modifying the items when put on the pedestal, this thing has caused issues for other people too. I don't know what plugin it is but try and repro without any other plugins.

If you can, post repro steps along with a video showing `/sf versions` and `/plugins`

**Comment by NCBPFluffyBear** [comment]
The sole purpose of the command block was to break the pedestal and reproduce it alone, a normal player can break it too (You would need someone else to help you). 

The plugin that modifies the items coming out of the pedestal is not the source of the problem. I verified it in a local server without item stacking, entity stacking, holograms (or really anything else besides EssentialsX).

**Comment by XXY233** [comment]
I think I don’t have the plugin that caused the error, but I can still copy the item.
https://youtu.be/F1gqAo8mioQ
![2020-08-26 101116](https://user-images.githubusercontent.com/46647646/91247307-946b9800-e784-11ea-941a-2f6c21a846c6.png)

**Comment by Rothes** [comment]
> [14:04:25 INFO]: Plugins (37): AntiRepeat*, BentoBox, BossShopPro, BungeeTabListPlus, ColorMOTD*, CoreProtect, CS-CoreLib, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGUI*, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, GrItemTags*, HolographicDisplays, InventoryRollback, LuckPerms, Multiverse-Core, NeverLag*, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, SignEdit, Skript, Slimefun, SlimefunItemId*, TabooLib5*, TitleManager, Vault, ViaBackwards, ViaVersion, VIPCustom, WGAcheck, WorldBorderAPI, WorldEdit


> [14:04:44 INFO]: This Server uses the following setup of Slimefun:
[14:04:44 INFO]: Paper v1_16_R2
[14:04:44 INFO]: CS-CoreLib vDEV - 90 (git 9dd4a1cf)
[14:04:44 INFO]: Slimefun vDEV - 639 (git ec95797c)
[14:04:44 INFO]: Metrics build: #16
[14:04:44 INFO]:
[14:04:44 INFO]: Installed Addons: (1)
[14:04:44 INFO]:  SlimefunItemId v1.0

**Comment by LinoxGH** [comment]
A possible fix is adding a cooldown to using altar(and perhaps to all machines that you interact with) this way spamming won't be able to cause duping.

**Comment by Shuot0614** [comment]
![2020-08-26_10 59 54](https://user-images.githubusercontent.com/37780163/91320455-88cf9f80-e78b-11ea-973f-37741340fad0.png)

**Comment by Mace68** [comment]
I can confirm this dupe works. Running the following versions.
![Versions](https://i.gyazo.com/08b98c3da3d4b052828f19d3265baf1e.png)

**Comment by TheBusyBiscuit** [comment]
Can anyone try and see if the issue persists in build "DEV - 646"?
If so, give adequate versions info and steps on how to reproduce this. Best would be a video.

**Comment by poma123** [comment]
It now corrupts the displayname of the item. Also, sometimes when I break the pedestal and there was an item on it, the dropped item disappears. At least the dupe doesn't work anymore.

4 videos: https://imgur.com/a/MLXTE9w

* **Plugins** (14): CS-CoreLib, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, PlaceholderAPI, PlugMan, ProtocolLib, SkinsRestorer, Slimefun, TitleManager, Vault, WorldEdit, WorldGuard
* **Server software:** Paper version git-Paper-157 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
* **/sf versions:**
![image](https://user-images.githubusercontent.com/25465545/91612173-263df580-e97d-11ea-97d6-b50b9aeb27e1.png)

**Comment by TheBusyBiscuit** [comment]
Good that this bug is fixed at least XD
Can you make a new bug report for this new issue?

**Comment by poma123** [comment]
Well, sure.

**Comment by Rothes** [comment]
Tried over 50 times now. The bug was fixed and the pedestal works perfectly, without any problems.
> Slimefun vDEV - 647 (git ac5d5521)
