### ISSUE TITLE
Fluid Pump: Lava dupe!

### ISSUE THREAD

**Issue by Lehinx** [TheBusyBiscuit/Slimefun4#2265]
## Description (REQUIRED)

Buckets get filled from non-source water/lava. 

https://github.com/TheBusyBiscuit/Slimefun4/pull/2256

## Steps to reproduce the Issue (REQUIRED)

https://www.youtube.com/watch?v=quJMXYGEzb0

## Expected behavior (REQUIRED)

Shouldn't fillup buckets from non-source lava/water.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.2-R0.1-SNAPSHOT
 - Slimefun Version: DEV - 648
 - CS-CoreLib Version: DEV - 79

**Comment by LinoxGH** [comment]
I think this is caused by Vein.find method. The method can fill the list it returns with the same blocks so in this case the non-source blocks. Gonna fix that in a pr to cs-corelib2 soon.
