### ISSUE TITLE
Backpacks can go inside shulker boxes and shulker boxes inside backpacks for infinite storage

### ISSUE THREAD

**Issue by Momshroom** [TheBusyBiscuit/Slimefun4#227]
## Description
You can put a backpack with a shulker box in it inside a shulker box inside a backpack ad infinitum for infinite storage

## Server Log
There are no errors.

## Evidence / Proof
https://youtu.be/LkPQhRbfIA4

## Environment
http://prntscr.com/erejrf

**Comment by VoidAngel** [comment]
Proposed tweak
#267
