### ISSUE TITLE
Auto updater URL's still containing spaces.

### ISSUE THREAD

**Issue by LeafyMitsuwa** [TheBusyBiscuit/Slimefun4#228]
## Description
See #199 for more information.

The update URL's for V1.5.13 -> V1.5.14 for CS-CoreLib and V4.1.3 -> V4.1.5 are still using spaces, rather than a %20 or an underscore.

## Server Log
http://puu.sh/v6xH3/35bab61247.png

## Environment
CS-Corelib v1.5.13
Slimefun v4.1.3

**Comment by TheBusyBiscuit** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9176152-196095049_1-s1-v1.png?transparent=1&palette=1&width=246)

How about... **updating to get the Update in which it has been fixed...**
