### ISSUE TITLE
Cannot measure distance between worlds

### ISSUE THREAD

**Issue by Deathinflames** [TheBusyBiscuit/Slimefun4#230]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.

**Issue suspected to be related to cargo as the IllegalArgumentException starts spamming in the console when near these machines.** 

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

[https://pastebin.com/raw/7DcFzZiK](https://pastebin.com/raw/7DcFzZiK)

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

Server: CraftBukkit git-Spigot-b605b31-f4822eb (MC: 1.11.2)
>sf versions
[02:51:40 INFO]: CraftBukkit v1_11_R1
[02:51:40 INFO]:
[02:51:40 INFO]: CS-CoreLib v1.5.14
[02:51:40 INFO]: Slimefun v4.1.5
[02:51:40 INFO]:
[02:51:40 INFO]: Installed Addons:
[02:51:40 INFO]:  ExoticGarden v1.6.1

**Comment by TheBusyBiscuit** [comment]
Fixed in CS-CoreLib 1.5.15
