### ISSUE TITLE
Full disable of a Slimefun item/change

### ISSUE THREAD

**Issue by Tim3game-zz** [TheBusyBiscuit/Slimefun4#231]
## Description
I have installed Slimefun v4.1.5  and i need to disable changes, that slimefun is making (I need to disable changes like Elytra, Chainmail Armor, Drinks...). But when I try to disable them fully from the files, it still is saying **"You do not have enough Knowledge to understand this"** or **"This Item has been disabled! How did you even get that?"**. I really need to disable the items from Slimefun, and best to remove them from the Guide.

## Server Log
https://pastebin.com/dGREGKkZ (I really hope nothing important gets leaked :D)

## Evidence / Proof
[http://prntscr.com/erx5in](url)

## Environment
**Minecraft version:** 1.11.2 (/sf versions: CraftBukkit v1_11_R1)
**Spigot version:** git-Spigot-625bc00-b5f7b6d (API: 1.11.2-R0.1-SNAPSHOT)
**CS-CoreLib version:** 1.5.14
**Slimefun version:** 4.1.5
  **HotbarPets:** 1.1
  **ExoticGarden:** 1.6.1
  **Barrels:** 1.9

**Comment by Poslovitch** [comment]
I approve this idea

**Comment by BlackBeltPanda** [comment]
Would also like this feature. =)
