### ISSUE TITLE
Vein mining pick duplication

### ISSUE THREAD

**Issue by dart737** [TheBusyBiscuit/Slimefun4#232]
## Description
If you put fortune of any level on a vein mining pick, you can simply re-place the ores you mine, mine them and get more than what you originally placed, leading to infinite duplication of any ore. It does not do this with any other pick that I've seen. 

## Server Log
The console does not produce any errors when this is done.

## Environment
Minecraft version: 1.11.2
Core lib: 1.5.12 (I will update this, but it doesn't seem as if the bug is fixed with the updates)
Slimefun: 4.1.5

**Comment by TheBusyBiscuit** [comment]
Any Addons?

**Comment by dart737** [comment]
Yes, Exoticgardens and Barrels

**Comment by DeathlyPanda** [comment]
Edited Vein Mining Pick, should stop duplication of ores once patch goes through.
