### ISSUE TITLE
Can't extract items from output

### ISSUE THREAD

**Issue by unknownerror51** [TheBusyBiscuit/Slimefun4#234]
I can't pull any of the items out of the output from my server, I cant figure out whats going wrong with it, its not client mods, i can't see anything in the config that stops me extracting. I'm not too sure if it was one of my plugins or something I messed up in config. Other players have had this issue too. I can put things into machines but can't take them out, I can put in and out of backpacks ect.

I'm running a bukkit server on version 1.11.2.

I have:
CS-Corelib%20v1.5.13
CommandWatcher
CoreProtect_2.14.2
EndlessEnchant
Essentials-2.x-SNAPSHOT
EssentialsAntiBuild.x-SNAPSHOT
EssentialsChat-2.x-SNAPSHOT
EssentialsGeoIP-2.x-SNAPSHOT
EssentialsProtect-2.x-SNAPSHOT
EssentialsSpawn-2.x-SNAPSHOT
GriefPrevention
InfernalMobs
InsaneMobs
InsaneMobs%20v2.01_1.11
Multiverse-core-2.5-b717
Openinv
PerWorldInventory-1.7.5
PermissionsEx-1.23.4
SensibleToolbox_v1.0.99
Shopkeepers
SilkSpawners
SlimeMobs_v1.4
SlimeXpansion_v1.1.8
Slimefun%20v4.1.3
SlimefunOres_v1.4.6
TreeAssist
votifier-1.9
worldedit-bukkit-6.1.5
worldguard-6.2

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
