### ISSUE TITLE
Slimefun Items stuck in output slot

### ISSUE THREAD

**Issue by unknownerror51** [TheBusyBiscuit/Slimefun4#235]
I can't pull any of the items out of the output from my server, I cant figure out whats going wrong with it, its not client mods, i can't see anything in the config that stops me extracting. I'm not too sure if it was one of my plugins or something I messed up in config. Other players have had this issue too. I can put things into machines but can't take them out, I can put in and out of backpacks ect.

I'm running a bukkit server on version 1.11.2.

I have:
CS-Corelib%20v1.5.13
CommandWatcher
CoreProtect_2.14.2
EndlessEnchant
Essentials-2.x-SNAPSHOT
EssentialsAntiBuild.x-SNAPSHOT
EssentialsChat-2.x-SNAPSHOT
EssentialsGeoIP-2.x-SNAPSHOT
EssentialsProtect-2.x-SNAPSHOT
EssentialsSpawn-2.x-SNAPSHOT
GriefPrevention
InfernalMobs
InsaneMobs
InsaneMobs%20v2.01_1.11
Multiverse-core-2.5-b717
Openinv
PerWorldInventory-1.7.5
PermissionsEx-1.23.4
SensibleToolbox_v1.0.99
Shopkeepers
SilkSpawners
SlimeMobs_v1.4
SlimeXpansion_v1.1.8
Slimefun%20v4.1.3
SlimefunOres_v1.4.6
TreeAssist
votifier-1.9
worldedit-bukkit-6.1.5
worldguard-6.2

https://pastebin.com/EKTtC1Lc Here are my logs but these are completely useless, there is no information that i would class as useful here as i say this issue has been going on for a while.

## Evidence / Proof
What will a picture show i cant pull items out of machines, image one in the machine in the output image 2 still there enough said?

## Environment
I am on minecraft PC obv, MC version 1.11.2 what other informations can i provide? I need help no one has any answers anywhere ive looked, Slimefun v4.1.3 as said above. along with all the slimefun versions and all my plugin versions. do you need any other information like my config for slimefun. can you also actually tell me something that helps.
![slimefun](https://cloud.githubusercontent.com/assets/26882674/24726388/1983343c-1a4a-11e7-8bc3-cec2c7f73915.png)

EDIT: I realised i had the wrong logs in there those were from another server, updated maybe have some useful info in this now.

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
