### ISSUE TITLE
NullPointerException with Electric Gold Pan

### ISSUE THREAD

**Issue by Deathinflames** [TheBusyBiscuit/Slimefun4#236]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.

I am not sure exactly how to re-produce this particular message, but it has appeared approximately 8 times in the past week. We've had reports of the Electric Gold Pan and the Electric Ore Grinder items turning into 'normal items' that lose their attachment to SlimeFun. So far it appears to be random occurrences but it is occurring more often as time goes on.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

https://pastebin.com/raw/QcFiShVV

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

Server Software: CraftBukkit
  Build: git-Spigot-b605b31-f4822eb (MC: 1.11.2)
  Minecraft: 1.11.2-R0.1-SNAPSHOT
  CS-CoreLib 1.5.14
  Slimefun 4.1.5

**Comment by freethemice** [comment]
This is a common problem

**Comment by freethemice** [comment]
I've been trying to fix this bug for some time now and what is causing it is when it save "energy-charge" with "addBlockInfo" in "D:\Daniel\Documents\SourceTree\Slimefun4\src\me\mrCookieSlime\Slimefun\api\BlockStorage.java"
it will sometimes save it with out the "id" tag.
I don't know why. im still trying to figure it out, its hard to track down.
I think it has to do with, it reads the configfile then it adds to it, but when this happens it reads a black config for it, this resets it with no "id"
I hope that helps the team

**Comment by TheBusyBiscuit** [comment]
@freethemice This is completely unrelated.

**Comment by Deathinflames** [comment]
This is a similar error but with the Electric Dust Washer machine:

https://pastebin.com/raw/gSVdbyTd
