### ISSUE TITLE
Furnace bug

### ISSUE THREAD

**Issue by Tim3game** [TheBusyBiscuit/Slimefun4#238]
## Description
When I have installed Slimefun (even without Addons), there appears a bug with the furnace, that when I take the items from the furnace with a Right Click (Taking out half of the items), instead of taking out the half I wanted, it updates and takes ALL of the items in the current slot. I reported this sooner, but now I running the newest Spigot, SlimeFun and Exotic Garden version. If it's a bug or not, please say it before closing it. I didn't find anyone that had this problem, and I experienced this maybe 1 year ago and it's really annoying to play with it!
## Server Log
No errors in console.

## Evidence / Proof
![sffurnacebug](https://cloud.githubusercontent.com/assets/10467214/24840636/cb2c4ce0-1d70-11e7-97d4-9281669fd9fa.gif)

## Environment
**Minecraft version:** 1.11.2 (/sf versions: CraftBukkit v1_11_R1)
**Spigot version:** git-Spigot-d276ab1-d219213 (API: 1.11.2-R0.1-SNAPSHOT)
**CS-CoreLib version:** 1.5.14
**Slimefun version:** 4.1.6
  **HotbarPets:** 1.1
  **ExoticGarden:** 1.6.3

**Comment by TheBusyBiscuit** [comment]
Do not repost Issues, this is not caused by Slimefun.
