### ISSUE TITLE
Hostile Skeleton/Zombie Dupe System by: Ender Talisman of the Hunter

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#239]
Easy if you have a MobSpwaner.... of Zombie or Skeleton (from Minecraft works)
not using others plugins....

Ender Talisman of the Hunter:
20% change double all drops from mobs you kill
Equip your p4 set, take close of a Zombie or Skeleton let they kill you.
Back and kill it back with Talisman on inventory. 
Done you have Duped your P4 item. Works with any equipable item.

So... to solve this problem you have to update plugin and add an option in the config.yml  to let ppl setup if want or not make hostile creatures equip items dropped from players ? Or another solution? Like Talisman of the Hunter cant duplicate equipped items ?

https://www.youtube.com/watch?v=LEEXFVi8W_4

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
