### ISSUE TITLE
Auto Updater not functioning

### ISSUE THREAD

**Issue by LeafyMitsuwa** [TheBusyBiscuit/Slimefun4#240]
## Description
Slimefun autoupdater does not account for spaces in the .jar file hosted on a server, generating an I/O error.

## Server Log
http://puu.sh/vfmw5/fb19528037.png

## Evidence / Proof
http://puu.sh/vfmw5/fb19528037.png

## Environment
CS-CoreLib v1.5.14 and Slimefun v4.1.5

**Comment by TheBusyBiscuit** [comment]
This has nothing to do with spaces, your Server Software does not automatically handle auto-updates, create a folder called "update" in your plugins folder yourself.
