### ISSUE TITLE
[HELP] Deleting things in the slimefun guide

### ISSUE THREAD

**Issue by davidshaver** [TheBusyBiscuit/Slimefun4#243]
I was wondering if there's a way to delete a spot in the slime guide, for example, i don't use the machines and how would I get rid of it on the guide?
also i don't want players to spawn with the guide can i disable it if so, how?

thanks in advance

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
