### ISSUE TITLE
Electric blocks only display a gui for players with op

### ISSUE THREAD

**Issue by lordofbore** [TheBusyBiscuit/Slimefun4#248]
## Description
After many fingers have been broken after repeatedly clicking on various blocks of coloured clay, I can conclude that most of the GPS heads do in fact, work (except for the oil pump) but this caused me to conclude the error is only for specific guis. (as a simple player on the server, I have no access to the full range of machines but if you require me to test them all, I will without hesitation. 👍 )

## Server Log
I do believe this is a link to the server log, do tell if there is any problems with it.
https://pastebin.com/cUz5mrVt
(Thanks Spawki!)

## Evidence / Proof
I greatly apologise, my screenshot didn't upload but I can say that the "GPS control panel" and the "GPS Geo-scanner" did work and had the guis displayed correctly while the "Electric gold pan II", "Electric furnace" and the "Oil pump" had no guis and even refused hopper input (I was unable to place a hopper on any of the blocks, when I placed the machine on the block it had no effect)
If you have any suggestions for other things to try, I am all ears.

## Environment
As a resident "dumb dumb" that has been well established, I do not have the correct permissions to access the "/sf version" command but I believe it is slimefun4. The minecraft version is 1.11.2 and I have been raised to believe a CS-CoreLib is a fancy device for preparing apples and software is a method of cheese making.

## Other notes
I have seen one other person post this error but it seemed to be immediately closed without any solution apparent. I do hope that this is an error on my part or simply a chest protection plugin needing a update.

Oh and, the server owner did apparently post something on a forum about this but it was removed without any reply (I apologise if I'm just jumping the gun a bit) but if you are just going to, well, "brush this error under the doormat" please, tell me if you are because if you don't I will be forced to keep looking and looking for a solution and I am getting tired of writing.

Have a good day person who skipped to the end :).

**Comment by Venomous777** [comment]
Here's a log I got from my server: https://pastebin.com/cUz5mrVt
Here's video proof: https://pastebin.com/cUz5mrVt
