### ISSUE TITLE
Two dupe glitches using backpack

### ISSUE THREAD

**Issue by kiritss** [TheBusyBiscuit/Slimefun4#250]
1. right clicking a ancient pedestal and getting another person to take out the content from the backpack while you take out items from your backpack

2. Right clicking + dropping a backpack at the same time and doing the same as above

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
