### ISSUE TITLE
Backpack dupe

### ISSUE THREAD

**Issue by kiritss** [TheBusyBiscuit/Slimefun4#251]
## Description
Right clicking + dropping backpacks allow another players to loot the backpack and take items out while you also take items out.

Right clicking an ancient pedestal also produces the same results

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
Latest version of cscorelib + slimefun

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
