### ISSUE TITLE
Grappling Hook Stops Working When Fired Into Void

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#253]
## Description
When using the Grappling Hook, if a player fires it into the Void, the player is then unable to use the Grappling Hook again until the server is restarted.

## Server Log
No errors

## Evidence / Proof
GIF: https://i.gyazo.com/7237c15ba97ce133227e7f3282eccae7.gif
You can't really see it in the GIF, but I was unable to fire the Grappling Hook again after that until the server was restarted.

## Environment
MC: 1.11.2 git-Paper-1072
CS-CoreLib: 1.5.12
Slimefun: 4.1.2

**Comment by jordanwilliams1** [comment]
@BlackBeltPanda If you shoot a bow after it going in the void does it duplicate the item?

**Comment by BlackBeltPanda** [comment]
@jordanwilliams1 It doesn't duplicate but it does teleport me to the arrow and drops a new Grappling Hook.

**Comment by lew69** [comment]
hi we find the same probleme but only the player who made it can't use his grappling hook
