### ISSUE TITLE
how to use the Trash Can in a Cargo Management System 

### ISSUE THREAD

**Issue by zhunihuifeima** [TheBusyBiscuit/Slimefun4#254]
## Description
I have tried it many times but still can‘t make it。 Please show me

## Server Log
No errors
## Evidence / Proof
No

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
