### ISSUE TITLE
Pistons Duplicate Cargo Holograms

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#256]
## Description
Using a piston, you can push a Cargo Hologram and duplicate it.

## Server Log
No errors.

## Evidence / Proof
GIF: https://i.gyazo.com/cacaf3e3ec0b9e973c6d75f85983d10c.gif

## Environment
MC: 1.11.2 git-Paper-1072
CS-CoreLib: 1.5.12
Slimefun: 4.1.2

**Comment by Randou** [comment]
Not only do the pistons double the holograms, putting 1 hologram on top of the other can cause them to double if they are close together, and it also happens that the Energy Regulator can have this same bug if something explodes near the machine

**Comment by BsnNick** [comment]
@TheBusyBiscuit In your CS-CoreLib, couldn't adding `armorStand.setMarker(true)` in the createHidden method fix this issue by preventing blocks interacting with the hologram?

Even if that API call doesn't exist in older Bukkit/Spigot versions, the tag itself has existed in Minecraft since 1.8.

**Comment by TheBusyBiscuit** [comment]
@BsnNick Never heard of that method, I don't know, I haven't looked into Bukkit or Minecraft since many many Versions.

Do some research, perform tests and implement it if it proposes a fix.

**Comment by TheBusyBiscuit** [comment]
This has been fixed in CS-CoreLib.
