### ISSUE TITLE
A new way to have power anywhere

### ISSUE THREAD

**Issue by BearWithAScarf** [TheBusyBiscuit/Slimefun4#257]
Hello! It is always annoying to have to stay at your energy and not have power anywhere else. I suggest a new way to bring power anywhere. Here is the idea, Batteries. These will be crafted in different tiers as the capacitors are. I know there are already batteries but these will be used as the base crafting for these new ones. So now let me explain how they will be put to use.. So each machine will have a new slot in the corner for these batteries. You stick the batterie in that slot and then that machine will use the power from the battery inside it and run off of that power. Also maybe capacitors  will also be able to hold a battery and run machines near by using that capacitor using the battery. And these batteries will be charged in the charging bench witch will also create a opportunity for a mark. 2 charging bench. This would work out perfectly because it is not a game changing feature and is super convenient and cool and would not need to rely on pre loaded chunks and would be the best route for power anywhere . This would add for a great new Feature in the next slime fun update! Sorry I did not know where to put this suggestion! Have a great day! (big fan of this plugin and want to help it grow!) and also do not know how to put labels on posts so yeah! Also Something cool would be Safari nets. These could capture animals and then place them in a new location.

**Comment by lordofbore** [comment]
I thought the whole "energy network" was a large part of slimefun, the ability to place a machine and instantly power it, skips quite a bit.

**Comment by John000708** [comment]
As @lordofbore mentioned the energy network is an important part of Slimefun. Infact, the machines can't be ticked without them being connected to an Energy Network, since they get remotely ticked.
