### ISSUE TITLE
Will this plugin someday support full language translate (in config)?

### ISSUE THREAD

**Issue by evernife** [TheBusyBiscuit/Slimefun4#259]
Is there any chance for this plugin have a full locale.yml config for all dialogs, texts and items?

Or it is something too exhaustive to be done:question:

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
