### ISSUE TITLE
Crucible not working as advertised / differences with ElectricCrucible

### ISSUE THREAD

**Issue by claer** [TheBusyBiscuit/Slimefun4#263]
## Description
In the Crucible description (in game) it says that 12 hardened clays could be converted to water.
It looks like the information is sourced from file "src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java", line 2287
                 new ItemStack [] {new ItemStack(Material.COBBLESTONE, 16), new ItemStack(Material.LAVA_BUCKET), new ItemStack(Material.LEAVES, 16), new ItemStack(Material.WATER_BUCKET), new ItemStack(Materia     l.HARD_CLAY, 12), new ItemStack(Material.WATER_BUCKET)})

When trying, I couldn't create water from hardened clay (nor lava) while it worked nicely for cobble to lava.

All that story came because I wanted to convert clay to hardened clay then to water automatically to cool my nuclear reactor. And when I tried to transform hardened clay with ElectricCrucible, I got lava.
Maybe from file src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectrifiedCrucible.java, line 19:
registerRecipe(8, new ItemStack[] {new ItemStack(Material.BUCKET), new ItemStack(Material.HARD_CLAY, 12)}, new ItemStack[]{new ItemStack(Material.LAVA_BUCKET)});

Please fix the inconsistency :)

## Server Log
Sorry I'm only user, I don't have access to those.

## Evidence / Proof
src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java", line 2287
vs
src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectrifiedCrucible.java, line 19

## Environment
Minecraft 1.11.2, SF 4.1.5. Again sorry I'm only a user and I don't have access to /sf versions for more details.

**Comment by VoidAngel** [comment]
Proposed fix
#267

**Comment by claer** [comment]
Hello VoidAngel,
Yep it would be nice to see this fix merged
thx
