### ISSUE TITLE
Docs for making add-ons..

### ISSUE THREAD

**Issue by chibill** [TheBusyBiscuit/Slimefun4#264]
## Description
No docs just a very messy doc of small parts of the API.
No docs on what needs to be extended for it to be seen as an add on.
Also it's odd that you force all add ons to be GPL by choosing GPL...
.

**Comment by chibill** [comment]
If you don't document how to make them I will be forced to see how yours are made.

**Comment by chibill** [comment]
Also you current docs don't document interacting with any part of the API other then the item and block part.

**Comment by TheBusyBiscuit** [comment]
Yep.
