### ISSUE TITLE
ExtraGear crashing

### ISSUE THREAD

**Issue by EonGaminq** [TheBusyBiscuit/Slimefun4#269]
## Description
Slimefun itself is working Properly but the addon "Extra Gear" Is not working, I will provide the logs.

## Server Log
https://pastebin.com/FCn4r7SQ

## Evidence / Proof
http://imgur.com/a/8pJtd

## Environment
Spigot 1.9.4-R0.1
Slimefun
Slimefun v4.1.7
CS-CoreLib v1.5.14
ExtraGear_v1.1

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
