### ISSUE TITLE
Items don't break

### ISSUE THREAD

**Issue by SoSeDiK** [TheBusyBiscuit/Slimefun4#273]
## Description
Armor, weapons, tools don't break, their durability goes into negative.
This happened after updating to Slimefun 4.1.7, with 4.1.6 there is no such problem.

## Evidence / Proof
https://youtu.be/cMVo0w53dOk

## Environment
'/sf versions' :
CraftBukkit 1_11_R1

CS-CoreLib v1.5.15
Slimefun 4.1.7

Installed Addons (9):
ExtraGear v1.1
ExoticGarden v1.6.3
SlimeScrap v1.2.2
ZeldaHearts v2.0.2
SlimeXpansion v1.1.8
SlimefunBarrels v1.9
HotbarPets v1.1
SlimefunLuckyBlocks v.1.1
SlimefunOres 1.4.6

**Comment by Sidious82** [comment]
agreed
