### ISSUE TITLE
Advanced Android Farmer

### ISSUE THREAD

**Issue by WBgroup** [TheBusyBiscuit/Slimefun4#277]
I wanted to move it, so I broke it, and placed it.  I downloaded program and started it. When i did that it vanished, same was with second Android (But new one first changed to skeleton skull)

## Server Log
I don't have permissions because I'm not an admin

## Evidence / Proof
![2017-05-04_19 22 58](https://cloud.githubusercontent.com/assets/25838025/25719071/88a495c0-3108-11e7-94ba-47690e4c8b4f.png)

## Environment
Slimefun 4.1.2
Minecraft 1.11.2
When i use the command it says: "You do not have the required Permission to do this"

Sorry for my English...

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
