### ISSUE TITLE
Paperclip Build Will not load

### ISSUE THREAD

**Issue by crston** [TheBusyBiscuit/Slimefun4#286]
## Description

When I opened the server with spigot build, the server stopped frequently, so I changed to paperbuild but it disappeared, but the slimefun function was disabled.

## Server Log

https://pastebin.com/zL45AXra

## Evidence / Proof
None

## Environment

Minecraft Version: 1.11.2
Server version: Paperclip-1095.jar
CS-CoreLib v1.5.14
Slimefun: v4.1.8 

Addons:
Exotic Garden: v1.6.3

**Comment by TheBusyBiscuit** [comment]
The Error you provided does not help at all since it is fired when disabling the Plugin, a log showing Slimefun's boot sequence would be much better.
It would be the best if you posted your **full** Server log.

**Comment by crston** [comment]
Here you are. 
https://pastebin.com/RQdJJ4ZU

**Comment by crston** [comment]
https://pastebin.com/5q28sQG3

**Comment by andris155** [comment]
This server is running Paper version git-Paper-1104 and SlimeFun work.

**Comment by NicksWorld** [comment]
It appears to be missing files in the plugins or the files are altered
