### ISSUE TITLE
Changing a Broker Spawner in a Pig Spawner

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#290]
_## Description_
If you Take any Mob-Spawner, and broke it with the Pickaxe of Containment, it will be renamed to: Broken Spawner Type "Mob". So now, put the Mob-Spawner on a anvil and rename it. Now put the Broken Spawner on the ground. Done you have a Pig Spawner

_## Server Log_
cant open pastebin.com > ERR_CONNECTION_TIMED_OUT using codeshare.io
https://codeshare.io/5ePj04

_## Evidence / Proof_
https://www.youtube.com/watch?v=LAPTkSEMIXg

_## Environment_
Server Spigot 1.11.2 Build: 3fb9445eca2
Client Minecraft Original 1.11.2
Plugin: SlimeFun 4.1.8
Plugin: CS-CoreLib v1.5.14

**Comment by andris155** [comment]
Found a solution:
https://www.spigotmc.org/threads/disable-item-renaming-in-anvil.131780/

**Comment by comonier** [comment]
solved ty
