### ISSUE TITLE
Rainbow Clay/Cargo nodes changing properties.

### ISSUE THREAD

**Issue by Ballzz06** [TheBusyBiscuit/Slimefun4#291]
## Description
I was looking through my console trying to debug the issue we are having with the cargo nodes changing back into CSCorelib heads when I came across this error message. Just thought you might want to be aware of it. It is throwing multiple errors. It seems that anytime there is an error thrown by one of these blocks, all of our cargo nodes on the server has to be reset.

## Server Log
https://pastebin.com/7b43iPD9 this is one of our 12 hour cycles. At the bottom you can see where it threw multiple errors and spamed the console. 

## Environment
https://pastebin.com/CAj9vdpy that is a copy of exactly everything that your error log takes record of including every plugin and every version we are running in.

**Comment by BlackBeltPanda** [comment]
Was wondering why I had this problem and, sure enough, a search through my logs reveals that same error.
