### ISSUE TITLE
Fresh server CS-CoreLib Plugin.yml error. Including after being deleted.

### ISSUE THREAD

**Issue by LigerXT5** [TheBusyBiscuit/Slimefun4#294]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Fresh server setup. No Slimefun-based folders. Error appears about a bad plugin.yml in the CS-CoreLib.jar. Appears to be only a CS-CoreLib Related error, but happens when I delete it and allow auto-download/update.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/yxMB82b1

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
The best I could do is show pictures of proof no folders for CS CoreLib and Slimefun is not being created.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Linux - Ubuntu Server 17.04.
Java 8
MC Spigot: This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
Latest builds of Slimefun and related plugins at the date of this post.

**Comment by TheBusyBiscuit** [comment]
Reinstall CS-CoreLib.
