### ISSUE TITLE
Fish Glitch in Enhanced Furnaces

### ISSUE THREAD

**Issue by pinkpig3777** [TheBusyBiscuit/Slimefun4#299]
## Description
Any furnace within the "Basic Machines" section can be used to dupe fish including normal fish and salmon. 
Another issue is that it changes raw fish to cooked salmon. So there are two issues. One: it doesn't use up the raw fish but keeps making more cooked fish. Two: It changes raw fish to cooked salmon instead of cooked fish. 

## Server Log
https://pastebin.com/Nx5v85r6

## Evidence / Proof
https://youtu.be/_KddYSGOsP0

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Spigot 1.10
CS-CoreLib 1.5.14
SlimeFun 4.1.8

Thank you.

**Comment by andris155** [comment]
1.10 TerrainControl http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/164/

**Comment by NicksWorld** [comment]
I have just tested and there is **NO** issue in my test server
![2017-06-04_15 42 15](https://cloud.githubusercontent.com/assets/29175042/26764829/85337310-493c-11e7-9e1b-35f6f8ff40ba.png)

**Comment by pinkpig3777** [comment]
There is the issue on my actual server and test server.... Both are 1.10 Spigot.

**Comment by John000708** [comment]
I cannot reproduce the issue as well, using 1.12 Spigot and the latest version of Slimefun @pinkpig3777

**Comment by pinkpig3777** [comment]
:/

**Comment by pinkpig3777** [comment]
NicksWorld was your test server on 1.10 or 1.12?

**Comment by NicksWorld** [comment]
1.10 1.12 wasn't out yet
