### ISSUE TITLE
/sf give with amount parameter

### ISSUE THREAD

**Issue by pinkpig3777** [TheBusyBiscuit/Slimefun4#300]
## Description
When I disable items I offer my players their items back that were used to craft the disabled item. It would help a lot if I were able to give a certain amount of each item instead of one at a time. Also, I use a custom mobs plugin and on a custom creeper's death I'd like it to give the player a few sifted ore but I can't because there is no way to give more than one at a time.

## Server Log
No need because it's a suggestion.

## Evidence / Proof
Whenever I try to do:
/sf give PiggiesGoSqueal Sifted_Ore 3
it will say:
Slimefun > Usage: /sf give <Player> <Slimefun Item>

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Spigot 1.10
CS-CoreLib 1.5.14
SlimeFun 4.1.8

Thank you.

**Comment by LeafyMitsuwa** [comment]
I second this as a suggesion.
