### ISSUE TITLE
Slimefun Ignoring Config file and permissions settings

### ISSUE THREAD

**Issue by Elithelion** [TheBusyBiscuit/Slimefun4#303]
## Description
I have a multiple world server comprising of a survival world and a creative world. I have the allow-free-creative-research option set to false yet people are still able to unlock items in their books. I have also dissallowed the /sf and all /slimefun commands using PermissionsEX and that is getting ignored.

## Server Log
https://pastebin.com/DufVCgZS

## Evidence / Proof
![2017-05-28_08 05 11](https://cloud.githubusercontent.com/assets/6694126/26529081/08fc906e-437f-11e7-9df0-3454fa53379a.png)
![2017-05-28_08 09 33](https://cloud.githubusercontent.com/assets/6694126/26529079/08f44300-437f-11e7-89cd-2ed306453c5b.png)
![2017-05-28_08 09 47](https://cloud.githubusercontent.com/assets/6694126/26529080/08f50b78-437f-11e7-87fe-119a4402ab09.png)
![2017-05-28_08 09 52](https://cloud.githubusercontent.com/assets/6694126/26529082/0900e93e-437f-11e7-927a-9fa51765ca0d.png)
[permissions.zip](https://github.com/TheBusyBiscuit/Slimefun4/files/1034166/permissions.zip)
[config.zip](https://github.com/TheBusyBiscuit/Slimefun4/files/1034167/config.zip)

## Environment
CraftBukkit v1_11_r1

CS-Corelib v1.5.14

Slimefun v4.1.8

**Comment by TheBusyBiscuit** [comment]
It is not ignoring your Permissions, there are simply no Permissions for this.
Use something like CommandOverride or any other plugin to restrict command usage.

Either way, this is not Slimefun-related but a fatal mistake with your Server Setup.
