### ISSUE TITLE
Toggleable Research Fireworks (via config.yml)

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#308]
would be nice if someone add an option to disable fireworks when we learn a new recipe from sf guide.

**Comment by Poslovitch** [comment]
It would be even nicer if we could disable it only for /sf research all, because it can generate lot, lot, lot of fireworks

**Comment by Poslovitch** [comment]
I will work on that, that's something I really want to be able to do as soon as possible.
