### ISSUE TITLE
/WARN]: [Slimefun] Exception caught while ticking a Block:java.lang.NullPointerException

### ISSUE THREAD

**Issue by Sidious82** [TheBusyBiscuit/Slimefun4#309]
## Description
BTLteamTNT - Today at 6:00 PM
Slimefhn dun goofed again
Slimefun
All of ster and my machines broke
Sidious82 - Today at 6:54 PM
k
what broke about them
BTLteamTNT - Today at 7:21 PM
No idea
Sidious82 - Today at 7:23 PM
very helpful
thank you

## Server Log
see line 3510
https://pastebin.com/YmPGXWEU

## Evidence / Proof
upon trying to replace the auto disenchanter that was broken, it generated this error log:
https://pastebin.com/gZ0XvCCi

## Environment
https://pastebin.com/gZ0XvCCi

**Comment by TheBusyBiscuit** [comment]
Not related to Slimefun, looks like some other Plugin added a corrupted Enchantment to an Item.
