### ISSUE TITLE
Crook duplication glitch

### ISSUE THREAD

**Issue by Momshroom** [TheBusyBiscuit/Slimefun4#313]
## Description
If you break tilled soil with a crook, it drops a duplicate crook instead of dirt, as described in this closed issue about soulbound shovels and hoes: https://github.com/TheBusyBiscuit/Slimefun4/issues/74  This leads to infinite crooks.
I confirmed that the glitch no longer happens with the soulbound hoe. 

## Server Log
No console errors related to this glitch.

## Evidence / Proof
https://www.youtube.com/watch?v=aqtkUts2ERw

## Environment
http://prntscr.com/fi7ntx.

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
