### ISSUE TITLE
Crook duplication glitch when breaking tilled soil

### ISSUE THREAD

**Issue by Momshroom** [TheBusyBiscuit/Slimefun4#314]
## Description
When breaking tilled soil with a crook, it drops a duplicate crook rather than dirt.

A similar issue was previously reported and fixed regarding the soulbound hoe.  This is NOT the same issue being reported.  I'm referencing the other issue b/c I expect the fix is similar. https://github.com/TheBusyBiscuit/Slimefun4/issues/74

## Server Log
https://pastebin.com/0TSeBKFW

There are no console errors and I can't imagine why you would possibly want to read a huge server log to see that but since that is the only thing I can see that possibly doesn't follow your posting guidelines that caused you to delete my last post about a DUPLICATION GLITCH w/o bothering to tell me why other than to read the posting guidelines I'd already read and followed, here is a copy of the vast log with people's personal info in it.  Knock yourself out. :P  The guidelines say not to repost, but seeing as I think it was closed for formatting, I'd assume you'd still want to know about a DUPLICATION GLITCH in your plugin.

## Evidence / Proof
https://www.youtube.com/watch?v=aqtkUts2ERw

## Environment
http://prntscr.com/fi7ntx

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
