### ISSUE TITLE
Magical Eye Of Ender Disappearing

### ISSUE THREAD

**Issue by Ac3dUd3** [TheBusyBiscuit/Slimefun4#317]
When wearing the Ender Armor and teleporting using the Magical Eye Of Ender, it eye disappears after it sends the pearl.

Im not sure what else to write sorry

04:41:02 [INFO] Slimefun version 4.1.8
04:41:27 [INFO] CS-CoreLib version 1.5.14
04:41:39 [INFO] This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
