### ISSUE TITLE
Magical Eye Of Ender Disappearing

### ISSUE THREAD

**Issue by Ac3dUd3** [TheBusyBiscuit/Slimefun4#319]
## Description
When wearing the Ender Armor and teleporting using the Magical Eye Of Ender, it eye disappears after it sends the pearl.

## Server Log
https://pastebin.com/5BB8Kt52

## Evidence / Proof
A player told me about it, he did not have screenshots sorry. no console errors from what i can see

## Environment
12:38:00 [INFO] Slimefun version 4.1.8
12:38:17 [INFO] This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
12:38:28 [INFO] CS-CoreLib version 1.5.14

**Comment by devonc0** [comment]
Noticing the same issue on DifferentCraft:

Steps to reproduce:
1) Wear full ender armor suit - no enchants
2) Craft Magical Eye of Ender
3) Crouch
4) Right-click

Results:
1) Magical Eye of Ender acts like a regular Eye of Ender
2) Magical Eye of Ender no longer present in inventory.

Notes:
1) While Full Ender Armor suit equipped, the text for "Requires full Ender Armor" remains red (as if indicating I'm not wearing the armor)

**Comment by jordanwilliams1** [comment]
Thanks for reporting this for me @devonc0 😉

**Comment by jordanwilliams1** [comment]
Are we going to get this fixed?

**Comment by Poslovitch** [comment]
Did some tests.
It seemed that the PlayerInteractEvent isn't cancelled (even if, when debugging, it appeared it correctly was), so the Ender Eye was still thrown.
Didn't find any fix for that.

**Comment by Poslovitch** [comment]
@TheBusyBiscuit close this issue : fixed in 4.1.11 (https://github.com/TheBusyBiscuit/Slimefun4/commit/d9ef5bab02368ad71125bb62c0d3a03aa39118e1)
