### ISSUE TITLE
Beheading Enchant Breaks Auto-Disenchanter

### ISSUE THREAD

**Issue by dharbigt** [TheBusyBiscuit/Slimefun4#322]
## Description
When trying to disenchant a sword with Beheading, the Auto-Disenchanter becomes bricked, turning into a standard enchanting table for all intents and purposes.  Placing another Auto-Disenchanter in the same spot produces strange results, appearing to reflect the inventory of the previous Auto-Disenchanter before it broke.

## Server Log
I'm not an admin, but my admin didn't seem concerned enough to report this bug.  It should be easy enough to reproduce on any server.

## Evidence / Proof
![screen shot 2017-06-14 at 7 04 54 am](https://user-images.githubusercontent.com/16137900/27129329-d8839690-50cf-11e7-94ab-2d6cd881e203.png)

## Environment
I've asked the admin for this information and will report it if/when it becomes available.

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
