### ISSUE TITLE
Disable recipes

### ISSUE THREAD

**Issue by SnowyTSW** [TheBusyBiscuit/Slimefun4#325]
## Description
I'd like to be able to disable crafting recipes for certain Slimefun items via config without disabling the item itself (unless this already exists and I'm just blind). I know that it is already possible to disable the specific item (and therefore the recipe), but this is not what I'm looking for.

## Server Log
As this is a suggestion, there is none.

## Evidence / Proof
There isn't much to show with this one, but I can't find anything that relates to disabling the recipe.

## Environment
CraftBukkit v1_11_R1 (This is what shows up in /sf versions, but I'm pretty sure it's Spigot 1.11.2)
CS-CoreLib v1.5.13
Slimefun v.4.1.8

**Comment by viocu** [comment]
I would also like to see this happen. I want players to be able to use the item but not be able to craft it. It can only be obtained through an OP or admin or other special means.

**Comment by TheBusyBiscuit** [comment]
@Poslovitch already added this.
But it could use a little tweaking before it will be released.
Dont ask when.
