### ISSUE TITLE
Suggesting a better item recognition system

### ISSUE THREAD

**Issue by Poslovitch** [TheBusyBiscuit/Slimefun4#332]
## Description
To recognize items, Slimefun currently checks its display name (and sometimes the lore).
This causes a lot of trouble when we start thinking about localisation. I've already tried to translate Slimefun from English to French. I translated messages, ranks, researches... But when I tried to translate items, this has caused all the items my players had to break. They were no longer recognized by the plugin, and I had to give them back in their french version. This was a real mess.

What I suggest here, is to use another item recognition system I've already experimented.

I added to the first lore line of each item a weird text.
`this.item = new CustomItem(item, item.getItemMeta().getDisplayName(), new String[] {"§m§i§n§i§b§l§o§c§k"});`

Which in game looks invisible :
![](http://puu.sh/wouzp/dc05f747bd.png)

As you can see, this id is made up by a pattern `§<letter>`.
Minecraft understands it as "color codes", but as there is no text to display, it just shows a blank line.

**But!**

That's why we want. Whatever the display name of the item is, I just check if the first lore line contains `§m§i§n§i§b§l§o§c§k`, so I instantly know that this item is "miniblock".
Even better ! No matter if the player renames its item : it still has the id in its lore, so I can still know that this item is "miniblock".

This system will allow us to make items translatable, as well as fixing a lot of potential bugs. (see, for example, the evidence section).

Thanks.

## Server Log
Not needed as this is a suggestion.

## Evidence / Proof
Here is an example of what problems the actual recognition system can causes :
#290 - https://www.youtube.com/watch?v=LAPTkSEMIXg

## Environment
This problem affects each Slimefun version, regardless of the environment.
But, for compliance motives, here is the environment I currently use : 

Paper v1_11_R1
CS-CoreLib v1.5.14
Slimefun v4.1.9

**Comment by TheBusyBiscuit** [comment]
I would suggest hashing the id to hexes and using that as an identifier in color codes, since they
That way, anything but this hash should be completely customizable.
It could also be in the name, lore whatever.

I would write a system like that myself but it would mostly invalidate any ItemStacks currently present on Slimefun Servers.
Also a very drastic change, should definitely be a part of a huge Update.
Slimefun 5? I would then need to shift my current Slimefun 5 project to a different Name or Slimefun 6 then XD

Or there has to be some sort of migration method...

**Comment by Poslovitch** [comment]
Ahah! Yup, you should name your Slimefun 5 project to something like "Slimefun Standalone 3000", just to be sure x)

Hashing IDs to hexes looks good, but yep : this will be a drastic change, but I'm not sure the most part of Slimefun servers will like to loose again all items and machines while updating. We must necessarly support a migration.

**Comment by Redemption198** [comment]
Or maybe jump from 4 to 6, leaving the 5 as standalone

**Comment by AlexLander123** [comment]
Maybe keep the old recognition system around for a few updates but integrate it with the new system . 

For example:
Add the hash to the lore of every item that pass SlimefunManager#isItemSimilar() but does not have a hash. This will slowly convert the items to work with the new system.

**Comment by Poslovitch** [comment]
I agree with your idea. Providing a smooth migration is far better than just saying «Give the new items back.»

**Comment by MrCubed** [comment]
I will say I have minimal experience with these type of things,

but perhaps all slimefun items also much have the custom nbt data such as {SlimefunItem:1} or something...

This might be a complete waste of time, BUT
it worked for me when I needed to distinguish between items in a vanilla environment.
Again, this is a plugin, not a vanilla command. So please don't be mad at me if this is completely useless xD.

Also I like the idea of Miniblocks, and I have no idea how to add slimefun items, maybe you could help me xD

**Comment by TheBusyBiscuit** [comment]
@MrCubed 
NBT is good for client-side stuff.
But Plugins are server-side and this is not particular easy to access, let alone use NBT properly without requiring a major rewrite everytime Minecraft updates.

**Comment by tr7zw** [comment]
Hey, I kinda just found out about Slimefun, after spending some time developing my own ftb like plugin. I'm kinda shocked that you are storing data in the displayname/lore. I use my own reflection based NBT api that enables you to practically add everything to the nbt. https://www.spigotmc.org/resources/item-entity-tile-nbt-api.7939/ NBT clientside is just useful for visual stuff but serverside they are really powerful to track stats, traits, custom enchantments and so on. As example: https://github.com/LogisticsCraft/Logistics-API

**Comment by SoSeDiK** [comment]
I was thinking about this lately.
I see the 3 *(or almost)* ways.
1. We can use custom nbt tags. It's complicated and won't work with every plugin. I don't mind using it as a developer but it can be hard for regular user who uses only fully premade public plugins.
2. Using lore. Not sure about hexes but we can use something like '&0sf:item_id". As a good thing, we can do whatever we want with this item (rename/enchant/etc) and easily make the resource pack using OptiFine.
3. This one is the same is the second one but with the ability to hide the ids in lore using ProtocolLib. Useful if you don't use the OptiFine & resource pack as it makes item look nicer.
The main issue, as was already noted, is that every SF item will break. And that's the point where I was thinking about making the final 1.13 release as a huge update (SF 5?). We can remove all deprecated and unused code/API (like fixing old SF books, just get rid of them) and implement systems like this one and #861.
As an alternative, we can also wait for 1.14 with its custom model data and use that for identifying. Also, till that time we can make a complete list of game/plugin-breaking things and release fresh Slimefun 5 ror 1.14.
I would like to hear your thoughts.
