### ISSUE TITLE
Slimefun Juices with Saturation do nothing. (MC1.11.2 and MC1.12)

### ISSUE THREAD

**Issue by RightyBird** [TheBusyBiscuit/Slimefun4#333]
## Description
While using Minecraft 1.11 or higher (confirmed in 1.12 as well), drinking any potion that gives saturation is consumed with no effect given.

## Server Log
https://pastebin.com/PcNLe28Y
Note: No server log messages at time of consumption. 

## Evidence / Proof
Simple test.  Using any 'juice' from either slimefun or exotic garden that is supposed to satisfy hunger will show it has no saturation effect when consumed.  Other potions work.  Tested on MC1.11.2 and MC1.12

## Environment
CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
Installed Addons (8)
HotbarPets v1.1
ExoticGarden v1.6.3
ZeldaHearts v2.0.2
SoulShards v1.9.5
SlimeXpansion v1.1.9
SlimefunOres v1.4.6
Shelter v1.0.2
SlimefunGuidePlus v1.0

## Research
https://bugs.mojang.com/browse/MC-112389 - seems to be related to Minecraft 1.11.2 and up.

## Suggested solution
Ability to turn-off juices selectively, or the migration of all recipes into an external text file that could be red and modified.  I understand I can comment out the juices in the code but this is not a very plugin friendly solution.  It would be better if controlled by a .config or a .yml file

**Comment by Poslovitch** [comment]
Your suggested solution looks similar to #325. I will work on that.

**Comment by TheBusyBiscuit** [comment]
@Poslovitch 
I would suggest you to write an Interface for SlimefunItems such as IStaticRecipe or so that prevents Recipe Editing. Backpacks for example or ExoticGarden Bushes or Machine-internal Recipes like the Crucible rely heavily on static Recipes.
Also, this should rather be an Addon, side note: Addons can call SlimefunItem#setRecipe()
You could export/import JSON files for this but keep in mind that fancy JSONs can take massively longer to load.

**Comment by Goldentoenail** [comment]
Concerning the Juice consumption issue.
I have looked at the class me.mrCookieSlime.Slimefun.listeners.ItemListener
At the Event 'public void onEat(PlayerItemConsumeEvent e)', line 276 which handles the Juices. There is no player consume event dealt with.

Sorry, if I have missed this happening elsewhere.

**Comment by TheBusyBiscuit** [comment]
@Goldentoenail 
There is no Event needed.
Juice are just Potions, you drink a Potion and get its Effects (Saturation in this case), no need for us to do anything but somehow Minecraft itself broke something about it, or Bukkit/Spigot.

**Comment by Goldentoenail** [comment]
Understood. thanks.

**Comment by Zippers99** [comment]
I am also having this issue. Any word on a possible fix?

**Comment by Meta-Win** [comment]
Just drag it on your plugin folder to fix
https://www.spigotmc.org/resources/drinkfixer-fix-saturation-potion.47610/

**Comment by Poslovitch** [comment]
I checked the code of this plugin and this looks like an easy trick.

Gonna do a PR asap.

**Comment by Poslovitch** [comment]
Thanks :)
