### ISSUE TITLE
Guide dupes vanilla items

### ISSUE THREAD

**Issue by trebiluk** [TheBusyBiscuit/Slimefun4#345]
## Description
With Slimefun 4 and the bleeding-edge CS-Corelib - I can pull items, like the dispenser, from the guide and throw them on the ground. The error comes from CS-Corelib and from Slimefun  in console with Spigot 1.12 latest.

## Server Log
https://pastebin.com/RFiGKYHc

## Evidence / Proof
http://prntscr.com/fpkr1w - dispenser does not pop back in place.
http://prntscr.com/fpkrl4 - two dispensers on the ground from the guide.

## Environment
http://prntscr.com/fpksfo

**Comment by TheBusyBiscuit** [comment]
The Error you posted traces back to a bug in your Server Software, not Slimefun.
Either one of your Plugins messed with your Recipe System or your Server Software is bugged, either way, not related to Slimefun.
