### ISSUE TITLE
Installing addons to slimefun

### ISSUE THREAD

**Issue by TheGeekFactor** [TheBusyBiscuit/Slimefun4#351]
Hi there,

All I need to know is how to install addons to slimefun. I've had some trouble with it and I CANNOT FOR LIFE OF ME FIND ANYTHING ONLINE ABOUT IT. So if ANYONE can tell me or show me how, I'd be grateful

**Comment by xH3LLRAIZ3Rx** [comment]
Its as simple as drag and drop the addon into the plugins folder, if it doesnt work, make sure you have an up-to-date CS-Corelib and Slimefun
