### ISSUE TITLE
Player can trash items using Slimefun Guide

### ISSUE THREAD

**Issue by nahkd123** [TheBusyBiscuit/Slimefun4#354]
Hi, I just found a bug. When player open Slimefun guide, put the cursor into blank slot in guide then press number from 1 to 9, the item from player will send to Slimefun guide. You can still get item out when you put it into guide, but when player close the GUI without take item out, the item lost forever and can't get it back anymore.

Here is an screenshot :
![2017-07-07_15 44 33](https://user-images.githubusercontent.com/20136708/27950395-487809fa-632b-11e7-8494-a77b6678eae8.png)

**Comment by Poslovitch** [comment]
Please follow the issue template.
