### ISSUE TITLE
Automated Crafting Chamber

### ISSUE THREAD

**Issue by NapoleonBae** [TheBusyBiscuit/Slimefun4#357]
Ok so here's the description -- no one on my server knows and I don't know where to post this so here it is. Please feel free to dm me, remove this thread or move it to a new location. 

 With the automated crafting chamber, I want to make all the quartz I have into quartz blocks but I have like 40 double chests of it (hoppers connecting all chests). If I put the pattern, 4 quartz in a square in the automated crafting table and I put a coal generator and large capacitor next to it (the electricity isn't my concern I have a lot of resources to produce a lot) is there any way I can connect all the chests of quartz to the automated crafting table? I doubt you can use hoppers but is there anything else in sf where I can connect it because the sneak peek video confused me and I'd hate to spend all my money and resources I have left into it if it can't accomplish the goal I need. All I want to do is let it run continuously on it's own fully automatically and come back an hour or day later and see all the quartz made into quartz blocks without manually touching anything. Thanks so much, I really appreciate it :))﻿

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

**Comment by NapoleonBae** [comment]
So I've just been told that automated crafting chambers don't work with regular vanilla items. Is that true? Cause like then I'm sad :(( is there any other way to auto craft

**Comment by Poslovitch** [comment]
It currently doesn't work with vanilla items. There is a piece of code that may have been intended for getting vanilla recipes however it is commented out.

And for item transportation, check the CARGO nodes

**Comment by NapoleonBae** [comment]
What do you mean commented out? Is it possible to put it back maybe?

**Comment by Poslovitch** [comment]
In the source code, it is there, however it is « commented out ». This means that it doesn't get compiled, and so it isn't read by the server.

We could probably put it back, but if it has been commented out, this probably means that it wasn't functionnal. @TheBusyBiscuit ?

**Comment by TheBusyBiscuit** [comment]
@Poslovitch It isn't commented out, it was never added in the first place, the commented out part is a completely empty block of code... It doesn't do anything.

**Comment by Poslovitch** [comment]
It doesn't do anything. However it seems it runs through vanilla recipes. Is it a WIP part? Was it hard to implement?

If it effectively is a placeholder code, I suggest to implement it with an "Advanced Automated Crafting Chamber".

**Comment by TheBusyBiscuit** [comment]
It isn't WIP or anything.
Who knows what was going on in my silly mind back then?

"If it effectively is a placeholder code, I suggest to implement it with an "Advanced Automated Crafting Chamber"."
Go ahead.

**Comment by Poslovitch** [comment]
I didn't intend to offend you.

I will work on that when I'll be back.

**Comment by TheBusyBiscuit** [comment]
@Poslovitch 
You didn't...
I simply have a very self-sarcastic humor :P

**Comment by John000708** [comment]
@TheBusyBiscuit If my memory is good enough, you had told me that you didn't implement it because it'd take too many resources calculating the vanilla resources, so you left the Slimefun ones only.

**Comment by TheBusyBiscuit** [comment]
@John000708 That was about the recursive LUTs I believe.
This however is implementable.

**Comment by Poslovitch** [comment]
Okay, got it. Maybe should calculate them asynchronously?
