### ISSUE TITLE
SOLVED: Research at 100% from beginning 

### ISSUE THREAD

**Issue by DrunkIrishPotato** [TheBusyBiscuit/Slimefun4#358]
SOLVED: REMOVED MULTIVERSE AND RESEARCH WAS FIXED
## Description
When we add Slimefun to our server all players have 100% research unlocked from the very start. We have tried reinstalling both Cs-CoreLib and Slimefun many times, installing Cs-CoreLib first and Slimefun second. The data-storage/Slimefun/Players folder is empty also. 

## Server Log
https://pastebin.com/10BxtYJ9

## Evidence / Proof
![9743e00c-21b9-4cb1-b3f0-962e6f55bfec](https://user-images.githubusercontent.com/23072632/28128738-abe9277a-6728-11e7-96a6-e2ce545e3a54.png)

## Environment
We are running Minecraft version 1.12, SlimeFun version 4.1.9 and CS-CoreLib version 1.5.15

Any help would be really appreciated, thank you.

**Comment by Vennreni** [comment]
I  have the same problem here!

**Comment by StarWishsama** [comment]
You can try update your WorldEdit or Essentials/GroupManager
