### ISSUE TITLE
Add Cost and Click to unlock to messages.yml

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#359]
## Description
I would love it if you can add the Cost: %level% and Click to unlock to the messages.yml

**Comment by Poslovitch** [comment]
Can you explain it a bit more? I don't understand what you meant

**Comment by xH3LLRAIZ3Rx** [comment]
I would love it where you can modify the message over the researches that are locked where it tells you click to unlock and the cost: http://i.imgur.com/I8b1NC0.png

**Comment by Poslovitch** [comment]
You mean, be able to edit/translate them?

I think I'll go through all the code to make as much texts editable as we can. 
I'll do it in about a week.

**Comment by xH3LLRAIZ3Rx** [comment]
If anyone still wants to do it, go ahead, but I have no use for it now since I decided to learn a little java to modify the code myself ;)

**Comment by Gusted** [comment]
This suggestion has been solved in my pull request #818
