### ISSUE TITLE
MultiTool Translate

### ISSUE THREAD

**Issue by coco0325** [TheBusyBiscuit/Slimefun4#360]
Hi. I want translate MultiTool's mode massege. But I can't translate "%mode%". Just like this--> [http://imgur.com/a/T1SXQ](url) You can tell me which file I should translate? .class or .yml?
Thanks.

**Comment by Poslovitch** [comment]
You currently can't without editing the source code. Ad I said in #359, I'll go through the code in about two weeks to make as much texts translatable as I can.

**Comment by coco0325** [comment]
Thank you. You mean there will be a new version?

**Comment by Poslovitch** [comment]
Sure. I don't decide when a new version is released, however there will be a new one.
