### ISSUE TITLE
Slimefun not downloading CS-Core lib? </sf argument>

### ISSUE THREAD

**Issue by iiEon** [TheBusyBiscuit/Slimefun4#369]
When I download Slimefun and restart my server, it shows me a message in the console that says it needs to restart to download CS-Core lib. I restart again, and it gives me a message saying CS-Core lib didn't run properly. I never got a CS-Core lib directory or a Slimefun directory.

Any help? Thanks!

**Comment by TheBusyBiscuit** [comment]
Well, download CsCoreLib then...
