### ISSUE TITLE
Question about items.yml

### ISSUE THREAD

**Issue by viocu** [TheBusyBiscuit/Slimefun4#378]
## Description

Sorry if this has been answered somewhere, I have looked throughout this site and around google, but can't really find anything describing it. In items.yml, there is an area in each item that says "required-permission: '' " How do I use this? Can items be configured so that they can be gotten by admins only and not craftable by regular players? The goal is to reward players with certain items but they cannot craft them, they can only be gotten from a special treasure chest, etc. Thanks for any feedback!

example:
can this be explained in more detail on how to configure it?
HOTBAR_PET_WALSHRUS:
  enabled: true
  can-be-used-in-workbenches: false
  allow-disenchanting: false
  required-permission: ''

**Comment by TheBusyBiscuit** [comment]
Set the required permission to a permission tbat should be required for that Item...
