### ISSUE TITLE
MultiTool VII

### ISSUE THREAD

**Issue by Skydog28** [TheBusyBiscuit/Slimefun4#379]
How do I use the MultiTool? I make the carbonardo one, and all i can do is portable dustbin or Magical eye of ender, which doesnt seem to do anything. (I make the ender armor and that didnt help the issue either)
How do i add more modes to the tool?

**Comment by Pajlis** [comment]
In the items.yml, locate that item name and under "mode" you can enable or disable a mode. There are your modes.
