### ISSUE TITLE
Cargo system bug

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#390]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
The last github Slimefun version of cargo system contains a bug, it seems cargo output and Advanced cargo output don't work correctly: Please try to make a simple system with box of coal + carbonpress + box for compressed carbon. Carbonpress receives coal from the box on channel 1, it compresses them, but 2nd channel won't push compressed carbons in 2nd box, they come in carbonpress input box. It seems Cargo output mixes the channels.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need this.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9 https://github.com/TheBusyBiscuit/Slimefun4/tree/bbf4b5ed85d07d5b9b5db44a3b636faf28e7be4e
Installed Addons (4)
ExtraGear v1.1.1
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
ElectricSpawners v1.0
```

**Comment by TheBusyBiscuit** [comment]
Please provide a video to show what you mean.
