### ISSUE TITLE
Slimefun Reinforced spawner bug (1.12.1 - bug) (1.12 - works perfectly)

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#391]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Place spider, blaze etc... Reinforced Spawner always Pig spawner.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need this.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://www.youtube.com/watch?v=uJWtlPgY5DI

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
```

**Comment by Poslovitch** [comment]
That's a 1.12.1 Spigot bug, indeed.
You should consider submit an issue on their bug tracker

**Comment by andris155** [comment]
Spigot bug tracker not support plugins.

**Comment by Poslovitch** [comment]
This is not a bug from the plugin (cause this is happening on ASkyBlock too). This comes from CreatureSpawner#setSpawnedType() that is no longer working in 1.12.1.

**Comment by TheBusyBiscuit** [comment]
Closed since this is a Spigot Bug.
