### ISSUE TITLE
Smeltery slot bug

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#392]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Smeltery slot bug

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need this.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://www.youtube.com/watch?v=QMzj0jv01Go

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
Installed Addons (4)
ExtraGear v1.1.1
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
ElectricSpawners v1.0
```

**Comment by Poslovitch** [comment]
Did some tests.

```java
for (int j = 0; j < inv.getContents().length; j++) {
	if (j == (inv.getContents().length) && !SlimefunManager.isItemSimiliar(converting, inv.getContents()[j], true, SlimefunManager.DataType.ALWAYS)) {
		craft = false;
		break;
	}
	else if (SlimefunManager.isItemSimiliar(inv.getContents()[j], converting, true, SlimefunManager.DataType.ALWAYS)) break;
}
```

It appeared that modifying the condition below by removing the `-1` fixes the 9th slot not working.
```java
j == (inv.getContents().length - 1)
```

However, it breaks the Smeltery - because it then allows to craft a Reinforced Alloy Ingot from... nothing. ahah
