### ISSUE TITLE
Energy Regulator disappear

### ISSUE THREAD

**Issue by coco0325** [TheBusyBiscuit/Slimefun4#394]
When I place a Energy Regulator, It will be disappear.
ERR report:
Server Software: CraftBukkit
  Build: git-Spigot-99c2a37-d35483b (MC: 1.12)
  Minecraft: 1.12-R0.1-SNAPSHOT

Installed Plugins (58)
  + RPGHealthIndicator 1.6
  + slimelab-AMLCB 0.1
  + Lobbys 1
  + MythicLib 0.0.1-SNAPSHOT
  + PistonBlocker 1.1
  + AntiAFKPlus 2.11
  + PlayerSkills 1.4.4
  + Friends3_0 3.0.2.3
  + EpicWorldGenerator 7.2.29
  + AsyncWorldEditInjector 2.3.0
  + CoreProtect 2.14.2
  + icJukeBox 1.6.3
  + WorldEdit 6.1.7;dd00bb1
  + Kycraft 1.0.41
  + NBTEditor 2.3-SNAPSHOT
  + ClearLag 2.9.7
  + MessageAnnouncer 1.8.0
  + ProtocolLib 4.3.1-SNAPSHOT-b378
  + Multiverse-Core 1.1
  + MCCore 1.61
  + DeathMessagesPrime 1.12.10
  + LibsDisguises 9.4.0-SNAPSHOT
  + NoCheatPlus 3.15.0-SNAPSHOT-sMD5NET-b1022
  + AsyncWorldEdit 2.3.3
  + PermissionsEx 1.23.4
  + TAB 1.2.8
  + LiteJoin 3.5
  + StainedText 0.0.4
  + CS-CoreLib 1.5.16
  + Multiverse-Portals 2.5.0-b751
  + CustomJoinItems 1.5.2
  + SwearReplacer 1.0
  + Vault 1.5.5-b47
  + DailyRewards 1.3.1
  + SimpleSit 1.5.1
  + UltraCosmetics 2.4.9
  + PerWorldInventory 1.10.0
  + HolographicDisplays 2.2.6
  + WorldGuard 6.2.1;84bc322
  + SkillAPI 3.101
  + MythicMobs 4.2.0-SNAPSHOT
  + ChestCommands 3.1.4
  + Slimefun 4.1.9
  + PetBlocks 6.0.0
  + RedstoneClockPreventer 1.3.1
  + Orebfuscator4 4.3.0
  + Essentials 2.0.1-b370
  + Citizens 2.0.22-SNAPSHOT (build 1484)
  + ColoredTags 2.1.3
  + Shopkeepers 1.82
  + DiscordSRV 14.8
  + EssentialsChat 2.0.1-b434
  + ExoticGarden 1.6.3
  + GriefPrevention 16.7.1
  + MoreTP 0.3.4b
  + Quests 2.9.7-b163
  + RandomTeleport 1.7.4 (build #20)
  + TradeMe 4.0.1.9

Ticked Block:
  World: slimefun
  X: -19107
  Y: 234
  Z: 617

Slimefun Data:
  ID: ENERGY_REGULATOR
  Inventory: false
  Data: {"id":"ENERGY_REGULATOR"}

Stacktrace:

java.lang.IllegalArgumentException: Item cannot be null
	at org.apache.commons.lang.Validate.noNullElements(Validate.java:364)
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.addItem(CraftInventory.java:282)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.machines.ReactorAccessPort.pushItems(ReactorAccessPort.java:223)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AReactor$10.generateEnergy(AReactor.java:372)
	at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3111)
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Server log:
[Sun, 13. Aug 2017 12:11:53 UTC WARN] [Slimefun] X: -19107 Y: 234 Z: 613(ENERGY_REGULATOR)
[Sun, 13. Aug 2017 12:11:53 UTC WARN] [Slimefun] has thrown 4 Exceptions in the last 4 Ticks, the Block has been terminated.
[Sun, 13. Aug 2017 12:11:53 UTC WARN] [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.
[Sun, 13. Aug 2017 12:11:53 UTC WARN] [Slimefun]
[Sun, 13. Aug 2017 12:11:57 UTC WARN] [Slimefun] Exception caught while ticking a Block:java.lang.IllegalArgumentException
[Sun, 13. Aug 2017 12:11:57 UTC WARN] [Slimefun] X: -19107 Y: 234 Z: 614
[Sun, 13. Aug 2017 12:11:57 UTC WARN] [Slimefun] Saved as: 
[Sun, 13. Aug 2017 12:11:57 UTC WARN] [Slimefun] /plugins/Slimefun/error-reports/2017-08-13-12-11(4).err
[Sun, 13. Aug 2017 12:11:57 UTC WARN] [Slimefun] Please consider sending this File to the developer(s) of Slimefun, sending this Error won't get you any help though.

**Comment by TheBusyBiscuit** [comment]
This has already been reported and fixed.
