### ISSUE TITLE
Enhanced Furnace speed bonus breaks with Minecraft 1.12.1

### ISSUE THREAD

**Issue by Momshroom** [TheBusyBiscuit/Slimefun4#395]
## Description
Enhanced furnaces stop providing a speed boost on server upgrade to Spigot 1.12.1.  They work properly in 1.12.  Reverting the server to 1.12 fixes the issue, even on the same furnace.

## Server Log
There are no related errors. Here is the log from the 1.12.1 bootup with the issue: https://pastebin.com/TAdHF0uM

## Evidence / Proof
If you really need a video, I can make one, let me know.
To replicate, simply boot the server in 1.12.1 Spigot and put anything in an enhanced furnace. ( I was testing with the level 10 ones)

## Environment
Working environment: http://prntscr.com/g87nxf
Non-working environment: http://prntscr.com/g87nap
Please note that even though /sf versions reports 1.12 for both, the spigot /version command (output shown in images) reports correctly that the working environment is 1.12 and the non-working one is 1.12.1

**Comment by andris155** [comment]
same problem

**Comment by Fharen** [comment]
I'm also having this problem,. But carbonado problem does not end there. after leaving it alone,. then some restart logoff whatever,. I can't pinpoint on how to make it happen exactly,. while carbonado is bugged and active, after some while, it will start throwing tons of whatever item is placed inside.
