### ISSUE TITLE
SlimeFun clash with Grief Prevention

### ISSUE THREAD

**Issue by Ac3dUd3** [TheBusyBiscuit/Slimefun4#400]
## Description
if you hit a claimed animal with a one shot kill sword, then it doesnt die, but if you spam it, you will get the loot you get from the slimefun plugin
its normal, but becuase it doesnt die, you can do it for hours, and get a bunch of end game machines

## Server Log
https://hastebin.com/oluhuqoqol.bash

## Evidence / Proof
N/A

## Environment
04:49:17 [INFO] CraftBukkit v1_12_R1
04:49:17 [INFO]
04:49:17 [INFO] CS-CoreLib v1.5.16
04:49:17 [INFO] Slimefun v4.1.9
04:49:17 [INFO]
04:49:17 [INFO] Installed Addons (9)
04:49:17 [INFO] Barrels v1.11
04:49:17 [INFO] SlimeXpansion v1.1.9
04:49:17 [INFO] ExtraGear v1.1.1
04:49:17 [INFO] SlimefunLuckyBlocks v1.1
04:49:17 [INFO] ExoticGarden v1.6.3
04:49:17 [INFO] SoulJars v1.0
04:49:17 [INFO] SlimefunOres v1.4.6
04:49:17 [INFO] SlimeCalculator v1.0.0
04:49:17 [INFO] SlimeScrap v1.2.2

**Comment by DaddyElf** [comment]
Animals shouldn't drop slimefun items, fix your config. I removed animals the first day when a chicken dropped waffles, yes it was funny but  just no 📦

**Comment by Ac3dUd3** [comment]
Animals will drop SF items if you have slimefun mobs installed. I will post the issue in that plugin issue tracker
