### ISSUE TITLE
using permission nodes

### ISSUE THREAD

**Issue by viocu** [TheBusyBiscuit/Slimefun4#405]
How would i use the permission nodes in the items.yml? Like, required-permission: "slimefun.item.*" for all items, or required-permission:"slimefun.item.grandmas-walking-stick"? Thanks for the help!

**Comment by TheBusyBiscuit** [comment]
Just put a permission node there that will be required for this item, make something up, like
"slimefun.walking_stick" or "rank.vip", whatever. Then just assign this permission to the people who should be able to use that item.
