### ISSUE TITLE
Cargo output nodes channel ID bug

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#408]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Both kinds of cargo output nodes are bugged, they don't check for the channel ID.
For example, there's an input node on channel 5 and an output node on channel 3 and it'll work.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
![kepkivagas](https://user-images.githubusercontent.com/8324198/29727425-1c2eca3a-89d4-11e7-8a4b-6e21e9e8a517.PNG)

**Comment by TheBusyBiscuit** [comment]
@Poslovitch 
0b54f079e4e1c6c3af54303873d9a4cb83826ca2

**Comment by Poslovitch** [comment]
@TheBusyBiscuit do you mean my commit solves this?

**Comment by Poslovitch** [comment]
Well, I'll investigate that

**Comment by FallonTPC** [comment]
I'm having the same exact issue on my server. It only happened after the most recent update.

**Comment by Phloydman** [comment]
Hey folks,  I can confirm this issue exists as well, and as FallonTPC states above it only broke recently.

**Comment by TheBusyBiscuit** [comment]
@Phloydman Your video shows the opposite, it shows how the nodes are working as intended...
1. This is about channels, not items...
2. Different types of stone are stone. You didn't set your input node to segregate between sub-ids/durability...

**Comment by Phloydman** [comment]
TheBusyBiscuit, wow....ok learned something new.
Didn't know the sword is also used for selecting sub ids thought it was only durability.
thanks.

**Comment by Phloydman** [comment]
Are you available some time to see my SF build?

**Comment by mrcoffee1026** [comment]
No, this is still a bug.  It's not just subitems/durability.  Used to be that channels were 'obeyed' now they are not.  I have output in a Channel 3 (Charcoal) being somehow magically being output into channel 1 (which takes input of coal from a different location...) with or without the subid being selected... cross contamination of channel #s is causing this with this release.  Please fix ASAP as it is rendering cargo unpredictable and practically worthless.

**Comment by Poslovitch** [comment]
This has been fixed by this commit. I ensure it. It took 3h to debug it, and I've properly done a bunch of tests.
