### ISSUE TITLE
Duplication of items 

### ISSUE THREAD

**Issue by WilliamEstrela** [TheBusyBiscuit/Slimefun4#415]
## Description
How to make the bug:
Step 1: Move the slimefun block of your site with a piston.
Step 2: Break this block and put any other block in place and move with a piston to where originally the slimefun block was.
Step 3: When you break the block it will return to the slime machine fun

If we do this with an anvil auto, when breaking it dps to be moved with the piston we will have an iron block, and when breaking the block that was put in place of the auto anvil with the piston before being moved, we will receive return to auto anvil .

## Server Log
Log: https://pastebin.com/tAcRqKx1

## Evidence / Proof
https://youtu.be/7zde63M4Dcs

## Environment
![image](https://user-images.githubusercontent.com/5386302/29883851-e6faee2c-8d87-11e7-82b8-5703795b379b.png)

**Comment by TheBusyBiscuit** [comment]
Please disable ads on your Video, gaining profit from this is inaporopriate.

**Comment by WilliamEstrela** [comment]
I was defunct, I'm going to deactivate

**Comment by chanjx1204** [comment]
why close my issue? my issue is the same as his....
i even have the proof

**Comment by TheBusyBiscuit** [comment]
@chanjx1204 If it's the same, then it is a duplicate.
No need to report the same issue multiple times, instead of spamming with new reports, you could just contribute to this conversation by supplying information, or you could at least read the guidelines.

**Comment by chanjx1204** [comment]
well , i hope you can fix it as fast as your can.
1 more issue, sry, i don't know how to write this issue properly:
cargo's channel is bugged. everything using cargo system won't follow the correct channel.
tried to reload the plugin again and again,using the newest version. still the same
