### ISSUE TITLE
It wont let me craft

### ISSUE THREAD

**Issue by NTheGamerGirl** [TheBusyBiscuit/Slimefun4#416]
Whenever I try crafting one of the machines it won't let me and it never works I don't know how or why it does this, I have no control over the madder at hand, that's why I'm writing this so you can fix it. For example if I try making the Ore Washer, I'd put everything in the right order then I right click the fence post and it says "Sorry this item(s) is not recognizable please do a pattern/craft within my knowledge" I don't know how to fix the problem even people tried helping me like Labby200, but it wouldn't work then he/she gave up (couldn't tell gender) so did I, after hours later I still don't understand even though that I do it by the recipe it always says "Unrecognizable, please try a different pattern that I know" So that's why I made this complaint...

**Comment by sjx233** [comment]
Put Sifted Ore in the dispenser, then right click the fence post
