### ISSUE TITLE
Add compatibility

### ISSUE THREAD

**Issue by 100petr** [TheBusyBiscuit/Slimefun4#417]
Hello, I have a plugin on the server https://www.spigotmc.org/resources/restrictedcreative.42790/ and if the player destroys the explosive pickaxe built blocks in the creative should not fall but fall and the plugin author has referred me to this .. "If The other plugin's developer is interested in supporting my plugin, then I'll add an API for that in the next version. " - the author of the plugin, would you like to do something about this? (I'm sorry I do not have the topic filled according to the original, but it's not quite like that.)
https://www.youtube.com/watch?v=8ICeT-Hm_1I (ignore name video)
http://prntscr.com/gf9nkg
(Sorry for my English, I'm not Englishman and I use it google translate)

**Comment by TheBusyBiscuit** [comment]
No, not going to hook into a Premium Resource...
