### ISSUE TITLE
Backpack Duplication of items

### ISSUE THREAD

**Issue by StarWishsama** [TheBusyBiscuit/Slimefun4#424]
## Description
ALL Backpack Duplication of items.

1. Put items into backpack.
2. Unlock any research.
3. Take out the items in backpack during unlocking research.
4. When unlock research done, open backpack, you'll see the items that were once taken from the backpack appear inside the backpack.

(Sorry about bad English)

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

## Evidence / Proof

Youtube Video: https://www.youtube.com/watch?v=itmz_UohR0Y

## Environment

PaperClip 1.12.1 latest version
Slimefun V4.1.10
CS-CoreLib 1.5.16

**Comment by TheBusyBiscuit** [comment]
This Video is more than a year old and shows an unofficial Slimefun Build which cannot represent tbhe version you stated.
