### ISSUE TITLE
ChestGui makes it able to pick up the Grass Block

### ISSUE THREAD

**Issue by Liferdorp** [TheBusyBiscuit/Slimefun4#429]
## Description
I installed the SlimeFun plugin  and I am really happy! It works like a charm! Except for one thing... When you open the guide in "Chest Gui" mode you can pick up the grassblock from vanilla. This happens with, and without vanilla enabled.

This means you shift click the grass block in you own inventory

There are no errors in the log

I will include a picture

Before:
![image](https://user-images.githubusercontent.com/15012298/30287293-cb566506-9724-11e7-8082-24f23d661d44.png)

After shift clicking
![image](https://user-images.githubusercontent.com/15012298/30287317-ded889ba-9724-11e7-8f11-9f2c5a8948c0.png)

## Environment
I am using alle the newest version of the plugins
![image](https://user-images.githubusercontent.com/15012298/30287344-f9438462-9724-11e7-9746-bda1d02ec362.png)

**Comment by TheBusyBiscuit** [comment]
This is from an Addon, not Slimefun...
