### ISSUE TITLE
/sf argument is the only thing i get when putting in any command.

### ISSUE THREAD

**Issue by lacyoftime** [TheBusyBiscuit/Slimefun4#430]
## Description
i try to use anything in slimefun, and all i get is sf arguement

## Server Log
https://pastebin.com/y5vw6C70

## Evidence / Proof
https://gyazo.com/563bd66f112cc3106fc7d56b6c0963d1
https://gyazo.com/cc01b9b5ffcb6663e45ef90927e1f76f

## Environment
minecraft is on 1.12.1, CS-CoreLib 1.5.15 ,slime fun 4.1.10
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

**Comment by TheBusyBiscuit** [comment]
(Re)install CS-CoreLib...
