### ISSUE TITLE
Fortune V doesn't exist.

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#431]
## Description
After attempting to enchant double chest fulls of golden pickaxes at a max enchantment table with plenty of exp and lapis using the Wizard talisman... being on a server with several OP players attempting the same... acquiring MANY Fortune IV enchantments... as no one has received a Fortune V enchant on my server or the server we previously played - it is my belief this enchantment does not exist.  As this hasn't been reported as a bug... please if you have actually successfully enchanted a Fortune V, please argue the point, but I believe there must be a mathematical error in the odds thereby preventing them from ever taking place.

## Server Log
Nothing significant.

## Evidence / Proof
In this case, any evidence to the contrary would prove me wrong just fine.

## Environment
CraftBukkit v1_12_R1
Slimefun 1.4.9
CS-CoreLib v1.5.16
ExoticGarden 1.6.3

**Comment by TheBusyBiscuit** [comment]
Been reported before, been fixed before, you are running an old version...
