### ISSUE TITLE
Cargo Input/Output ID Bug

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#433]
## Description
Items are to be outputted in Channel #5.  Items are instead being output back into Channel #1 (or wherever).  There seems to be virtually no correlation between channel #s, filters established on input/output nodes... and where items actually end up.  Cargo is now unpredictable and useless.  Please Fix ASAP.

## Server Log
Nothing relevent.

## Evidence / Proof
[http://caffeinatedweb.com/mc/issue1.jpg](url)
[http://caffeinatedweb.com/mc/issue2.jpg](url)
[http://caffeinatedweb.com/mc/issue3.jpg](url)

## Environment
CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.10

**Comment by Poslovitch** [comment]
Will be fixed in 4.1.11.
