### ISSUE TITLE
Question about the open source plugin Slimefun

### ISSUE THREAD

**Issue by BandedPig** [TheBusyBiscuit/Slimefun4#434]
## Description
Where can I change the items which you can use to make dirt in the composter? Do you know which java packes it is in your plugin? I can't find it because there are so many java packes. 

## Server Log
There is no server log needed

## Evidence / Proof
Also not needed.

## Environment
I use Eclipse to change the plugin.

I hope you can help me with it! Thank you!

**Comment by xH3LLRAIZ3Rx** [comment]
Its in the me.mrCookieSlime.Slimefun.Setup package in SlimefunSetup.java, search for Composter
