### ISSUE TITLE
Could not pass event ItemUseEvent to slimefun 4.1.10

### ISSUE THREAD

**Issue by infinity3113** [TheBusyBiscuit/Slimefun4#438]
## Description

When opening the crafting table of the charging does not serve and sends crash in the console, but having op does not happen this is something that can be done? excuse my bad english I use a translator

## Server Log
https://pastebin.com/Fnte6t9N

## Evidence / Proof
![image](https://user-images.githubusercontent.com/32003718/30507555-3531ef68-9a54-11e7-9f28-ca99ce8d97fb.png)

## Environment
Spigot: 1.11.2
CS-CoreLib: 1.5.16
ExoticGarden: 1.6.3

**Comment by TheBusyBiscuit** [comment]
Not related to Slimefun.
It's from PreciousStones (CS-CoreLib's hook implementation)
