### ISSUE TITLE
Certain items stop working turn into heads

### ISSUE THREAD

**Issue by FatmanC** [TheBusyBiscuit/Slimefun4#451]
![2017-10-11_12 25 57](https://user-images.githubusercontent.com/30946891/31418062-6c4f4eca-ae7f-11e7-89fc-655bf2363100.png)
## Description
The following items, turn into heads every time the server does a reboot:
1: coal generator
2: small capacitor
3: disenchanters turn into normal enchant tables
These are the main conerns. 

## Server Log
Server log only shows that we are using 4.1.9 and that we should upgrade... ugrading broke our furnces.. and the fortune/speed stopped working so we went back to 4.19 to combat this.... only to end up with this problem. 

## Evidence / Proof
![2017-10-11_12 25 59](https://user-images.githubusercontent.com/30946891/31418059-65253132-ae7f-11e7-8a7a-efd7c6856638.png)
![2017-10-11_12 25 57](https://user-images.githubusercontent.com/30946891/31418076-8c920380-ae7f-11e7-9899-75e5ca79e975.png)
![2017-10-11_12 25 55](https://user-images.githubusercontent.com/30946891/31418082-9ac1613a-ae7f-11e7-9465-0c175725e30d.png)
![2017-10-11_12 25 47](https://user-images.githubusercontent.com/30946891/31418098-b164f73a-ae7f-11e7-9773-b296b3c68bbd.png)
![2017-10-11_12 25 50](https://user-images.githubusercontent.com/30946891/31418099-b196a172-ae7f-11e7-8c99-d96c48cc8bcf.png)
![2017-10-11_12 25 53](https://user-images.githubusercontent.com/30946891/31418101-b1c7c32e-ae7f-11e7-9c91-e88a958ec43c.png)

## Environment

MC - 1.12 craft bukkit, spigot mod
CS-corelib v1.5.15
Slimefun 4.1.9
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
![2017-10-11_12 35 45](https://user-images.githubusercontent.com/30946891/31418259-bb65c880-ae80-11e7-8b4c-f462dfda700c.png)

**Comment by TheBusyBiscuit** [comment]
Nothing that can be done about unless you are able to provide an error-report from /plugins/Slimefun/error-reports/
