### ISSUE TITLE
Toxic Metals not giving effects in offhand

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#46]
When you have toxic metals (Uranium, Thorium, etc) in your offhand you do not get any of the effects

http://i.imgur.com/5bL5AlY.jpg

Spigot 1.11, CS-Corelib V1.5.12, Slimefun V4.1.1

**Comment by xH3LLRAIZ3Rx** [comment]
also you can place the toxic metal with your offhand and it dupes it

**Comment by TheBusyBiscuit** [comment]
Fixed in next Build.
