### ISSUE TITLE
Operators Unlock all problem

### ISSUE THREAD

**Issue by ProxyErr0r** [TheBusyBiscuit/Slimefun4#462]
Basically all the slimefun stuff is fine Expect for one Massive problem, Having OP automatically unlocks EVERYTHING, And I enjoy to play normally with my players and that completey ruins it, How do I fix or disable that, I tried reseting my stats. Instantly pops back up to max

**Comment by StarWishsama** [comment]
Well, do you have a try to disable "allow-free-creative-research"?
That may can help you :)
