### ISSUE TITLE
A suggestion about translate

### ISSUE THREAD

**Issue by StarWishsama** [TheBusyBiscuit/Slimefun4#464]
Hi, I using slimefun for a long time.
But when i want to translate into Chinese, i can't replace "Click to open" in Slimefun Guide.
This isn't a serious bug, but i still want it can be solved :)

(Sorry of my bad English)

**Comment by Poslovitch** [comment]
Cause it comes from CSCoreLib

**Comment by StarWishsama** [comment]
Well, if i modify cscorelib, can solve this problem?

**Comment by Poslovitch** [comment]
Yup
