### ISSUE TITLE
Ancient Altar used to repair Broken Spawner after put on the ground change to Pig spawner.

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#466]
## Description

I decided to open this ticket just to report it. 

After I update my server to version 1.12.2 (before 1.12) when a player places a mob-spawner repaired by the Ancient Altar on the floor even though the Mob-Spwner is for example Zombie appears Pig and if the player uses the pick of containment to remove- it again appears as Borken Spawner Pig. Note, no error appears during the process, even after repairing the Broken-Spawaner of any mob in Ancient Altar he drops the Mob-Spawner repaired perfectly, with the correct Mob name. The problem only occurs after placing the Mob-Spwaner on the floor.

## Environment
Spigot 1.12.2 (git-Spigot-93e20b3-31d3159 )
Slimefun v4.1.10
CS-CoreLib v1.5.16
Essentials v2.0.1-bSNAPSHOT
ProtocolLib v4.4.0-SNAPSHOT-b390

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/pull/461

**Comment by comonier** [comment]
I'm sorry I'm not a programmer, I do not know how to solve the problem, I did not understand anything that was written in the link that you sent me on how to solve the mob-spawner problem. Can you be more specific please?

**Comment by comonier** [comment]
https://i.imgur.com/Hq0C6Rp.jpg  latest update
Placing default spawner (weither this spawner is invalid or disabled)
