### ISSUE TITLE
Barrels error

### ISSUE THREAD

**Issue by viocu** [TheBusyBiscuit/Slimefun4#467]
## Description
Barrels has a large amount of items placed into a barrel (this case, a gigantic barrel) and all but two stacks disappear before it says 'empty'. Threw an error and I am enclosing the log here: https://pastebin.com/jhfDKt93

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

error thrown in console:

`10/24/2017 04:25:20
04:25:20[Slimefun] Exception caught while ticking a Block:java.lang.NumberFormatException
[Slimefun] X: 3997 Y: 71 Z: 5614
[Slimefun] Saved as: 
[Slimefun] /plugins/Slimefun/error-reports/2017-10-24-04-25.err
[Slimefun] Please consider sending this File to the developer(s) of Slimefun, sending this Error won't get you any help though.
[Slimefun]`

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

https://puu.sh/y5PQ8.jpg This is my player's setup. He has a chest that feeds into the barrel. I placed more stone into the barrel manually instead of through his hopper setup.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

Slimefun version 4.1.11
ExoticGarden 1.6.3
Barrels 1.11
HotbarPets 1.1
SlimefunLuckyBlocks 1.1
SensibleToolbox 1.1

**Comment by TheBusyBiscuit** [comment]
This is the Issue Tracker for Slimefun, not for Barrels.
