### ISSUE TITLE
Problems with SF that we have found so far!

### ISSUE THREAD

**Issue by UR3EKA** [TheBusyBiscuit/Slimefun4#475]
## Description
1) Reinforced spawners turning to pig spawners when placed.
2) Lucky Pickaxe fortune 10 enchantment does not work on it. (doesnt get any of the item when you mine it)
3) Hercules Pickaxe does not smash ores into dust.
4)  Smelting Pickaxe does not smelt ores when mined.
5) enhanced furnace spitting out fuel, ores and duping them. 

## Server Log
https://hastebin.com/asemoviciy.erl

## Evidence / Proof
(will put once I get them sent to me)

## Environment
03:19:35 [INFO] This server is running CraftBukkit version git-Spigot-93e20b3-31d3159 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
03:19:35 [INFO] Checking version, please wait...
03:19:35 [INFO] You are running the latest version

03:19:55 [INFO] CraftBukkit v1_12_R1
03:19:55 [INFO]
03:19:55 [INFO] CS-CoreLib v1.5.16
03:19:55 [INFO] Slimefun v4.1.10
03:19:55 [INFO]
03:19:55 [INFO] Installed Addons (8)
03:19:55 [INFO]  SlimeXpansion v1.1.9
03:19:55 [INFO]  ExtraGear v1.1.1
03:19:55 [INFO]  SlimefunLuckyBlocks v1.1
03:19:55 [INFO]  ExoticGarden v1.6.3
03:19:55 [INFO]  SoulJars v1.0
03:19:55 [INFO]  SlimefunOres v1.4.6
03:19:55 [INFO]  SlimeCalculator v1.0.0
03:19:55 [INFO]  SlimeScrap v1.2.2

**Comment by TheBusyBiscuit** [comment]
No evidence.
