### ISSUE TITLE
enhanced furnace dupe

### ISSUE THREAD

**Issue by UR3EKA** [TheBusyBiscuit/Slimefun4#476]
## Description
enhanced furnace barfing out ores and fuel. when it does this it dupes the items. 

## Server Log
https://hastebin.com/asemoviciy.erl

## Evidence / Proof
![proof](https://user-images.githubusercontent.com/33165241/32141795-894d5e34-bc46-11e7-8e57-a0d469c7e9b8.PNG)

## Environment
03:19:35 [INFO] This server is running CraftBukkit version git-Spigot-93e20b3-31d3159 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
03:19:35 [INFO] Checking version, please wait...
03:19:35 [INFO] You are running the latest version

03:19:55 [INFO] CraftBukkit v1_12_R1
03:19:55 [INFO]
03:19:55 [INFO] CS-CoreLib v1.5.16
03:19:55 [INFO] Slimefun v4.1.10
03:19:55 [INFO]
03:19:55 [INFO] Installed Addons (8)
03:19:55 [INFO]  SlimeXpansion v1.1.9
03:19:55 [INFO]  ExtraGear v1.1.1
03:19:55 [INFO]  SlimefunLuckyBlocks v1.1
03:19:55 [INFO]  ExoticGarden v1.6.3
03:19:55 [INFO]  SoulJars v1.0
03:19:55 [INFO]  SlimefunOres v1.4.6
03:19:55 [INFO]  SlimeCalculator v1.0.0
03:19:55 [INFO]  SlimeScrap v1.2.2

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/411

**Comment by shaady91** [comment]
Quick question. How did you get this version of CoreLib ? CS-CoreLib v1.5.16

**Comment by SoSeDiK** [comment]
@shaady91 It's the lastest version of CS-CoreLib. Yeah, on Bukkit last release was v1.5.15, but you can get v1.5.16 by compiling CS-CoreLib ([here](https://github.com/TheBusyBiscuit/CS-CoreLib)) by yourself.

**Comment by VoidAngel** [comment]
I was told that this happens when you unload the chunk of the enhanced furnace while it is cooking. I don't know if this is true. Ive never been able to replicate it but it seems to happen randomly

**Comment by arizrain1** [comment]
Will this be fixed?!

**Comment by Poslovitch** [comment]
This is not as easy as you think it is, otherwise it would have been fixed 2 months ago. I've already spend ten hours to try to find what causes this bug. Without success.

And devs are not machines, robots or whatever.
You are lucky Slimefun is open source, and free. This helps a lot to keep the project alive.

**Comment by John000708** [comment]
@UR3EKA Can you give me a list with ALL your installed plugins?

**Comment by Sheepotastic** [comment]
I've had this happen as well. Duping glitches are very server breaking, so I hope this is a high priority for the devs.
This said, I hope the devs don't stress over it, just means us owners have to keep an eye on people with these furnaces.

**Comment by madolebr** [comment]
actually its a better idea just to disable the furnaces for now. before you know it it will ruin your economy. there are other plugins you can use to upgrade furnace speed for the meantime, but personally i dont trust them to report when it happens

**Comment by UR3EKA** [comment]
This server doesn't exist anymore. Owner shut it down because he couldn't keep up with all the bugs in slimefun and not having the time to try and solve them.
