### ISSUE TITLE
Bio Reactor inventory guide bug

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#479]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Bio Reactor inventory guide bug

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
![kepkivagas](https://user-images.githubusercontent.com/8324198/32146440-c733a6ae-bcd7-11e7-847f-83ea7ec11941.PNG)

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
29.10 18:34:40 [Server] INFO Paper v1_12_R1
29.10 18:34:40 [Server] INFO CS-CoreLib v1.5.16
29.10 18:34:40 [Server] INFO Slimefun v4.1.11
29.10 18:34:40 [Server] INFO Installed Addons (4)
29.10 18:34:40 [Server] INFO ExtraGear v1.1.1
29.10 18:34:40 [Server] INFO SlimefunLuckyBlocks v1.1
29.10 18:34:40 [Server] INFO ExoticGarden v1.6.3
29.10 18:34:40 [Server] INFO ElectricSpawners v1.0
```

**Comment by TheBusyBiscuit** [comment]
This is not a bug, this is what Minecraft does...
