### ISSUE TITLE
auto enchanter, auto dischanter glitch 

### ISSUE THREAD

**Issue by Volendam** [TheBusyBiscuit/Slimefun4#48]
![2016-12-15_22 22 49](https://cloud.githubusercontent.com/assets/24565612/21225611/11381a22-c315-11e6-999f-e7f322020cdc.png)
![2016-12-15_22 30 57](https://cloud.githubusercontent.com/assets/24565612/21225875/4f3f925e-c316-11e6-9a32-ee72bb43a926.png)
![2016-12-15_22 31 11](https://cloud.githubusercontent.com/assets/24565612/21225879/547554b6-c316-11e6-86b6-08e0815abfed.png)
![2016-12-15_22 35 50](https://cloud.githubusercontent.com/assets/24565612/21225986/dafc431e-c316-11e6-92ad-f2877c3c6eda.png)

Sorry Developer I don't know how to explain

**Comment by Volendam** [comment]
+ When i using explosive pickaxe, i can break commandblock survivalmod

**Comment by xH3LLRAIZ3Rx** [comment]
I honestly don't see the issue

**Comment by NathanAdhitya** [comment]
It's not an issue. Isn't that what the Auto Enchanter and Auto Disenchanter is meant to do?

**Comment by John000708** [comment]
Definitely not an issue. Tell your server owner not to allow that high level enchantments to be available.
