### ISSUE TITLE
Task #1786 for Slimefun v4.1.10 generated an exception

### ISSUE THREAD

**Issue by kawohi** [TheBusyBiscuit/Slimefun4#489]
## Description
While starting up the server I get the error. Task #1786 for Slimefun v4.1.10 generated an exception

## Server Log
https://gist.github.com/kawohi/5a958dfa5f1dff11499cd6f22afccf74

## Evidence / Proof
It happens when the server startsup, not much else to say.

## Environment
CS-CoreLib: 1.5.16,, MC/Spigot: 1.12.2 (https://i.imgur.com/jdB0xf6.png), Slimefun: 4.1.10

**Comment by TheBusyBiscuit** [comment]
This has nothing to do with Slimefun.
The Log says it is caused by one of @John000708 's addons, post it on the addon page instead.
