### ISSUE TITLE
Opening the SF guide with commands

### ISSUE THREAD

**Issue by oddare** [TheBusyBiscuit/Slimefun4#491]
## Description
Running a Skyblock I am attempting to let my players merely use a GUI for all their commands as this is faster and easier for the majority.

The SF guide, however, is currently excluded from this as it so far requires the book to get into. Is there a way I can get into this using commands, instead of routing through to the book?

**Comment by TheBusyBiscuit** [comment]
Someone should just make an Addon for this, it is a very small request.

**Comment by ScuroK** [comment]
i dont agree. i think things like this are quite basic and should be included in a plugin like slimefun.

**Comment by Poslovitch** [comment]
Gonna do it. This will be quite easy.
I will take this opportunity to add some features into the guide. :)

**Comment by Grinthy** [comment]
On a server I play on, there's a command called **/sf guide** that lets you get a book with the default chest GUI.  Is that an add on @TheBusyBiscuit ?

**Comment by Poslovitch** [comment]
Nope, it isn't. It gives you the book

**Comment by Poslovitch** [comment]
Should be closed now ^^
