### ISSUE TITLE
Problem with 1.8

### ISSUE THREAD

**Issue by samcefalo** [TheBusyBiscuit/Slimefun4#495]
## Description
I'm try to use the SlimeFun v4.1 with my 1.8.8 server ,but SlimeFun don't start

## Server Log
https://pastebin.com/SHmJ1WkH

## Evidence / Proof
The Slimefun version in bukkit and the /plugin command color(red) : https://imgur.com/a/RtBnz

## Environment
spigot 1.8_R3

**Comment by Poslovitch** [comment]
```[00:32:19] [Server thread/WARN]: ###
[00:32:19] [Server thread/WARN]: ### You are using Minecraft v1_8_R3
[00:32:19] [Server thread/WARN]: ### but Slimefun v4.1 requires you to be using
[00:32:19] [Server thread/WARN]: ### Minecraft 1.9.X or 1.10.X
[00:32:19] [Server thread/WARN]: ###
[00:32:19] [Server thread/WARN]: ### Please use an older Version of Slimefun and disable auto-updating
[00:32:19] [Server thread/WARN]: ### or consider updating your Server Software.
[00:32:19] [Server thread/INFO]: [Slimefun] Disabling Slimefun v4.1
```

**Comment by samcefalo** [comment]
But look the image, SlimeFun v4.1 os to 1.8.1 too

**Comment by samcefalo** [comment]
https://imgur.com/a/RtBnz

**Comment by Poslovitch** [comment]
Afaik, as of 4.1, there is no 1.8 support

**Comment by samcefalo** [comment]
What version of SlimeFun is to 1.8??

**Comment by Poslovitch** [comment]
I'd heavily recommend you to update to 1.12, as 1.8 has fewer and fewer plugins compatible with. However, try all the Slimefun versions prior to 4.1 and see which one works.

**Comment by samcefalo** [comment]
If i update to 1.12 i'll lise too many players

**Comment by samcefalo** [comment]
Lose*

**Comment by AtomicScience** [comment]
Well, in that case, you can download Slimefun v. 3.6.6 or older, which officialy supports 1.8 [(Link)](https://dev.bukkit.org/projects/slimefun/files/898858), but concider, what this version contains less features and more bugs.
By the way, I would recomend you to make your server multiversional - just install ViaVersion or simular plugin, update your server to 1.12.2, and players with 1.8.x and newer will be able to play at your server
