### ISSUE TITLE
Request for Help - How to translate Ancient Pedestal?

### ISSUE THREAD

**Issue by Meta-Win** [TheBusyBiscuit/Slimefun4#505]
Ok, I am working to create a new minecraft server, with Slimefun, and I want to translate Slimefun to Brazilian Portuguese, but i'm new at programming.
I already translate all items, but when i place a item on Ancient Pedestal, the item name shows in english, even with my Minecraft in portuguese. How i can translate it to portuguese?

The name of Item in Portuguese - https://prnt.sc/hexm8g
The name of Item on the Ancient Pedestal - https://prnt.sc/hexm6p

**Comment by TheBusyBiscuit** [comment]
Hmmm, I will close this for now, either Spigot has a way to get the item names with a language parameter, or CS-CoreLib needs to implement something for that.
