### ISSUE TITLE
How i can add more items on slimefun guide?

### ISSUE THREAD

**Issue by Meta-Win** [TheBusyBiscuit/Slimefun4#508]
I want to add the pipes from Transport-Pipes plugin in the slimefun guide.
But i don't know how to do it
Anyone have any tutorial? Or then other plugin open-source to do it?
I find a plugin to add itens on slimefun guide, but in english. I need anything in portuguese.

**Comment by Redemption198** [comment]
@Meta-Win If you want to add items in the Slimefun guide you can check the Slimefun's API (https://github.com/TheBusyBiscuit/Slimefun4/wiki/API)

**Comment by Meta-Win** [comment]
Thanks!

**Comment by Meta-Win** [comment]
But... Have a method to add only a recipe? I don't want to add more itens.

**Comment by Poslovitch** [comment]
You can't add a recipe, you can just edit the existing one for an item.

**Comment by Meta-Win** [comment]
I found this plugin for this, but it is in English, I would like something that could be translated.
So I figured I could create the recipes myself in slimefun

**Comment by Meta-Win** [comment]
https://www.spigotmc.org/resources/slimefun-customizer.49012/

**Comment by Meta-Win** [comment]
Ok , i found a method to do this. 
I create a new item on slimefun, but i don't place a product to the recipe.
With this the recipe of other plugin still working without conflict, and the item as been added to the guide.

**Comment by Meta-Win** [comment]
I found a method to do this.
I create a new item on slimefun, but in your recipe, i don't put a product.
And in the Items.yml, i place : "can-be-used-in-workbenches: true"
With this, the recipe of slimefun don't conflict with the other plugin.
