### ISSUE TITLE
Upon new installation (Spigot 1.11) OP sees repeating ingame message

### ISSUE THREAD

**Issue by Jawakotb** [TheBusyBiscuit/Slimefun4#51]
## Description
I just recently installed Slimefun on my Spigot 1.11 server (originally with two addons, but I have since removed their jar files, thus it is only Slimefun running) and upon loggin onto the server as an OP, which I have not tried this as a 'non-op' player, there are four messages stating :"Slimefun > You do not have enough Knowledge to understand this". These four in-game messages appear approx every 10 seconds.  I have deleted the plugin folder and let it set itself back up, but the messages still appear.  I would really like to know if this was a self-inflicted issue, a 'owner has no idea how to configure plugin' issue or a spigot/mc1.11/conflicting plugin issue.

Thanks for all your help, I do appreciate it.

## Server Log
Please upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

There are no errors/messages appearing in console

--->  http://pastebin.com/Yk89wnur

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

In-game messages: (I did update the messages.yml file to ensure it was the core SlimeFun plugin)

--->  i.imgur.com/Mb5SDJr.png

## Environment
Please state what Version of Minecraft, CS-CoreLib and Slimefun you're using.

Spigot 1.11 (latest as of posting this issue)  CS-CoreLib v1.5.12,  SlimeFun v4.1.1, Oracle Java 1.8.0_111, Ubunut 16.04 LTS

**Comment by xH3LLRAIZ3Rx** [comment]
Does that person have Chain Armor on? if so that is the reason since chain armor is a research in the Slimefun Guide

**Comment by John000708** [comment]
Something is definitely wrong with your Slimefun installation.
1. "The Titans have not granted you enough Knowledge to understand this" This is not a message that exists in default Slimefun. Have you edited the messages.yml? Is the Slimefun jar downloaded from the Bukkit site?

2. It also seems like Slimefun cannot save the chunks. Could you maybe make the following folder in the server's root directory? (Where the spigot jar is located at) "data-storage/Slimefun/stored-chunks/chunks.sfc"

3. Since you are running Ubuntu, can you chmod 777 the whole server directory?

**Comment by Jawakotb** [comment]
Thanks HellRaizer!  Upon removing the chainmail armor my alt had while I was making armorstand NPCs....long story... the prompts all stopped.  To validate this, I first put on one piece of chainmail and only saw one prompt appear.  Placing two pieces gave me two prompts.  Removing it all eliminated the prompts. ;)   I validated this behavior with another toon and found the same.  THAT WAS AN EASY FIX!   Thanks again!  

John,
  On your #1) I have tailored the prompt via the messages.yml file to fit the lore of the server more.  (I would NEVER DL a jar from an untrustworthy site.......not on purpose anyway.)

Thanks for the fast responses and quick resolution!


PLEASE CLOSE THIS ISSUE!
