### ISSUE TITLE
Slimefun Spitting Errors

### ISSUE THREAD

**Issue by itslukemango** [TheBusyBiscuit/Slimefun4#510]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Spitting console errors
## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/kGCXnJya
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
-
## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
PaperSpigot 1.12.2 v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.10
Barrels v1.11
SlimeXpansion v1.1.9

**Comment by Poslovitch** [comment]
This pastebin doesn't give us any information.

Please paste the part below the "Caused by : ..."

**Comment by itslukemango** [comment]
https://pastebin.com/ecEYuDZ3

**Comment by itslukemango** [comment]
https://pastebin.com/pgLCAHL3

**Comment by WindUnwaken** [comment]
I have this issue when startup  with latest spigot build

**Comment by Poslovitch** [comment]
In these three pastebin, the error is
`Could not pass event InventoryMoveItemEvent to Slimefun v4.1.11`

and caused by `java.lang.ClassCastException`

**Comment by Poslovitch** [comment]
Okay, I know where it comes from : https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java#L66

```java
	@EventHandler
	public void onIgnitionChamberItemMove(InventoryMoveItemEvent e) {
		if(BlockStorage.check(((Hopper) e.getInitiator().getHolder()).getBlock(), "IGNITION_CHAMBER")) {
			e.setCancelled(true);
		}
	}
```

@AtomicScience 

There are not enough checks there. I'll push a fix.
