### ISSUE TITLE
Grappling hook bug!

### ISSUE THREAD

**Issue by HunGamerFake** [TheBusyBiscuit/Slimefun4#511]
Szia! Ez a bug ez az, hogy eldobom nagyon messzire a grappling hook-ot és valahova mellém egy-két blokknyira kidob egy lasszót. Hogyha ezután lövök egyet íjjal, akkor oda elrepít ahova lőttem és ahova repít, oda kidob egy grappling hook-ot.Ezáltal azt értem el hogy tudom farmolni a lasszókat.

by: HunGamerFake

**Comment by Poslovitch** [comment]
We don't understand hungarian, sorry.
Please repost your issue by following the template and in english.

**Comment by andris155** [comment]
I understand this. Smilar: https://github.com/TheBusyBiscuit/Slimefun4/issues/253

**Comment by andris155** [comment]
@HunGamerFake please make a video.

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=C2xhvmCKar8

**Comment by Poslovitch** [comment]
Thanks for your video. Gonna fix it asap.
