### ISSUE TITLE
4.1.11 floods console with errors nonstop from startup:  [20:53:56] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to Slimefun v4.1.11

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#518]
## Description
Errors are incessant and nonstop, creating MBs worth of logs in minutes.

## Server Log
https://pastebin.com/5cqhz1Dy

## Evidence / Proof
This didn't happen from the start that I know of?  Just started happening more recently... nothing else changed version so for now I'm blaming... the appearance of Christmas items??  Chocolate Milk - among others on this list - would not craft... no idea if this is a related issue or not.

## Environment
We need the EXACT VERSIONS of the Software you are using.
CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.11
ExoticGarden v1.6.3

**Comment by mrcoffee1026** [comment]
Checked, christmas recipes also broken in last viable release (4.1.9), but no errors appear in console when attempting interaction with them so the christmas item appearance is coincidental.

**Comment by TheBusyBiscuit** [comment]
Will be fixed in 4.1.12
