### ISSUE TITLE
Christmas Items That Can't Be Crafted

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#519]
## Description
The Following Items In the "Christmas" Topic in the guide do not craft:
Chocolate Milk
Christmas Cookie
Hot Chocolate (Since Chocolate Milk doesn't craft)
Christmas Cake (produces Fruit Cake instead -- also shows this pictured in the guide)
Rainbow Wool (Christmas) -- Because Christmas Cookies cannot be crafted.
Rainbow Glass (Christmas) -- Because Christmas Cookies cannot be crafted.
Rainbow Glass Pane (Christmas) -- Because Christmas Cookies cannot be crafted.
Rainbow Clay (Christmas) -- Because Christmas Cookies cannot be crafted.

## Server Log
Nothing Relevant (no errors).

## Evidence / Proof
"Slimefun > Sorry, I could not recognize this Pattern. Please place the Items in the correct Pattern into the Dispenser." - when putting the recipes as given for the ones I listed.

## Environment
CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9-v4.1.11
ExoticGarden v1.6.3

**Comment by mrcoffee1026** [comment]
also christmas hot chocolate has the same name as the Exotic Gardens - Drinks Hot Chocolate... so if I disable one, they both vanish... could we possibly get a christmas-specific title for the Christmas Hot Chocolate?

**Comment by xH3LLRAIZ3Rx** [comment]
The christmas cookie is not craftable because in the code for the recipe this is used:
`new CustomItem(Material.INK_SACK, 10)`
when it should be:
`new MaterialData(Material.INK_SACK, (byte) 10).toItemStack(1)`

**Comment by Meta-Win** [comment]
#522

**Comment by xH3LLRAIZ3Rx** [comment]
@Meta-Win to fix the christmas cake you simply go to the recipe of it and at the end of the recipe string change FRUIT_CAKE to CHRISTMAS_CAKE
