### ISSUE TITLE
Juice drank in OffHand give the bottle

### ISSUE THREAD

**Issue by Poslovitch** [TheBusyBiscuit/Slimefun4#52]
## Description
When you drink a juice in offhand, the glass bottle doesnt disappear

## Server Log
There is no error.

## Evidence / Proof
Pretty easy to check out.

## Environment
PaperSpigot 1.11 (built 10 december 2016)
CS-CoreLib_v1.5.12
Slimefun 4.1.1

**Comment by NathanAdhitya** [comment]
Tested out a temporary fix. Maybe that'll solve the problem. XD
