### ISSUE TITLE
InventoryMoveEvent error

### ISSUE THREAD

**Issue by DrOreo002** [TheBusyBiscuit/Slimefun4#521]
## Description
My console is flooded with this error. Please fix it, It should not take really long just to fix NullPointerException. Ty
## Server Log
https://pastebin.com/D930UJMs

## Evidence / Proof
I don't think that I need to put ss here.

## Environment
Minecraft : 1.12.2
CS-CoreLib : 1.5.15
Slimefun : 4.1.11

**Comment by TheBusyBiscuit** [comment]
Will be fixed in 4.1.12
