### ISSUE TITLE
Christmas Cookies not working?

### ISSUE THREAD

**Issue by ChitterChatter** [TheBusyBiscuit/Slimefun4#523]
## Description
Hi there, not sure if this is the right place or not. I see the Christmas Cake is fixed, however the cookies are not working?

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
I am going by the guide...
![image](https://user-images.githubusercontent.com/28234726/33520804-ecc06ff6-d776-11e7-93c0-2e5708b69098.png)

and adding the ingrediants as required to my enhanced crafting table

![image](https://user-images.githubusercontent.com/28234726/33520816-0e5d66e6-d777-11e7-8715-8f6600e2133c.png)

I still get this....
![image](https://user-images.githubusercontent.com/28234726/33520797-cd8e38ac-d776-11e7-9f85-673d1ba31250.png)

I can do the fruit cake and the christmas cake without issues.

## Environment
I am running the following:
![image](https://user-images.githubusercontent.com/28234726/33520850-85fc0cfc-d777-11e7-893e-6313a8d71d31.png)

**Comment by Meta-Win** [comment]
Hey, you can say for me if the Christmas Cookies have appeared in the dispenser?

Sorry, bad english
