### ISSUE TITLE
Christmas Items That Can't Be Crafted

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#526]
## Description
NOTE:  Since these items were "fixed" in 4.1.12, this problem must be BRAND NEW, do not handle this ticket as a duplicate please, this Issue exists in Slimefun 4.1.12:
The Following Items In the "Christmas" Topic in the guide do not craft:
Chocolate Milk
Christmas Cookie
Hot Chocolate (Since Chocolate Milk doesn't craft)
Christmas Cake (produces Fruit Cake instead -- also shows this pictured in the guide)
Rainbow Wool (Christmas) -- Because Christmas Cookies cannot be crafted.
Rainbow Glass (Christmas) -- Because Christmas Cookies cannot be crafted.
Rainbow Glass Pane (Christmas) -- Because Christmas Cookies cannot be crafted.
Rainbow Clay (Christmas) -- Because Christmas Cookies cannot be crafted.

## Server Log
Nothing Relevant (no errors).

## Evidence / Proof
"Slimefun > Sorry, I could not recognize this Pattern. Please place the Items in the correct Pattern into the Dispenser." - when putting the recipes as given for the ones I listed.

## Environment
CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.12
ExoticGarden v1.6.3

**Comment by Poslovitch** [comment]
They are not fixed in 4.1.12. The fix was commited after the release of this version.
