### ISSUE TITLE
Plugin Slimefun v4.1.12 generated an exception while executing task 58 java.lang.IllegalStateException: Asynchronous entity track!

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#528]
## Description
Error in log, not sure what's causing it?  Moving woodcutter android block?  I'm not sure.

## Server Log
https://pastebin.com/Xp0a9gVs

## Environment
CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.12
ExoticGarden v1.6.3

**Comment by WindUnwaken** [comment]
https://pastebin.com/KRkzxGqy

When I update the spigot to latest version, it shows up, maybe spigot have wrong logic, wait for others confirm
