### ISSUE TITLE
Unable to open backpacks crafted

### ISSUE THREAD

**Issue by SpiritAmet** [TheBusyBiscuit/Slimefun4#536]
## Description
As the title says, I have crafted a backpack, then upgraded it and still when right clicking it I am unable to open it.  I did indeed use the /sf research (playername) all command.  I really dont know how to explain it more than that (and yes it shows a UUID tied to it.

## Server Log
I apologize but the file was too large elsewhere.
[latest logs for toc.txt](https://github.com/TheBusyBiscuit/Slimefun4/files/1564560/latest.logs.for.toc.txt)

## Evidence / Proof
Sadly gyazo gif does not want to co-operate to show you a gif

## Environment
https://gyazo.com/bca16dad6c91cc042f89f941bbc3c7f6

Currently using Spigot 1.12.2

**Comment by Meta-Win** [comment]
Make a backup of the server first if desired.

Try download again the [Slimefun v4.1.12](https://dev.bukkit.org/projects/slimefun/files/2505640/download)

In the log have errors from MagicLoot v2.1.0, SlimeMobs v1.4 and SimplePets v3.8
Caused by incompability with 1.12

And a load error on file : data-storage/Slimefun/stored-blocks/world/PEAR_SAPLING.sfb
Try delet this file.

**Comment by SpiritAmet** [comment]
I will work on that over the next day or two, and will reply as soon as I have tested that, Thank you for the advice.

**Comment by SpiritAmet** [comment]
Tested it out, and still nothing, no error messages.  And I have confirmed with another player that it shows the UUID but does not respond.  Attaching a link to an image showing the backpack.  When we left click on it nothing happens, no error message on console at all either.  https://cdn.discordapp.com/attachments/315398628627972097/393490068129447936/2017-12-21_19.49.01.png

**Comment by Meta-Win** [comment]
Then try download again Slimefun, bot now from [HERE](https://www.dropbox.com/s/bzlyqfl2yndy9pk/Slimefun%20v4.1.12.jar?dl=1).
After that, use the command /sf research YOURNICK all

Try open the backpack.

**Comment by SpiritAmet** [comment]
I had everything unlocked before, now we seem to have no diamond_safe usage it changed to a CSCoreLib's Head.  We will investigate this further and let you know.

**Comment by Poslovitch** [comment]
The backpack previously shown in the screen should open.

What is the "diamond_safe usage" you're talking about @SpiritAmet ?
@Meta-Win What did you change exactly in your version? The best would have been to provide a link to your GitHub fork repository and file a release from it.

**Comment by Poslovitch** [comment]
Did some testing : Backpacks correctly recognized in the listener, But nothing happens : any update of the ID, and no inventory is popping. Backpack still can't be placed on ground (which is, at least, good news)
SF Guide working fine.
![/sf versions](http://prntscr.com/hr0iru)
![/version](http://prntscr.com/hr0j23)

**Comment by SpiritAmet** [comment]
@Poslovitch The backpacks do work correctly as stated before.  the DIAMOND SAFE is in the personal storage part (same as a diamond chest, but it locks itself automatically so others cannot open it.)

**Comment by Poslovitch** [comment]
What have fixed your issue? Is the version provided by Meta-Win?

I did the tests on the official 4.1.12 version.

**Comment by Meta-Win** [comment]
(Bad English)
 I downloaded version 4.1.12 for testing. And I realized that actually the backpacks were not working, and also not some slimefun commands.
 Then I just compiled myself the slimefun.

 It seems to me that the version on the bukkit site is not working properly.

**Comment by Redemption198** [comment]
@Meta-Win That's strange, maybe @TheBusyBiscuit should leave the repo server link on the bukkit page, just in case.

**Comment by SpiritAmet** [comment]
@Poslovitch yes the link @Meta-Win provided last caused backpacks to work, but some items broken in the process, replacing them with new items allowed them to work again.

**Comment by SpiritAmet** [comment]
Though it seems we have a mass dupe glitch with furnaces now..

**Comment by Poslovitch** [comment]
@SpiritAmet the dupe glitch with furnaces is #512

**Comment by Redemption198** [comment]
@SpiritAmet Download the latest build from here:(https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/). The bug should have been fixed.
