### ISSUE TITLE
Items not loading in guide

### ISSUE THREAD

**Issue by IvanBloodstone** [TheBusyBiscuit/Slimefun4#538]
## Description
I can seem to get certain items to load in the book, I've deleted and installed 1.12 several times, i even tried 1.11 and 1.10 they all seem to have the same issue, Everything is enabled, nothing has been disabled in the .yml files. This is all fresh unedited instals. 

## Server Log
[latest.log](https://github.com/TheBusyBiscuit/Slimefun4/files/1568936/latest.log)

## Evidence / Proof
Basic Machines section of book
![bwcidf3stpaeesj5ksqfxg](https://user-images.githubusercontent.com/34657934/34118819-f9149916-e3ed-11e7-9f47-5b32efd5045a.png)
Reserches.yml
![av4davq5toik6pjtggjljg](https://user-images.githubusercontent.com/34657934/34118869-2613d242-e3ee-11e7-880f-ecc47b08b003.png)
Items.yml
![qe94krrdqfqzkohrcsrexa](https://user-images.githubusercontent.com/34657934/34119700-26d9b7ca-e3f1-11e7-8ca3-ee05e0328131.png)

Energy and Electricity section of book
![9uhsazcbqi2bf5d4bjoi0g](https://user-images.githubusercontent.com/34657934/34118828-03d88592-e3ee-11e7-9477-e4f56bba39b4.png)
Researches.yml
![byb78mvmrikfep73l_ii5a](https://user-images.githubusercontent.com/34657934/34118839-0d322602-e3ee-11e7-9456-d019095b510c.png)
Items.yml
![fp6m69j8qq6-yyyhf1bczq](https://user-images.githubusercontent.com/34657934/34119756-52fbe30a-e3f1-11e7-9efc-f272201ffda8.png)

## Environment
Minecraft 1.12
Bukkit 1.12
Slimefun 1.12
CS-CoreLib 1.5.16

**Comment by Meta-Win** [comment]
In config.yml set "enable-tickers:" to true

**Comment by IvanBloodstone** [comment]
![5o8l0f0qto_cdeg2qkj9sq](https://user-images.githubusercontent.com/34657934/34142647-5b244ea4-e456-11e7-8ffe-3af078fac81b.png)
This is all there is in config.yml

**Comment by Meta-Win** [comment]
Try add it on config.yml

`options:
  auto-update: true
  armor-update-interval: 10
  give-guide-on-first-join: true
  print-out-loading: false
  print-out-github-data-retrieving: false
  enable-armor-effects: true
  prefix: '&a&lSlimefun &7>'
  auto-save-delay-in-minutes: 10
  show-vanilla-recipes-in-guide: true
  allow-free-creative-research: true
  emerald-enchantment-limit: 2
  research-unlock-fireworks: true
  research-give-fireworks: true
guide:
  default-view-book: false
URID:
  info-delay: 3000
  custom-ticker-delay: 12
  enable-tickers: true
items:
  talismans: true
  coolers: true
  backpacks: true
research-ranks:
- Chicken
- Cow
- Spider
- Villager
- Beginner
- Clumsy Student
- Unskilled Student
- Incompetent Student
- Student
- Clumsy Apprentice
- Apprentice
- Skilled Apprentice
- Upcoming Mage
- Excellent Mage
- Young Magician
- Incompetent Magician
- Common Magician
- Magician
- Proficient Magician
- Skilled Magician
- Accustomed Magician
- Great Magician
- Clumsy Wizard
- Wizard
- Common Wizard
- Skilled Wizard
- Great Wizard
- Impressive Wizard
- Young Master
- Clumsy Master
- Upcoming Master
- Competent Master
- Master
- Skilled Master
- Excellent Master
- Great Master
- Proficient Master
- The chosen One`

**Comment by Meta-Win** [comment]
Try add it on config.yml : 

options:
  auto-update: true
  armor-update-interval: 10
  give-guide-on-first-join: true
  print-out-loading: false
  print-out-github-data-retrieving: false
  enable-armor-effects: true
  prefix: '&a&lSlimefun &7>'
  auto-save-delay-in-minutes: 10
  show-vanilla-recipes-in-guide: true
  allow-free-creative-research: true
  emerald-enchantment-limit: 2
  research-unlock-fireworks: true
  research-give-fireworks: true
guide:
  default-view-book: false
URID:
  info-delay: 3000
  custom-ticker-delay: 12
  enable-tickers: true
items:
  talismans: true
  coolers: true
  backpacks: true
research-ranks:
- Chicken
- Cow
- Spider
- Villager
- Beginner
- Clumsy Student
- Unskilled Student
- Incompetent Student
- Student
- Clumsy Apprentice
- Apprentice
- Skilled Apprentice
- Upcoming Mage
- Excellent Mage
- Young Magician
- Incompetent Magician
- Common Magician
- Magician
- Proficient Magician
- Skilled Magician
- Accustomed Magician
- Great Magician
- Clumsy Wizard
- Wizard
- Common Wizard
- Skilled Wizard
- Great Wizard
- Impressive Wizard
- Young Master
- Clumsy Master
- Upcoming Master
- Competent Master
- Master
- Skilled Master
- Excellent Master
- Great Master
- Proficient Master
- The chosen One

**Comment by IvanBloodstone** [comment]
Update, Used a Config.yml from old copy of slimefun to add just that to it and it all works now, thank you very much

**Comment by Redemption198** [comment]
If you fixed your problem and everything works fine, please close this issue.
