### ISSUE TITLE
Slimefun Block Fading When It's Broken

### ISSUE THREAD

**Issue by ThalesGames037** [TheBusyBiscuit/Slimefun4#540]
When I Break A Block Of Slimefun It Is Disappearing Personal That Correct That Is Very Boring Having To Create The Block Every Time
That disappears

**Comment by Redemption198** [comment]
Can you explain your problem in a better way?
Use this template (https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/ISSUE_TEMPLATE.md)
