### ISSUE TITLE
Unable to create Worlds with Multiverse

### ISSUE THREAD

**Issue by KlenerTeufel96** [TheBusyBiscuit/Slimefun4#542]
I have a Paper Spigot 1.8.8 Server and Slimefun v.3.6.6 + CS-Corelib 1.5.16. I cant update SlimeFun because the console said to me, that the higher versions needs Minecraft version 1.9 or higher. So, if i would like to create a new World with Multiverse-Core, then the Console said this to my (Its very large): 

https://pastebin.com/As3c3sJ8

It is spamming so long, that my server is crashing when i create a world. 
Is this because of my Server Version or have somebody a fix for it? 

Thank you for your help :)

Best regards
KlenerTeufel96

**Comment by Meta-Win** [comment]
(Bad English)

Try using [CS-CoreLib v1.3.1](https://dev.bukkit.org/projects/cs-corelib/files/911418/download)
But I recommend upgrading your server.

**Comment by TheBusyBiscuit** [comment]
You need 1.9 or higher and are using 1.8...
