### ISSUE TITLE
Slimefun Ancient Altar Dupe glitch

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#546]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Slimefun Ancient Altar Dupe glitch

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://www.youtube.com/watch?v=I0y4w7zAu0I

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
21.12 13:48:00 [Server] INFO Paper v1_12_R1
21.12 13:48:00 [Server] INFO CS-CoreLib v1.5.16
21.12 13:48:00 [Server] INFO Slimefun v4.1.12
21.12 13:48:00 [Server] INFO Installed Addons (4)
21.12 13:48:00 [Server] INFO ExtraGear v1.1.1
21.12 13:48:00 [Server] INFO SlimefunLuckyBlocks v1.1
21.12 13:48:00 [Server] INFO ExoticGarden v1.6.3
21.12 13:48:00 [Server] INFO ElectricSpawners v1.0
```

**Comment by TheBusyBiscuit** [comment]
Adressed in #683 and available in later builds:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master
