### ISSUE TITLE
Hologram Character Bugs

### ISSUE THREAD

**Issue by NathanAdhitya** [TheBusyBiscuit/Slimefun4#55]
## Description
The Hologram Projector, refuses to remove the hologram (Armor Stand) upon breaking if there are special characters ex: ( `"/"` and `"\"` )

## Server Log
There were no errors, No Warnings, Nothing, everything seemed fine

## Evidence / Proof
Easy To Try Out. Just place a Hologram Projector, and then set the text with a text containing `"/"` or `"\"` .

## Scenario
1. Place a Hologram Projector
2. Set the text to a text containing the character `"/"` or `"\"` . Example: \test
3. Break the Hologram Projector
4. Normally, without and of the two characters, the Hologram dissapears, but this time, it does not.
(And will never dissapear until manually broken using commands)

## Environment
PaperSpigot 1.11 (paperclip-965)
CS-CoreLib_v1.5.12
Slimefun 4.1.1

**Comment by NathanAdhitya** [comment]
Define needing more info?
I think it was just enough info to try and test it out...

**Comment by Poslovitch** [comment]
I think it means "investigating".

**Comment by TheBusyBiscuit** [comment]
@NathanAdhitya 
"Need More Info" means that we need more info... -_-
Providing us evidence and a detailed list of scenarios makes our jobs easier.
Devs dont have the most time of the world and not giving us proof just puts extra work onto us...

**Comment by NathanAdhitya** [comment]
Should that scenario be easy to test out? Basically, just place a hologram projector, and try typing anything that has `/` or `\` in the text. Then try breaking the hologram.
Normally the hologram breaks fine. but weirdly the hologram doesn't break. like, the text is still there even without the projector.

**Comment by TheBusyBiscuit** [comment]
Closed since the OP failed to provide us enough Information.
