### ISSUE TITLE
Most Items not even craftable

### ISSUE THREAD

**Issue by advancedMicah** [TheBusyBiscuit/Slimefun4#550]
I am having trouble with crafting items, there is some items that I craft that work just fine but most items I use it never works and I just get spammed saying it doesn't match a pattern 
![image](https://user-images.githubusercontent.com/34846957/34344512-3a8484c6-e99b-11e7-8f0f-8a297b1d7bfe.png)

**Comment by Redemption198** [comment]
Are you using the latest version of Slimefun from bukkit? If yes download the latest version from here (https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/).
It seems that the bukkit version has some problems.

**Comment by Poslovitch** [comment]
@Redemption198 Just downloaded the latest version on builds. Seems to have the same problem.
We should investigate each build till finding when the problem originated
