### ISSUE TITLE
Holograms Staying around

### ISSUE THREAD

**Issue by Cobwebster** [TheBusyBiscuit/Slimefun4#552]
https://gyazo.com/4e7bf75d67438adfc5d04a22c4841e57

Upon breaking some of the machines, the hologram just isn't removed. 

Latest slimefun and spigot.

**Comment by Redemption198** [comment]
If you are the server admin you can try this workaround (https://github.com/TheBusyBiscuit/Slimefun4/issues/537)
We’ll investigate to find a cause and a fix for tho bug.
