### ISSUE TITLE
A Problem about build Slimefun

### ISSUE THREAD

**Issue by StarWishsama** [TheBusyBiscuit/Slimefun4#554]
"http://maven.sk89q.com/repo/org/bukkit/bukkit/1.12-R0.1-SNAPSHOT/maven-metadata.xml"

maven.sk89q.com don't provide Bukkit 1.12-R0.1 SNAPSHOT now. so i can't build it with IDEA.

What should i do?

**Comment by TheBusyBiscuit** [comment]
That is not Bukkit's Repo, it's WorlEdit's.
The Bukkit API is provided by this Repository:
https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/bukkit/

**Comment by StarWishsama** [comment]
Thanks a lot :)

**Comment by StarWishsama** [comment]
Downloading: http://maven.sk89q.com/repo/org/bukkit/bukkit/1.12-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bukkit:bukkit:1.12-R0.1-SNAPSHOT/maven-metadata.xml from/to worldedit-worldguard-repo (http://maven.sk89q.com/repo/): Connect to maven.sk89q.com:80 [maven.sk89q.com/104.28.7.113, maven.sk89q.com/104.28.6.113] failed: Connection timed out: connect
[WARNING] Failure to transfer org.bukkit:bukkit:1.12-R0.1-SNAPSHOT/maven-metadata.xml from http://maven.sk89q.com/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of worldedit-worldguard-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:bukkit:1.12-R0.1-SNAPSHOT/maven-metadata.xml from/to worldedit-worldguard-repo (http://maven.sk89q.com/repo/): Connect to maven.sk89q.com:80 [maven.sk89q.com/104.28.7.113, maven.sk89q.com/104.28.6.113] failed: Connection timed out: connect

**Comment by StarWishsama** [comment]
Downloading: http://maven.sk89q.com/repo/com/sk89q/worldedit/worldedit-bukkit/6.1.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.sk89q.worldedit:worldedit-bukkit:6.1.1-SNAPSHOT/maven-metadata.xml from/to worldedit-worldguard-repo (http://maven.sk89q.com/repo/): Connect to maven.sk89q.com:80 [maven.sk89q.com/104.28.7.113, maven.sk89q.com/104.28.6.113] failed: Connection timed out: connect
[WARNING] Failure to transfer com.sk89q.worldedit:worldedit-bukkit:6.1.1-SNAPSHOT/maven-metadata.xml from http://maven.sk89q.com/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of worldedit-worldguard-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.sk89q.worldedit:worldedit-bukkit:6.1.1-SNAPSHOT/maven-metadata.xml from/to worldedit-worldguard-repo (http://maven.sk89q.com/repo/): Connect to maven.sk89q.com:80 [maven.sk89q.com/104.28.7.113, maven.sk89q.com/104.28.6.113] failed: Connection timed out: connect

**Comment by TheBusyBiscuit** [comment]
You are targeting a Bukkit Version that does not exist...

Just use the existing pom.xml, it works for sure.
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/
