### ISSUE TITLE
Add API Event on Unlock A Research

### ISSUE THREAD

**Issue by coco0325** [TheBusyBiscuit/Slimefun4#555]
## Description
I think if API have a event on player unlock a research, can use that to Bungeecord.

Just a little suggestion.

**Comment by TheBusyBiscuit** [comment]
ResearchUnlockEvent...
It always existed.
https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Events/ResearchUnlockEvent.java
