### ISSUE TITLE
Durability Bug

### ISSUE THREAD

**Issue by Faicu** [TheBusyBiscuit/Slimefun4#556]
## Description
Explosive Pickaxe it's unbreakable

## Server Log
There is no error/log.

## Evidence / Proof
https://youtu.be/0Bh2_SX_d1U

## Environment
git-Spigot-549c1fa-8c37e2e (MC: 1.12.2)
Slimefun v4.1.12
CS-CoreLib v1.5.16

**Comment by Poslovitch** [comment]
Please provide an evidence for this bug. Explosive Pickaxe is not explicitly unbreakable.

**Comment by Faicu** [comment]
https://youtu.be/0Bh2_SX_d1U

**Comment by Chiaro-Amos** [comment]
While I haven't seen this specific bug, I wanted to comment on the Explosive Pickaxe as I have noticed that it does seem to have a rather high durability especially for what it does. From what I am aware many people consider it to be an OP item. 

While this is just an idea, and I have very little knowledge when it comes to coding/writing plugins, but would it be possible to increase the durability damage that the Explosive Pickaxe takes on use? Potentially a custom amount that could be set in the items.yml file?
 
Considering that it usually breaks 18 blocks on an average use while mining in a straight line, it saves a significant amount of time and effort so I think the increased durability damage would be a fair trade for those benefits. Personally, I would like to take at least 10 times more durability damage than a normal pickaxe would take on block break, but I know some server owners/admins might want it to take the normal intended durability damage so a configurable setting for it would be convenient.

**Comment by meiamsome** [comment]
I didn't realize this was a bug, I just thought the pickaxe was OP. Should the behaviour be to remove the durability of every block destroyed? That would make sense to me.

**Comment by mrcoffee1026** [comment]
Yeah I'm not confident that it's not supposed to be OP and virtually unbreakable... but it probably should take SOME damage eventually?  In my experience using one that doesn't even have mending on it will result in virtually no durability loss even when using it for hours at a time.  If it is not supposed to be an indestructible pick, there's something wrong with it.
