### ISSUE TITLE
PlotSquared protection support

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#558]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Please add PlotSquared protection support.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
none

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
01.01 23:36:50 [Server] INFO Paper v1_12_R1
01.01 23:36:50 [Server] INFO CS-CoreLib v1.5.16
01.01 23:36:50 [Server] INFO Slimefun v4.1.12
01.01 23:36:50 [Server] INFO Installed Addons (4)
01.01 23:36:50 [Server] INFO ExtraGear v1.1.1
01.01 23:36:50 [Server] INFO SlimefunLuckyBlocks v1.1
01.01 23:36:50 [Server] INFO ExoticGarden v1.6.3
01.01 23:36:50 [Server] INFO ElectricSpawners v1.0
```

**Comment by TheBusyBiscuit** [comment]
Protection Plugins are handled by CS-CoreLib, requests for that should belong here:
https://github.com/TheBusyBiscuit/CS-CoreLib/issues
