### ISSUE TITLE
Apple Pie exists SF4 Dev #10

### ISSUE THREAD

**Issue by Aberzhulan** [TheBusyBiscuit/Slimefun4#559]
## Description
Error about apple pie already existing. 

## Server Log
https://pastebin.com/93tuf5Ce

## Environment
Server version: Paper version git-Paper-1275 (MC: 1.12.2)
CS-CoreLib: 1.5.16
SF Version:  4.1.12 (Dev build 10)

**Comment by Poslovitch** [comment]
Yup, wanted to fix it, but don't know how.

Should I put a prefix like "CHRISTMAS_..." before each Christmas items, and do the same for each "monthly" category? @TheBusyBiscuit

**Comment by TheBusyBiscuit** [comment]
@Poslovitch 
No. I would just set the category to be
(april) ? easter: christmas

**Comment by Poslovitch** [comment]
Okay, that's a way better idea.

**Comment by MCTyler** [comment]
Can you just suppress those warnings in your Java to cure my OCD? I hate errors in my startup lol.
