### ISSUE TITLE
Transdimensional Cargo Nodes

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#561]
I would love to see a Transdimensional Cargo Nodes where you can transfer things to and from other dimensions. This could be end game type of things too.

**Comment by Poslovitch** [comment]
Should be implemented by an addon I think. Not every server owners would like to see these overpowered nodes pop on their servers.

**Comment by TheBusyBiscuit** [comment]
https://dev.bukkit.org/projects/colored-ender-chests
