### ISSUE TITLE
Extending Cargo Channels

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#562]
I think it would be neat if you can if possible add a feature where if theres more than one Cargo Manager in a cargo net, it would increase the channels, so like if have two Cargo Managers in one cargo net it would have 32 channels and so on.

**Comment by Poslovitch** [comment]
That might be possible, but it would add more load on the server.

**Comment by xH3LLRAIZ3Rx** [comment]
Hmm, then maybe a more difficult to make Cargo Channel Extender block?

**Comment by Poslovitch** [comment]
A more or less difficult block to obtain don't avoid the additional load when parsing the Cargo Network. If we consider 16 channels as a load of 100%, adding 16 more would result in a load of 225%, following the results of a test I've just run.

I'm still thinking this should be done by an addon. However, it would need a little tweak in the CargoNet to allow creation of CargoManagers handling 4, 8 or even 17 channels.

**Comment by TheBusyBiscuit** [comment]
No.
