### ISSUE TITLE
SF Stats

### ISSUE THREAD

**Issue by RyseEmpire** [TheBusyBiscuit/Slimefun4#564]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
I am currently unable to run the command /sf stats on my server.
## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/XYXmf6dF
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
http://prntscr.com/hw1ve5
## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

Minecraft Version: 1.12.2
CS-CoreLib: 1.5.16
SlimeFun: 4.1.12

**Comment by Redemption198** [comment]
There isn't any Slimefun error in the server log, do you have the right permissions to execute the command? Have you tried disabling your chat managers (TownyChat, EssentialsChat... etcetera)?

**Comment by RyseEmpire** [comment]
Ah ok. I will try that when I get home and then update you. 
Thanks

**Comment by Poslovitch** [comment]
@RyseEmpire Basically, when you type /sf stats it tells you that an error has occured?

@Redemption198 I've had an error with /sf stats once, and as far as I remember, this happened when I switched my dev server from online to offline mode, causing a lot of mess with Bukkit trying to get some values. May not be related, but we have to wait @RyseEmpire to send us the files and then we'll know.

**Comment by RyseEmpire** [comment]
@Poslovitch I have tested it without any chat feature plugin and it still kicks out the error. Unfortunately, I do not know of a way to enable Online mode to true without harming my Bungeecord so I am stumped on what to do.

**Comment by Poslovitch** [comment]
@RyseEmpire I've never asked you to change your mode to online or whatever. I said that I encountered a similar problem on my dev server when switching from online mode to offline.

But, by reading into what you said, the bug not only appears on this case.

So please, provide logs that contains the error as soon as possible.

**Comment by RyseEmpire** [comment]
Here is my latest.log
https://pastebin.com/ZfY2Ze6d

and here is the console output
http://prntscr.com/hwfp93

**Comment by Poslovitch** [comment]
@RyseEmpire It appears that you don't have any "research title". Can you please send us your config.yml?

**Comment by RyseEmpire** [comment]
My config.yml is very small and solely consists of commented out info:


# 
# Name: Slimefun
# Author: The Slimefun 4 Community
# 
# Do not modify the Config while the Server is running
# otherwise bad things might happen!
# 
# This Plugin also requires CS-CoreLib to run!
# If you don't have it installed already, its going to be
# automatically installed for you
# 
# This Plugin utilises an Auto-Updater. If you want to turn that off,
# simply set options -> auto-update to false

**Comment by Poslovitch** [comment]
Well, I originally wanted to say that this didn't look like a good config.yml and then to send an example of what it looks like for me...

But then, I opened it, and found the same thing : 
```yaml
# 
# Name: Slimefun
# Author: The Slimefun 4 Community
# 
# Do not modify the Config while the Server is running
# otherwise bad things might happen!
# 
# This Plugin also requires CS-CoreLib to run!
# If you don't have it installed already, its going to be
# automatically installed for you
# 
# This Plugin utilises an Auto-Updater. If you want to turn that off,
# simply set options -> auto-update to false
```

Which is weird.

**Comment by RyseEmpire** [comment]
Ah I see. This is strange though because I can still unlock the majority of items but I am just confused why /sf stats shoots out an error. Can you run /sf stats on your server, @Poslovitch ?

**Comment by Poslovitch** [comment]
@RyseEmpire No, I can't. Because of the same problem than you : the config.yml has not been pasted correctly. I'm currently working on a fix to avoid IndexOutOfBoundException, but I'll have to have a look at why the config.yml wasn't properly pasted.

**Comment by RyseEmpire** [comment]
Ah ok. If you are successful, it'd be great if you notify me. : )

**Comment by Poslovitch** [comment]
Once the fixes will be merged, you will be to download them here : https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by RyseEmpire** [comment]
Ah brilliant. Thank you!

**Comment by TheBusyBiscuit** [comment]
Apparently, noone, not even I noticed this:
But Maven apparently doesnt put the config.yml into the jar :?
All Builds that were compiled with it, on Bukkit and my Build Server show this problem.

**Comment by TheBusyBiscuit** [comment]
Fixed.
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#11
