### ISSUE TITLE
Backpack not opening

### ISSUE THREAD

**Issue by Seyyyer** [TheBusyBiscuit/Slimefun4#565]
## Description
Describe your Issue AS DETAILED AS POSSIBLE: Opening a small, medium, big or woven backpack doesn't work, it just shows a normal right click animation (the backpack isn't placed either)

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all: n/a

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
![2018-01-04_19 23 50] 
![2018-01-04_19 23 50](https://user-images.githubusercontent.com/35112536/34578417-25f30a72-f185-11e7-8c9a-6acbe68775ff.png)

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command. : 
Minecraft 1.12.2 Optifine/1.12.2 vanilla
CS-CoreLib v1.5.16
Slimefun v4.1.12
Edit: I was using some of the "official" addons, so I tried without, still, doesnt work.

**Comment by Bredosen** [comment]
Same her

**Comment by Poslovitch** [comment]
Possibly related to #566

@Bredosen Could you please also provide your logs and your environment, so we can do some comparison?

**Comment by Redemption198** [comment]
@Bredosen Try to download the latest build from here (https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/) the bug should have been fixed.
