### ISSUE TITLE
Items are missing!

### ISSUE THREAD

**Issue by LecraM2003** [TheBusyBiscuit/Slimefun4#566]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
In the cathegory "Energy and Electricity" many Items are missing! (see Screenshot)

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/VggvrbKR
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
![2018-01-04_22 59 19](https://user-images.githubusercontent.com/22198605/34586167-8b9b59a8-f1ab-11e7-8411-b18b6b5d77c8.png)

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
CS-CoreLib: 1.5.16
Slimefun: 4.1.12
Minecraft: Spigot 1.12.2
Java: Java 8

**Comment by Poslovitch** [comment]
Same problem on my dev server

They are loaded, but not displayed.

**Comment by Bredosen** [comment]
Same here

**Comment by Poslovitch** [comment]
@Bredosen Could you please also provide your logs and your environment, so we can do some comparison?

**Comment by RyseEmpire** [comment]
I am also having this issue. If I drop it down a version and turn off auto-update, would it fix it?

**Comment by Poslovitch** [comment]
@RyseEmpire Probably not.
But please, as I asked above, provide logs and your environment, so we can compare different setups.

**Comment by RyseEmpire** [comment]
Of course, @Poslovitch 

**LOGS**
https://pastebin.com/jdtY9ZJJ
**ENVIRONMENT**
CS-Corelib 1.5.16
Slimefun 4.1.12
Spigot 1.12.2
Java 8

**Comment by phuchptty** [comment]
i have the same problem too 
CS-Corelib 1.5.16
Slimefun 4.112
Spigot 1.10.2
Java 8

**Comment by TheBusyBiscuit** [comment]
The missing items is connected to the empty config as there are booleans for enabling ticker items, etc...
#564

**Comment by TheBusyBiscuit** [comment]
Apparently, noone, not even I noticed this:
But Maven apparently doesnt put the config.yml into the jar :?
All Builds that were compiled with it, on Bukkit and my Build Server show this problem.

**Comment by TheBusyBiscuit** [comment]
Fixed.
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#11
