### ISSUE TITLE
Tome of Knowledge Sharing craft not work

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#574]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Tome of Knowledge Sharing craft not work

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
![kepkivagas](https://user-images.githubusercontent.com/8324198/34830846-74a88150-f6e5-11e7-86d7-1a80e7068956.PNG)

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
![kepkivagas](https://user-images.githubusercontent.com/8324198/34830868-88d204c6-f6e5-11e7-9fc6-ea81caaaa306.PNG)

**Comment by TheBusyBiscuit** [comment]
Is the Item in the middle a Magical book cover and not just a paper...?

**Comment by sziamizu** [comment]
Javaslom a SlimeFun visszaállítását, és a MyPet kivételét.
