### ISSUE TITLE
Help about database - how to remove an armorstand before server starts

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#577]
Hello, in 1 only place of the server, inside the house of 1 player, in a machine room of slimefun, there is a damn armor stand, an ex: energy regulator, which even I deleting, when the server starts, it is regenerated , and any player who enters the chunk where it is hangs and drops the server. I can only erase it if I disable the energy regulator by items.yml. Dae I delete it, I can enter the player's house, I disconnect the server, reactivate the energy regulator, and I connect the server, but it appears there again, and again crashes and crashes the server when someone tries to load the chunk where it is. Can you remove this item from some slimefun database file with the server off?

**Comment by comonier** [comment]
please tell me how I could check and edit the file where the slimefun items are stored so that you can remove them with the server turned off 1 to 1, causing problems and causing the server to freeze and crash

**Comment by Redemption198** [comment]
You can find Slimefun's storage inside the main server folder "data-storage", the files which have the .sfb extension can be easily opened with a notepad.

**Comment by comonier** [comment]
TY VERY MUTH IT WORK PROBLEM SOLVED.
