### ISSUE TITLE
Slimefun duplication glitch

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#578]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Two players need.
1. player - remove fast item from inventory.
2. player - break slimefun block.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://www.youtube.com/watch?v=OdXnNJQ1ReQ

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
14.01 00:13:56 [Server] INFO Paper v1_12_R1
14.01 00:13:56 [Server] INFO CS-CoreLib v1.5.16
14.01 00:13:56 [Server] INFO Slimefun v4.1.13
14.01 00:13:56 [Server] INFO Installed Addons (4)
14.01 00:13:56 [Server] INFO ExtraGear v1.1.1
14.01 00:13:56 [Server] INFO SlimefunLuckyBlocks v1.1
14.01 00:13:56 [Server] INFO ExoticGarden v1.6.3
14.01 00:13:56 [Server] INFO ElectricSpawners v1.0
```

**Comment by Pajlis** [comment]
Repeat of issue #412 i believe..

**Comment by TheBusyBiscuit** [comment]
@Pajlis Yep.
