### ISSUE TITLE
Soulbound Items in KeepInventory region duplicate on player death

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#579]
## Description
Worldguard Region: Keep-Inventory set to true... die with soullbound picks, weapons, backpacks... backpacks are stacked 2 each in every slot, all items and weapons copied exactly.

## Server Log
Nothing relevant.

## Evidence / Proof
https://imgur.com/a/aySbw

## Environment
CraftBukkit v1_12_R1
Cs-CoreLib v1.5.16
Slimefun v4.1.13 (dev 4-17)

**Comment by mrcoffee1026** [comment]
Should clarify this is a WorldGuard extra flag "keep-inventory true" not a gamerule for the world -- which seems to work as expected (https://www.spigotmc.org/resources/worldguard-extra-flags.4823/)

**Comment by AtomicScience** [comment]
Well, fix isn't much hard to make - just check right after respawn if player's inventory contains needed item

Probably, I'll make patch, but i'm unsure I'll find some time

**Comment by mrcoffee1026** [comment]
Well as soon as you can would be great since I will use the heck out of this feature for events and things.  until then I'll have to mod the gamerule during events... fine for me, but I was thinking more along the lines of staffs that don't have that ability to just be able to arrive at an event location and not have to worry about it.  (or worse, if i forget to change the gamerule before an event or something...)  Anyway thanks, I'll keep an eye out for updates.

**Comment by madolebr** [comment]
that would be great, as i disabled all soulbound items to prevent dupes on my towny server

**Comment by Sakanas** [comment]
this also happens with redprotect /rp flag keep-inventory true

**Comment by mrcoffee1026** [comment]
Any soulbound ARMOR or ELYTRA the person is wearing STILL duplicates, please repair
