### ISSUE TITLE
Full stack of enchanted item in autodisenchanter duplicates unenchanted copy.

### ISSUE THREAD

**Issue by FatherWh0** [TheBusyBiscuit/Slimefun4#580]
## Description
Place a full stack of any enchanted item in the autodisenchanter. It will disenchant the first one and create a full stack of the unenchanted version from a single item. In this example the elemental staff of wind is used. The unenchanted form works the same as the enchanted form. Removing the enchant does not remove the ability to fly. One Elemental staff of wind becomes 64 without the luck of the sea I enchant but still with the ability to fly.

## Server Log
There are no errors or entries in the logs when this happens.
## Evidence / Proof
http://prntscr.com/i2zakb
http://prntscr.com/i2zazk
## Environment
Slimefun v4.1.13
CS-CoreLib v1.5.16
paper 1.12.2 build#1301

**Comment by VoidAngel** [comment]
This and #532 have been fixed with #608. To get the fix you will need to compile a Slimefun jar from the current github code.
:)
