### ISSUE TITLE
Damaged by Unlocking Items

### ISSUE THREAD

**Issue by shredz7** [TheBusyBiscuit/Slimefun4#581]
## Description
When unlocking items (I unlocked the Magic Eye of Ender) it shot out a firework on my position, but due to the latest update, fireworks damage you, so I was damaged.

## Server Log
No need for server log

## Evidence / Proof
None, I experienced this on a server that I do not own, so I cannot recreate it (I have no server of my own with slimefun on it)

## Environment
Minecraft: Optifine 1.12.2
SlimeFun: Latest as of January 21, 2018
But other than the Minecraft version these won't be necessary, surely.

I can program well and would love to fix this for myself, but what should I change? Should I remove the firework, change its location, etc?

**Comment by TheBusyBiscuit** [comment]
Missing Environment details...
