### ISSUE TITLE
Altar ender pearls

### ISSUE THREAD

**Issue by comfuzzled** [TheBusyBiscuit/Slimefun4#586]
## Description
I cannot place ender pearls into the alarm pedestals, I can place other things in, just not epearls.

## Server Log
Sorry I don't own the server, but it is the SRP server on IDMC.

## Evidence / Proof
I can't click it in, if I shift click, it gives the Cooldown animation for the epearl, and makes the throwing noise, but doesn't teleport the player or consume the epearl.

## Environment
I'm running Optifine 1.12.2 C6, and I'm pretty sure the server is running a recent version of the slime fun plugin, at most three months old.

**Comment by TheBusyBiscuit** [comment]
Don't post here if you cannot give us any of the important information.
