### ISSUE TITLE
It seems that one can not get vanilla gold ingot from dust?

### ISSUE THREAD

**Issue by ruhuasiyu** [TheBusyBiscuit/Slimefun4#588]
The Smeltery machine can translate gold dust to gold ingot(4 -Carat), but it cann't used for vanilla crafting.
So I still need to use furnace to smelt an ore?

I'm not sure whether it's intentional...

Beside, I hope that the Ore Crusher can crush copper ingot, etc?

**Comment by TheBusyBiscuit** [comment]
It is intentional...

And no it cannot.
