### ISSUE TITLE
Exotic Garden Heads Drop  CSCoreLib's Head

### ISSUE THREAD

**Issue by Coolkc456** [TheBusyBiscuit/Slimefun4#589]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Everytime someone breaks a Slimefun Exotic Harden head, CSCoreLib's head drops. I made a ticket like this a couple days ago but they told me to backup Slimefun's configs (or something like a folder but I didn't have a folder like that) so I regenerated the entire Slimefun files yet the problem persists.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/iLJUSWUc

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://www.youtube.com/watch?v=WvvTjJVncpU&feature=youtu.be

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Craftbukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.13
ExoticGarden v1.6.3

**Comment by TheBusyBiscuit** [comment]
This is Slimefun's Bug Tracker, not ExoticGarden's...
