### ISSUE TITLE
1.12.2 incompatible

### ISSUE THREAD

**Issue by ShadowPauler** [TheBusyBiscuit/Slimefun4#595]
## Description
Upon loading Slimefun, when the server is fully loaded, when someone joins, it gives a io.netty error saying that it is not responding, hard crashing the server.

## Server Log
I'm at school at the moment, I cannot paste it right now.

## Evidence / Proof
I'll send it when I get home.

## Environment
The latest version of spigot 1.12.2, latest version of Slimefun, latest version of CS-corelib, latest version of java, on ubuntu 16.04 server LTS

**Comment by AtomicScience** [comment]
Are you still at school?
We can't help you unless you'll send us your logs.
