### ISSUE TITLE
Properly write OOP code.

### ISSUE THREAD

**Issue by LaxWasHere** [TheBusyBiscuit/Slimefun4#598]
## Description
The codebase is a mess.

## Server Log
https://hasteb.in/atumogenoy.vbs

## Evidence / Proof
https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L2010

## Environment
https://i.imgur.com/o6sPiKM.png

**Comment by MiniDigger** [comment]
+1

**Comment by spammy23** [comment]
+1

**Comment by NickAcPT** [comment]
+1

**Comment by pimkennedy** [comment]
+1

**Comment by Vertanzil** [comment]
+1

**Comment by Towelie** [comment]
+1

**Comment by John000708** [comment]
Nice botting. Since you seem to know what you're talking about, why don't you go ahead and fix it yourself?

**Comment by TheBusyBiscuit** [comment]
a) The codebase is very old, there is of course much room for improvement. I am pretty certain there are parts that could be improved by object orientation. HOWEVER, statics help to reduce memory load and computation time if resources are needed more frequently, Java may be an OOP, but OOP is not always the way to go.
b) All your links point to absolutely nothing, no room for improvement on there.
c) This project is open-source. "Make it better" is not helpful, improve it yourself and make a Pull Request.
