### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by Vertanzil** [TheBusyBiscuit/Slimefun4#599]
# PS WE ARE NOT BOTS WE ARE A COMMUNITY OF DEVELOPERS TRYING TO MAKE YOU DO BETTER!.

## Description
The codebase is a mess.

## Server Log
https://hasteb.in/atumogenoy.vbs

## Evidence / Proof
https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java

https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L2010

## Environment
https://i.imgur.com/o6sPiKM.png

**Comment by TheBusyBiscuit** [comment]
Then do it better, and make a Pull Request.

This is just nonsense spam.
