### ISSUE TITLE
Consider using TaskChain

### ISSUE THREAD

**Issue by aikar** [TheBusyBiscuit/Slimefun4#606]
I've seen the pattern a few places, but notably here: https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L2010

I wanted to make you aware of my [TaskChain](https://github.com/aikar/taskchain) library, which greatly helps clean up code like this.

TaskChain would look like:

```java
TaskChain<?> chain = SlimfunStartup.newChain();
for (int i = 0; i < 11; i++) {
  chain.sync(() -> {
    if (input.getType().isBlock()) b.getWorld().playEffect(b.getLocation(), Effect.STEP_SOUND, input.getType());
    else b.getWorld().playEffect(b.getLocation(), Effect.STEP_SOUND, Material.HAY_BLOCK);
  });
  if (i < 10) {
    chain.delay(30);
  }
}
chain.sync(() -> {
  p.getWorld().playSound(p.getLocation(), Sound.ENTITY_ARROW_HIT_PLAYER, 1F, 1F);
  b.getWorld().dropItemNaturally(b.getRelative(BlockFace.UP).getLocation(), adding);
});
chain.execute();
```

It can help clean up series of delayed tasks greatly. Hope it helps.

**Comment by TheBusyBiscuit** [comment]
@aikar Looks elegant.
I don't like adding hard dependencies, but then again I abandoned the project a long time ago as well.
I'm leaving this open, in case someone wants to incorporate a smiliar concept into Slimefun, or (even better) CS-CoreLib and submits a PR.

**Comment by aikar** [comment]
FYI it is a dep you would shade into the plugin, so it's transparent to the end users.

**Comment by TheBusyBiscuit** [comment]
@aikar Didn't check your license or anything. Alright then, again, leaving this open for people to see and propose a PR.
