### ISSUE TITLE
[1.12.2]ID "HOT_CHOCOLATE" and "APPLE_PIE" already exists

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [TheBusyBiscuit/Slimefun4#607]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
```
WHen I start the server, these ids collide.
I believe somehow Exotic Garden re-register these ids while Slimefun did it b4
```

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/YV7F4igC
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Slimefun 4.1.13 , Exotic Garden 1.6.3, Paperclip 1.12.2

**Comment by TheBusyBiscuit** [comment]
Duplicate.
