### ISSUE TITLE
CargoNet heavily impacting server performance

### ISSUE THREAD

**Issue by ericbarbwire** [TheBusyBiscuit/Slimefun4#609]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.

So basically I run a medium sized server that has a lot of people that enjoy using SlimeFun - what lagged my server heavily was CargoNets on the server. We found a fix for this by modifying the ticker delay in the config: custom-ticker-delay: 115 the downside to this was the fact that this made ALL machines slower - so much so to the point that users began to get frustrated with the server. I think it would be greatly beneficial if you could adjust the ticker delay for just CargoNets or even an option to disable CatgoNets.
## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
Log: https://pastebin.com/waUVk1iB
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
Timings report: https://timings.spigotmc.org/?url=yoleduwetu
https://media.discordapp.net/attachments/408435238986055692/414922858272129033/unknown.png?width=1235&height=671

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun vDev (latest)

Add-ons
ExoticGarden v1.6.3
TinkerTools V2.0.0
SlimeXpansion v1.1.9
HotbarPets v1.1

**Comment by Poslovitch** [comment]
At least you're not asking us to optimize them :')

@TheBusyBiscuit Does the design of the Tickers would allow us to do such a change?

**Comment by TheBusyBiscuit** [comment]
You can disable Cargo Nets in the config.yml and disable any Item in the Items.yml
