### ISSUE TITLE
Hologram Character Bug With A Video.

### ISSUE THREAD

**Issue by NathanAdhitya** [TheBusyBiscuit/Slimefun4#61]
## Description
The Hologram Projector, refuses to remove the hologram (Armor Stand) upon breaking if there are special characters ex: ( "/" and "\" )

## Server Log
There were no errors, No Warnings, Nothing, everything seemed fine

## Evidence / Proof
Easy To Try Out. Just place a Hologram Projector, and then set the text with a text containing "/" or "\" .
Extra Evidence: https://youtu.be/joeKa4m8auQ

## Scenario
Place a Hologram Projector
Set the text to a text containing the character "/" or "\" . Example: \test
Break the Hologram Projector
Normally, without and of the two characters, the Hologram dissapears, but this time, it does not.
(And will never dissapear until manually broken using commands)

## Environment
PaperSpigot 1.11 (paperclip-965)
CS-CoreLib_v1.5.12
Slimefun 4.1.1

**Comment by TheBusyBiscuit** [comment]
Fixed.
