### ISSUE TITLE
Heated Pressure Chamber Freezing

### ISSUE THREAD

**Issue by lukemango** [TheBusyBiscuit/Slimefun4#611]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
The pressure chamber does not progress, it just stays at 0.0
## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/buyAvNAj
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://imgur.com/a/5ZwRe
## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Spigot- git-Spigot-4bg94dc-f4ca180 (MC:1.12.2)
CS-CoreLib - 1.5.16
Slimefun - 4.1.13

**Comment by TheBusyBiscuit** [comment]
Is it connect to an energy grid?

**Comment by lukemango** [comment]
Yes, it can be seen here:
http://prntscr.com/iiao2g

**Comment by TheBusyBiscuit** [comment]
@lukemango 
It is not. Replace the generator that is connected to your chamber with an energy capacitor.

**Comment by lukemango** [comment]
Ah, apologies.
Thankyou for the help
