### ISSUE TITLE
CARBONADO EDGED FURNACE  irregular working

### ISSUE THREAD

**Issue by zwtdj** [TheBusyBiscuit/Slimefun4#614]
![qq 20180226144106](https://user-images.githubusercontent.com/12005261/36656551-e4bd36c4-1b03-11e8-8877-66f105fd6e40.png)
![qq 20180226144149](https://user-images.githubusercontent.com/12005261/36656557-e851ec80-1b03-11e8-84ee-aaad5e6a55e6.png)
![qq 20180226144342](https://user-images.githubusercontent.com/12005261/36656561-ebc19d98-1b03-11e8-8d51-3c32a64c9d3c.png)

**Comment by TheBusyBiscuit** [comment]
Has been reported multiple times.
