### ISSUE TITLE
Question for adding functions.

### ISSUE THREAD

**Issue by Joapple** [TheBusyBiscuit/Slimefun4#615]
Let me start with Hello beautiful gang! Right now I am using a custom version I edited. I limited the number or androids that my players can place, i want to know if i do a pull request would be accepted to add that thing to the config file. I don't want to edit it everytime the plugin get's updated. Since ticking cargo nodes has been an issue we disabled it, but leaving androids works. If i make the config and the code beautiful would it be added, or i should continue like i'm doing right now? 

(The question is simple, do i want to config it, or only disable it in the code itself instead.)

Thanks and have a good day! Joapple.

Also, sorry for my bad english :P

**Comment by AtomicScience** [comment]
Well, I think it will be nice if you'll make pull request with this feature and it won't complicate plugin's code

**Comment by TheBusyBiscuit** [comment]
I generally think putting in a limit for the Androids per Player is not a good idea, and you can already disable the cargo net via the config.

Although I am not against Pull Requests at all, I even encourage them, I have to say that I am probably unlikely to merge something like this.

But you can still maintain your fork, and if editing the files everytime Slimefun updates is a hassle, try something like Code Injection, e.g. a script that inserts your code automatically at the place you want it to be.
