### ISSUE TITLE
Dust Washer Probabilities do not match Wiki

### ISSUE THREAD

**Issue by meiamsome** [TheBusyBiscuit/Slimefun4#616]
## Description
In the [wiki](https://github.com/TheBusyBiscuit/Slimefun4/wiki/Dusts) the dusts are listed in order of probability:

* Iron Dust
* Gold Dust
* Aluminium Dust
* Zinc Dust
* Tin Dust
* Copper Dust
* Magnesium Dust
* Lead Dust
* Silver Dust

However, the code [here](https://github.com/TheBusyBiscuit/Slimefun4/blob/c33c8e065e3e72863f751d9979cb4244cac5f764/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L1325) and [here](https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/ElectricDustWasher.java#L86) calculates the dusts as follows:
<img src="https://latex.codecogs.com/gif.latex?P(dust_n)&space;=&space;\dfrac{1}{4}&space;\cdot&space;\left(\dfrac{3}{4}\right)&space;^&space;n" title="P(dust_n) = \dfrac{1}{4} \cdot \left(\dfrac{3}{4}\right) ^ n" />
For the following dust with n on the left, approx probability after

| n | Dust Name | Probability Fraction | Probability Percentage |
| -- | -- | -- | -- |
| 0 | Gold | 1/4 | 25.00% |
| 1 | Aluminium | 3/16 | 18.75% |
| 2 | Copper | 9/64 | 14.06% |
| 3 | Zinc | 27/256 | 10.55% |
| 4 | Tin | 81/1024 | 7.91% |
| 5 | Magnesium | 243/4096 | 5.93% |
| 6 | Lead | 729/16384 | 4.45% |
| 7 | Silver | 2187/65536 | 3.34% |

Iron is given whatever remains, which is given by:
<img src="https://latex.codecogs.com/gif.latex?P(Iron)&space;=&space;1&space;-&space;\sum_{n&space;=&space;0}^7\left(\dfrac{1}{4}&space;\cdot&space;\left(\dfrac{3}{4}\right)&space;^&space;n&space;\right)" title="P(Iron) = 1 - \sum_{n = 0}^7\left(\dfrac{1}{4} \cdot \left(\dfrac{3}{4}\right) ^ n \right)" />
Which is 6561/65536 (Approximately 10.0%), making Iron slightly less likely than Zinc but more likely than Tin. Is this simply a Wiki error?

**Comment by TheBusyBiscuit** [comment]
@meiamsome First of all, your links are invalid but I still got what you meant.
You are right, the Wiki is wrong about this.
It's also nice to see this data arranged like this, as I never calculated the actual probabilities for each Ore.

May your table be used on the wiki? (With Iron added of course)

**Comment by meiamsome** [comment]
Oh, turns out that style of markdown links doesn't work on github issues! I fixed them, but it's semi-irrelevant.

Yes, feel free to use the table on the wiki!

**Comment by AtomicScience** [comment]
Formally, the Wiki isn't lying, because it mentions:
> you can randomly get the following dust types **(Order from the most common to the rarest)**

But I still think what this table is still useful and should be added to the article

**Comment by meiamsome** [comment]
@AtomicScience I'm not sure what you mean? It explicitly asserts its ordering is correct, when it isn't? Or perhaps I misunderstand what you're asserting from that quote (Which in that form I'm not sure where it's from?)

**Comment by meiamsome** [comment]
Oh, it's from the page on the Dust Washer - I was looking on the Dusts page. Yeah, this should be updated too I guess

**Comment by TheBusyBiscuit** [comment]
Updated.
