### ISSUE TITLE
Electric Dust Washer permits chosing the output Dusts

### ISSUE THREAD

**Issue by meiamsome** [TheBusyBiscuit/Slimefun4#617]
Creating a Dust Washer that is not input into a cargo node (Although it is possible to do this too), you can leave at least one dust in each output slot to make it produce only that one or those two dusts.

I will be happy to provide a PR to fix this issue in a short while.

**Comment by AtomicScience** [comment]
Well, if i understood you correctly, you mean us the issue which is already fixed: #503 
Am I right?

P.S.
Please, in future follow the example of issue and don't forget to attach server log, version of plugin and proofs of the bug

**Comment by meiamsome** [comment]
Sorry if I wasn't clear, the electric dust washer remains unfixed. I did realise this was fixed for the non-electric one but did not reference the issue while writing. Should I attach a log despite there being nothing of use in the log? Seems like a bit of an unnecessary ask, tbh, but sure. plugin version was 4.1.13

**Comment by AtomicScience** [comment]
I think, making a video evidence of this bug is a good idea

**Comment by meiamsome** [comment]
That's not terribly easy for me in my current setup - I'll see what I can do

**Comment by AtomicScience** [comment]
Imho, some good screenshots will be enough

**Comment by meiamsome** [comment]
Here is a before/after for you, where both the dusts on the right are copper - although you can do any dust or two dusts you prefer:

![Before](https://user-images.githubusercontent.com/1187491/36920246-06789fcc-1e58-11e8-9a0b-3522f4896a71.png)
![After](https://user-images.githubusercontent.com/1187491/36920250-09b7e224-1e58-11e8-9af4-9b47d66d0883.png)

**Comment by AtomicScience** [comment]
OK, just saw your fix and understood what you're talking about - yea, this fix must work, but it will halve the avalible space for production, which is not very good. However, it's better then letting players cheat this way, so make a PR. 

Thank you for your contribution :D

P.S.
What does "TBH" means?

**Comment by meiamsome** [comment]
It means "To be honest", I was perhaps being a tad snarky, thanks for looking over my solution - a PR of it is in #619

**Comment by meiamsome** [comment]
Another potential solution would be to store what dust is being produced, but not finish the production unless it fits (So in essence the machine would get stuck trying to output it). This behaviour seems more like the manual Dust Washer behaviour, but I am happy to try implementing the other one if that sounds better.
