### ISSUE TITLE
Flask of Knowledge on the Ancient Pedestal

### ISSUE THREAD

**Issue by Tom-Davidson** [TheBusyBiscuit/Slimefun4#62]
## Description
When placing a "Flask of Knowledge" on the "Ancient Pedestal" and you have more than 1 in the stack you are using 1 goes onto the pedestal and 1 is filled with xp. If there is only 1 in the stack then it fills with xp instead of going onto the pedestal (so it seems like when you have a stack the first is used and the 2nd goes onto the pedestal).

## Evidence / Proof
![2016-12-22_22 32 51](https://cloud.githubusercontent.com/assets/489078/21442600/c3d80486-c896-11e6-87ac-e87fd70e433f.png)
![2016-12-22_22 33 05](https://cloud.githubusercontent.com/assets/489078/21442598/c3d7750c-c896-11e6-9783-f47f40dd4753.png)
![2016-12-22_22 33 22](https://cloud.githubusercontent.com/assets/489078/21442599/c3d78a2e-c896-11e6-909b-4ccebeabbf3b.png)

## Environment
cscorelib version 1.5.12
slimefun version 4.1.1
spigot version 1.10.2

**Comment by NathanAdhitya** [comment]
Funnily, Happens with backpacks too.looks like the pedestals doesn't cancel the SF Event? :P
