### ISSUE TITLE
Metrics Error

### ISSUE THREAD

**Issue by Loonyy** [TheBusyBiscuit/Slimefun4#622]
## Server Log
https://pastebin.com/SMW0zxtC

## Environment
03.03 15:20:05 [Server] INFO CraftBukkit v1_11_R1
03.03 15:20:05 [Server] INFO CS-CoreLib v1.5.16
03.03 15:20:05 [Server] INFO Slimefun v4.1.13
03.03 15:20:05 [Server] INFO Installed Addons (2)
03.03 15:20:05 [Server] INFO ExoticGarden v1.6.3
03.03 15:20:05 [Server] INFO ElementumCore v2.9

**Comment by TheBusyBiscuit** [comment]
Metrics are handled by CS-CoreLib. So if this issue persists, try to tackle it there. But this error hasn't occured since a long time, try updating all your plugins (even unrelated ones). Maybe one of them implements an older version of the Metrics system and overrides the newest one.
