### ISSUE TITLE
Suggestion: Color/renamer

### ISSUE THREAD

**Issue by comfuzzled** [TheBusyBiscuit/Slimefun4#624]
## Description
There should be a new item called the item renamer, perhaps crafted with a red, orange, yellow, green, blue, and violet dyes and an auto-anvil (MK I or II). It's purpose is to rename items, as well as color their names using electricity instead of levels.

## Server Log
Unimportant, as it is only a suggestion.

## Evidence / Proof
Still unimportant

## Environment
I don't even own the server I use slimefun on.

**Comment by AtomicScience** [comment]
I don't think it'll be to easy, because Slimefun recognizes its items using lore and name, so renamed/recolored stuffs'll lose their properties.
