### ISSUE TITLE
Exotic Garden Schematic Position (Suggestion)

### ISSUE THREAD

**Issue by LordDarmix** [TheBusyBiscuit/Slimefun4#628]
Good Afternoon.

In our server we want to make big trees schematics, but some of them have roots that go underground. When the sapplings grow, the schematic pastes like it was copied at the bottom, resulting in the roots getting outside the earth.

¿Is it possible to add an exotic garden schematic position option? We just wonder if this is something that you could add.

Thanks for your time.

**Comment by TheBusyBiscuit** [comment]
This is an Issue Tracker for Slimefun, not a Suggestion Board for ExoticGarden...
