### ISSUE TITLE
Soulbound Elytra recipe produces an Infused Elytra

### ISSUE THREAD

**Issue by Tom-Davidson** [TheBusyBiscuit/Slimefun4#63]
## Description
Recipe for "Soulbound Elytra" in the guide produces "Infused Elytra"

## Evidence / Proof
If the altar mechanics scans the item setup for the first match maybe it's hitting [INFUSED_ELYTRA](https://github.com/TheBusyBiscuit/Slimefun4/blob/da4fd57906bb95cef3dfaac23e8774d6c6308c79/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L4248) and finding a match before it reaches [SOULBOUND_ELYTRA](https://github.com/TheBusyBiscuit/Slimefun4/blob/da4fd57906bb95cef3dfaac23e8774d6c6308c79/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L4252). I've not read deep enough to see how it works so may be wrong about the cause.

## Environment
cscorelib version 1.5.12
slimefun version 4.1.1
spigot version 1.10.2

**Comment by AlexLander123** [comment]
I submitted a Pull Request which should fix this issue.
