### ISSUE TITLE
Asynchronous entity track

### ISSUE THREAD

**Issue by WindUnwaken** [TheBusyBiscuit/Slimefun4#636]
## Description
Error spam after update spigot to latest

## Server Log
https://pastebin.com/UCE6apCL

## Environment
![image](https://user-images.githubusercontent.com/19383943/37563365-15cdd0b4-2aba-11e8-9d66-fe0b5e29c33d.png)
Slimefun 4.1.14

**Comment by LoXR** [comment]
I get this aswell, and then my server crashes.

**Comment by TheBusyBiscuit** [comment]
Should be fixed in a later build
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/
