### ISSUE TITLE
1.13 ?.?

### ISSUE THREAD

**Issue by Yukyxy** [TheBusyBiscuit/Slimefun4#637]
Just a question this plugin will still work in 1.13? :s
Someone will take it back?

**Comment by Redemption198** [comment]
Yes.

**Comment by Yukyxy** [comment]
ok thank you ^^

**Comment by Poslovitch** [comment]
This will just break backwards support. Supporting 1.13 means dropping support of 1.12, due to the big changes that are occuring.
