### ISSUE TITLE
Using an Explosive Pickaxe on a Shulker Box eliminates the contents

### ISSUE THREAD

**Issue by Jawakotb** [TheBusyBiscuit/Slimefun4#64]
## Description
When using an Explosive Pickaxe on a ShulkerBox filled with items, the dropped shulkerbox looses it's contents.  

## Server Log
No errors on the Server to report.

## Evidence / Proof
ShulkerBox with Items -->  http://i.imgur.com/Eo9c4bI.png

Used Explosive Pickaxe -->  http://i.imgur.com/0g8NS4l.png

ShulkerBox Without Items -->  http://i.imgur.com/KYg5Pff.png

## Environment
Slimefun v.4.1.1, Spigot 1.11.2

**Comment by Jawakotb** [comment]
Please note:  I have already added "Shulker_box" to the list of "UnbreakableItems" for the Explosive Pickaxe, along with Barrier blocks and CommandBlocks

**Comment by John000708** [comment]
You have to add WHITE_SHULKER_BOX and so on for each color.
