### ISSUE TITLE
Editing android script for android miner

### ISSUE THREAD

**Issue by PutraAK29** [TheBusyBiscuit/Slimefun4#641]
## Description
I want to remove certain script for android miner, so player can't select "move foward", "move down", move up". I want to do this since some player use android miner to grief other player home inside protection area. Can someone help how i can remove it?

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
I will ask the owner about this.

**Comment by TheBusyBiscuit** [comment]
You cannot remove it at the moment.
But Androids cannot "grief", they follow protection plugins. Granted that you use one that is supported.

**Comment by PutraAK29** [comment]
Then i will try using other protection plugin. Maybe our current protection plugin don't work well with android

**Comment by PutraAK29** [comment]
By the way. Anyone know what plugin that can work with android;

**Comment by PutraAK29** [comment]
Bumb

**Comment by Redemption198** [comment]
CS-CoreLib currently supports: 
- ASkyBlock
- Factions
- GriefPrevention
- Lockette 
- LWC
- PlotSquared
- PreciousStones
- Towny
- WorldGuard

If you want you can request to support another plugin by opening an issue on CS-CoreLib GitHub page.

**Comment by PutraAK29** [comment]
Thank you redemption198 for your information. I will inform the owner about this.

**Comment by DrOreo002** [comment]
Hey, so I'm the server owner. Ty PutraAK29 for the help :3 

So my server use RedProtect for protection and can you make it so it will support RedProtect?.

**Comment by Redemption198** [comment]
@DrOreo002 open an issue at [CS-CoreLib's GitHub page](https://github.com/TheBusyBiscuit/CS-CoreLib).
