### ISSUE TITLE
WindStaff/JetBoots kicking players for flying

### ISSUE THREAD

**Issue by ShaneBolenback** [TheBusyBiscuit/Slimefun4#648]
## Description
So on my server... we have ALLOWFLIGHT set to false, and a couple of players have complained that using the wind staff and jet boots they get kicked for flying. 

## Server Log
No Need

## Evidence / Proof
I do not have any visual proof, other than my players constantly getting kicked from my server.

## Environment
Spigot 1.12.2
SlimeFun 4.1.14
CS CoreLib 1.5.16

**Comment by ShaneBolenback** [comment]
Ah okay, thanks for getting back to me.
I will have to look into some anti-hack stuff.
I had a few hackers on my server today flying, so i had to turn ALLOW FLIGHT off.
Do you have any suggestions on a good anti-hack or anti-fly system?

**Comment by mrcoffee1026** [comment]
Best system is good staff to watch out for people from what I've seen... every "anti fly" thing seems to be vulnerable to some kind of bypass and the only thing an effective one seems to result in is doing things like this: kicking people for using slimefun items and the like.
