### ISSUE TITLE
SF guide is given but not usable

### ISSUE THREAD

**Issue by hmmcrunchy** [TheBusyBiscuit/Slimefun4#65]
## Description
Use /sf guide to give a guide book - completes ok
right click with book in hand to view, book changes to normal book not enchanted and has word in * invalid book tag *
console has error (below) and book is now normal book with aforementioned text

## Server Log

http://pastebin.com/gWr0yjfT

## Environment
spigot 1.11.2
cscorelib 1.5.10
slimefun 4.1.1
exotic garden 1.6

thanks for looking :)

**Comment by John000708** [comment]
CS-CoreLib version 1.5.10 doesn't support 1.11

**Comment by hmmcrunchy** [comment]
Hi john 

That would be it thanks for reply sorry lame issue 

Thanks for maintaining this it's amazing
