### ISSUE TITLE
Up the dust percentages please

### ISSUE THREAD

**Issue by MikeyMouse321** [TheBusyBiscuit/Slimefun4#654]
We are a couple of people playing slimefun and we all agreed that it is way to hard getting the materials using the dusts. We ask you to up the the percentages on the dusts getting from sifted ore.

We don't really have a server because we are just all friends to each others.

**Comment by madolebr** [comment]
why dont you just get the addon slimefun ores? get dust while ur mining ores

**Comment by PutraAK29** [comment]
Tell your server administator, not to github.
