### ISSUE TITLE
Auto Enchanter Max Enchant Limit

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#66]
## Description
Please add a max enchant limit to items in the auto enchanter, please, this is getting out of hand

## Evidence / Proof
http://i.imgur.com/90MYI84.jpg

**Comment by VoidAngel** [comment]
11 out of 16 of those enchants cant be added or modified by the auto enchanter, and even if there was a limit, the auto enchanter would not catch those 11 custom enchants.

So those other 5 enchants are the ones in question.
Are you asking to limit the amount of enchants you can have on 1 item?
Or are you asking to limit the max enchant level of any single enchant?

**Comment by xH3LLRAIZ3Rx** [comment]
Can you add a check in for lore, basically limit amount of enchants on items (so for example, can only have 5 enchants applied)

**Comment by xH3LLRAIZ3Rx** [comment]
I am hoping you guys will do this sooner, as you can see it is a major issue: http://i.imgur.com/OtpAfba.jpg

**Comment by NathanAdhitya** [comment]
Uhh.... what are those enchants at the bottom made out of?
They are not vanilla. so big chances that they aren't copyable (Auto Enchanted).
Except if those were EmeraldEnchants. Since there's no such thing as enchants under the Color tag of a chestpiece.

**Comment by xH3LLRAIZ3Rx** [comment]
Those are all EmeraldEnchants Enchants

**Comment by NathanAdhitya** [comment]
Ah, alright. Agreed with the idea of limiting emerald enchants
