### ISSUE TITLE
Possible Towny crash cause

### ISSUE THREAD

**Issue by LoXR** [TheBusyBiscuit/Slimefun4#660]
## Description
Basically been having several crashes in my server due to a chunk error, which may be linked to slimefun

## Server Log
https://pastebin.com/Ym9L9s9q

## Evidence / Proof
Slimefun error: https://pastebin.com/HjDxvkVD
Crash error: https://pastebin.com/eCKJi6RY

## Environment
Slimefun v4.1.14
git-Spigot-2086bb0-21d5f75 (MC: 1.12.2)
CS-CoreLib version 1.5.16

**Comment by LoXR** [comment]
@madolebr

**Comment by Redemption198** [comment]
Can you share this file "/plugins/Slimefun/error-reports/2018-04-20-12-39.err"?

**Comment by madolebr** [comment]
we may have found the issue. the sf error report pointed at a regulator we had at spawn in our slime fun tutorial, along with maybe react causing a server crash, it seems it may have registered as being that regulator for some reason

**Comment by TheBusyBiscuit** [comment]
@madolebr The Bug seen in your Error Report has already been adressed in #632 
The Fix is available in later builds:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by TheBusyBiscuit** [comment]
@madolebr You can wait for a full release, you can use a development build, it is up to you.
This was just meant as a heads up that the Issue is taken care of in the next Update or newer versions in general.

**Comment by madolebr** [comment]
i got you. just trying to ensure there was no issues going from an official release to one of the builds. are there changelogs to go with the builds/is the guide dupe bug fixed in the builds so i dont have to use the fix i have for them?
