### ISSUE TITLE
build 34 nuclear reactor resets energy network

### ISSUE THREAD

**Issue by madolebr** [TheBusyBiscuit/Slimefun4#665]
## Description
alright. if you have a nuclear reactor linked to your energy network, when it reaches around 16.6kj of energy in the network, it resets back to nothing, and continues to do this until the reactor is destroyed

## Server Log
not relevant

## Environment
slime fun:

 build 34
cscore: 1.5.16

**Comment by VoidAngel** [comment]
What do you mean by "resets" @madolebr ?
And are there no errors in console when this happens? No SF error logs?

**Comment by madolebr** [comment]
[20180425_160209.zip](https://github.com/TheBusyBiscuit/Slimefun4/files/1948836/20180425_160209.zip)
here is a very short video of it happening
