### ISSUE TITLE
power generators dont stop version 34

### ISSUE THREAD

**Issue by madolebr** [TheBusyBiscuit/Slimefun4#666]
## Description
tried to figure out the best way to do this, as to reopen my last issue or to make a new one, so decided to go with this.

sf power generators, i.e. generators and reactors, do not stop once the network is full of power. i know in normal releases they will freeze at the percentage they are at, and i can imagine that may have been a bug mistaken for a feature, but they should at least stop taking new fuel once the network is full of power. its throwing off the players for one since the energy regulator will go up to a larger amount than the network can hold, then it corrects it back to what the capacitors can hold, but its still using fuel constantly, so causing alot of wasted power
## Server Log
n/a

## Evidence / Proof
shouldnt be needed

## Environment
slime fun build 34
cscorelib 1.5.16

**Comment by Redemption198** [comment]
Can you try to use the latest builds for both Slimefun and CS-CoreLib?

**Comment by madolebr** [comment]
ill test with them here shortly and see what happens.

**Comment by madolebr** [comment]
still happening with the latest builds. just downloaded them and put them on a test server. energy networks are still building up past their limits and then lowering to their capacity and continuing this cycle over and over again. the only acception is that the reactors have an option that will cause them to stop generating power once the network is full, but they are still constantly using uranium. same with coal gens.

**Comment by madolebr** [comment]
just wanting to confirm this is also happening in slime fun 4.1.15

**Comment by capthehacker99** [comment]
madolebr it's the nuclear reactor and generator energy buffer keep resetting

**Comment by capthehacker99** [comment]
4 now just use the older version

**Comment by TheBusyBiscuit** [comment]
Most likely related to this: #629

**Comment by TheBusyBiscuit** [comment]
I got a spare minute so I fixed that in 340fc04

The fix should be available in Build 42 and later:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by madolebr** [comment]
afraid not. still bugged unfortunately

**Comment by madolebr** [comment]
in version 48, the issue is still present
