### ISSUE TITLE
how to fix error setup slimefun mrcookie

### ISSUE THREAD

**Issue by icansc187** [TheBusyBiscuit/Slimefun4#684]
## Description
How to fix error

## Server Log
https://pastebin.com/Ln0k2D6A

## Environment
Slimefun v4.1.14
CS-CoreLib v1.5.15

**Comment by VoidAngel** [comment]
Its an incompatibility with paperspigot. I'm not aware of any actual effects of that error, other than the obvious spam on startup.

**Comment by SoSeDiK** [comment]
I'm using the Paper for a long time, and I never seen that warning. Can it be because of outdated version (1.11.2)?
