### ISSUE TITLE
Digital Miner / Advanced Digital Miner will craft with vanilla blocks

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#687]
## Description
Use redstone vanilla daylight detectors and gold block in place of Solar Cells and 24-C Gold Block, will work as usual.

## Server Log
Not relevant.

## Evidence / Proof
This has been true for ages, I thought there'd be a ticket about it already but I can't find one.

## Environment
Latest.

**Comment by mrcoffee1026** [comment]
seriously?  why did you close this???

**Comment by TheBusyBiscuit** [comment]
Please follow our template, we are unable to provide any support if you don't give us any details such as the exact versions you are using.
Read and follow the template, it is already explained in there...
