### ISSUE TITLE
Item Registration failed: MULTIMETER

### ISSUE THREAD

**Issue by OmgItsNik** [TheBusyBiscuit/Slimefun4#689]
https://pastebin.com/kPnCsF88

Spigot: 1.12.2
CS:  1.5.18
SF: 4.1.15

ADDONS:
SlimeXpansion
ExtraGeat
SensibleToolbox
HotbarPets
ExoticGarden

**Comment by TheBusyBiscuit** [comment]
That is an Error related to SensibleToolbox, not Slimefun.
