### ISSUE TITLE
Digital Miner / Advanced Digital Miner will craft with vanilla blocks

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#690]
## Description
Use redstone vanilla daylight detectors and gold block in place of Solar Cells and 24-C Gold Block, will work as usual.

## Server Log
Not relevant.

## Evidence / Proof
Build both contraptions, use vanilla gold blocks (craft from nine ingots in craft table) in place of 24-c gold blocks and the vanilla redstone daylight detectors on either device in place of solar panels.  Use them.

## Environment
CraftBukkit v1_12_R1
CS-CoreLib vv1.5.18
Slimefun vv4.1.15
ExoticGarden v.1.6.3

**Comment by ThisTNTSquid** [comment]
I noticed this issue a year ago, but still forgot to report it as i usually disable that one due to the problem of being unfair to other players (especially new players) mining underground. I'm happy to see this issue finally being reported 😂
