### ISSUE TITLE
Can you send me a Slimefun V3.6.6 Source code?

### ISSUE THREAD

**Issue by minepaoz** [TheBusyBiscuit/Slimefun4#694]
## Description
i tried to modify Slimefun Guide book language on Eclipse but i found any of error, i couldn't fix it
I want you to submit the source code version 3.6.6 to me.
#sorry for bad english

## Server Log
-

## Evidence / Proof
-
## Environment
Eclipse-luna
CS-CoreLib_v1.3.1
spigot-1.8.8-R0.1-SNAPSHOT-latest

**Comment by TheBusyBiscuit** [comment]
No, source code of Slimefun 3 does no longer exist.
