### ISSUE TITLE
BUG OR ERROR ???

### ISSUE THREAD

**Issue by icansc187** [TheBusyBiscuit/Slimefun4#698]
## Description
How to fix error

## Server Log
https://pastebin.com/XeJqhRLS

## Environment
Slimefun_v4.1.1.jar 
CS-CoreLib+v1.5.18.jar
Spigot 1.11.2

**Comment by VoidAngel** [comment]
Hmm it looks like 1.11.2 BlockBreakEvent doesnt have the method setDropItems(). This is an error from CS-CoreLib though. I don't really know if CS-CoreLib is meant to be keeping backwards compatibility or not.
The fastest fix for you would be to downgrade to CS-CoreLib v1.5.16. However, this has its own risks. You can read the recent changes [here](https://dev.bukkit.org/projects/cs-corelib/files/2555439)

**Comment by TheBusyBiscuit** [comment]
This error is from CS-CoreLib.
