### ISSUE TITLE
How can add sf fix for slimefun? I see some server have this

### ISSUE THREAD

**Issue by KyoRion** [TheBusyBiscuit/Slimefun4#700]
Like title this's my question
How add /sf fix - fix machine in server

**Comment by VoidAngel** [comment]
That is a feature of my custom fork of slimefun. Its a band-aid fix so its not really something you are going to be able to get support with here at the main branch.

**Comment by madolebr** [comment]
not to mention the guide dupe issue was fixed, which is that that patch was for. just use sf 4.1.15. it is fixed in that version and up
