### ISSUE TITLE
Crafting - Basic Machines

### ISSUE THREAD

**Issue by Gumist** [TheBusyBiscuit/Slimefun4#702]
**## Description**
  Only the furnaces of the basic machines are running on my server, the others are not crafting.
  And no error appears and no plugin message.

**## Evidence**
https://youtu.be/AWQZxz4cTEE

## Environment

  CS-CoreLib v1.5.18
  Spigot v1.12
  SlimeFun v4.1.15

**Comment by VoidAngel** [comment]
This is probably an incompatibility with another plugin.
Can you try running slimefun on a server with no other plugins installed besides CS-Corelib?

**Comment by Gumist** [comment]
You're right there must be some conflict between plugin. I have tested here Slimefun and Cs-corelib and some additional sf plugins, and it worked perfectly.

**Comment by VoidAngel** [comment]
Mhm :D you can probably figure out the source of it pretty quickly by adding plugins back a group at a time until it stops working again. 
But this isnt really an SF issue so you should probably close this ticket xD
