### ISSUE TITLE
Big problem with an book guide.

### ISSUE THREAD

**Issue by masterfusionxD** [TheBusyBiscuit/Slimefun4#705]
Hello. I have a really annoying problem with a guide. When I join the server and try to open the guide it doesn't work. Furthermore, when I try to use /sf open_guide I get this thing:
![2018-05-21_20 38 24](https://user-images.githubusercontent.com/39492044/40323838-fcc32718-5d36-11e8-9691-49d1bf923a8e.png)

Here is the full log: https://pastebin.ca/4031053

The only proof I can show is that earlier SS of trying to use /sf open_guide. Relogging doesn't help either

Minecraft and server versions are the same: 1.11.2. Here is the SS of the other things needed:
![2018-05-21_20 40 47](https://user-images.githubusercontent.com/39492044/40323970-560dc80a-5d37-11e8-893d-d92bd8b4a36f.png)

**Comment by TheBusyBiscuit** [comment]
You are using and outdated Version of CS-CoreLib. Update it.
