### ISSUE TITLE
gps transmitter async crash

### ISSUE THREAD

**Issue by madolebr** [TheBusyBiscuit/Slimefun4#708]
## Description (Required)
server was running perfectly normal until this error came up in slime fun.java.lang.IllegalStateException: Asynchronous entity track!. it was on a gps transmitter teir 2. the crash didnt show in the logs, but it did crash. i have 2 logs. one from before the slime fun error, and one for after showing the server restarting. the error showed 5 times in 7 hours before it crashed the server, along with 3 energy regulator errors like i have posted about already

## Server Log
doesnt have relevant info

## Evidence / Proof (Required)

https://pastebin.com/B0q0iFeW
## Environment (Required)
slime fun dev 42
cscore 1.5.18
craftbukkit 1.12.2-R0.1-SNAPSHOT

**Comment by madolebr** [comment]
has anybody even read this? this error is popping up sever times a day, along with the energy regulators. its quite annoying

**Comment by TheBusyBiscuit** [comment]
Definitely a code design mistake, GPS Networks should refer to Location, rather than Block, this also causes this asynchronous access.

Leaving this for anyone in mood for a PR.

**Comment by madolebr** [comment]
i hope somebody does, as the error is happening more and more frequently as more people are building gps networks. this one im going to attach is still a async error with the gps's, but instead of crashing the server, it timed out all the players:
https://pastebin.com/0CdbeTzH
