### ISSUE TITLE
Slimefun machine turns into normal heads

### ISSUE THREAD

**Issue by DrOreo002** [TheBusyBiscuit/Slimefun4#709]
## Description (Required)
I don't know why, but somehow player on my server reported that their slimefun machine turns into CS-Corelib head, after the server restart

## Server Log
No error log

## Evidence / Proof (Required)
I don't think this is needed. Because what this bug does its just turns the slimefun machine into heads

## Environment (Required)
Slimefun : Latest version on bukkit dev
Cs - Corelib : Latest version on bukkit dev

Do you know why this is happening?. I really need answers.

**Comment by madolebr** [comment]
constant issue with slime fun items. if you check the slime fun folder, there is another folder for errors. all the errors would be there from them changing

**Comment by DrOreo002** [comment]
I saw only 2 error logs. And that log was created like a month ago. Not today (where the problem occour)

**Comment by DrOreo002** [comment]
So, there's no way yo fix this?

**Comment by madolebr** [comment]
i believe the developers are constantly working towards trying to fix it, but at this time, no. just gotta replace them for the players. which is kinda annoying. are you using clearlagg or react to help server performance or anything like that?

**Comment by DrOreo002** [comment]
Uhh yea, I have clear lag on my server. But I've disabled the clear dropped items features and many other things

I only use it to limit mobs per chunk and mob breeding. Is that the problem?

**Comment by madolebr** [comment]
not really if you have it limited like that. just was an option that might have been contributing to it more. personally we use react due to some of clearlaggs habits, but we still have the issue as well. its moreover an issue with cscore-lib not registering that item as being a slime fun item instead of a head.

**Comment by DrOreo002** [comment]
well, okay then.. Ty for the information btw

I'll close this issue later, I need more information from the dev.

**Comment by madolebr** [comment]
i dont think the admins are paying attention to here. been completely silent for 2 weeks. but here's a but if advise: try going to paper. we went to paper and all those head issues are fixed

**Comment by DrOreo002** [comment]
Hmmm, a lot of my plugin is usingthe spigot api. So prob it will broke if I use paper
