### ISSUE TITLE
grappling hook causing server crash possibly

### ISSUE THREAD

**Issue by madolebr** [TheBusyBiscuit/Slimefun4#713]
## Description (Required)
well. im not sure how to reproduce this, but i've had it happen a few times since upgrading to paper. the pastebin file is the error from the console, as no other errors show, but it mentions excessive velocity and names bowlistener and the item grappling hook.

## Server Log
https://pastebin.com/aKummuRT

## Evidence / Proof (Required)
nothing can be shown besides the error log

## Environment (Required)
slime fun dev build 42
cscorelib 1.5.18
exotic guardens
barrels
slimexpansion

**Comment by VoidAngel** [comment]
This is a weird issue with paper spigot. For some reason paper has a velocity limit of + or - 4.
4 isn't even a huge velocity so I don't really understand it xD
The only thing that we could do would be to cap the velocity limit. But is that really worth it when its papers problem anyways?

**Comment by madolebr** [comment]
from my understanding they cap it because that is supposedly the max that minecraft can handle, but then again i got that from just searching google all over for people having related issues with it. for now i have the item disabled, which i dont think many players used it before. and people have already asked the people developing paper to add in a configurable value instead of a set value for it and they will not do it. so if no solution could come from you guys, then its just another item that has to be disabled from slime fun. just this one is paper specific
