### ISSUE TITLE
Slimefun Task #390

### ISSUE THREAD

**Issue by MurryPuppins** [TheBusyBiscuit/Slimefun4#716]
I haven't seen any bugs/issues popping up on my server yet, but I'm sure I'll find out shortly as players tend to find them quickly and bring it to my attention. However, I had a previous issue, but fixed it after updating CS-Corelib. This is all that's left behind, perhaps it's nothing to be concerned about? If so, I'm sorry if I wasted any time here, just wanted to report it, in case it was an issue to be addressed. 

## Server Log
https://pastebin.com/yqvB3sq9

## Evidence / Proof (Required)
No evidence/proof yet. No known issue was found on the server, just an error output. 

## Environment (Required)
https://gyazo.com/07319ac4187b52c4c9b26e107d8943f6

**Comment by TheBusyBiscuit** [comment]
This error is not related to energy regulators or anything like that.
Some Inventory in the code has been badly designed.

Unfortunately due to how Java works, the true nature of the error is untraceable.
