### ISSUE TITLE
soulbound recipes issues

### ISSUE THREAD

**Issue by Volendam** [TheBusyBiscuit/Slimefun4#72]
![2016-12-28_19 23 59](https://cloud.githubusercontent.com/assets/24565612/21519876/b57e880a-cd33-11e6-81f4-bbaf0f8617a1.png)
![2016-12-28_19 24 16](https://cloud.githubusercontent.com/assets/24565612/21519880/b8abd85c-cd33-11e6-9e7e-7577c6e98ef5.png)

i make soulbound elytra 
but this machine make infused elytra

**Comment by AlexLander123** [comment]
The issue is already fixed in the upcoming Slimefun build.
