### ISSUE TITLE
About localization

### ISSUE THREAD

**Issue by Krauzzer** [TheBusyBiscuit/Slimefun4#721]
I'm just wondering if there's a way to fully locate the plugin's contents so I can translate them to my server. If there is, how can one do that? The messages files only let me translate some of it, I'd like to locate all of the blocks and items though.
I'll appreciate any information 👍 <3

**Comment by Poslovitch** [comment]
With the current way Slimefun recognizes items, it's not possible - I did try for my own server. But I'm working on #332, that'll make that possible.
