### ISSUE TITLE
sf items revert to vanilla items bug

### ISSUE THREAD

**Issue by realchessx** [TheBusyBiscuit/Slimefun4#722]
## Description (Required)
sf items revert back to vanilla after server restart, 

one of my player say it got 40percent chance

is there a way to force save items/machines, /sf save

## Evidence / Proof (Required)
sorry it happen when  server restart

## Environment (Required)
slimefun 4.1.15
cs-corelib 1.5.18

**Comment by madolebr** [comment]
this has been a constant issue with slime fun. its the items loosing their nbt data. although they are trying to find a fix, there hasnt been one for a while

**Comment by AtomicScience** [comment]
Try to load last Slimefun data backup from /data-storage/Slimefun/block-backups - sometimes Slimefun resets all data
