### ISSUE TITLE
Reinforced Spawners become Spawners of type <Type> whenever they are placed

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#725]
## Description (Required)
User reported a blaze spawner becoming a pig spawner on placement... they repaired a blaze spawner, placed it... saw it was a pig spawner so mined it again and saw it was a spawner of type \<Type\>.  So far as I know, no pull requests have altered anything having to do with spawners for awhile now, so I didn't really believe this, but verified this happens with all types, not just Blaze, upon repairing the spawner I have a "repaired Cave Spider spawner" but the moment I place it, it has the appearance of a pig spawner.  Mining the spawner with a pickaxe of containment gives me a Reinforced Spawner of \<Type\>.

## Server Log
Nothing relevant.

## Evidence / Proof (Required)
https://imgur.com/a/Ed5DSbu
Images of spawner type both before and after placement/re-mining with pickaxe of containment.  This has all the appearance of what nearly everyone refers to as a "glitched" Slimefun item which happens when data files forget everything about the block.. and then a player mines it.  The information area should likely be 3-5x as large and contain a description of a reinforced spawner... it doesn't because it no longer knows what it is.  Item can be "fixed" by using a spawn egg on it (or is a working pig spawner without doing anything additional).

## Environment (Required)
This server is running CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
CraftBukkit v1_12_R1
CS-CoreLib vv1.5.18
Slimefun vDEV (4-42)
Installed Addons (1)
ExoticGarden v1.6.3

**Comment by madolebr** [comment]
its silkspawners, most likely. ik it causes unrecognized spawners to become pig spawners, and i had to disable the reinforced spawners and such due to that

**Comment by mrcoffee1026** [comment]
i don't have silkspawners...

**Comment by madolebr** [comment]
do you just use the pickaxe of containment for mining spawners on your server? or any other plugins that affect spawners?

**Comment by mrcoffee1026** [comment]
yes and that's this is the only plugin that affects spawners that I know of (Slimefun).

**Comment by mrcoffee1026** [comment]
I do notice this only happens when breaking a reinforced spawner - somehow.  I'm not sure how that's really possible since - so far as I know - "reinforced spawner" data isn't really put anywhere?  I thought they became vanilla spawners when placed but... a vanilla spawner still gives a broken spawner as expected.  Breaking a reinforced one results in a (working) spawner of \<Type\> and... this limitation is not horrible since the process of fixing the spawner has already been completed once at that point.  I'm not convinced another plugin is causing this, at all since completing that procedure is required and this only applies to reinforced spawners.

**Comment by Firebuggie** [comment]
From what I've tested, this piece code from SlimefunSetup.java, which apparently fixes spawner type isn't called somehow. (lines 2890-2905):
`@Override
			public boolean onBlockPlace(BlockPlaceEvent e, ItemStack item) {
				if (SlimefunManager.isItemSimiliar(item, SlimefunItems.REPAIRED_SPAWNER, false)) {
					EntityType type = null;
					for (String line: item.getItemMeta().getLore()) {
						if (ChatColor.stripColor(line).startsWith("Type: ")) type = EntityType.valueOf(ChatColor.stripColor(line).replace("Type: ", "").replace(" ", "_").toUpperCase());
					}
					if (type != null) {
						CreatureSpawner spawner = (CreatureSpawner) e.getBlock().getState();
						spawner.setSpawnedType(type);
						spawner.update(true, false);
					}
					return true;
				}
				else return false;
			}`

**Comment by mrcoffee1026** [comment]
If you revert this then Reinforced Spawner recipe can no longer be accessed.

**Comment by Firebuggie** [comment]
Just tested this; managed to repair a spawner, place it, break it, repair and place it again and it worked just fine.

**Comment by mrcoffee1026** [comment]
You have to break it again to complete the "test".
