### ISSUE TITLE
Remote accessible Elevator plates

### ISSUE THREAD

**Issue by SECRETCRAFTER** [TheBusyBiscuit/Slimefun4#726]
Remote accessible Elevator plates

Machines/things that are using a book interface (Elevator plates...) can be remote accessed, if you drop the book that appears in your hotbar at the right moment. then you can open the book anywhere and teleport back to your elevator plate.

Fix:
make the books undroppable or add data to the book and clear books with that data from every player.
 
SF version: 4.1.15
Server tested on: skykingdoms.net

![2018-06-23_16 53 50](https://user-images.githubusercontent.com/40522294/41810888-091112e4-7706-11e8-9a77-0f8dd43dcae5.png)
![2018-06-23_16 53 11](https://user-images.githubusercontent.com/40522294/41810889-0b19e9bc-7706-11e8-9df3-76771c202aff.png)

**Comment by Spellbind4201** [comment]
Could not replicate. Funny to say but I actually want to do this.
