### ISSUE TITLE
Slimefun Ticking Error

### ISSUE THREAD

**Issue by lukemango** [TheBusyBiscuit/Slimefun4#727]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
Slimefun Error (I don't know what the issue is, but the console is saying for me to report this)

## Server Log
All Error files/messages need to be provided via http://pastebin.com/
https://pastebin.com/fhkq99WW

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
http://prntscr.com/jyg311

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
All details on the Pastebin

**Comment by madolebr** [comment]
here's what you should check, as i have noticed this with slime fun barrels. someone at that location has probably tried to put a hopper on a barrel, which breaks the plugin. check the location stated in that error. either that or a hopper or something is picking up the barrels hologram, which i have seen that happen as well

**Comment by lukemango** [comment]
@madolebr Thanks for the reply, but I was wondering if that could be fixed :)

**Comment by TheBusyBiscuit** [comment]
This is related to Barrels.
Not Slimefun. And therefore doesn't belong here.
