### ISSUE TITLE
Items turned into heads (not cs-corelib heads)

### ISSUE THREAD

**Issue by LadyCutieButt** [TheBusyBiscuit/Slimefun4#728]
## Description (Required)
All the machines and all that's not "minecraft items" turns into heads. My friends can load the items, but i can't. The heads don't turn into cs-corelib heads, it just looks like steve heads.

## Server Log
No server log
## Evidence / Proof (Required)
![image](https://user-images.githubusercontent.com/40584686/41883627-d0c6b326-78ef-11e8-957d-bb6253828d71.png)
I don't think i need to show the evidence, items just turns into heads.

## Environment (Required)
Slimefun: Lastest version
Cs-corelib: Lastest version

I really need help, some of my friends have this issue and some not.

**Comment by madolebr** [comment]
thats corruption in your minecraft assets folder. nothing to do with the plugin or whatever server u are referring to
