### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by Imothep80** [TheBusyBiscuit/Slimefun4#73]
Hello,

thx for your big and create work. All members of my Server are glad to use sf. :)
This makes me also happy.
If you like to vist us you can find us here: (IP redacted)

You can delete this post if you like.

**Comment by NathanAdhitya** [comment]
Sir, please read, this is an "ISSUES" section, not a thankyou or a comment section.

**Comment by TheBusyBiscuit** [comment]
Thanks but this is not a Server advertising platform...
