### ISSUE TITLE
Unable to research?

### ISSUE THREAD

**Issue by katalinea** [TheBusyBiscuit/Slimefun4#731]
When my players try to unlock things it takes XP, says they're researching the subject, then it never unlocks the subject.

I would provide something from my log, however there are no related messages, error or not. 

I asked the player who was having the issue to record it. I was unable to recreate the issue, but the recording shows it clearly.
link to video of issue: https://youtu.be/Upws-ozqUFA

![slimefun](https://user-images.githubusercontent.com/40867541/42415394-5120130c-8212-11e8-9238-5ec68f138d66.PNG)

**Comment by Poslovitch** [comment]
This might be related to the player's UUID. Are you running in offline mode?

**Comment by katalinea** [comment]
I am not. The only changes I've made that might have affected UUID were swapping my current data-storage folder with a previous one. (the data-storage does hold some Slimefun data)

**Comment by Poslovitch** [comment]
Hmmm.
Can you send us the file of the player?
It can be found in data-storage/Players/"player's-uuid".yml.

**Comment by katalinea** [comment]
[playeruuid.zip](https://github.com/TheBusyBiscuit/Slimefun4/files/2173220/playeruuid.zip)
I wasn't able to add the .yml file, so I added it into an archive.

**Comment by Poslovitch** [comment]
Okay, so here is the content of the yml file : 
```yaml
researches:
  '124': true
  '105': true
  '12': true
  '18': true
  '132': true
  '35': true
  '53': true
  '30': true
  '6': true
  '50': true
```

It clearly show that he somehow could research some items. Does the bug only happen with Monster Jerky's research? Does it happen with other researches?

**Comment by katalinea** [comment]
It does happen with other researches. This only started happening after I replaced the storage with a backup, which is why he had being able to do some research before I replaced the file. Also, I've just had two other players report the same issue.
