### ISSUE TITLE
Digital Miner and Reinforced Digital Miner do not work at all.

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#734]
## Description (Required)
Since closing of #690, neither device can be used AT ALL, even with the proper slimefun blocks. (pull request #724)

## Server Log
Nothing relevant.

## Evidence / Proof (Required)
Place blocks per instructions, attempt to use as normal.  Nothing happens upon "use".

## Environment (Required)
CraftBukkit v1_12_R1

CS-CoreLib vv1.5.18
Slimefun vDEV  (Slimefun4-48.jar)

Installed Addons (1)
ExoticGarden v1.6.3

**Comment by mrcoffee1026** [comment]
This fix for misplaced parentheses... either #736 or #6 here... now digital miners work.  However, vanilla gold blocks can still be used for the advanced digital miners.

**Comment by VoidAngel** [comment]
Getting there :D lol

**Comment by Poslovitch** [comment]
The problem with Slimefun blocks being used in Multiblocks rely on the way Multiblocks are handled.

**Comment by VoidAngel** [comment]
Yeah 🤔 well would it be better to make the digital miner a single block machine? Or perhaps change the required SF blocks in the multiblock recipe to be vanilla blocks instead? or should we go ahead and add more blockstorage checks to keep it how it is?

**Comment by mrcoffee1026** [comment]
i'm not sure how to deal with it I was looking at the coding and couldn't sort out a proper approach which is why i made a ticket instead of trying to sort it out on my own.  i feel like it should be able to tell if the blocks are the appropriate blocks it just somehow isn't.
