### ISSUE TITLE
Exception with BlockMenuPreset

### ISSUE THREAD

**Issue by MurryPuppins** [TheBusyBiscuit/Slimefun4#737]
Ever since we've updated the slimefun, this particular error message has been outputted on every startup of the server. We've been experiencing issues with lag on our server, and after a timings report, found Slimefun to be using a lot of ticks. Whether this issue is causing it or not, it's something being outputted, so figured I'd report it should it be a bug. Hopefully you'd be able to assist!

## Server Log
https://pastebin.com/raw/LfitFgEF

## Evidence / Proof (Required)
https://gyazo.com/0715e6731fb5ced495f984c60e3b2ad3

## Environment (Required)
MC Version: Spigot 1.11.2
CS-Corelib: v1.5.18
Slimefun: v4.1.15
ExoticGarden: v1.6.3
ElectricSpawners: v1.0
MagicLoot: v2.1.0

**Comment by madolebr** [comment]
it's been like that on alotta servers. slime fun is an intense plugin.
