### ISSUE TITLE
Ability to turn of crafting

### ISSUE THREAD

**Issue by 1StormDragon** [TheBusyBiscuit/Slimefun4#738]
## Description (Required)
Hello, I would like to have a feature to disable specific crafting recipes for slimefun items without needing to disable the full item, I would still like the items to be obtainable through /sf give or /sf cheat but not crafted.

## Server Log
None needed since this is a suggestion.

## Evidence / Proof (Required)
None needed since this is a suggestion, Other than the fact that there doesn't seem to be anything that does this function already.

## Environment (Required)
CraftBukkit v1_12_R1
CS-CoreLib vv1.5.18
Slimefun vDEV (#48)

**Comment by madolebr** [comment]
there is an option  it's in items.yml
