### ISSUE TITLE
Duplicating Grappling hook

### ISSUE THREAD

**Issue by Goro922** [TheBusyBiscuit/Slimefun4#740]
## Description (Required)
hold bow on left hand, hold grappling hook on right hand and then right click one time, and 2 grappling hook will appear (see video)

## Server Log
no error

## Evidence / Proof (Required)
https://youtu.be/aHino3Cc7gk

## Environment (Required)
CraftBukkit version git-Spigot-4bd94dc-fb414fe (MC: 1.12.2) (Implementing API Version 1.12.2-R0.1-SNAPSHOT)
CS-CoreLib v1.5.18
Slimefun v4.1.15
https://imgur.com/a/fPiEJjQ

**Comment by DrOreo002** [comment]
Fixed. I hope the dev will acc my pr ASAP xD

PS : Makasi bro dah report, membantu banget untuk server ane ;)
