### ISSUE TITLE
Items Resetting After Restart

### ISSUE THREAD

**Issue by FrayFox** [TheBusyBiscuit/Slimefun4#742]
## Description (Required)
Whenever the server restarts, several slimefun items are reset into their vanilla counterparts i.e. The Auto gold pan reverts back into brown terracotta. This only happens with seemingly random items, as only one of several cargo output nodes was reset back into a CSCordeLib head.
UPDATE:
I noticed that for me, some blocks (solar panels and capacitors) are being reset without a restart of the game, possibly inside the spaces that were previously used by other parts that had been reset by a restart

## Evidence / Proof (Required)

![image](https://user-images.githubusercontent.com/41274315/42740133-08025546-8860-11e8-844d-918e4bcfed12.png)

## Environment (Required)
Minecraft 1.12.2
CraftBukkit v1_12_R1
CS-CoreLib vv1.5.10
Slimefun vv4.1.15
SlimeXpansion v1.5.9
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
SlimefunOres v1.4.6
SlimefunScrap v1.2.2

**Comment by DrOreo002** [comment]
This also happens to me, its seems like slimefun data storing is not good. And some of the blocks lost their data and stuff. Also I'm still working to fix this problem, if I can fix it. I'll make a pr here

**Comment by Poslovitch** [comment]
Best solution = switch to full SQL database.
We have the same problem as developpers of ASkyBlock and BSkyBlock. Bukkit's file storage API became unstable due to changes to permissions and file protections on nearly all the existing OSs.

**Comment by fyxrim** [comment]
I am a Chinese. My English is not good.



I also have this problem.



ASkyBlock plugins do not have SQL data. How do you convert SQL data?

**Comment by BlackBeltPanda** [comment]
See #621

**Comment by FrayFox** [comment]
any progress being made?
