### ISSUE TITLE
[ Question ] What is the listener class for slimefun block breaking things?

### ISSUE THREAD

**Issue by DrOreo002** [TheBusyBiscuit/Slimefun4#743]
Well, the title say it all. I just want to know

**Comment by DrOreo002** [comment]
I cant find it. All of the class on the Listener package didn't have any block break event.

**Comment by Poslovitch** [comment]
That took me a few seconds : 

https://github.com/TheBusyBiscuit/Slimefun4/blob/7b07bc8c611d24eef498991835b77cd45d1851a9/src/me/mrCookieSlime/Slimefun/listeners/NetworkListener.java#L9

https://github.com/TheBusyBiscuit/Slimefun4/blob/f9e7c3cae69edf27261322ca8e83de19fb7756ce/src/me/mrCookieSlime/Slimefun/listeners/TalismanListener.java#L23

https://github.com/TheBusyBiscuit/Slimefun4/blob/0ce04d6a495d801c24651164851b39658b8d27e4/src/me/mrCookieSlime/Slimefun/listeners/ToolListener.java#L14

**Comment by DrOreo002** [comment]
Well I thought its a different listener lol. Ty for da help
