### ISSUE TITLE
Huge Lag When Open Guide

### ISSUE THREAD

**Issue by coco0325** [TheBusyBiscuit/Slimefun4#749]
## Description (Required)
Server get a big lag when players open their guide.

## Server Log
None

## Evidence / Proof (Required)
None

## Environment (Required)
Spigot: Spigot 1.12.2-R0.1-SNAPSHOT
CS-Corelib+v1.5.18
Slimefun+v4.1.15

**Comment by Poslovitch** [comment]
Most likely, cause : heads on 1.12.2. Mojang increased the delay between each request to get the texture of a head.
Can't do anything, except removing custom skulls.

**Comment by coco0325** [comment]
Is there any way to cache the heads?
