### ISSUE TITLE
explosive pickaxe bug

### ISSUE THREAD

**Issue by Volendam** [TheBusyBiscuit/Slimefun4#75]
i said "When using the Explosive Pickaxe, i can break commandblock and barrier"

developer said "Just add COMMAND_BLOCK to the Explosive Pickaxe's Blacklist in the Items.yml ..."

barrier is worked 
but commandblock still break...

## Environment
Spigot 1.11.2
CS-CoreLib v1.5.12
Slimefun 4.11

**Comment by Volendam** [comment]
i don't support yml file

**Comment by TheBusyBiscuit** [comment]
COMMAND not COMMAND_BLOCK
