### ISSUE TITLE
Running with 1.13

### ISSUE THREAD

**Issue by ShaneBeee** [TheBusyBiscuit/Slimefun4#750]
## Description (Required)
So I noticed a few people have asked here whether or not SF will run with 1.13 and their issues have been closed and ignored. So Im curious if you guys will be working on support for 1.13?
I also saw one person say it should run with 1.13, but when I tried, it said it wouldn't load.

## Server Log
Here is a paste of what happens when I run this with spigot 1.13
https://pastebin.com/aSUaE11J

## Evidence / Proof (Required)
No required

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
[12:01:40 INFO]: Slimefun version v4.1.15
[12:01:51 INFO]: CS-CoreLib version v1.5.18
[12:01:56 INFO]: This server is running CraftBukkit version git-Spigot-69774b3-549d9b0 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by Meta-Win** [comment]
Slimefun for Minecraft 1.13 not is ready yet
Here is the pull request for the 1.13 update - #746

**Comment by PrzemoVi** [comment]
My version is 100% working ( form pull request )

Jar files on my google drive:
https://drive.google.com/open?id=13rSlLxNKxH_hRLXsOVNwZtqzNO3bp8DS

**Comment by ozm8** [comment]
@PrzemoVi It doesn't work. /sf guide works and the gui but /sf research and the mechanics don't work

**Comment by Cekkostyle** [comment]
I found two Bug with the LumberAxe
1) When you use it to turn Logs into the Striped Logs you get a Lumber Axe after Breaking the Striped Log.
2)The LumberAxe feature (breaking the tree at once) only works for Oak and Acacia but for Acacia it does not realy work to be fair (look at the pictures I don't know how to describe it)
![2018-08-13_06 05 21](https://user-images.githubusercontent.com/34059963/44012386-058fa4ba-9ebf-11e8-9cef-c6fe0615f3f1.png)
![2018-08-13_06 05 25](https://user-images.githubusercontent.com/34059963/44012388-05ad02ee-9ebf-11e8-8dba-2fceb39e6efe.png)
And sorry for my bad english 😞

**Comment by ShaneBeee** [comment]
Hey @Cekkostyle  They don't normally reply to closed issues, so you should create a new issue for this
