### ISSUE TITLE
Extract the Cargo Management System as a separate plugin

### ISSUE THREAD

**Issue by rlf** [TheBusyBiscuit/Slimefun4#752]
## Description (Required)
I love the Cargo Management System.
I want it!
But not neccesarily all the other stuff.
Please extract it from Slimefun, and let Slimefun shade it in or something, but allow others to use the transport system as a standalone. None of the alternatives comes close.

## Server Log
N/A

## Evidence / Proof (Required)
N/A

## Environment (Required)
N/A

**Comment by TheBusyBiscuit** [comment]
Then just disable what you do not like in your Items.yml

**Comment by rlf** [comment]
I get that is an option, but the cargo-management system is such an awesome tool, that I think it merits to be on it's own, granted Slimefun4 is a "comprehensible game-changing plugin", but when some of the components are literally components, they could/should be modularized (IMO). But hey, no probs if that is not a priority.

**Comment by rlf** [comment]
Also, doing what you propose still requires the server to use slimefun, i.e. for knowledge and all the componnents etc. But, I see that the cargo thing is quite tightly integrated into SF - I will try to extract it my self, and put it as a separate plugin. Thanks.
