### ISSUE TITLE
Server crashed when OP open guide

### ISSUE THREAD

**Issue by coco0325** [TheBusyBiscuit/Slimefun4#754]
## Description (Required)
Server crashed when OP open guide again and again.
Server also lag when OP open guide once.

## Server Log
https://pastebin.com/SNrMV2dp
https://pastebin.com/901uJtNf

## Environment (Required)
Spigot 1.12.2 git-Spigot-642f6d2-57ab4cf
Slimefun 4.1.15
CS-corelib 1.5.18

**Comment by Gusted** [comment]
So long I can see from the server crash, it's that the config is not has been well set with research things at the data-storage/Slimefun/Players/ the UUID of the op.yml and then in that file. research/ in that file is a error i think or remove the file what can cause the research he have are removed, but the problem will be fixed then.
