### ISSUE TITLE
Book comes with unlocked items.

### ISSUE THREAD

**Issue by UnlimitedNinjas** [TheBusyBiscuit/Slimefun4#755]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
When doing /sf guide everything is unlocked, u dont need xp. I want it so players can use xp to unlock them.

## Server Log
All Error files/messages need to be provided via http://pastebin.com/
No errors

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://gyazo.com/bc972bfed13babb0d95fd5c8cd451084

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
SF > v4.1.12
CS-C > v1.5.18
CRAFTBUKKIT > v1_12_R1
0 addons

**Comment by Meta-Win** [comment]
Try:
- Update your slimefun to the v4.1.15
- Set the "enable-researching" to "true" in Researches.yml on /plugins/Slimefun folder
