### ISSUE TITLE
[Question] Multiple recipes per item

### ISSUE THREAD

**Issue by ShaneBeee** [TheBusyBiscuit/Slimefun4#759]
## Description (Required)
Hello... is it possible to create multiple recipes for one item? For instance, i have created an item where smelting iron dust in a furnace gives me 1 "unrefined iron" but i want to add a second recipe where in the smeltery it will give me more than 1 as the output. Is that possible?

**Comment by DrOreo002** [comment]
Yes. But you'll need to edit the code

**Comment by DrOreo002** [comment]
If that's the case. I don't think you can. By editing the code I mean edit the slimefun directly

**Comment by ShaneBeee** [comment]
Okay I see what you mean, okay thanks.... I will go a different route
