### ISSUE TITLE
[Suggestion] Crafting more than 1 item at a time in enhanced crafting table

### ISSUE THREAD

**Issue by ShaneBeee** [TheBusyBiscuit/Slimefun4#760]
## Description (Required)
So one thing people get annoyed with constantly is the fact you can only craft 1 thing at a time in the enhanced crafting table. I would love to see a system similar to how other machines work. Take the smeltery for example. If you put the items in for the required recipe, lets say a stack of each item, you can just click on the fence post over and over again and it will keep smelting said item. Whereas in the crafting table, you have to click, open the crafting table, take the item out, click again, and do that over and over.. Its a huge pain that everyone complains about. I love SF but i have to say that is only part I hate about it ;)
If it can be set to be like the other machines that would be AWESOME. Or maybe an option in the config? Either or, it would just be nice to be able to craft more than 1 item at once. 

Thank you for reading

**Comment by madolebr** [comment]
use the automated crafting chamber then.

**Comment by ShaneBeee** [comment]
Im aware of that, thats not what i was asking. I was suggesting a change to the enhanced crafting table.
