### ISSUE TITLE
Cargo System Lag

### ISSUE THREAD

**Issue by 1StormDragon** [TheBusyBiscuit/Slimefun4#761]
## Description (Required)
Lately I have noticed that cargo systems around the server have been lagging a TON.

## Server Log
No error(s)

## Evidence / Proof (Required)
![image](https://user-images.githubusercontent.com/36472285/43988308-f843d2f8-9d75-11e8-8cfc-d298c178f3b1.png)

## Environment (Required)
Slimefun vDEV (52)
CS-CoreLib vv1.5.18
CraftBukkit v1_12_R1 
Installed Addons:
ExtraGear v1.1.1
ExoticGarden v1.6.3
PrivateStorage v3.0
Barrels v1.11
TinkerTools v2.1.0
SlimeXpansion v1.1.9
HotbarPets v1.1
SlimefunOres v1.4.6
MagicLoot v2.1.0
Dolly v2.06

**Comment by madolebr** [comment]
your lucky thats all yours is. cargo nodes are resource intensive on servers

**Comment by 1StormDragon** [comment]
Any way to fix/improve the lag issue?

**Comment by creator3** [comment]
Could you collect more information with [Spark](https://github.com/lucko/spark)?

**Comment by 1StormDragon** [comment]
Sure, Here are my results: https://sparkprofiler.github.io/?t2DSvVokON
