### ISSUE TITLE
EnergyNet ConcurrentModificationException

### ISSUE THREAD

**Issue by narcissu14** [TheBusyBiscuit/Slimefun4#763]
## Description (Required)
EnergyNet java.util.ConcurrentModificationException

## Server Log
https://pastebin.com/ku60XnHd

## Evidence / Proof (Required)
ENERGY_REGULATOR dissapear

## Environment (Required)
CS-CoreLib v1.5.18
Slimefun 4.1.15

**Comment by madolebr** [comment]
#696
