### ISSUE TITLE
[BUG]!BLOCK_PLACER play with hopper can brush items.

### ISSUE THREAD

**Issue by rxsglzc** [TheBusyBiscuit/Slimefun4#767]
## Description (Required)
While the BLOCK_PLACER place a item, put a hopper under the BLOCK_PLACER so that the item is placed and there is another one in the funnel.
Use redstone is quicker

## Server Log
none

## Evidence / Proof (Required)
[http://233-10067805.cossh.myqcloud.com/kk%202018-08-24%2020-36-58_%E5%AD%97%E5%B9%95.mp4](url)
I made a video of myself.

## Environment (Required)
spigot 1.11.2
Slimefun  ---The latest version, I follow commits update.

**Comment by YiMengYanYu** [comment]
![qq](https://github.com/Slimefun/Slimefun4/assets/111495241/ea667bfb-bef3-41c6-ade5-7dc96db9812c)
国内玩家现状

**Comment by Boomer-1** [comment]
> 国内玩家现状

what does this have to do with this issue
