### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by lukemango** [TheBusyBiscuit/Slimefun4#768]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
Console Spamming - I have to be honest, i'm not sure what's happening in-game, just console spam really.
## Server Log
All Error files/messages need to be provided via http://pastebin.com/
https://pastebin.com/cdhK1tq5
## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://pastebin.com/cdhK1tq5
## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

Paper v1_12_R1
CS-CoreLib vv1.5.18
Slimefun vv4.1.15
Installed Addons (3)
ExoticGarden v1.6.3
Barrels v1.11
SlimeXpansion v1.1.9

**Comment by Gusted** [comment]
This problem has nothing to do with Slimefun, it's with CS-CoreLib you can better move this issue to the project: https://github.com/TheBusyBiscuit/CS-CoreLib
