### ISSUE TITLE
SF error on towny plots

### ISSUE THREAD

**Issue by QueenKisaki** [TheBusyBiscuit/Slimefun4#77]
## Description
Slimefun had no problems working before on claimed plots but once a player moved and made a new town, they moved their machines and even made new ones but they only work in the wild. We've played around with towny perms and have them all on but it still says he cant use anything.

## Server Log
There are no errors.

## Evidence / Proof
https://s29.postimg.org/dvrv8tomf/E10_D2_CEE80_A933_C76_DDD93_C16_EADFCBA8_A56_BCBC840_EEF8.jpg
.

## Environment
1.10.2 and everything else is up to date with latest.

**Comment by TheBusyBiscuit** [comment]
@AlexLander123 You were the last one to temper around with the Towny Integration, so Im putting you onto the job :P

**Comment by AlexLander123** [comment]
This was the error I was fixing while improving the Towny Protection. @TheBusyBiscuit You will have to compile the latest copy as he is using the older version and not my version.
The latest CS-CoreLib is released on 26 November (Before my patch on the module).

**Comment by AlexLander123** [comment]
By the way, @QueenKisaki In the current latest released version (CS-CoreLib v1.5.12), only the plot owner, town mayor, plot owner's friend and town resident can use the machine in town land. It has nothing to do with Towny permission system.

**Comment by QueenKisaki** [comment]
Yes I just updated corelib to 1.5.12 and the mayor of the town owns all the plots and is still unable to use it and gets that same msg. lol not sure what else to do or what could be causing it.

**Comment by AlexLander123** [comment]
@TheBusyBiscuit You need to recompile and upload a new version. The November 26th release has issue with Towny Protection Module which is already fixed in ee34031c83c0e4ebe1497e7aa4e746cb71ba079e the commit but not released.

@QueenKisaki The issue was already fixed in repo but the new version is not released.
