### ISSUE TITLE
Infernal bonemeal is a big net loss

### ISSUE THREAD

**Issue by Iiridayn** [TheBusyBiscuit/Slimefun4#771]
## Description
Recipe takes: 11 netherwart, 6 stone, 3 obsidian, 2 dirt, 1 bonemeal, and 1 blaze powder. It gives you 8 pieces.

To grow netherwart from planted to harvestable requires 3 uses. GCD gives us 24 pieces at a cost of 33 netherwart, for a net yield (1-3 net gain per harvest, probably even distribution, so average gain of 2) of 16 netherwart. So - our net _gain_ from making 3 recipes of this stuff is:

-9 obsidian, -18 stone, -6 dirt, -3 blaze powder, and _-15 netherwart_. There is no positive net gain!

## Environment (Required)
CraftBukkit v1_12_R1

CS-CoreLib vv1.5.18
Slimefun vv4.1.15

Installed Addons (2)
 ExoticGarden v1.6.3
 Barrels v 1.11

## Resolution

Give more Infernal Bonemeal per recipe (minimum of 17 just to barely exceed break-even on the netherwart _alone_, not to speak of the crafting time and the obsidian), or increase the effectiveness - fully maturing a plant from any stage would result (with careful use) in a net gain of 5 netherwart (in exchange for 3 obsidian, 6 stone, 1 blaze powder, etc).

Proposed fair and balanced approach:
- fully mature netherwart on single use
- _and_ recipe gives 20 infernal bonemeal.

This results in a net gain of 29 netherwart - in exchange for 3 obsidian et al, this seems a _minimally_ reasonable fair and balanced gain for a somewhat laborious recipe.

**Comment by TheBusyBiscuit** [comment]
Interesting. Thanks for the insight.

**Comment by omer03** [comment]
This isnt fixed?

**Comment by Iiridayn** [comment]
Just tested it out - Infernal Bonemeal now fully matures netherwart, but still only 8 pieces. I got a net gain of netherwart, but I don't feel the obsidian cost/crafting time was worthwhile. Still, at least it is a tradeoff instead of completely useless.
