### ISSUE TITLE
1.13 not loading right

### ISSUE THREAD

**Issue by madolebr** [TheBusyBiscuit/Slimefun4#777]
## Description (Required)
basically just started to try tomake my networks `1.13 towny server, when this error pops up every time the server is started up. no slimefun commands are working and its not recognizing any machines either.

## Server Log
https://pastebin.com/htWLnpXb

## Evidence / Proof (Required)
https://pastebin.com/htWLnpXb

## Environment (Required)
sf dev 4.57
cscore v 1.5.18
craftbukkit 1.13.1

**Comment by VoidAngel** [comment]
`10.09 16:29:50 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.CSCoreLibPlugin.compatibility.MaterialHelper`

This means that your Slimefun plugin could not find the piece of code called MaterialHelper inside of the CS-CoreLib plugin. MaterialHelper is a new part of the CS-CoreLib plugin made to help transition into 1.13.

You need to compile a CS-CoreLib jar from here
https://github.com/TheBusyBiscuit/CS-CoreLib

**Comment by TheBusyBiscuit** [comment]
You need to use a 1.13 compatible Version of CS-CoreLib...

**Comment by madolebr** [comment]
compiled the 1.13 version from your repository, or at least i think i did it right. had alot of errors during, but it started up. however trying to do anything results in tons of errors in the console. and as well, nothing working as it is supposed to. i believe it is due to worldguard. https://pastebin.com/u5UyWLGR
@TheBusyBiscuit

**Comment by madolebr** [comment]
10.09 21:30:58 [Server] ERROR Could not pass event PlayerInteractEvent to Slimefun vDEV
10.09 21:30:58 [Server] INFO org.bukkit.event.EventException: null
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
10.09 21:30:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
10.09 21:30:58 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.CSCoreLibPlugin.protection.modules.WorldGuardProtectionModule.canAccessChest(WorldGuardProtectionModule.java:19) ~[?:?]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.canAccessChest(ProtectionManager.java:106) ~[?:?]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$2.onInteract(SlimefunSetup.java:202) ~[?:?]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.Slimefun.listeners.BlockListener.onRightClick(BlockListener.java:149) ~[?:?]
10.09 21:30:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO ... 17 more
10.09 21:30:58 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WGBukkit
10.09 21:30:58 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.CSCoreLibPlugin.protection.modules.WorldGuardProtectionModule.canAccessChest(WorldGuardProtectionModule.java:19) ~[?:?]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.canAccessChest(ProtectionManager.java:106) ~[?:?]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$2.onInteract(SlimefunSetup.java:202) ~[?:?]
10.09 21:30:58 [Server] INFO at me.mrCookieSlime.Slimefun.listeners.BlockListener.onRightClick(BlockListener.java:149) ~[?:?]
10.09 21:30:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
10.09 21:30:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-500ff5d-7033f18]
10.09 21:30:58 [Server] INFO ... 17 more

**Comment by madolebr** [comment]
https://pastebin.com/JfFZsujZ
whenever trying to use a basic machine, like enhanced crafting table
https://pastebin.com/1AVq6VZe
when trying to use explosive pick

so atm, only thing im sure is working is energy from solar panels

**Comment by VoidAngel** [comment]
This comment will probably get deleted by TheBusyBuscuit again :P 
BUT
That error message indicates that your worldguard is out of date (in relation to the slimefun project and minecraft 1.13). I recommend trying to learn what the error messages mean. It may help you solve problems faster in the future.

If you go to WorldGuards website you should be able to find a dev build for WG 7

**Comment by madolebr** [comment]
i already have the worldguard snapshot 7.0.0

**Comment by VoidAngel** [comment]
My bad! After reading the error more carefully, I can see its actually caused by your CS-CoreLib. I also just realized that the public CS-CoreLib doesnt have WG7 integration yet.
So my guess is you will have to wait until that is updated, but that might time some time because WG7 isnt even "officially" out yet. Unless of course you have someone to update it for you.
