### ISSUE TITLE
Machine (player head) issues.

### ISSUE THREAD

**Issue by l3st4tPlugins** [TheBusyBiscuit/Slimefun4#782]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.

Basically, sometimes, machines, stop working and when broken, they turn into heads with the "CS-CoreLib's Head" name.
I know it's in the Troubleshooting Guide, but I do have an error report which matches with the machine.

## Server Log
All Error files/messages need to be provided via http://pastebin.com/
Slimefun Error Report:
https://pastebin.com/Uv1Let18

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://i.imgur.com/LLk3ENB.png

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
https://i.imgur.com/Rkcwu3h.png

The custom addons do not add any machine and are not affected by this glitch, it's the energy-based machines (regulator, capacitor...) that are affected.

**Comment by 1StormDragon** [comment]
A temporary fix to this issue for now is deleting the “null.sfb” file in **datastorage/Slimefun/stored-blocks/worldname** before restarting your server appears to fix this bug though usually it will come back and you will need to remove it again. Blocks that are broken should appear in this file, deleting the file will not fix already broken items.

**Comment by l3st4tPlugins** [comment]
Is there a more permanent fix to this issue? My server does not restart often,

**Comment by madolebr** [comment]
not one bit. they have been trying to fix the issue for over a year that i know of.

**Comment by DrOreo002** [comment]
I fixed this on my server. I can tell you how to fix it, its just the problem with the block storage. The item data is available but the block storage didn't load it somehow, so you can check if the player break a slimefun item and if that slimefun item is not inside the block storage class cache load up the block data from sfb file. And yeah its basically reloading it every time the player break a slimefun item
