### ISSUE TITLE
NullPointerException on first server stop

### ISSUE THREAD

**Issue by Tarluin** [TheBusyBiscuit/Slimefun4#784]
## Description (Required)
After installing Slimefun on a new server, no other plugins installed, there is a null error when you stop the server.

## Server Log
https://pastebin.com/GvRUNrBg

## Environment (Required)
This server is running CraftBukkit version git-Spigot-68acb93-65bb2d0 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

[Slimefun] Enabling Slimefun vDEV - 58 (git 18881806)

This error occurred before CS-Corelib was installed automatically.

**Comment by TheBusyBiscuit** [comment]
You are missing CS-CoreLib, if you want to use the experimental Slimefun build for 1.13, you will also need the experimental CS-CoreLib build for 1.13

https://thebusybiscuit.github.io/builds/
