### ISSUE TITLE
Error on 1.13.1

### ISSUE THREAD

**Issue by Amiroslo** [TheBusyBiscuit/Slimefun4#787]
## Description (Required)
Just trying to run the server with latest build for 1.13.1

## Server Log
https://pastebin.com/WZdXSZWj

## Environment (Required)
MC 1.13.1 Paper-318
CS-CoreLib+v1.5.18
Slimefun4-58

**Comment by xH3LLRAIZ3Rx** [comment]
@Amiroslo You need to use the latest dev build of CS-CoreLib here: https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/CS-CoreLib-28.jar
