### ISSUE TITLE
UPDATE TO THE 1.13.1?

### ISSUE THREAD

**Issue by andfont** [TheBusyBiscuit/Slimefun4#788]
Please! Tell me if there is an intention to update this plugin to version 13 to know if I continue to program it on my own or I wait for you to act it out. if it is not going to update more or it is an abandoned project please say it just ask this, if it is abandoned project or not, if it is abandoned I will follow its programming but I need to know it! thanks friends!

**Comment by TheBusyBiscuit** [comment]
The project was already updated to 1.13.
It is available as an experimental development build
https://TheBusyBiscuit.github.io/builds/

You will also need a CS-CoreLib build that supports 1.13

**Comment by ShaneBeee** [comment]
@TheBusyBiscuit 
You guys should put a note in the main readme stating that the builds for 1.13 are at that link.
Its not documented anywhere and its really confusing people. 
Not to mention the second someone opens a question about it you immediately close it. 

I feel like if there was some effort into updating your posts and letting the community know that 1.13 builds are available and that you guys are actively working on the project would be very helpful to the community who really enjoys and supports this plugin!

**Comment by andfont** [comment]
hello thank you for answering I just wanted to know if you were working for the new version thanks, but I will wait because it has many errors I get sf <argument> and I do not see anything else and the exotic also errors, so I expect a stable version for 1.13.1 since 1.13 is very bad and with many errors. When you have a stable version please indicate it on the main website thank you very much for your work!
