### ISSUE TITLE
Do not read the items.yml

### ISSUE THREAD

**Issue by andfont** [TheBusyBiscuit/Slimefun4#790]
Hello, why do you close it? it is not reading correctly the items.yml always stays in WITHER_ASSEMBLER but it does not keep registering and there is no way that the rest of the add-ons work, please do not close the case I can not see where it fails in the source code thanks!
I'm with the 1.13 server and with the latest compilation

**Comment by TheBusyBiscuit** [comment]
Stop spamming.
Read the guidelines and use the template.

**Comment by andfont** [comment]
the problem is that it does not read the items.yml is not spam friend please I have already done everything that can be done, it is not spam it is not working, you are not reading the file items.yml completely and you are not registering the items. please do not close is a bug. Thank you
