### ISSUE TITLE
Cargo Stuffs won't work.

### ISSUE THREAD

**Issue by Gelox1209** [TheBusyBiscuit/Slimefun4#791]
## Description (Required)
It seems that whenever I run the latest cscore lib and slimefun, everything is working except the input/output cargo stuffs, whenever I try to connect things it doesn't connect, and it won't transport any items whatever I try, and the only error it ever spits out is on startup and is in the pastebin below.

## Server Log
https://pastebin.com/aPywCQxd

## Evidence / Proof (Required)

![image](https://user-images.githubusercontent.com/14896896/46574104-4f050e00-c953-11e8-808e-57b62c2b489a.png)

## Environment (Required)
Latest 1.13 spigot server
AutoPockets-v1.1.0
CorpseReborn-Hotfix
CS-CoreLib-28
DiabloDrops
EssentialsX-2.15.0.45
multisleep-1.6-SNAPSHOT
QuickExit
riflechairs
RightCrops1.1
Seasons-Core-2.1.0
Slimefun4-58
Stew1.13.x
TreeGravity_3.0.0
VeinMiner-1.12.2

**Comment by VoidAngel** [comment]
I think the error log is from something else.

In the picture you have there, the system does not appear to be correctly set up. What happens if you place the cargo manager right next to the connector node?

**Comment by Gelox1209** [comment]
![image](https://user-images.githubusercontent.com/14896896/46576347-54c31980-c97c-11e8-926e-8961d209c926.png)

**Comment by PrzemoVi** [comment]
Are you using latest build from https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/?

You can also try using my modified .jars:
https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5

Fixed worldedit 7 (my request https://github.com/TheBusyBiscuit/Slimefun4/pull/814)
Fixed enchanted furnaces and lumber axe duplication glitch (https://github.com/TheBusyBiscuit/Slimefun4/pull/810)
Fixed auto. crafting. table, electric furnace and charging bench (my request https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64)
Some other changes and optimalizations

Warn: This will broke support with worldedit older than 7.0!!!
