### ISSUE TITLE
Lumber axe duplication

### ISSUE THREAD

**Issue by Frozen-Craft** [TheBusyBiscuit/Slimefun4#797]
## Description (Required)
in 1.13 when you click a log with a lumber axe (to transform it to striped log) when you break the striped log a second lumber axe will drop

## Server Log
there isn't error in the logs

## Evidence / Proof (Required)
https://youtu.be/gqenItGpUvo

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version: 1.13.1
CraftBukkit: v1_13_R2
your CS-CoreLib version: 29
your Slimefun Version: 4-58
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

**Comment by xH3LLRAIZ3Rx** [comment]
Getting the same problem
