### ISSUE TITLE
Saw Mill bug

### ISSUE THREAD

**Issue by Frozen-Craft** [TheBusyBiscuit/Slimefun4#798]
## Description (Required)
When you use the saw mill it dosen't give you 8 wooden planks but a bark log and it only "work" with the oak log

## Server Log
Dont have any error log

## Evidence / Proof (Required)
https://youtu.be/pE5rAyTiuv8

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version: MC 1.13.1 CraftBukit v1_13_R2 (spigot)
your CS-CoreLib version: vDEV -29
and your Slimefun Version: vDev - 58

**Comment by Sniddunc** [comment]
#810 
I submitted a PR to fix this. There is a problem with Slimefun where only 1 item is dropped, but the main issue is within CSCore-Lib (which I've also submitted a PR to). In 1.13, they changed the material of all planks from something like OAK_WOOD to OAK_PLANKS. OAK_WOOD now represents the bark.
