### ISSUE TITLE
Short Question: Does this work on 1.13.1?

### ISSUE THREAD

**Issue by MothGirlMusic** [TheBusyBiscuit/Slimefun4#799]
not seen any documentation and last edit was a month ago and last release was back in may while the website says the dev only codes on other games now...so, does this or is this planning on supporting 1.13.1?

**Comment by TheBusyBiscuit** [comment]
There are dev builds for 1.13 available.
You need both Slimefun and CS-CoreLib.

https://thebusybiscuit.github.io/builds/
