### ISSUE TITLE
Energy Capacitators Becoming Corrupt

### ISSUE THREAD

**Issue by MrWardy** [TheBusyBiscuit/Slimefun4#801]
## Description (Required)
So basically, upon restarting my server, energy capacitators continue to corrupt themselves. Essentialls what happens is the texture (amount of energy in the capacitator) will look the same as before the capacitator became corrupt, even when power to the capacitator is corrupt. I am unsure if this happens at different times however I do know it happens when the server restarts. When breaking these corrupt capacitators, they drop a head textured as it would look when you break it (for example if you break it when it *looks* like the capacitator is full, the texture in your inventory will be the same) and the name of the item is "CSCoreLib's Head".

## Server Log
Full Restart Log (Shutdown and Startup): https://pastebin.com/jaF5hHb9

## Evidence / Proof (Required)
Placed down corrupt capacitator: https://i.badlion.net/LsHmyqNBL6MJFhUt4bmcaH.png
Item in inventory: https://inovus.co/RteUHr.png
Item with name in inventory: https://inovus.co/bdDYKP.png

## Environment (Required)
Minecraft: 1.12.2
Paper: v1_12_R1

CS-CoreLib: vv1.5.18
Slimefun: vv4.1.15

Barrels: v1.11
SlimeXpansion: v1.1.9
ExtraGear: v1.1.1
HotbarPets: v1.1
ExoticGarden: v1.6.3
SlimefunOres: v1.4.6

https://inovus.co/uxNxT9.png

**Comment by loper12** [comment]
Same problem here, but happening on spigot, and with gps transmitters

**Comment by loper12** [comment]
Probably has to do with BlockBreakEvent or remembering what heads are where.
