### ISSUE TITLE
Ancient Altar it does not work

### ISSUE THREAD

**Issue by andfont** [TheBusyBiscuit/Slimefun4#803]
## Description (Required)
the altar does not work, it does not manufacture the items, there is no way, whatever it does, it does not give anything.

## Server Log
it does not give error it simply does not

## Evidence / Proof (Required)
it just does not do it for the Slimefun version DEV - 58 version (git 18881806)

## Environment (Required)
- Slimefun version DEV - 58 (git 18881806)
- CS-CoreLib version DEV - 28 (git 09822a9f)

**Comment by VoidAngel** [comment]
The issue is here
https://github.com/TheBusyBiscuit/Slimefun4/blob/188818061cbb9d71c2ddb5e4781a7c93458e48bc/src/me/mrCookieSlime/Slimefun/listeners/AncientAltarListener.java#L148

The method was changed because it was depreciated but the new method is broken all together because it renames vanilla items to white with italics.

**Comment by andfont** [comment]
If you are right I see the problem, because when possible we expect a new revision with the resolution of the problem, thank you very much for your work friend, and you inform us of the progress. regards!

**Comment by xH3LLRAIZ3Rx** [comment]
Just tested the old method: if (customName.equals(StringUtils.formatItemName(itemStack.getData().toItemStack(1), false)))

Seems like its not deprecated anymore, at least my IDE is not popping up it being deprecated, and it seems to have fixed the problem.

**Comment by andfont** [comment]
perfect! we wait for a new revision great work friend xD notify us when a new revision is available compilation xD

**Comment by andfont** [comment]
hi, are you going to make a new compilation with all the bugs fixed like the altar? please if the project is abandoned please advise because I have fixed it for my server but I do not want to modify the code if this project is active and it is going to make new compilations, thanks greetings friend.

**Comment by MothGirlMusic** [comment]
@andfont how did you fix this?

**Comment by andfont** [comment]
I converted the custom name in ITALIC italics, I programmed it so that it does not happen. but it is that there were more failures but I have everything fixed, at the moment I have it working everything with exotic garden, electri, sensible expansion everything I have programmed it so that it works well. Thanks for your interest but it works for us.
Also mistakes of the many spawners! but it also works for us. for fixing the altar you have to check the:
// ABF We fix by giving the item with your custom arrange the italic
e.getPlayer (). getInventory (). addItem (fixItemStack (stack.getItemStack (), stack.getCustomName ()));
Implement something like this:
public static ItemStack fixItemStack (ItemStack itemStack, String customName) {
ItemStack stack = itemStack.clone ();
if (customName.equals (StringUtils.formatItemName (new CustomItem (itemStack, 1), false))) {
ItemMeta im = stack.getItemMeta ();
im.setDisplayName (null);
stack.setItemMeta (im);
}
else {
ItemMeta im = stack.getItemMeta ();
if (customName.contains ("§")) {
// ABF We fix the italic italic always white at the beginning!
//System.out.println ("cus:" + customName);
im.setDisplayName ("§f" + customName);
} else {
im.setDisplayName (null);
}
//im.setDisplayName("§f "+ customName);
stack.setItemMeta (im);
}
return stack;
}

**Comment by PrzemoVi** [comment]
Use my modified .jars (both cscorelib and slimefun):
https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5

Fixed worldedit 7 (my request https://github.com/TheBusyBiscuit/Slimefun4/pull/814)
Fixed enchanted furnaces and lumber axe duplication glitch (https://github.com/TheBusyBiscuit/Slimefun4/pull/810)
Fixed auto. crafting. table, electric furnace and charging bench (my request https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64)
Fixed Ancient Altar itemstack fixing ;)

Warn: This will broke support with worldedit older than 7.0!!!

**Comment by PrzemoVi** [comment]
You found a way to workaround this.
I found way to fix this ;)

Modified fixItemstack method
public static ItemStack fixItemStack(ItemStack itemStack, String customName) {
		ItemStack stack = itemStack.clone();
		if (customName.equals(StringUtils.formatItemName(new ItemStack(itemStack.getType()), false))) {
			ItemMeta im = stack.getItemMeta();
			im.setDisplayName(null);
			stack.setItemMeta(im);
		} else {
			ItemMeta im = stack.getItemMeta();
			im.setDisplayName(customName);
			stack.setItemMeta(im);
		}
		return stack;
	}

**Comment by MothGirlMusic** [comment]
so this fixes ancient altars not working? thanks man!

**Comment by PrzemoVi** [comment]
> 
> 
> so this fixes ancient altars not working because of some italics issue?[thats how i understood the issue] but uh, thanks man!

Yes ;)
No problem ;)

**Comment by andfont** [comment]
ok thanks but I have already made many improvements like the spawners that have never worked well now with my version already work and another bug also solved, please I would like to see the source code to share what I need thanks or wait for the new code coding new to compare thanks.

**Comment by PrzemoVi** [comment]
I uploaded my source code to my google drive: https://drive.google.com/drive/folders/16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5
Do you have exotic garden, electri and sensible expansion working with 1.13.2?
Can you share jar files to me? :)

**Comment by andfont** [comment]
I currently have it working perfectly at 1.13.1 but I think that in a few weeks I will have it for 1.13.2 xD when I have it I warned you xD

**Comment by PrzemoVi** [comment]
Ok, but can you upload 1.13.1 files? :D

**Comment by andfont** [comment]
mm ok friend I'll do it for you xD there's a lot of work in them I hope you are useful and update it in an official version someday xD I sent the link:
https://drive.google.com/drive/u/0/folders/18L4jQeTfWZdcOPOgTQpsrkZK3ZX_z86D

**Comment by PrzemoVi** [comment]
Thank you! :)

**Comment by MothGirlMusic** [comment]
i second this, my server is extatic to even have a semi-working version. [i am on 1.13.2]

**Comment by PrzemoVi** [comment]
After some modifications i get Slimefun and all listed addons to work on 1.13.2 without ANY bugs.
I`m so happy :D

**Comment by PrzemoVi** [comment]
Here you are:
https://drive.google.com/open?id=1SxB7yeHZjB5cNWdvjrnlwTQbdb-eDNIi

My latest modified Slimefun, cscorelib with fixed all bugs and andfont`s addons modified by me to 1.13.2 :smile: 

I tested it and everything is working

**Comment by andfont** [comment]
I'm glad friend xD a I'm fixing some details and various bugs but minor sensitivetools etc .. but in general everything is correct xD my users are happy for 1 month but now it is almost all perfect xD great work at all xD

**Comment by MothGirlMusic** [comment]
@PrzemoVi it seems your version of sensibletoolbox.jar when used with the updated slimefun and CS-lib [as the official version has now been updated with your fixes and other things] now causes furnaces to not work with vanilla recipes. have you updated your copy since?

**Comment by andfont** [comment]
if I have it fixed among many other things, I have made many improvements and I have my own version of cs-lib because of problems etc. etc. I have everything working perfectly, the recipes also, I had many problems among many others as the record keeping of data storage was very bad that part! I have created separate programs that clean, delete all records obsoletos, also duplicate records etc etc, update regions of the world that no longer exist etc etc, many improvements of sensibletools, slimefun, exoticgarden etc etc. I currently have everything running perfectly xD

**Comment by andfont** [comment]
your problems are related to obsolescent registers, duplicates, registers of regions that no longer exist etc etc, slimefun creates a file called null.sfb where it keeps erroneously and duplicates these registers, I have it all solved because I have another plugin made by my cleaner , fix these records and perform a complete maintenance of all my plugins including slimefin, exotic, shopchest, restorechets etc etc. thanks to my plugin I never have problems with my plugins. slimefun can not perform this type of maintenance because it would slow down the server and could not work for that reason I have my plugin manreg.jar for my daily maintenance. I'm sorry but this kind of problems you will always have because you can never handle so many records in real time for a server. with the particles I have my own particle plugin that works perfectly with all my modified plugins. I also have for my improved holographies for electricspawner.jar etc. etc. I have it for my plugins, I do not think it will be useful for me at this time. but for me everything is working perfectly.

**Comment by ViperGriffin** [comment]
so how does one fix this plzz send help

**Comment by PrzemoVi** [comment]
You can just delete null.sfb file, that`s all.
I have line in my server startscript that deletes that file and everything is working fine.

It is happening when you shut down server without executing "stop" command.

**Comment by extral1f3** [comment]
Okay the altar isnt doing ANYTHING when i right click it with the rune even though the recipe is correct.

**Comment by WalshyDev** [comment]
@ViperGriffin @extral1f3 Are you still having issues on the latest build? https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#122
Should have been fixed a few days ago.
