### ISSUE TITLE
Just reporting an error i see, and altars dont work.

### ISSUE THREAD

**Issue by MothGirlMusic** [TheBusyBiscuit/Slimefun4#807]
## Description (Required)
i found an error on start up. doesn't seem to cause anything bad but is shown in console at times. also, altars don't work, but i assume its just being worked on and this issue is unrelated. honestly just trying to be a "good citizen" and reporting stuff that doesn't seem to be documented in known bugs or anythign.

## Server Log & evidence
![screen shot 2018-11-20 at 17 04 34](https://user-images.githubusercontent.com/1746550/48805882-9dddeb80-ece6-11e8-9326-aaf13e76a872.png)

## Environment (Required)
![screen shot 2018-11-20 at 17 07 42](https://user-images.githubusercontent.com/1746550/48805948-d7165b80-ece6-11e8-81a8-e8e0971a133c.png)
![screen shot 2018-11-20 at 17 08 21](https://user-images.githubusercontent.com/1746550/48805971-e695a480-ece6-11e8-80af-1617df64f808.png)

**Comment by TheBusyBiscuit** [comment]
Build 33 and later will now omit the Auto-Updater from freaking out when it sees a dev-build.
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#33

(In response to the error you saw)
