### ISSUE TITLE
1.13.2 its not the problem, worldguard is.

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#808]
Paper version git-Paper-455 (MC: 1.13.2)
(Implementing API version 1.13.2-R0.1-SNAPSHOT)
ProtocolLib v4.4.0
Slimefun v5, CS-CoreLib v5, 
WorldGuard v7.0.0-SNAPSHOT;1756-015f192
WorldEdit v7.0.0-SNAPSHOT;3943-e0dcd2e

Slimefun working PERFECT on 1.13.2 without WorldGuard
With Worldguard error: https://codeshare.io/arxORv

paper download: https://yivesmirror.com/downloads/paper
worldguard download: http://builds.enginehub.org/job/worldguard?branch=master
slimefun v5 + cs-corelib v5 download: https://drive.google.com/drive/folders/13rSlLxNKxH_hRLXsOVNwZtqzNO3bp8DS

worldguard config: https://codeshare.io/2BvOLy
slimefun config: https://codeshare.io/5vmPRW
`

**Comment by VoidAngel** [comment]
Looking at that error, it looks like your CS-Corelib is not up to date

**Comment by WindUnwaken** [comment]
worldguard7 changed their api in  build 1754
http://builds.enginehub.org/job/worldguard?branch=master

many plugins breaks after this build, such as griefprevention, so  tried old version of worldguard

**Comment by brooklynstarr** [comment]
I can confirm, not only does it break other plugins, but it's almost impossible to revert without completely restoring your server. I stopped downloading both worldguard and worldedit after this build.

**Comment by comonier** [comment]
> Looking at that error, it looks like your CS-Corelib is not up to date.
> Maybe try a CS-Corelib from the repo server :D
> https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/

VoidAngel, after I updated the latest version of - CS-CoreLib, everything worked perfectly. Thanks a lot for the tip, I'm using the latest build of the paper, the last build of worldguard and the last build of cs-corelib and everything is working. Thank you very much, I love you.
