### ISSUE TITLE
Updating plugin messed up everything

### ISSUE THREAD

**Issue by KabanFriends** [TheBusyBiscuit/Slimefun4#809]
I was using Slimefun v4.1.10 on my friend's server and I updated it to v4.1.15 (newest version)
and then everything messed up. For example, player backpacks, electric machines, and some other things like Ancient Altar went back to the normal minecraft blocks.

The biggest problem is player backpacks became glitchy.
Backpacks created in old Slimefun are now not able to be opened and when someone right click on it, their inventory completely messes up.

Everything is messed up but there are no errors.

## Proof of one of the glitches: Backpacks
Inventory before you open the glitched backpack:
![image](https://user-images.githubusercontent.com/45000995/48964981-56fa3980-eff7-11e8-884b-fef4437214f2.png)
Inventory after you right click the glitched backpack: (No backpack GUI appeared)
![image](https://user-images.githubusercontent.com/45000995/48964986-64afbf00-eff7-11e8-8a0d-9e8ab7e02b8d.png)

## Environment (Before updating)
CraftBukkit version: v1_12_R1
Spigot version: 1.12.2.-R0.1-SNAPSHOT (final build of 1.12.2 spigot)
Slimefun version: vv4.1.10
CS-CoreLib version: vv1.15.18

(Installed Addon) ExoticGarden v1.6.3

## Environment (After updating)
CraftBukkit version: v1_12_R1
Spigot version: 1.12.2.-R0.1-SNAPSHOT (final build of 1.12.2 spigot)
Slimefun version: vv4.1.15
CS-CoreLib version: vv1.15.18

(Installed Addon) ExoticGarden v1.6.3

**Comment by VoidAngel** [comment]
The latest version of Slimefun is meant for Minecraft 1.13.
You should go back to an older version.

**Comment by KabanFriends** [comment]
Okay :cry:
But I couldn't find anything that shows v4.1.15 is for 1.13.

**Comment by VoidAngel** [comment]
Ahhh xD no you are right. I didn’t read as well as I should have. Are you sure you don’t have any error logs? Not even at start up? That’s probably the only thing that would help at this point D:
