### ISSUE TITLE
Electric Ore Grinder Level I - F

### ISSUE THREAD

**Issue by locopabs** [TheBusyBiscuit/Slimefun4#817]
## Description (Required)
I built the electric ore grinder, it does not function as stated. It instead acts as a furnace and brings up the furnace interface. 
## Evidence / Proof (Required)
![electricoregrinder](https://user-images.githubusercontent.com/45866037/49982983-8086f080-ff25-11e8-8197-00e517d656e4.png)

## Environment (Required)
Minecraft 1.13.2
Not able to get other stuff from /sf versions, waiting to hear from server admin

**Comment by Gusted** [comment]
@locopabs Can you give the server logs maybe there is an error that caused this problem. 
PS: Is this still a bug or it already solved.
