### ISSUE TITLE
Slimefun Resource Pack

### ISSUE THREAD

**Issue by MothGirlMusic** [TheBusyBiscuit/Slimefun4#819]
Slimefun is epic, but is there a resource pack for it for 1.13.2? i know theres a bunch of like 1.12.x resource packs out there like https://www.planetminecraft.com/texture_pack/slimefun-texture-by-raulh22/ for instance.. but i dont know how to update resource packs.. i just hope by linking that here that if one of you guys can update it, it'd be a win-win for everyone in the little slimefun community here.

**Comment by DrOreo002** [comment]
Well updating resource pack to new version of mc should be easy, you can do it by ur own. U only have to change the texture location. Just find the changed texture, and then create a new blank resourcepack and rename those texture to match 1.13's item ID's

Btw for those who want to use it : I wouldn't recommend to use it, since the resource pack will also change other texture

**Comment by MothGirlMusic** [comment]
other texture? also thank you for explaining. i used something like this in 1.12.2 before.. it never rewrote other textures, it was really nice.. i don't have it anymore of course but i'm hoping this one is it and it works. anyway, thanks. i'll see what i can do on it

**Comment by DrOreo002** [comment]
Well I mean it will not be 100% custom Since it will change the item texture and it didn't make it a custom texture. So if you have a normal stick the texture will be changed to be the same as the grandma's walking stick and it would make the player confuse on choosing which are real stick or not

**Comment by MothGirlMusic** [comment]
so after reading up on how this works, that's incorrect.. slime fun adds data to the items which you can actually call and set the texture for those specific data points so it should be custom, just like how vanilla additions does it.. it uses diamond pickaxes for 8 different items and still has the original diamond pickaxe be itself. i promise you after doing some research on updating this pack, it should be custom 100% as long as slime fun's system for keeping track of items hasn't changed since 1.12

**Comment by DrOreo002** [comment]
Really?, well as far as I know resource pack can only be customized by using the durability feature on mc

**Comment by MothGirlMusic** [comment]
correct, but the durability can go like 32 digits after the decimal point. its really specific. but there is a second feature for damage and idk how it works, but its there.. and being really specific, i promise it can be custom. also damage = data... that's where all the data of an item is kept. [as far as I've researched in this hour or two]

**Comment by MothGirlMusic** [comment]
turns out we were both wrong. another feature can be name of the item "nbt.display.Name=ipattern:*\u00a76Smelter's Pickaxe*"

**Comment by DrOreo002** [comment]
But well it still require optifine huh?, if so then the only way to make a custom item texture is by the durability method. You can specify when the resource will visible by the item's durability

**Comment by MothGirlMusic** [comment]
it just doesn't work without optifine so its win-win no confusion because it just simply doesn't work. either way, i don't think i'll be talked out of wanting a resource pack for slimeufun.. most of my users are begging for it and tbh i want it as well. and most of the users already use optifine anyway.
