### ISSUE TITLE
Cargo Items Disappeared Completely

### ISSUE THREAD

**Issue by Sniper18075** [TheBusyBiscuit/Slimefun4#820]
## Description (Required)
Ever since I upgraded my server to 1.13.2 and the slimefun 1.13 builds, cargo items no longer show in the slimefun guide and I cannot give them with /sf give & /sf cheat. They still work on my dev server though that has the exact same versions of slimefun, cs-corelib, and paper installed.

## Evidence / Proof (Required)
Main server (Where it does not work): https://i.imgur.com/3aHNKqy.jpg
Dev server (Where it does work): https://i.imgur.com/kiyZBJf.png

## Environment (Required)
Minecraft: Paper-481 (1.13.2) (I have tried multiple versions for 1.13.2)
CS-CoreLib-29
Slimefun4-58
(The main server is running 2 addons; SlimeXpansion and ExoticGarden, but I have tested it without them and it still didn't work.)

**Comment by comonier** [comment]
@Sniper18075 
Update it from here [ new builds to 1.13.2 ]
https://thebusybiscuit.github.io/builds/

**Comment by Sniper18075** [comment]
@comonier I am on the latest builds from there and cargo items still do not show up in the guide or with “/sf give”. I have even tried regenerating my Slimefun folder completely and still no results.

**Comment by PrzemoVi** [comment]
Try to delete slimefun and cs-corelib config.yml and items.yml

**Comment by ItsSniper** [comment]
@PrzemoVi I have tried and had no luck. Even on the latest dev builds.

**Comment by PrzemoVi** [comment]
SF is inconpatybile with paper. Install latest Spigot.
