### ISSUE TITLE
Automated Crafting Chamber Not Working with Heads in Recipes

### ISSUE THREAD

**Issue by Mabit100** [TheBusyBiscuit/Slimefun4#822]
## Description (Required)
Automated Crafting Chamber Not Working with Heads in Recipes. It will make any thing as long as there is not a head in the recipe. For example you can make Small Energy Capacitor, but you cant then make medium as its uses the small capacitor in the recipe.  

This is the same for Uranium, Heating Coils, ElectroMagnets and all the others.

## Evidence / Proof (Required)
https://screenshot.net/lxvndiq
https://screenshot.net/qd4jrfg

## Environment (Required)
Minecraft version 1.13.2
Craftbukkit v1_13_R2
CS-Corelib V1.5.19
Slimefun V4.1.16

Addons.

Barrels v1.12
ChestTerminal v1.0
Slimefun Lucky Blocks v1.1

**Comment by MothGirlMusic** [comment]
where did you get chest terminal and sf luckyblocks from? they may be outdated which may cause your issue.

**Comment by EnderHater** [comment]
> where did you get chest terminal and sf luckyblocks from? they may be outdated which may cause your issue.

I have these installed but I'm using the latest 1.12x builds, and they work fine.

**Comment by MothGirlMusic** [comment]
i mean, if you want help i'd need a link to download and test them and see if i can reproduce your issue [which i can't as of right now so i wouldn't know how to help you] so even if you upload those to drop box and link the .zip here, i'd be able to help you more.

**Comment by Mabit100** [comment]
Thanks for the comments. 
I got the plugins from here, Yeah Chest terminal is not working at all, but lucky blocks works fine they just cant make them but they can open them.

If I knew where in the code it was looking at the recipe for the Autocrafter I may be able to fix it, but its strange that its the only machine that cant take in heads. It can output them just not input them.

**Comment by MothGirlMusic** [comment]
@Mabit100 this issue recently got upgraded to official bug. the devs know about it and are fixing it. i don't remember what the specific issue was this was posted in, but i'm sure if you search through issues, you can find it.. but yeah. confirmation this is a legit issue and its being looked at.

**Comment by Mabit100** [comment]
I have tried the build with no plugins too, and the same issue.

**Comment by comonier** [comment]
@MothGirlMusic 

https://thebusybiscuit.github.io/builds/

**Comment by Mabit100** [comment]
Is there a way you can release the code change that you made @comonier?  We have a lot of custom items in our jar file for our server and would rather just edit the code manually than install a new release.

**Comment by mrcoffee1026** [comment]
Issue still alive and well in these versions:
[15:32:04] [main/INFO]: [CHAT] Paper v1_13_R2
[15:32:04] [main/INFO]: [CHAT] 
[15:32:04] [main/INFO]: [CHAT] CS-CoreLib vDEV - 36 (git 2e140f82)
[15:32:04] [main/INFO]: [CHAT] Slimefun vDEV - 92 (git 4f05f804)
[15:32:04] [main/INFO]: [CHAT] 
[15:32:04] [main/INFO]: [CHAT] Installed Addons (2)
[15:32:04] [main/INFO]: [CHAT]  ExoticGarden vDEV - 8 (git 20923cd3)
[15:32:04] [main/INFO]: [CHAT]  SoulJars vDEV - 1 (git 3c1e410e)

**Comment by Acegaming1011** [comment]
I am also having an issue crafting Uranium in the automated crafting chambers

**Comment by BluGhostYT** [comment]
This issue needs to be flagged as a bug report

**Comment by TheBusyBiscuit** [comment]
Can someone confirm that this has been fixed in the latest build? 108
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by BluGhostYT** [comment]
I will check in a few moments

**Comment by BluGhostYT** [comment]
> Can someone confirm that this has been fixed in the latest build? 108
> https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

Can confirm, the latest commit by you has fixed issue #822

**Comment by Mabit100** [comment]
Can confirm this is working on 
Minecraft 1.14.2
SF - 109
Corelib - 51
