### ISSUE TITLE
SlimeFun

### ISSUE THREAD

**Issue by MoeMilord** [TheBusyBiscuit/Slimefun4#823]
https://pastebin.com/Lhp7juCM
Can someone Explain and tell me how to resolve these warns/errors? i'm running a 1.13.2 spigot server. not sure why would this occur since I'm running the latest Dev version of slimefun that should support 1.13.2
Also, in game, the only accessible command is /sf but! it's reading any arguments i'm typing in like, /sf give let's say.

**Comment by TheBusyBiscuit** [comment]
Update CS-CoreLib to a version that supports 1.13
