### ISSUE TITLE
Bug Head with Water_Bucket

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#825]
@TheBusyBiscuit 
## Description (Required)

Bug? Put a Head on the ground and remove it with a bucket of water.
**Possible solution, block the heads from dropping with water**

example  Eletromagnet

put it on the ground
take a water_bucket  on hand
put water on same block were the Eletromagnet is
and it will drop a CSCoreLib Head

## Server Log
there is no error in log

## Evidence / Proof (Required)
![image](https://user-images.githubusercontent.com/19571541/50805742-effcbf80-12da-11e9-8a75-d7dc415092ff.png)

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
Paper Build: 455 
Slimefun4 Build 65
CSCoreLibe Builde 33

**Comment by PrzemoVi** [comment]
Fixed: https://github.com/TheBusyBiscuit/Slimefun4/pull/829
