### ISSUE TITLE
Can't use enhanced Crafting table

### ISSUE THREAD

**Issue by Nektun** [TheBusyBiscuit/Slimefun4#826]
## Description (Required)
Whenever i build Enhanced CT it doesn't work. I get message that it couldn't recognize this pattern.

## Server Log
Nothing in logs shows up.

## Evidence / Proof (Required)
https://imgur.com/a/FPRW8xJ
## Environment (Required)
CraftBukkit v1_12_R1
CS-Corelib v1.5.18
Slimefun v4.1.15

**Comment by md5sha256** [comment]
The enhanced CT is functioning as just fine, you need to put in the correct slimefun items in the _dispense_r and right click to the _crafting table_ for it to 'work'. Please read the slimefun guide in game before posting this as an issue as it is not.

**Comment by BossGamesYT** [comment]
"
> The enhanced CT is functioning as just fine, you need to put in the correct slimefun items in the _dispense_r and right click to the _crafting table_ for it to 'work'. Please read the slimefun guide in game before posting this as an issue as it is not."

Now first of all you cant just say this without elaborating I have the exact same problem and what hes probably experiencing is the same as me what happends is that we cant even use it as soon as we right click the crafting table it just opens it up like a regular crafting table so please someone else please come up with an answer as well
