### ISSUE TITLE
Ancient Altar Recipes not being recognized

### ISSUE THREAD

**Issue by Lyreken** [TheBusyBiscuit/Slimefun4#827]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
Currently whenever trying to create anything in the ancient altar, everything works (putting items onto the altars ,etc) but when I try any recipes ( so far only been able to try blank rune) it says that its the incorrect recipe. On top of this, despite having everything unlocked, 5 items are still missing (which I suspect are the runes) Any idea how to fix this?

## Server Log
All Error files/messages need to be provided via http://pastebin.com/
No error messages

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://imgur.com/a/HYbc8yJ
## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
minecraft 1.13 version 4.1.16

**Comment by MothGirlMusic** [comment]
can you take a picture of where the runes are missing? they're supposed to be in magical items.. should be the top row if you're using chest inventory style guide book. and the runes are at the bottom of that page. theres 6 of them.

**Comment by MothGirlMusic** [comment]
also: CS-CoreLib is different versions than slimefun. you only listed "version 4.1.16" is this for slimefun or CS-corelib? and for whichever one it is, what is the version of the other? you can also say which build # you downloaded from the website.
