### ISSUE TITLE
user data savedata

### ISSUE THREAD

**Issue by Imothep80** [TheBusyBiscuit/Slimefun4#83]
## Description
We switch to a bigger server and change from single server to bungee. Now the problem is that i can't find any user saves.

So it would be helpful if you can tell me where i can get it and if you have planned to make an MySQL storage possible.

Tell me if i can help you.

## Server Log
Not possible. Because isn't an issue itselv.

## Evidence / Proof
-

## Environment
Latest Bungeecord with spigot 1.11

**Comment by NathanAdhitya** [comment]
I think it is on the root of the server jar (on my condition)
It's in a folder named data-storage.
