### ISSUE TITLE
Great Advertising

### ISSUE THREAD

**Issue by Aquafloew** [TheBusyBiscuit/Slimefun4#833]
## Description (Required)
Well you see, they clearly advertise on their page at https://minecraftservers.org/server/532541 that they require staff, yet when I join requesting literally to help and nothing more they call me scum etc. 
I didn't ask for permissions or a long term role as I expected a lack of trust and provided ideas to test building in a safe environment such as in a multiverse. However, they didn't care and were quite rude to a new player who was just asking to help out - following accordance with the advertisement requesting for staff. No, I am not staff hunting, I am simply requesting to help them by building a single structure for them. 

Also, yes I am well aware that this is not a bug but because of the lack of respect you show me, I don't give one.

## Server Log
None
## Evidence / Proof (Required)
Come on, you know who you are Mr. Owner :)

## Environment (Required)
N/A

**Comment by MothGirlMusic** [comment]
from all i can see the server doesn't even have slimefun on it. its a rainforest survival server.
