### ISSUE TITLE
Slimefun "/sf argument"

### ISSUE THREAD

**Issue by genessee596** [TheBusyBiscuit/Slimefun4#836]
## Description (Required)
Whenever I try to do any slimefun command, I get '/sf argument' in return. I have the most recent version of CS-CoreLib.

## Server Log
https://pastebin.com/PGtbsM2f

## Evidence / Proof (Required)
![image](https://user-images.githubusercontent.com/46986487/52165309-fb21f000-26cc-11e9-9153-d768fc3f4bd5.png)
![image](https://user-images.githubusercontent.com/46986487/52165312-037a2b00-26cd-11e9-88d1-1b52057f0530.png)

## Environment (Required)
I have tried using every Slimefun version from 65 to 41.15. All of them have similar results.
I am running Minecraft 1.13.2.
I am running CS-CoreLib 1.5.18.

**Comment by TheBusyBiscuit** [comment]
You are not using the Slimefun or CS-CoreLIb versions that support 1.13.X
