### ISSUE TITLE
A backpack bug!!!

### ISSUE THREAD

**Issue by Rothes** [TheBusyBiscuit/Slimefun4#838]
## Description (Required)
This bug works on every backpack!!
You open the backpack, click a item that you want to copy,then click at the backpack at the same time close the gui.Than you will get the two items and you lose your backpack!

## Server Log
nothing

## Evidence / Proof (Required)
VIDIO:
https://drive.google.com/file/d/1EqIpkKjJ1AsqKoMuyFD3brnFMJA11j7w/view?usp=sharing

## Environment (Required)
git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Slimefun v4.1.15
CS-CoreLib v1.5.18

**Comment by ChinaMeritocracy** [comment]
Amazing ! Thanks so much for your great job! Now I can cheat in my server!

**Comment by Rothes** [comment]
> Amazing ! Thanks so much for your great job! Now I can cheat in my server!

你牛逼啊

**Comment by ChinaMeritocracy** [comment]
> > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> 
> 你牛逼啊

妈个比服务器卡了 这个好像已经修复了

**Comment by ChinaMeritocracy** [comment]
> > > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> > 
> > 
> > 你牛逼啊
> 
> 妈个比服务器卡了 这个好像已经修复了

发这个bug的是国人，看bug的也是国人，佛了

**Comment by ChinaMeritocracy** [comment]
> > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> 
> 你牛逼啊

我不知道是服务器的什么限制还是插件本身的更新，我玩的时候打开背包和粘液机器的时候是不能拿取物品的

**Comment by ChinaMeritocracy** [comment]
> ## Description (Required)
> This bug works on every backpack!!
> You open the backpack, click a item that you want to copy,then click at the backpack at the same time close the gui.Than you will get the two items and you lose your backpack!
> 
> ## Server Log
> nothing
> 
> ## Evidence / Proof (Required)
> VIDIO:
> https://drive.google.com/file/d/1EqIpkKjJ1AsqKoMuyFD3brnFMJA11j7w/view?usp=sharing
> 
> ## Environment (Required)
> git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
> Slimefun v4.1.15
> CS-CoreLib v1.5 how to take an item by force in this situation.

> ## Description (Required)
> This bug works on every backpack!!
> You open the backpack, click a item that you want to copy,then click at the backpack at the same time close the gui.Than you will get the two items and you lose your backpack!
> 
> ## Server Log
> nothing
> 
> ## Evidence / Proof (Required)
> VIDIO:
> https://drive.google.com/file/d/1EqIpkKjJ1AsqKoMuyFD3brnFMJA11j7w/view?usp=sharing
> 
> ## Environment (Required)
> git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
> Slimefun v4.1.15
> CS-CoreLib v1.5.18

Tell me how to take an item by force in this situation plz

**Comment by ChinaMeritocracy** [comment]
Tell me how to take an item by force in this situation plz

**Comment by Rothes** [comment]
> > > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> > 
> > 
> > 你牛逼啊
> 
> 我不知道是服务器的什么限制还是插件本身的更新，我玩的时候打开背包和粘液机器的时候是不能拿取物品的

估计你服务器装了bugfixer

**Comment by ChinaMeritocracy** [comment]
> > > > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> > > 
> > > 
> > > 你牛逼啊
> > 
> > 
> > 我不知道是服务器的什么限制还是插件本身的更新，我玩的时候打开背包和粘液机器的时候是不能拿取物品的
> 
> 估计你服务器装了bugfixer

那怎么搞呢

**Comment by Rothes** [comment]
> > > > > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> > > > 
> > > > 
> > > > 你牛逼啊
> > > 
> > > 
> > > 我不知道是服务器的什么限制还是插件本身的更新，我玩的时候打开背包和粘液机器的时候是不能拿取物品的
> > 
> > 
> > 估计你服务器装了bugfixer
> 
> 那怎么搞呢

没见过你那种bugfixer的.我只知道mcbbs上有一个拿着指南书的禁止自动物品的bugfixer 但是那个插件也会造成某bug

**Comment by ChinaMeritocracy** [comment]
老哥求告知在我服猎人护身符已ban的情况下，开着机器GUI物品还拿不动，还有什么bug可以利用？猎人护身符没ban的时候我们服务器有人用潜影盒刷了一堆东西（背包叠加应该被别的插件修复了）   粘液科技实在是太肝了，这谁顶得住

**Comment by ChinaMeritocracy** [comment]
> > > > > > Amazing ! Thanks so much for your great job! Now I can cheat in my server!
> > > > > 
> > > > > 
> > > > > 你牛逼啊
> > > > 
> > > > 
> > > > 我不知道是服务器的什么限制还是插件本身的更新，我玩的时候打开背包和粘液机器的时候是不能拿取物品的
> > > 
> > > 
> > > 估计你服务器装了bugfixer
> > 
> > 
> > 那怎么搞呢
> 
> 没见过你那种bugfixer的.我只知道mcbbs上有一个拿着指南书的禁止移动物品的bugfixer 但是那个插件也会造成某bug

还是说说我对你发的这个bug的尝试，背包打开是潜影盒不能动，普通物品可以动，刷完之后显示是两个物品，但是再更新的时候刷的那个物品就回变回背包

**Comment by Rothes** [comment]
> 老哥求告知在我服猎人护身符已ban的情况下，开着机器GUI物品还拿不动，还有什么bug可以利用？猎人护身符没ban的时候我们服务器有人用潜影盒刷了一堆东西（背包叠加应该被别的插件修复了） 粘液科技实在是太肝了，这谁顶得住

你粘液科技什么版本

**Comment by TheBusyBiscuit** [comment]
Closed as this bug tracker is meant to be used in English.

**Comment by VanishTime** [comment]
老哥你们是不是该留个国内的联系方式比较好

**Comment by Rothes** [comment]
QQ449181985
