### ISSUE TITLE
Cannot craft Necrotic Skull using Magic Workbench.

### ISSUE THREAD

**Issue by Goldenphelix** [TheBusyBiscuit/Slimefun4#839]
## Description (Required)
Cannot craft Necrotic Skull using magic workbench.
When I create a magic workbench and put:
4x Tier 3 Magical Lumps in the corners. 
1x Wither Skeleton skull in the middle.
And then right click the crafting table,
Slimefun says "I could not recognise that pattern."

This appears also to be a similar issue linked to this:
https://github.com/TheBusyBiscuit/Slimefun4/issues/443

## Server Log
No errors in console.

## Evidence / Proof (Required)
![ec9d195d9d3531fcf1ca75025d004b0f](https://user-images.githubusercontent.com/31835303/52457904-13a87380-2bc1-11e9-892e-81f6cc1bc8b8.png)
![f85b9b40dd91cbdf315a5a0a4dde30b4](https://user-images.githubusercontent.com/31835303/52457907-15723700-2bc1-11e9-81af-09997ab0ca08.png)

## Environment (Required)
![008906b43cf72ee9ba81310fa8a2e794](https://user-images.githubusercontent.com/31835303/52457900-1014ec80-2bc1-11e9-83e4-6b531726fbb2.png)

**Comment by lolllammas** [comment]
Yep i have same problem

**Comment by John000708** [comment]
Just tested it and it is working just fine for me.

**Comment by Pajlis** [comment]
Not sure if it's just the server I play on but wither skull from beheading vs the vanilla one has a different ID but if you use the vanilla one it works but not the ones you get from beheading sword. They have same name ect but just different ID which is weird. Hope this helps.

**Comment by mrcoffee1026** [comment]
Yes the beheading sword skulls now have the added "durability:1" NBT tag added to the skull making it one you can't craft the recipes with.  Hopefully that can be removed from that drop without too much trouble.

**Comment by BluGhostYT** [comment]
@TheBusyBiscuit , the NBT tag given to wither skeleton skulls after those skeletons get killed by the sword of beheading needs to be removed, if possible.

**Comment by TheBusyBiscuit** [comment]
@BluGhostYT Don't just tag me...
I am not gonna fix this anyway but I will happily merge any Pull Requests.
