### ISSUE TITLE
Ancient Altar not working, cannot craft runes.

### ISSUE THREAD

**Issue by goldrat1** [TheBusyBiscuit/Slimefun4#840]
## Description (Required)
Whenever anyone tries to make a Rune (Blank, or any elemental), regardless of whether or not we have the correct items in the Ancient Altar + Pedestals, whenever we try to use the catalyst the message "Unknown Recipe! Use the correct recipe instead" comes up instead.
The pedestals work, they still accept items, but the recipes aren't recognised. See video.

## Server Log
Through the tests I've had, nothing is spat into the console, not when items are put in neither when the catalyst is added.

## Evidence / Proof (Required)
Video proof:
https://youtu.be/PL3nmSfNFjM
Try to ignore the sounds, it's just our resource pack :P
I've also tried with recipes for the Earth Rune and Fire Rune, same thing happens.

## Environment (Required)
NOTE: This server is in 1.13.2 and both of the plugins are for 1.12. Would that be the problem?
**CS-CoreLib v1.5.18
Slimefun v4.1.15**

P.S: Lyreken made a post about this but it went nowhere. I actually have access to console so I thought I'd post this anyway.
Any help is appreciated!

**Comment by Pajlis** [comment]
Have you tried the latest builds? Seems to work fine on my 1.13.2 server.
