### ISSUE TITLE
A  backpack bug!!!(now in English :)

### ISSUE THREAD

**Issue by ChinaMeritocracy** [TheBusyBiscuit/Slimefun4#844]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.

## Server Log
All Error files/messages need to be provided via http://pastebin.com/

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
@Rothes

**Comment by Rothes** [comment]
## Description (Required)
This bug works on every backpack!!
You open the backpack, click a item that you want to copy,then click at the backpack at the same time close the gui.Than you will get the two items and you lose your backpack!

## Server Log
nothing

## Evidence / Proof (Required)
VIDIO:
https://drive.google.com/file/d/1EqIpkKjJ1AsqKoMuyFD3brnFMJA11j7w/view?usp=sharing

## Environment (Required)
git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Slimefun v4.1.15
CS-CoreLib v1.5.18
