### ISSUE TITLE
Slimefun furnaces no longer apply luck to non-ore blocks

### ISSUE THREAD

**Issue by coldcode69** [TheBusyBiscuit/Slimefun4#85]
## Description
Furnaces such as the Reinforced furnace no longer increase the output for blocks like sand and clay. Ores like iron and gold still work correctly. Is this a bug or intentional change?

## Environment
cscorelib version 1.5.12
slimefun version 4.1.1
spigot version 1.11.2

**Comment by TheBusyBiscuit** [comment]
It has literally always been this way...
