### ISSUE TITLE
Slimefun furnaces no longer apply luck to non-ore blocks (with evidence)

### ISSUE THREAD

**Issue by coldcode69** [TheBusyBiscuit/Slimefun4#86]
## Description
Furnaces such as the "Enhanced Furnace" and "Reinforced Furnace" no longer increase the output for blocks like sand and clay. Ores like iron and gold still work correctly.

I would prefer it if the luck was applied to all items as it was before, since that is what previous users expect.

Apologies for not providing proof in the previous post. Something has definitely changed since updating to MC 1.11, please let me know if you need any more information.

I performed both tests using the latest slimefun (4.1.1) and cscorelib (1.5.12), all other plugins were removed before testing to ensure it's not a conflicting plugin. I also did a second test on a new server with a newly generated world and an empty "data-storage" folder, with the same results.

## Server Log
spigot 1.10.2
[latest-before.txt](https://github.com/TheBusyBiscuit/Slimefun4/files/685094/latest-before.txt)

spigot 1.11.2
[latest-after.txt](https://github.com/TheBusyBiscuit/Slimefun4/files/685095/latest-after.txt)

## Evidence / Proof
This is the behaviour previously experienced using:
spigot 1.10.2
cscorelib version 1.5.12
slimefun version 4.1.1
![before](https://cloud.githubusercontent.com/assets/24900603/21646252/537d6252-d28d-11e6-80da-301c079e5a66.gif)
Anything that can be used in a furnace had luck applied to it. For example, sand, clay, raw fish, etc.

This is how they work now using:
spigot 1.11.2
cscorelib version 1.5.12
slimefun version 4.1.1
![after](https://cloud.githubusercontent.com/assets/24900603/21646257/56b1f9e2-d28d-11e6-91bb-da27de75cd5c.gif)

**Comment by TheBusyBiscuit** [comment]
Well, since the only difference is your spigot version, this is obviously a Spigot Bug, not caused by Slimefun.
Although this seems very very very weird to me ?.?

Anyway, it is supposed to only work for Ores.
But if you want, this could be added as an option.

**Comment by coldcode69** [comment]
I agree it's very strange. Although if it was always meant to be this way then it appears to be "correct" with 1.11. However, adding an option to use the "broken" behaviour would be very much appreciated, as this is what my players are used to.

**Comment by NathanAdhitya** [comment]
ooh, It happens on the server I play which uses PaperSpigot with MC 1.10 too.
I never knew this was a bug. but It'll be great if there' a config for that.

**Comment by Andromeda11** [comment]
Any progress on the matter? It would be reeally nice, if we could config the furnaces to smelt more from non-ores too.

**Comment by mrcoffee1026** [comment]
This problem is larger than reported: using a hopper on output COMPLETELY DISABLES the 'luck' factor of the ovens.  Also, prior to the 1.11 release of minecraft, ingot to ore ratio was closer to 3:1.  Even without a hopper, the ovens currently are incapable of even 2:1.
