### ISSUE TITLE
Discussion: Multi Tools modes

### ISSUE THREAD

**Issue by SoSeDiK** [TheBusyBiscuit/Slimefun4#861]
## "The problem"
I was looking through the code and noticed that the Carbonado Multi Tool has one additional function *(Gold Pane)* but it's not available in game. So I went through code to figure this out.
## The reason
The issue lays in the ItemListener when checking the tool. Current code is written that so it always think that the Tier I Multi Tool was used.
## Tries of fixing
If you'll just fix the tool identifying it won't work.
First things first, you'll get the ArrayOutOfBounds exception if you'll choose the 4th mode and use a Multi Tool that has only 3 of them.
Not a big deal? Yes, you can make the additional check and just reset the mode to the first one.
But if you'll think, it's really bad for the future development.
Firstly, imagine you chose the 4th mode and used a tool with 3 modes. Now you want to return to the first tool. It was reset and you have to choose mode again. It's annoying, isn't it?
Secondly, imagine an addon with two tools, modes count doesn't matter. What if they have completely different modes in the same spot? It's very sophisticated and hard to use/remember current mode.
## Proposal
I propose removing the multi tool variable and use the item's lore instead. In this case we will be able to easily see the mode used by tool and have many of them with different modes, so you can switch between them.
## So what's the deal?
I would like to see what does the community think.
Should we implement this? Or maybe you have a better idea?
The only bad thing I see about this is that every existing multi tool will break. We can provide a code which will replace the old ones with the new ones when used like it was already done with Slimefun guide. But in this case we keep adding more and more unnecessary code making Slimefun more complicated.

### Afterwords
I also recommend you to read my comment there: #332. Would like to hear your opinion. Thanks.

**Comment by EnderSlime123** [comment]
@TheBusyBiscuit isn't gonna look at this since Slimefun is pretty much dead.

**Comment by SoSeDiK** [comment]
Who knows :P
Discord server was opened recently *(see README.md for a link)*.
Maybe there are still hopes.

**Comment by EnderSlime123** [comment]
> Who knows :P
> Discord server was opened recently _(see README.md for a link)_.
> Maybe there are still hopes.

Well @TheBusyBiscuit hates everything I say apperently so I'm not joining.

**Comment by TheBusyBiscuit** [comment]
Closing this since there hasn't been anything since over a month.
For the future: Let's shift such discussions to Discord, I think people will be more active on there.
