### ISSUE TITLE
Please add compilation tutorial

### ISSUE THREAD

**Issue by Atomix23** [TheBusyBiscuit/Slimefun4#878]
There is no compilation tutorial anywhere, so could you please add one to the Wiki or anywhere for Eclipse or IntelliJ, etc. That would be really helpful, thanks.

**Comment by xH3LLRAIZ3Rx** [comment]
Just google on how to build maven projects in Eclipse

**Comment by TheBusyBiscuit** [comment]
Install Maven.
Download the project.
Run "mvn package"

Or you can google "maven in (Eclipse/Intellij/etc...)"
