### ISSUE TITLE
Items not working properly. Other functions working properly though.

### ISSUE THREAD

**Issue by GitHub-Rusti** [TheBusyBiscuit/Slimefun4#883]
## Description (Required)
Not sure what could have caused this, but strangely some items on my server are not properly working such as the explosive pickaxe. It is only acting like a regular pickaxe and the cool explosion ability is not working.

## Server Log
https://pastebin.com/nyZh3xag

## Evidence / Proof (Required)
https://imgur.com/1CPWj15

## Environment (Required)
Minecraft 1.13.2
CraftBukkit v1_13_R2
CS-CoreLib vDEV - 36 
Slimefun vDEV - 86(87 did not work either)

Any help would be appreciated!

**Comment by SoSeDiK** [comment]
CS-CoreLib supports Factions and FactionsUUID. SavageFactions should work as well.
You use FactionsOne which may have changed API.
I suggest you to try one of them as FactionsOne is no longer maintaned by its author and there is no reason for adding support for it.
If error will remain I'll look into it.

**Comment by GitHub-Rusti** [comment]
Okay, thank you very much! Was very confused what was causing the issue and you definitely just cleared the air for me :)

I removed FactionsOne and everything is working again!
