### ISSUE TITLE
Cargo nodes increase channel ID button doesn't work

### ISSUE THREAD

**Issue by VersionOmega** [TheBusyBiscuit/Slimefun4#888]
Running Slimefun Dev - 89
CSCoreLib - 36

When inside of an input node or output, the "Increase Channel ID by 1" head doesn't increase the channel ID by one.

Note: This doesn't exist for the advanced output nodes

**Comment by mrcoffee1026** [comment]
Verified:
Spigot AND Paper v1_13_R2
Slimefun vDev - 91
CSCoreLib - 36
Exotic Garden vDev 8
