### ISSUE TITLE
Nuclear Reactor keeps consuming fuel when no machine is running on the network

### ISSUE THREAD

**Issue by sarhatabaot** [TheBusyBiscuit/Slimefun4#893]
## Description (Required)
Nuclear reactor will keep consuming fuel and generating energy in energy mode even if a machine isn't running in it's network.
This could lead to energy regulators corrupting as described in #892 

## Evidence / Proof (Required)
https://youtu.be/-yfTgMrNayY

## Environment (Required)
  + Spigot 1.13.2-R0.1-SNAPSHOT
  + CS-CoreLib DEV - 36 (git 2e140f82)
  + Slimefun DEV - 91 (git 9436c3d6)
  + Essentials 2.16.1.0
  + SlimefunOres 1.4.7
  + EssentialsSpawn 2.16.1.0
  + EssentialsChat 2.16.1.0
  + SlimefunLuckyBlocks 1.1
  + ExoticGarden DEV - 8 (git 20923cd3)

**Comment by Mr-Kaboose** [comment]
Same issue has been open for a year #666
