### ISSUE TITLE
Backpacks and Portable Crafter "place" on ground

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#895]
## Description (Required)
If you use a Portable Crafter, that head item is placed on the ground while you are using it, and you will need to then mine up the item to retrieve it to your inventory when done.

This happens when using Backpacks also - fortunately you do not have to mine those back up after... unfortunately this is not simply an additional delay to opening the item... if LWC is set to protect "player_head" and "player_wall_head", then it will place protection on the empty space where the backpack used to be each time you use one... and since there is no physical block there it requires someone with administrative permissions to remove the locked block.    

## Server Log
Neither event is creating errors or any activity in the log that I can tell.

## Evidence / Proof (Required)
Portable crafter on the ground after using:
![2019-04-17_14 40 52](https://user-images.githubusercontent.com/3322491/56312749-de6b5500-611e-11e9-8bac-4140e185dd91.png)
Here in vid form:
https://youtu.be/MPo7f1t5Kss

The backpacks don't need mined afterwards but with the interaction the item gets from other plugins, it would be better for this item to not be placed at all.

## Environment (Required)
[14:41:31] [main/INFO]: [CHAT] Paper v1_13_R2
[14:41:31] [main/INFO]: [CHAT] 
[14:41:31] [main/INFO]: [CHAT] CS-CoreLib vDEV - 36 (git 2e140f82)
[14:41:31] [main/INFO]: [CHAT] Slimefun vDEV - 92 (git 4f05f804)
[14:41:31] [main/INFO]: [CHAT] 
[14:41:31] [main/INFO]: [CHAT] Installed Addons (2)
[14:41:31] [main/INFO]: [CHAT]  ExoticGarden vDEV - 8 (git 20923cd3)
[14:41:31] [main/INFO]: [CHAT]  SoulJars vDEV - 1 (git 3c1e410e)

**Comment by TheBusyBiscuit** [comment]
This is completely wrong.
The block placement happens on the client, not the server, it cannot 'lag out' like that.
Also, NBT is something entirely different and not used for identifying anything.

**Comment by mrcoffee1026** [comment]
Updated text to include video and better explain what the problem with backpacks are, it is more than just a concern.
