### ISSUE TITLE
Canceling an Ancient Altar recipe that has started produces strange results

### ISSUE THREAD

**Issue by coldcode69** [TheBusyBiscuit/Slimefun4#90]
## Description
If you place the ingredients for an Ancient Altar recipe, start it by using the middle ingredient on the enchanting table and then right click one of the items on a pedestal to get it back, it will do one of the following:

Scenario 1 - Removing an item not long after starting it
Result: The process will stop and any items that have already been consumed will be lost.

Scenario 2 - Removing an item near the end
Result: The process will continue until the end, at which point all ingredients will be returned but they will be renamed to "ALTAR Probe - 39482719573823458". They will then be completely unusable in future recipes.

It would probably be best if it wasn't possible to cancel a recipe in progress to avoid strange behaviours. If that's not possible then making both scenarios return all items as they were before, without the name changed would also work.

## Evidence / Proof
http://i.imgur.com/pGikq6e.gifv

## Environment
spigot 1.11.2
cscorelib version 1.5.12
slimefun version 4.1.1

**Comment by TheBusyBiscuit** [comment]
Fixed in the next Update
