### ISSUE TITLE
ExoticGarden Suggestion: Allow for RWG(RealisticWorldGenerator) support.

### ISSUE THREAD

**Issue by EnderSlime123** [TheBusyBiscuit/Slimefun4#903]
Allow plants/trees to spawn in a RWG world via a config option of some sort.

I have tried asking the developer of RWG about this, but they say I must convert the schematic files to the file type they use for their system, and that they wouldn't be able to do so. So, I'm simply asking here. If anyone's willing to do a PR to do so.

ExoticGarden could achieve this by simply having a RWG_Schematics folder created if the config option is set to true, with all the converted schematic files inside it.

**Comment by TheBusyBiscuit** [comment]
1. This is a Bug Tracker, not a Suggestions drop box, you should rather post Suggestions on a designated discord server, not on the Bug Tracker.
2. This is Slimefun... Not ExoticGarden...
