### ISSUE TITLE
Slimefun Error

### ISSUE THREAD

**Issue by lukemango** [TheBusyBiscuit/Slimefun4#910]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
The server freezes every 10 minutes for 15 seconds then kicks everyone

## Server Log
All Error files/messages need to be provided via http://pastebin.com/
https://pastebin.com/BP8tDSTR
## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
CS-CoreLib: DEV - 36
Slimefun: DEV - 95

**Comment by MothGirlMusic** [comment]
For anything having to do with freezing, use timings.

When it lags, do:
/timings on
Wait a moment, then:
/timings paste

And paste that link here. 

———
73, KC1KSG

**Comment by TheBusyBiscuit** [comment]
The pastebin you provided does not contain an error message, that is just the current stack of the process.
If you are sure that it's Slimefun, try doing /sf timings and see what machines cause it.

**Comment by lukemango** [comment]
Done that,
Electric Ore Grinders
Energy Regulators
Recycler

**Comment by TheBusyBiscuit** [comment]
Well what does it say... Like what are the timings for example...?
