### ISSUE TITLE
Elevators Aren't Working Slimefun #99

### ISSUE THREAD

**Issue by A-Duo** [TheBusyBiscuit/Slimefun4#914]
## Description (Required)
This glitch causes you to obtain an elevator book item every time instead of opening the menu, the problem with this is that you can never update the list of elevators and can only teleport to any floor besides the first one you stepped on. Upon stepping on the elevator plate after losing the original book it will do nothing.

## Reproduce (Required)
place to elevator plates at the same x and z coordinates differing the y then simply step on one of the plates

## Expected behavior (Required)
To auto open the elevator book and move between floors then disappear reaching the next floor

## Server Log / Error Report
I do not have access to this

## Environment (Required)
[Sun, 19. May 2019 21:31:11 PDT INFO] CraftBukkit v1_14_R1
[Sun, 19. May 2019 21:31:11 PDT INFO] CS-CoreLib vv1.6
[Sun, 19. May 2019 21:31:11 PDT INFO] Slimefun vDEV - 99 (git 6df3f8df)
[Sun, 19. May 2019 21:31:11 PDT INFO] Installed Addons (0)

**Comment by TheBusyBiscuit** [comment]
Try again with CS-CoreLib build #49 and see if that works.
