### ISSUE TITLE
Error with cargo section

### ISSUE THREAD

**Issue by zThundy** [TheBusyBiscuit/Slimefun4#919]
## Description (Required)
Everything is working, but no particles for cargo managerr are shown and errors poups up.

## Steps to reproduce the Issue (Required)
No screen, just the error

## Expected behavior (Required)
Ehm? xD

## Server Log / Error Report
https://pastebin.com/ZzUHKPwj

## Environment (Required)
Obviusly it's a minor thing, but i think is good to report.

 - Minecraft Version:
 - Slimefun Version: Slimefun4 - #52
 - CS-CoreLib Version: CS-CoreLib vDEV - 47 (git 59557499)

**Comment by TheBusyBiscuit** [comment]
You are using an outdated Version of Slimefun
and your CS-CoreLib version is "too up-to-date", they're not compatible.
Update both or use CS-CoreLib build 33, it may work with your outdated Slimefun build.
