### ISSUE TITLE
Place-able Portable Crafter.

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/Slimefun4#923]
## Description (Required)

The Portable Crafter item was changed to a skull, but it can be placed.

## Steps to reproduce the Issue (Required)

Rightclick the ground or a wall with the Portable Crafter. Even though the GUI opens, it still places itself.

## Expected behavior (Required)

The Portable Crafter not placing itself.

## Server Log / Error Report

N/A

## Environment (Required)

- Minecraft Version:
 - Slimefun Version:
 - CS-CoreLib Version: 
![2019-06-01_21 07 30](https://user-images.githubusercontent.com/51277766/58756620-4ac4cc80-84b1-11e9-9fac-efa78bf66189.png)

Also still noticing that the color codes in ChestTerminal are still bugged. No errors.

**Comment by TheBusyBiscuit** [comment]
This has already been fixed in later Builds.

**Comment by EnderBro123** [comment]
> This has already been fixed in later Builds.

Oh. I'm using the latest 1.13.2 build.
