### ISSUE TITLE
Please help me fix this!

### ISSUE THREAD

**Issue by NinhXuanHai** [TheBusyBiscuit/Slimefun4#926]
## Description (Required)
 Ancient altar error

## Steps to reproduce the Issue (Required)
  ![image](https://user-images.githubusercontent.com/51499618/59141007-2aa37a80-8995-11e9-8068-d50d526c4230.png)

## Expected behavior (Required)
 The ancient altar does not work, meaning that items made from it will not happen!

## Server Log / Error Report
--> https://pastebin.com/MmkSRzZL
## Environment (Required)
  ![image](https://user-images.githubusercontent.com/51499618/59141079-583cf380-8996-11e9-8dad-d9c8fcf0d1a2.png)

 - Minecraft Version: 1.10.2
 - Slimefun Version: 4.1.15
 - CS-CoreLib Version: Dev 50

**Comment by TheBusyBiscuit** [comment]
Your CS-CoreLib Version does not support MC 1.10

Build 33 might work
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#33
