### ISSUE TITLE
Cargo & Energy Regulator Holograms Upside Down

### ISSUE THREAD

**Issue by Mabit100** [TheBusyBiscuit/Slimefun4#928]
## Description (Required)

The holograms for Cargo Managers and Energy Regulators are updside down
## Steps to reproduce the Issue (Required)

![image](https://user-images.githubusercontent.com/21134218/59152838-3bf79000-8a44-11e9-83b4-faff0e1a1577.png)

## Expected behavior (Required)

Holograms above

## Environment (Required)

Minecraft Version: V1.14.2 R0.1.20190527
CS-CoreLib Version: CS-CoreLib-51.jar
QuickMarket Version: QuickMarket-3.jar
Slimefun Version: Slimefun4-106.jar

**Comment by BluGhostYT** [comment]
Opened pull requests for the fix to that. #940 and #941
