### ISSUE TITLE
 Dupe bug/Changing Drop Bug

### ISSUE THREAD

**Issue by realchessx** [TheBusyBiscuit/Slimefun4#929]
Description: 
- Dupe bug/Changing Drop Bug
- Already reported it to quickshop plugin dev,
    he said to contact slimefun dev.  
<img width="204" alt="Screenshot_1" src="https://user-images.githubusercontent.com/4650217/59158960-f34bdf80-8af4-11e9-9350-9f829ab92272.png">

 http://prntscr.com/nzj2sr

Plugin version: 
  - Quickshop Reremake latest
     https://www.spigotmc.org/resources/quickshop-reremake-now-support-1-14.62575/
  - Slimefun build -107 
  - Cscore  build -51

Server: 
  - 1.14.2 paper-70

Video Link: 
https://youtu.be/Cebn5JMB-_4

Steps:
  1. place a new chest
  2. left click elytra on chest
  3. dont type item price
  4. destroy/mine the chest
  5. it dont return the chest
  6. it return elytra instead of chest

**Comment by NathanAdhitya** [comment]
Successfully reproduced with the latest Quickshop Reremake as well. Seems to be related with #958 as items mentioned there can be duplicated with the same method. Will look further.
