### ISSUE TITLE
Improved Digital Miners (AContainer)

### ISSUE THREAD

**Issue by NathanAdhitya** [TheBusyBiscuit/Slimefun4#93]
Here's an idea,
I was thinking about Digital Miners, for some reason people prefrer the **normal** more than advanced due to Exotic Garden needing their **raw ore form**.

Would it be great, if you are able to change modes by right clicking the hopper on a Advanced Digital Miner? Ex Modes: Fortune (For fortune-able ores?), Silk Touch, and Grinded? (For ores that are possible to be grinded, but fortune applies to non-grindable ores)

Leave a like, if you'd agree with this idea.

**Comment by TheBusyBiscuit** [comment]
It would make more sense (and is 1000 times more easy to implement) if the Digital Miner was moved to being an AContainer instead.

**Comment by NathanAdhitya** [comment]
Agreed.

**Comment by John000708** [comment]
I'll start working on it now

**Comment by Poslovitch** [comment]
Is it done?

**Comment by comfuzzled** [comment]
This is a great idea.
