### ISSUE TITLE
Slimefun Crashing Server

### ISSUE THREAD

**Issue by lukemango** [TheBusyBiscuit/Slimefun4#939]
## Description (Required)

Server crashing randomly
## Steps to reproduce the Issue (Required)

I honestly have no idea, but it happens every 2 hours ish.
## Expected behavior (Required)

Not to crash
## Server Log / Error Report
 https://pastebin.com/YVQvAt7V

## Environment (Required)

 - Minecraft Version: git-Paper-83
 - Slimefun Version: DEV - 109
 - CS-CoreLib Version: DEV - 51

**Comment by WalshyDev** [comment]
Not a crash just a normal exception, does your server **actually** crash or just an error being thrown?

**Comment by lukemango** [comment]
It does crash yes.

**Comment by WalshyDev** [comment]
Post the entire server log

**Comment by lukemango** [comment]
in #947
