### ISSUE TITLE
After some time server is freezing.

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/Slimefun4#945]
CS-CoreLib-60.jar
ExoticGarden-11.jar
Slimefun4-121.jar
git-Spigot-df0eb25-da071ec (MC: 1.14.2)
Freezing Log.
https://paste.ofcode.org/jNBKsV7HzakFWBpih5E2Lq
Full Log: https://paste.ofcode.org/9zacX2K79GFhdkp2nGpq2t

**Comment by TheBusyBiscuit** [comment]
Duplicate of https://github.com/TheBusyBiscuit/ExoticGarden/issues/63
This is also not Slimefun-related and does not belong here...
Also, follow the Ticket format...

**Comment by comonier** [comment]
First Freezing log Line 25
22.06 11:56:12 [Server] Spigot Watchdog Thread/ERROR me.mrCookieSlime.ExoticGarden.PlantsListener.onGenerate(PlantsListener.java:193)
Shoul i try without Exotic Garden ?
