### ISSUE TITLE
Items Resetting 

### ISSUE THREAD

**Issue by xXTrixieXx** [TheBusyBiscuit/Slimefun4#949]
## Description (Required)
When I load in Slimefun with a clean config, meaning I completely delete the folder and reload from fresh, it does fine. But as soon as the server is restarted all the data from the current items in slimefun that was placed, or used gets wiped. The manual still works, I can still do /sf cheat, but all items are not working after a restart. 

## Steps to reproduce the Issue (Required)
When server restarts 

## Expected behavior (Required)
I expected it to save the data from the slimefun items and not reset them. It appears that the block data isnt saving. 

## Server Log / Error Report

https://pastebin.com/MB0WEpKP

I have tried the newest with core, but the repo site says to use this version?

 - Minecraft Version:Spigot1.14.2
 - Slimefun Version:Slimefun4-121.jar
 - CS-CoreLib Version:CS-CoreLib-44.jar

**Comment by BluGhostYT** [comment]
Just saying, always use the LATEST build for CS-CoreLib

**Comment by xXTrixieXx** [comment]
I swapped it and same issue unfortunately. ;(
23.06 12:36:55 [Server] Spigot Watchdog Thread/INFO Disabling Slimefun vDEV - 121 (git 8f173ea7) 23.06 12:36:55 [Server] Spigot Watchdog Thread/WARN Could not save Slimefun Blocks for World "FunnyFarm1.14" 23.06 12:36:55 [Server] Spigot Watchdog Thread/WARN Could not save Slimefun Blocks for World "FunnyFarm1.14_nether" 23.06 12:36:55 [Server] Spigot Watchdog Thread/WARN Could not save Slimefun Blocks for World "FunnyFarm1.14_the_end" 23.06 12:36:55 [Server] Spigot Watchdog Thread/WARN Could not save Slimefun Blocks for World "Mining" 23.06 12:36:55 [Server] Spigot Watchdog Thread/WARN Could not save Slimefun Blocks for World "Spawn"

**Comment by BluGhostYT** [comment]
Have you deleted the Data-Storage folder?

**Comment by xXTrixieXx** [comment]
where would that be? i deleted the entire slimefun folder it generates.

**Comment by BluGhostYT** [comment]
> where would that be? i deleted the entire slimefun folder it generates.

It would be in the root folder for the server.
