### ISSUE TITLE
Problems with 1.13.2 dev build

### ISSUE THREAD

**Issue by SpiDrone** [TheBusyBiscuit/Slimefun4#952]
## Description (Required)
The portable crafter can be placed on the ground.

The Saw Mill only works on oak, when it normally works on all logs.

## Steps to reproduce the Issue (Required)
Use the portable crafter while looking at the ground where a block could be placed.

Try and saw mill some spruce.
## Expected behavior (Required)
It not to be placed.

8 spruce instead of 4.
## Server Log / Error Report
No error, I believe it's with the plugin itself.

## Environment (Required)

 - Minecraft Version: 1.13.2
 - Slimefun Version: vDEV - 95 (git 15555872)
 - CS-CoreLib Version: vv1.6.1

**Comment by TheBusyBiscuit** [comment]
The Portable Crafter Issue has already been fixed.
Later builds (which include the fix0 are for MC 1.14 only though.
