### ISSUE TITLE
Infinite books with /sf guide

### ISSUE THREAD

**Issue by Harveyplays02** [TheBusyBiscuit/Slimefun4#953]
## Description (Required)
Players can get infinite books using only /sf guide and a grindstone.

## Steps to reproduce the Issue (Required)
1. Get a slimefun guide with /sf guide
2. Put book inside of grindstone
3. Get book out of grindstone, unenchanted.
4. Book works as normal, such as working in crafting, enchanting tables, etc. 

## Expected behavior (Required)
Book should not be disenchantable.

## Environment (Required)
![image](https://user-images.githubusercontent.com/40532510/60628301-bbc90e00-9de8-11e9-9d0e-40823eb25171.png)

 - Minecraft Version: 1.14.3
 - Slimefun Version: vDEV 123
 - CS-CoreLib Version: vDEV 62

**Comment by BluGhostYT** [comment]
Bump to this issue
