### ISSUE TITLE
BlockBreakEvent using an Explosive Pickaxe

### ISSUE THREAD

**Issue by ItsSynchro** [TheBusyBiscuit/Slimefun4#954]
## Description (Required)
Mined machines using an Explosive Pickaxe

## Steps to reproduce the Issue (Required)
I placed a ton of machines next to each other and began breaking them with an Explosive Pickaxe

## Server Log / Error Report
https://pastebin.com/qTafKeeb

## Environment (Required)

 - Minecraft Version: Paper v1.14.R1
 - Slimefun Version: vDEV - 123 (git 4fe466c2)
 - CS-CoreLib Version: vDEV - 62 (git 8b1949df)

**Comment by TheBusyBiscuit** [comment]
The Paste has been deleted...
