### ISSUE TITLE
Stuck in the settings

### ISSUE THREAD

**Issue by oneCrazychild101** [TheBusyBiscuit/Slimefun4#955]
I don't know how but im stuck in the settings for the slimefun gui

No idea, i went afk with it open and when i came back is was stuck in settings.

I expected it to not be stuck in settings for some random reason?

Just standing near Bamboo and sweet berries when i went afk.

 - Minecraft Version:1.14.3
 - Slimefun Version:122 (git 64fca6ed)
 - CS-CoreLib Version:Not sure.

**Comment by TheBusyBiscuit** [comment]
Well, define "stuck"... A Video would be best...
