### ISSUE TITLE
Many slimefun items being duplicated by breaking grass with them

### ISSUE THREAD

**Issue by SebasTheNinja** [TheBusyBiscuit/Slimefun4#958]
## Description (Required)
Breaking grass with many slimefun items (like Beheading Sword, 24-Carat gold block, sifted ore, cheese and probably many others) will drop a duplicate of the item in hand instead of nothing.

## Steps to reproduce the Issue (Required)
1. Grab a slimefun item (example, 24-Carat Gold Block)
2. Break Grass with the item you chose
3. Infinite items! (In this case, would be infinite 24-Carat golden blocks)

## Expected behavior (Required)
Grass should not duplicate slimefun items when broken with them

## Server Log / Error Report
There are no errors being reported by the server

## Environment (Required)
![1](https://user-images.githubusercontent.com/32151264/60918340-7afa4a80-a269-11e9-912a-ce07e7aa8531.png)

 - Minecraft Version: 1.14.2
 - Slimefun Version: vDEV - 124 (git 6389a570)
 - CS-CoreLib Version: vv1.6.1

**Comment by NathanAdhitya** [comment]
Cannot reproduce, can you please post a video of it happening and your other installed plugins as well? Thanks.

**Comment by Yukyxy** [comment]
https://www.youtube.com/watch?v=gzeCIPiKfpg&feature=youtu.be

**Comment by NathanAdhitya** [comment]
Are you using any other plugins other than Slimefun and CSCoreLib?

**Comment by Yukyxy** [comment]
lot of whose exotic garden (but i tried to disable it, it's same)...
but i noticed that you have to do a right click before breaking the grass with the item.

**Comment by NathanAdhitya** [comment]
I seem to still cannot reproduce, anyone else has luck reproducing this ? :/

**Comment by SebasTheNinja** [comment]
I recorded it. An URL will be posted in a couple minutes. In my case i don't have to right click to dupe, just break the grass with it

**Comment by Yukyxy** [comment]
if you could try on Spigot-5e4e7f3-5f88938 (MC: 1.14.3)

**Comment by SebasTheNinja** [comment]
WIll take a while to download git and update it, but i will do it

**Comment by SebasTheNinja** [comment]
https://youtu.be/-4JbQvzRaWU

Here's my video.Minecraft Version 1.14.2

**Comment by Yukyxy** [comment]
i have the plugins placeitemsontheground and brewery in common with @SebasTheNinja

**Comment by Yukyxy** [comment]
it's placeitemsontheground the problem

**Comment by SebasTheNinja** [comment]
That's sad

**Comment by Yukyxy** [comment]
I have desactivate it and now we have no duplication with the grass

**Comment by NathanAdhitya** [comment]
Will look further as it seems to have dupe issues with other plugins as well.

**Comment by xH3LLRAIZ3Rx** [comment]
Cannot reproduce this in 1.14.4
