### ISSUE TITLE
Digital miner transform 2 of its 4 iron blocks into solar panels when broken

### ISSUE THREAD

**Issue by SebasTheNinja** [TheBusyBiscuit/Slimefun4#959]
## Description (Required)
Every time you break a Digital Miner, the 2 above iron blocks, of the 4 that are used to create the miner, will transform into Solar Panels

## Steps to reproduce the Issue (Required)

1. Create the Digital Miner multiblock
2. Break the 2 iron blocks above
3. 2 extra solar panels at the cost of 2 iron blocks. 

![1](https://user-images.githubusercontent.com/32151264/60919122-530be680-a26b-11e9-9e77-97292171a7b1.png)
![2](https://user-images.githubusercontent.com/32151264/60919126-556e4080-a26b-11e9-9169-7fe33596cc05.png)

## Expected behavior (Required)
Iron blocks should not transform into Solar Panels.

## Server Log / Error Report
The server shows no errors

## Environment (Required)
![3](https://user-images.githubusercontent.com/32151264/60919214-936b6480-a26b-11e9-9386-aa3f79a172dd.png)

 - Minecraft Version: 1.14.2
 - Slimefun Version: vDEV - 124 (git6389a570)
 - CS-CoreLib Version: vv1.6.1

**Comment by dniym** [comment]
Can not reproduce as of sf 147
