### ISSUE TITLE
Player able to Take Items Out of SF Guide

### ISSUE THREAD

**Issue by GeMiniXCape** [TheBusyBiscuit/Slimefun4#961]
## Description (Required)

When a player goes to anything that doesn't have a recipe, they can take it out of the inventory. This included barrier blocks or any item that doesn't have a recipe (ex gravel)
## Steps to reproduce the Issue (Required)

[https://i.imgur.com/0sznyZq.png](url)

- Go to an item that doesn't have a crafting recipe
- drag item out

## Expected behavior (Required)

Have it go right back into the inventory and not have players take it.

## Server Log / Error Report
  https://pastebin.com/p0RSKzhY
 

## Environment (Required)

[https://i.imgur.com/B76dpXA.png](url)

**Comment by xH3LLRAIZ3Rx** [comment]
Im not getting this problem in 1.14.4

**Comment by BluGhostYT** [comment]
@GeMiniXCape , try CS-CoreLib version 1.5.18. 1.6.1 is not meant for 1.12 as it has new methods that are meant for 1.13+
