### ISSUE TITLE
Elevator Plates Not Working 1.14.4

### ISSUE THREAD

**Issue by Mabit100** [TheBusyBiscuit/Slimefun4#964]
## Description (Required)

When using elevator plates. First one goes down and says no destinations found.
When placing the second nothing happens.

If existing elevator set up, no book opens to pick a floor.

## Steps to reproduce the Issue (Required)

https://youtu.be/jfRWogD-dNE

## Expected behavior (Required)

Normal elevator behaviours

## Server Log / Error Report
https://pastebin.com/tZ4hNPnx

## Environment (Required)

 - Minecraft Version:1.14.4
 - Slimefun Version:125
 - CS-CoreLib Version:62

**Comment by mrcoffee1026** [comment]
I don't get the error "no destination found" but when stepping on the lower floor (first placed) elevator I get a book named "Elevator .. by Slimefun" which I can then open and go to the second floor... but not back to the first since the book doesn't believe I've ever gone anywhere.  In any case it is not working in multiple ways.

**Comment by AJFire14** [comment]
Hello. I would like to also mention that I get the same issue on my server. When placing a SF elevator, I receive a book in my inventory which then I click on and it stays in my inventory, sometimes bugged. 

The old way of using elevators were perfect where you step on the elevator pressure plate and a book opens without taking space in your inventory, in which you select the floor you want to go in with ease like before. Would appreciate if this is fixed as it is a feature that many of our users use. 

Thanks.

**Comment by mrcoffee1026** [comment]
Had several users report that when the receive the book... if they're holding a sword in their main hand it is swapped for this book and never returned.

**Comment by dniym** [comment]
From what I can tell this  is a CS-CoreLib issue and not slimefun’s fault.   Whenever this happens I get an error in the console pointing to cs-core.
