### ISSUE TITLE
Ancient Altar Issue: lag or glitch?

### ISSUE THREAD

**Issue by Radcoon** [TheBusyBiscuit/Slimefun4#967]
## Description (Required)
When trying to create something with the Ancient Altar, all works well. All items go on the pedestals as expected, however whenever I use the Catalyst, it takes the item and nothing happens. No particles appear, and I don't get my desired item. After waiting about 5-10 minutes, the objects on the pedestals will eventually despawn.

## Steps to reproduce the Issue (Required)
https://www.youtube.com/watch?v=lp6dhUztMig

## Expected behavior (Required)
I expected the Altar to give me my desired item.
## Server Log / Error Report
https://pastebin.com/xU3HF0vJ

## Environment (Required)

 - Minecraft Version: 1.12.2
 - Slimefun Version: 4.1.15
 - CS-CoreLib Version: 1.6.1

**Comment by BluGhostYT** [comment]
Try CS-CoreLib version 1.5.18. That's the latest version of CS-CoreLib for 1.12.2. Be sure to DISABLE auto-update in CS-CoreLib's configuration, otherwise, you will go through that issue once again.
