### ISSUE TITLE
Explosive Pickaxe duplication glitch 2.0

### ISSUE THREAD

**Issue by BluGhostYT** [TheBusyBiscuit/Slimefun4#968]
## Description (Required)
So apparently, my fix for the explosive pickaxe duplication glitch did not entirely work. Now it begins to dupe with an energy regulator as well.

## Steps to reproduce the Issue (Required)
https://gyazo.com/f3ab5704874083fba2ab510fddc14fd6
https://gyazo.com/5e9ceb78a8fa81146a12b5602e8d5acc

## Expected behavior (Required)
What is expected to happen is that the generators should not break at all.

## Server Log / Error Report
https://pastebin.com/njZndTMs

## Environment (Required)
![image](https://user-images.githubusercontent.com/31489616/61746526-823d5000-ad61-11e9-8932-eac607e7a337.png)

**Comment by huynhqtienvtag** [comment]
Can reproduce this
Look like the item was added to the drop list twice
Still don't know why

**Comment by dniym** [comment]
This should also be closed, explosive pick does not seem dupe items in 147
