### ISSUE TITLE
Slimefun doesn't distinguish between vanilla Elytra and Slimefun crafted Elytra

### ISSUE THREAD

**Issue by coldcode69** [TheBusyBiscuit/Slimefun4#97]
## Description
Slimefun adds the ability to craft normal Elytra which requires researching to unlock **and use**. Since this is a vanilla item, it can be obtained without the recipe, but if you don't have it unlocked you are spammed with the "not enough knowledge" messages in chat. I don't think people who find the Elytra in the End should also have to research it in order to use it.

I suggest making it so that vanilla Elytra can be used by anyone regardless of research, but keeping the research requirement in order to unlock the recipe to craft Elytra (since crafting is specific to Slimefun and unavailable in vanilla Minecraft). This preserves the vanilla experience whilst adding the option to use Slimefun content and game mechanics.

An alternative idea would be to change the crafted Elytra into a new item "Crafted Elytra", so it is distinguished from vanilla Elytra. This would allow you to leave vanilla Elytra untouched and without any requirements to use, whilst retaining the option to research crafted Elytra.

## Environment
spigot 1.11.2
cscorelib version 1.5.12
slimefun version 4.1.1

**Comment by NathanAdhitya** [comment]
I agree with the idea.

**Comment by coldcode69** [comment]
This would have no effect on the upgraded Elytra. You could still use the vanilla Elytra or "Crafted Elytra" in those recipes. 

Essentially you could remove the chat spam for the vanilla item and leave everything else the same. I just feel as though most players wont be expecting to be required to research/unlock a vanilla item which they can obtain without the plugin. The research **should** remain for crafting Elytra, just not for using them.

**Comment by NathanAdhitya** [comment]
Ill see about that if i have time to do it... *smileyface*

**Comment by AlexLander123** [comment]
@TheBusyBiscuit  Will this be implemented? If yes, how will it be implemented?

P.S. I am asking because there is no labels yet and it seem to be a valid issue.

**Comment by Joapple** [comment]
This is happening with Chain armor and Gold Armor. Maybe, could remove spam message about those as well?

**Comment by akashaggarwal7** [comment]
What I did to fix this was I removed researching of Elytra, meaning it is already unlocked for everyone in researches.
