### ISSUE TITLE
Ancient Alter result item not appearing upon crafting.

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/Slimefun4#974]
## Description (Required)

Apparently ALL Ancient Alter recipes are bugged. No result item is given.

## Steps to reproduce the Issue (Required)

Try to make something with the Ancient Alter. Simple.

## Expected behavior (Required)

The result item to appear upon crafted.

## Server Log / Error Report

No errors.

## Environment (Required)

![2019-07-25_18 35 14](https://user-images.githubusercontent.com/51277766/61919569-0ed74200-af0b-11e9-99da-f592a8c5f6fa.png)

**Comment by BluGhostYT** [comment]
@EnderBro123 , do you mind providing actual proof of this issue? I recommend recording, because this is not enough evidence.

**Comment by EnderBro123** [comment]
> @EnderBro123 , do you mind providing actual proof of this issue? I recommend recording, because this is not enough evidence.

I don't have anything to record with so I can't really do that.

All I can say is this is happening on Build 125 of Slimefun.

**Comment by BluGhostYT** [comment]
> > @EnderBro123 , do you mind providing actual proof of this issue? I recommend recording, because this is not enough evidence.
> 
> I don't have anything to record with so I can't really do that.
> 
> All I can say is this is happening on Build 125 of Slimefun.

How about you look software up.... OBS is a good suggestion...........

**Comment by EnderBro123** [comment]
> > > @EnderBro123 , do you mind providing actual proof of this issue? I recommend recording, because this is not enough evidence.
> > 
> > 
> > I don't have anything to record with so I can't really do that.
> > All I can say is this is happening on Build 125 of Slimefun.
> 
> How about you look software up.... OBS is a good suggestion...........

Slimefun had an update so I will see if this is fixed in Build #129 (Ignore the hyperlink :P)

**Comment by EnderBro123** [comment]
> > > @EnderBro123 , do you mind providing actual proof of this issue? I recommend recording, because this is not enough evidence.
> > 
> > 
> > I don't have anything to record with so I can't really do that.
> > All I can say is this is happening on Build 125 of Slimefun.
> 
> How about you look software up.... OBS is a good suggestion...........

**EDIT:** Did some testing at the time I posted this comment and I believe that this is fixed.
