### ISSUE TITLE
NullPointerException at CargoNet.java

### ISSUE THREAD

**Issue by TheRBZ** [TheBusyBiscuit/Slimefun4#976]
## Description (Required)
CargoNet.java throws an NPE in the console as a warning, unknown cause. The warning will repeatedly fill up console until (supposedly) what I think is the cargo item getting unloaded.

## Server Log
https://pastebin.com/9dgN02Qw

## Evidence / Proof (Required)
Absolutely no idea what's causing the NPE or who even has cargo items, therefore I cannot provide any evidence or proof. Can try and find out but isn't my top priority.

## Environment (Required)
![image](https://user-images.githubusercontent.com/39860014/61993834-a94d9780-b069-11e9-8acb-2a6d29620d26.png)

**Comment by BluGhostYT** [comment]
Try Build 62 of CS-CoreLib and see if that fixes the issue
