### ISSUE TITLE
teleportation time GPS Teleporter

### ISSUE THREAD

**Issue by JamesAdams92150** [TheBusyBiscuit/Slimefun4#978]
## Description (Required)
the estimated teleportation time for the GPS Teleporter is always 50s

## Steps to reproduce the Issue (Required)
just build the GPS Teleporter

## Expected behavior (Required)
the time depends to the distance

## Server Log / Error Report
NO

## Environment (Required)

 - Minecraft Version: 1.14.2
 - Slimefun Version: Slimefun4 - #125
 - CS-CoreLib Version: CS-CoreLib-39

**Comment by JamesAdams92150** [comment]
why you closed my  issues ?

**Comment by BluGhostYT** [comment]
This issue was closed due to lack of evidence & lack of detail

**Comment by BluGhostYT** [comment]
^ to add to this, this isn't even an ISSUE or BUG
