### ISSUE TITLE
Andriods cannot be broken.

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/Slimefun4#997]
## Description (Required)

Any type of andriods cannot be removed.

## Steps to reproduce the Issue (Required)

Place any type of Andriod (Normal, Advanced, Empowered) and try removing it.

## Expected behavior (Required)

The andriod being removed and its item being returned.

## Server Log / Error Report

No errors.

## Environment (Required)

![2019-08-05_15 48 20](https://user-images.githubusercontent.com/51277766/62499697-79547180-b798-11e9-8364-fa6a2a31212b.png)

**Comment by xH3LLRAIZ3Rx** [comment]
Can confirm this.
