### ISSUE TITLE
Holographic Text Remains After Removing Energy Regulator

### ISSUE THREAD

**Issue by Goonhaven** [TheBusyBiscuit/Slimefun4#998]
## Description
If you try to set up a GPS transmitter network with an Advanced Solar Generator, Energy Regulator, Advanced GPS Transmitter, and GPS Transmitter x2, then the holographic text stating the power remains after removing all of said components.

Before:
![Minecraft 1 14 4 06_08_2019 00_32_59](https://user-images.githubusercontent.com/41123454/62501429-c8bf8f80-b7e2-11e9-990e-1a59498d2f9e.png)

After:
![Minecraft 1 14 4 06_08_2019 00_37_36](https://user-images.githubusercontent.com/41123454/62501434-d117ca80-b7e2-11e9-9ebe-6528e7889995.png)

## Expected behavior
The holographic text should disappear.

## Environment
Slimefun vDEV 133
Spigot 1.14.4
CS-CoreLib vv1.6.1

**Comment by dniym** [comment]
Can not reproduce this issue with recent versions of slimefun.
Consider using versions:
CS-CoreLib vDEV - 65 (git a6ce25a7) 
Slimefun vDEV - 135 (git f54fd125)
